### ISSUE TITLE
Add Korean Language Support??

### ISSUE THREAD

**Issue by wise0704** [fdorg/flashdevelop#1000]
# Congrats guys on the 1000 #references!!!

Anyways, 
I see that a lot of developers in Korea uses FlashDevelop.
Wouldn't it be nice if FlashDevelop also supports Korean?

I can do the job of adding the localized resource file `ko_KR`.
@Meychi

**Comment by Meychi** [comment]
That would be great! There are few other places that need localization too but that is the biggest hurdle. :)

**Comment by wise0704** [comment]
I will make a PR once I'm done translating the resource file?
You can let me know what else I have to do.

**Comment by Neverbirth** [comment]
+1. I'd say having more languages is always welcome. And AFAIK you only have to modify the resource file.

**Comment by wise0704** [comment]
20% completed...
A lot of those texts are quite confusing without context, and it is pretty hard to decide how to translate them... sadface
like if there is `"&Add"`, I don't know if I should do `"추가 (&A)"` with the parentheses or not. (Buttons will have the correct underlines, but codes that also use this text with `string.Replace("&", "")` will produce stuff quite funny.

I think I will need to take some time trying it out myself when the whole thing is completed before the actual release.

**Comment by Neverbirth** [comment]
Well, you can easily find for the confusing text keys and learn where they are used, cannot you?

**Comment by wise0704** [comment]
I did for most of them, but there is a limit to how much I can analyse what the code will do with some of the strings...

I would need to test it before release anyways just to make sure.
