### ISSUE TITLE
SWC Import Bug

### ISSUE THREAD

**Issue by ybelenko** [fdorg/flashdevelop#1008]
I've noticed some weird bug in FlashDevelop recently.
I'm trying to finish some old project so I have graphic in FLA files from 2013 year. When I publish these files as SWC and include them in FlashDevelop project my debugger stop working(wellknown for everyone error "Waiting for FlashPlayer for connect... "). It's even weirder that when I include SWC file 
but not use classes from it in code everything works great(I just comment lines where external classes are).

That's very frustrating that I can't work properly, maybe community can solve this problem somehow?
I've failed to attach SWC file in ZIP archive to this message. But I can send it via any email if it's important for a bug fixing.

Important note: Not working only in debug mode, in release mode everything goes fine.

Software info:
FlashDevelop 5.0.2.2
FlexSDK 4.6.0 with provided Debugger for Windows
Adobe Flash Professional CC Version 13.1.0.226
Windows 8.1 x64

**Comment by Neverbirth** [comment]
Mmmm I use SWCs in a lot of projects and never saw this problem. Maybe something funky in that SWC, if you could upload it to some file sharing service, DropBox, etc maybe we can find the reason.

**Comment by elsassph** [comment]
You want to try creating a new FLA and add symbols one by one and see if that works. The Flex SDK is known to have some issues with some graphics or animations. Can't remember exactly but it could be  silly as having an animation defined on empty keys.

**Comment by ybelenko** [comment]
Yep, I can do it while I have 100 symbols, but what if I have a thousands of symbols?

Here is the link to problem swc file:
https://www.dropbox.com/s/vb3e8ks6juh8xg7/full_kombat.swc?dl=0

**Comment by Neverbirth** [comment]
Well, if it's a problem with the SDK itself as Philippe suggests there is nothing we can do. Could you try debugging your project with another IDE like Flash Builder? I'll try to look into the problem and report back, but maybe next week.

**Comment by ybelenko** [comment]
It seems to me that it's not problem with SDK, because SWC file stopped working after resaving in new Flash IDE(originaly was Flash CS5). And again, it's weird that it's not working only in debug mode. I was trying with new FlashPlayer(11.8 instead of 10.3) versions, but with no luck.

**Comment by elsassph** [comment]
And the issue didn't happen if you use the original SWC produced using Flash CS5? Maybe you can try getting CS5 back somehow?

**Comment by ybelenko** [comment]
I did some research. I had to remove all layers from exported class one by one. Finally I've figured out that SWC file stops working when exported class has actionscript on a layer("stop();" mostly, obvious). It's very weird, maybe something wrong with my FlashCC IDE? I can delete all actionscript code from layers and replace it by custom code for animation, but for most of users this bug would be unacceptable.
I was trying to rollback to Flash CS5, but my old installer not working on Windows8 anymore, crashes with errors.
At the end I cannot understand why it's not working only in debug mode. In release mode everything perfect while in debug mode, flash player not showing up like it's waiting for something.

**Comment by elsassph** [comment]
That should definitely work...
Maybe you can try rebuilding the SWC making sure you check "Permit debugging" in the publish settings?

**Comment by ybelenko** [comment]
It wasn't checked. I've enabled "Permit debugging", but still no luck...

**Comment by elsassph** [comment]
I tried the SWC and confirm your result. 

So to clarify, adding to the library doesn't include anything until you reference a class from the SWC, and as soon as some symbol is included and compiled in debug mode, then Flex SDK basically generates an invalid SWF.

I would suggest to try a newer SDK (using Apache Flex SDK Installer tool).

Clearly the timeline code should not be the issue - you can probably try making a dummy FLA with and animation and a `stop()` on the last frame and it will probably work fine.

**Comment by ybelenko** [comment]
Yep, I've tried new dummy fla with classic tween and stop on the last frame. It works fine. In this case I'm confused even more, because don't understand where is the issue... I'm always using the last Flex SDK and I've checked two or even three of them when I've noticed this bug.
Where is the problem? Inside Flash CC and FLA files or in Flex SDK connected to FlashDevelop?

**Comment by elsassph** [comment]
The issue is in Flex SDK as far as I can tell. FD only runs the SDK and Flash seem ok with your FLA contents obviously.
Maybe there's something around Russian characters in some exported symbol names...

**Comment by elsassph** [comment]
You should try to raise an issue on https://issues.apache.org/jira/browse/FLEX

**Comment by ybelenko** [comment]
Thanks, Philippe
