### ISSUE TITLE
Flambe project does not work

### ISSUE THREAD

**Issue by markknol** [fdorg/flashdevelop#1010]
I'm trying to create a project template for Flambe to be part of the installation, but the build-in Flambe project does not work. When I start with a Haxe-JS project, then set the target to Flambe, put the flambe.yaml to the project and point to it, it does not compile.

I use Flambe on daily basis, but I personally use a customized version of the provided template of the flambe framework itself (`flambe new myprojectname`).

It would be nice if we get this to work. Maybe I'm just missing something?

**Comment by elsassph** [comment]
What built-in project? How do you create it?

**Comment by markknol** [comment]
I followed this steps:

1. In top nav: Project > _New project_
1. Choose "Haxe/Javascript project"
1. In top nav: Project > _Properties_
1. Add [this "flambe.yaml"](https://raw.githubusercontent.com/aduros/flambe/master/command/data/scaffold/flambe.yaml)  to the project, in root folder.
1. Select "Flambe" in the _platform_dropdown, use `flambe.yaml` as configuration
1. Try to compile the project

Update; I tried to reproduce it, but I think it's a misconfiguration on my side.
