### ISSUE TITLE
Cannot undo after build

### ISSUE THREAD

**Issue by huyhungkun** [fdorg/flashdevelop#1014]
I can't undo to previous task after build project. If I change code and then undo, it success, if i change code, build project and then undo, it failed.

**Comment by Meychi** [comment]
I can't reproduce this with the latest release version. Do you mean that you lose editor focus or even if you click the editor you can't undo?

Which version FD are you using? Do you have any 3rd party plugins installed? Do you have post or pre build tasks?

**Comment by huyhungkun** [comment]
Oh, I have two layout, is ReleaseLayout and DebugLayout. When write code, I use ReleaseLayout. In Program Settings -> FlashDebugger. I set "Switch To Layout On Debugger Start" = DebugLayout location. I am using FD 5.0.2.2 (lastest release) :D


[Layouts.zip](https://github.com/fdorg/flashdevelop/files/68234/Layouts.zip)

**Comment by Meychi** [comment]
Ah. This is due to the fact that FD needs to dispose current windows and then reopen them. I need to look if we could somehow reuse the existing windows do we don't lose undo history. Will mark this as a enhancement for future.
