### ISSUE TITLE
[haxe_distro] project settings platform dropdown is empty 

### ISSUE THREAD

**Issue by markknol** [fdorg/flashdevelop#1015]
![image](https://cloud.githubusercontent.com/assets/576184/11965277/fbe94eca-a8f3-11e5-85b8-48e2fd37475c.png)

I'm using:

![image](https://cloud.githubusercontent.com/assets/576184/11965256/d849a82a-a8f3-11e5-96da-88d44b7b846b.png)

**Comment by markknol** [comment]
I noticed this was only the first time I runned the application, after a restart I have the menu.

**Comment by elsassph** [comment]
Looks like HD didn't find the Platforms definitions.

**Comment by Meychi** [comment]
Should be fixed now.
