### ISSUE TITLE
Code peek

### ISSUE THREAD

**Issue by markknol** [fdorg/flashdevelop#1019]
https://twitter.com/Jeff__Ward/status/681216872189050880

I saw this, it would be a nice addition for our editor too?!

**Comment by 22Round** [comment]
+1 would be great

**Comment by markknol** [comment]
@SlavaRa otherwise this would be an nice idea for a plugin :)

**Comment by SlavaRa** [comment]
)) +1

**Comment by Neverbirth** [comment]
I'm not much into this, I'm more into what FD currently shows. But this could be done more or less easily I'd say and enabled on Shift+hover or similar (the normal hover shouldn't be overriden IMHO, and Ctrl will be used for Ctrl + Click).

**Comment by elsassph** [comment]
EditorMinimap plugin has a "peek" overlay - that would be a good start ;)

**Comment by SlavaRa** [comment]
implemented #1327
