### ISSUE TITLE
[haxe] support simple .hxml for build configuration

### ISSUE THREAD

**Issue by nadako** [fdorg/flashdevelop#102]
It would be a nice feature if, instead of configuring the whole haxe project in FD, you could just specify the .hxml file to use and FD would parse source paths, used libs and other configuration from it.

I imagine it would be useful not only for our project, but for many haxe projects out there, because .hxml is the standard build file format.

**Comment by SlavaRa** [comment]
Now FlashDevelop can import a project from an .hxml file. I think that this issue is accomplished
