### ISSUE TITLE
[haxe] callback code generation

### ISSUE THREAD

**Issue by markknol** [fdorg/flashdevelop#103]
It would be cool if we can get improved code generation on callbacks in Haxe
Lets say you have this class

```
class MyClass {
   public function onClick(event:Event->Void)
   {

   }
}

// implementation somewhere:
var instance = new MyClass();
instance.onClick(onInstanceClick // ctrl-shift-1 > create private function here!
```

gives this:

```
function onInstanceClick () {

}
```

I'd love to see this as:

```
function onInstanceClick (:Event):Void {

}
```

Optional, it would be even more cool to have some kind of documentation-rule for the parameter names

```
/**
* @param event (myNameHere:Event)->Void
*/
public function onClick(event:Event->Void)
   {

   }
```

So the function could be generated like this:

```
function onInstanceClick (myNameHere:Event):Void {

}
```

**Comment by SlavaRa** [comment]
soon
![fd_issue103](https://cloud.githubusercontent.com/assets/1700940/13803246/6bd8922a-eb54-11e5-9996-983e14cf50f4.gif)
I have to do refactoring and write tests
ps

**Comment by markknol** [comment]
Hey that's awesome!

**Comment by markknol** [comment]
Great, thanks!

**Comment by SlavaRa** [comment]
This is the first iteration. I will work on this generator still
