### ISSUE TITLE
[haxe] Goto declaration fails on Type.BaseType in Compiler.hx

### ISSUE THREAD

**Issue by Gama11** [fdorg/flashdevelop#1040]
![](http://i.imgur.com/04wpbpd.png)

Using goto declaration on `Type` takes you to the toplevel `Type.hx` instead of the one in `haxe.macro`.

`BaseType` isn't even recognized / highlighted as a type, so goto decalaration doesn't work there.

Explicitly importing `import haxe.macro.Type;` fixes both of these issues, but FD should be smart enough to figure it out by itself.
Position completion isn't really too useful here, since it's currently only used when FD doesn't find any results...

**Comment by SlavaRa** [comment]
I cannot reproduce this in FD 5.2.1.44

**Comment by Gama11** [comment]
Can confirm, seems fixed.
