### ISSUE TITLE
Cannot build Air App with target 19 or higher

### ISSUE THREAD

**Issue by ylazy** [fdorg/flashdevelop#1049]
I have FlashDevelop 5.1 and Flex 4.6 + AIRSDK 20 installed
When I test my app with target platform 18 everything is ok
When I change to 19, FD tell me the build succeeded, but the console say "error while loading initial content. Press any key to continue..."
Additional, I can't see the platform target 20, even if AIRSDK 20 installed.
Please help!

Thanks!

**Comment by elsassph** [comment]
It may be because your AIR xml app descriptor defines AIR 18 (that's really what matters), while you've asked to build a SWF for 19.
 FD shows versions as defined in an internal config file. It's usually not critical to update but the file is in your user FD files (under /Platforms).

**Comment by ylazy** [comment]
Thank so much! That really helped. I modified application.xml and air.xml and now it worked.
