### ISSUE TITLE
[haxe] Function not recognized as such with metadata afterwards

### ISSUE THREAD

**Issue by Gama11** [fdorg/flashdevelop#1065]
```haxe
class Main
{
	private function func():Void
	{
	}
	
	@:allow(flixel)
	private var test:Int;
}
```

The outline panel shows `func` as a regular variable:

![](http://i.imgur.com/Qi46lFm.png)

The important part seem to be the metadata's brackets - works as expected with just `@:allow`.

This feels like a recent regression.

**Comment by Gama11** [comment]
Also, if `func()` has no explicit return value, the metadata's name is used for that.

```haxe
class Main
{
    private function func()
    {
    }

    @:allow(flixel)
    private var test:Int;
}
```

![](http://i.imgur.com/MTjjBjb.png)

**Comment by Neverbirth** [comment]
Yes, the second one is known, and it's been there for 2 years more or less.

**Comment by elsassph** [comment]
This is fixed by the Haxe parsing improvements - we know understand Haxe metas.
