### ISSUE TITLE
Bug cannot compile with Adobe Animate CC

### ISSUE THREAD

**Issue by 22Round** [fdorg/flashdevelop#1069]
![cannot_compile](https://cloud.githubusercontent.com/assets/5682469/12914140/19654486-cf3c-11e5-9978-460773c191ab.jpg)

for compile FD asks Flash.exe!

**Comment by 22Round** [comment]
how to change Flash.exe to Animate.exe?

**Comment by Neverbirth** [comment]
By looking at the source code of FD, setting the whole path including the .exe file should work. It only looks for Flash.exe if you don't specify the full path.

https://github.com/fdorg/flashdevelop/blob/961772032b0fde59a7eb89a98b3494af67422f8d/External/Plugins/ASCompletion/Commands/CallFlashIDE.cs#L74

**Comment by 22Round** [comment]
@Neverbirth  thanks it works for full path
