### ISSUE TITLE
[haxe] Function header parsed incorrectly if previous return has type param

### ISSUE THREAD

**Issue by Gama11** [fdorg/flashdevelop#1075]
First noticed this in `String.hx`. This reproduces it:

```haxe
extern class String
{
	function charCodeAt( index : Int) : Null<Int>;
	function indexOf(str:String, ?startIndex:Int):Int;
}
```

Looks like this in the outline panel:

![](http://i.imgur.com/DFscxa2.png)

Removing the angle brackets fixes the signature of `indexOf()`.

**Comment by Neverbirth** [comment]
Yes, I know, it's the parser problem I mentioned in #1068.
