### ISSUE TITLE
null completed as Null

### ISSUE THREAD

**Issue by ncannasse** [fdorg/flashdevelop#1084]
I got the following completion in one of my files (HD 5.1.0)
It replaces my `null` by `Null` which is pretty annoying :)

![screen](https://cloud.githubusercontent.com/assets/1022912/13290063/8df5da72-db12-11e5-9410-beddeef7e610.png)

**Comment by elsassph** [comment]
I'm wondering if there is a problem with the user configuration files in general. @Meychi ?

**Comment by Meychi** [comment]
@elsassph: What kind of problem?

**Comment by Neverbirth** [comment]
Could you send the whole class to my account at gmail?

**Comment by ncannasse** [comment]
I'll try to reproduce again, it might have been temporary

**Comment by ncannasse** [comment]
Can't reproduce, the code have been heavily refactored, I'll open again once I have a reproducible case.

**Comment by Neverbirth** [comment]
So bad, yesterday I got a few ideas for it, but would have needed more details. Well, next time you know how to reach me :P

**Comment by elsassph** [comment]
This should not depend on the ambient code: `null` is a keyword like `true` and `false`.

**Comment by Neverbirth** [comment]
But if you look at the code it does (I'd say you did that part?). Wrong syntax and who knows what else may have an effect.
