### ISSUE TITLE
[5.1.0] Scrollbars don't change after changing theme

### ISSUE THREAD

**Issue by DleanJeans** [fdorg/flashdevelop#1088]
![beforeafterscrollbars](https://cloud.githubusercontent.com/assets/12462089/13347561/397d98aa-dca1-11e5-9bc0-5f4ddef50bd4.png)

**Comment by DleanJeans** [comment]
Also this, don't what's its name
![watchwindow](https://cloud.githubusercontent.com/assets/12462089/13349969/b8d329c2-dcaf-11e5-8dad-4df381e42170.png)

**Comment by ylazy** [comment]
FD 5.1 has new way to customize scrollbar and debug panel, and vsDark currently not compatible with the new FD 5.1.
You can use my theme to resolve this issue:
https://github.com/ylazy/FlashDevelop-Themes-YDark

**Comment by DleanJeans** [comment]
@ylazy Just trying to figure it out how to modify the Vs Theme and reading the files in your repo and found some Vietnamese. Are you a Vietnamese by any chance? :D

**Comment by ylazy** [comment]
@DleanJeans Yes, I'm a Vietnamese. Thank you ;)

**Comment by Meychi** [comment]
ScrollBar compatibility was fixed in https://github.com/fdorg/flashdevelop/commit/da9d38ea5b06b935528154bf77974087ab199dcc, debug panel theming is new in FD5.1.

**Comment by DleanJeans** [comment]
So this still hasn't been fixed yet
![watchwindow](https://cloud.githubusercontent.com/assets/12462089/13349969/b8d329c2-dcaf-11e5-8dad-4df381e42170.png)

**Comment by ylazy** [comment]
@DleanJeans Please provide more info. I'm using FD5.2 and it's working

![debug-panel](https://cloud.githubusercontent.com/assets/6010183/15381735/7f7c8f4a-1dac-11e6-9705-1f6074dc0b40.png)

1. Download file: YDark.fdz
2. Double-click to open YDark.fdz with Flash Develop
3. Restart FD

**Comment by DleanJeans** [comment]
Actually I'm talking about the box opened when you hover the mouse on a variable while debugging. Do you know what's its name? I'm gonna try to fix the VS theme myself.
