### ISSUE TITLE
Words Highlighting not working in Main.as, works in any other file

### ISSUE THREAD

**Issue by joseroux** [fdorg/flashdevelop#1089]
I've disabled the highlight selection plugin which is super slow, to try the native words highlighting thinking it would now (in 5.1) allow us to set the final, true, real background color of highlighted words
Sadly it doesn't, but I managed to get something good enough. Strangely it works on every file except with my Main.as file?

**Comment by Meychi** [comment]
Is your Main.as file big? Due to speed reasons, it does not kick in for very large files.

**Comment by joseroux** [comment]
Yep, 3700+ lines ... I have some cleanup to do ;-)
Is the limitation based on a line count or filesize?
Thanks

**Comment by Meychi** [comment]
The limit is at 65536 (64 * 1024) characters.

**Comment by joseroux** [comment]
OK, thanks, will close this 'issue'.
