### ISSUE TITLE
Results panel: "Copy Entry Details" only works for single selections

### ISSUE THREAD

**Issue by Gama11** [fdorg/flashdevelop#1092]
Would be convenient if this worked when mutliple entires are selected as well - currently it only copies the first entry.

Select all / Ctrl+A support would combo well with that.

**Comment by SlavaRa** [comment]
Fixed #1345

**Comment by devilpig** [comment]
This does not work in FD 5.2.0.3 on Windows 7. Am I doing something wrong?

**Comment by SlavaRa** [comment]
@devilpig This fix has been made after the release of 5.2

**Comment by devilpig** [comment]
@SlavaRa Thanks for the swift response :)
