### ISSUE TITLE
[HaxeDevelop] Can't find HaxeFlixel template after installing from AppMan

### ISSUE THREAD

**Issue by larsiusprime** [fdorg/flashdevelop#1103]
### Steps to reproduce:

1. Uninstall existing version of HaxeDevelop.
2. Download latest version of HaxeDevelop (tested with both latest release & latest development version) -- version I have right now is https://github.com/fdorg/flashdevelop/commit/db235bf2c9
3. Open up appman, scroll down to "HaxeFlixel Template", select install. Install seems successful.
4. Project -> New Project

### What I expected:

HaxeFlixel Project should be one of the options

### What happened instead:

HaxeFlixel Project is not one of the options.

Further steps:

5. Close HaxeDevelop, restart. (same result)
6. Delete HaxeFlixel template from AppMan, try again. (same result)
7. Click "Explore..." button from AppMan to remove downloaded flixel template, try again. (same result)

**Comment by Meychi** [comment]
Works here. Its the second to last Haxe template before Empty. Not there?

Do you have FlashDevelop also installed?

**Comment by larsiusprime** [comment]
Nope, not there:

![2016-03-03 15_38_19-new project](https://cloud.githubusercontent.com/assets/739064/13510437/102695ba-e156-11e5-833a-e015030ea605.png)

![2016-03-03 15_38_45-appman](https://cloud.githubusercontent.com/assets/739064/13510441/132ad74e-e156-11e5-83b7-c00a7dc3664c.png)

![2016-03-03 15_39_35-haxedevelop](https://cloud.githubusercontent.com/assets/739064/13510457/2690283e-e156-11e5-8c6e-7f538da508c6.png)

I do also have FlashDevelop installed.

**Comment by Meychi** [comment]
Please check that is it installed under FlashDevelop.

**Comment by larsiusprime** [comment]
It claims it's installed in FD as well:

![2016-03-03 15_47_32-appman](https://cloud.githubusercontent.com/assets/739064/13510689/52b5e902-e157-11e5-92fd-d65d08b96047.png)

But does not appear in the list of projects:
![2016-03-03 15_47_44-new project](https://cloud.githubusercontent.com/assets/739064/13510691/5731f7aa-e157-11e5-8560-21b5fdcccf56.png)

**Comment by Meychi** [comment]
Could you test this with a another user name? I'm just thinking if that space in the username gives problems with the fact that you have both installed.

**Comment by larsiusprime** [comment]
Sure, I'll try that later when I have a moment.

**Comment by Meychi** [comment]
Or i can also provide a patched AppMan and you could try if that works. Would that be easier?

**Comment by larsiusprime** [comment]
Sure, that's fine! I've got a lot of stuff open atm and I don't have a separate user account set up on this PC just yet...

**Comment by Meychi** [comment]
Ok give me a minute.

**Comment by Meychi** [comment]
Here you go. Remove the .txt extension. Let me know if HD works with this. [AppMan.exe.txt](https://github.com/fdorg/flashdevelop/files/157790/AppMan.exe.txt)

**Comment by larsiusprime** [comment]
![2016-03-03 16_35_28-new project](https://cloud.githubusercontent.com/assets/739064/13512043/f79d4784-e15d-11e5-8a92-0cfe80d21aac.png)

:)

**Comment by Meychi** [comment]
Yay!
