### ISSUE TITLE
Close start page (instead of untitled = true) on project open and document open

### ISSUE THREAD

**Issue by gene-pavlovsky** [fdorg/flashdevelop#1111]
I have both `close start page on project open` and `show start page instead of untitled` set to *true*. When I open a project, the start page remains open (as explained in the settings help - since no other document is open). After that I choose a document in the project panel and open it, I think at this moment the start page tab should close. How do you think guys?

**Comment by Meychi** [comment]
It's like this so that we don't end up reopening the startpage multiple times if you open one file and then close it. Also these options can contradict each other so we don't easily change the startpage logic as we may end up breaking it in another case. :)

**Comment by gene-pavlovsky** [comment]
All right sounds reasonable
