### ISSUE TITLE
Can't revert to default a keyboard shortcut that has been removed

### ISSUE THREAD

**Issue by gene-pavlovsky** [fdorg/flashdevelop#1112]
I accidentally did "remove shortcut" the Completion.Delete keyboard shortcut, originally set to "Back" by default. Doing "Revert to default" from the shortcut's context menu doesn't bring it back. I can set it manually to another shortcut (like Ctrl-Back), but I can't set it to "Back" manually.
Btw, what is Completion.Delete?

**Comment by Meychi** [comment]
Removed the shortcut definition as its an internal one and you can't customize the shortcut as it is invalid shortcut in .NET. 

It removes the added braces when you delete a character after the braces have been added.

**Comment by gene-pavlovsky** [comment]
If I understand correctly this refers to the "Add closing braces" ASCompletion option? Can you give an example on how to use this feature? I've typed "arr.sort(", a closing brace was added, pressing backspace just deleted the opening brace. Typing a character then pressing backspace just deleted this character. Is this something else?

**Comment by Meychi** [comment]
Hmm i think it should that. This was added by @Gama11 in fca1d3fcbf468622d48190192859fcab59f32666, want to chip in?
