### ISSUE TITLE
FlashDevelop performs invalid cross-thread operation

### ISSUE THREAD

**Issue by tom-seddon** [fdorg/flashdevelop#1114]
Building from 003a0cf98302a5db2225fe1a282a149caaf05b8b with VS2013.

I keep getting an InvalidOperationException exception in PluginCore.Controls.CompletionList.Hide. Seems it's trying to do something to a control on another thread.

Here's what Visual Studio has to say:

```
A first chance exception of type 'System.InvalidOperationException' occurred in System.Windows.Forms.dll
Additional information: Cross-thread operation not valid: Control '' accessed from a thread other than the thread it was created on.
```

Sometimes when this happens the completion lists gets stuck, with seemingly the only solution being to quit and restart.

Thanks,

--Tom

**Comment by tom-seddon** [comment]
Apologies. Forgot to provide a call stack.

```
>	PluginCore.dll!PluginCore.Controls.CompletionList.Hide() Line 306	C#
 	PluginCore.dll!PluginCore.Controls.UITools.OnUIRefresh(ScintillaNet.ScintillaControl sci) Line 298	C#
 	PluginCore.dll!PluginCore.Controls.UITools.HandleEvent(object sender, PluginCore.NotifyEvent e, PluginCore.HandlingPriority priority) Line 145	C#
 	PluginCore.dll!PluginCore.Managers.EventManager.DispatchEvent(object sender, PluginCore.NotifyEvent e) Line 141	C#
 	ProjectManager.dll!ProjectManager.ProjectManagerSettings.GetGlobalClasspaths(string lang) Line 238	C#
 	ProjectManager.dll!ProjectManager.ProjectManagerSettings.GlobalClasspaths.get() Line 218	C#
 	HaXeContext.dll!HaXeContext.HaxeComplete.BuildHxmlArgs() Line 114	C#
 	HaXeContext.dll!HaXeContext.HaxeComplete.StartThread<HaXeContext.HaxeCompleteResult>.AnonymousMethod__3(object _) Line 84	C#
```

**Comment by Meychi** [comment]
What did you do the get this error? Do you have any third party plugins installed?

**Comment by tom-seddon** [comment]
Just happens sometimes when I'm typing. Looks like it's happened once in my current session (I generally run FD under the debugger). No 3rd-party plugins. Built with VS2013, debug build, x86 platform.

Let me know if you need further details.

--Tom

**Comment by Meychi** [comment]
Could you share a sample project/file where it happens? I need to reproduce it.

**Comment by tom-seddon** [comment]
OK, thanks. I will try to create one or at least come up with some reliable repro steps.

--Tom

**Comment by Meychi** [comment]
@elsassph: The problem seems to be in HaxeComplete.BuildHxmlArgs (which runs in background) where it reads global classpaths from ProjectManager settings which causes events to fire. Is there a better way to do this?

**Comment by elsassph** [comment]
Ouch this is unfortunate indeed.

It looks like UITools is treating most events as "UI changes":

- generally UITools should test for specific events to use as "UI changes"
- UITools should test if the event is executed on the UI thread.
