### ISSUE TITLE
Builds, but doesn't start..

### ISSUE THREAD

**Issue by hopewise** [fdorg/flashdevelop#1117]
I can build the project, I get:
```
cmd: "C:\HaxeToolkit\haxe/haxelib" run lime build "client.xml" flash -debug -Dfdb
Build succeeded
Done(0)
[Starting debug session with FDB]
```
But, I have to manually double click the swf file to start it, I don't know why .. I have settings in place:
![image](https://cloud.githubusercontent.com/assets/1061157/13625945/a5fff522-e5c5-11e5-8093-4f7a0754b373.png)

**Comment by Meychi** [comment]
I see this also, i'll try to figure out whats happening.

**Comment by Meychi** [comment]
Ok, at least in my case the default Windows *.swf association was pointing to a old version of the Flash Player.

Try launching a *.swf file directly from the File Explorer and see if Windows asks you which app to use. If it does, it means the default file association is not working and lime is not able to launch the file. Most project templates launch SWF's with FD but lime i guess uses the default OS file association.

To fix this i needed to execute that Flash Player specified in the settings and open a *.swf. Or you can also when Windows asks which app to use, find that Flash Player and Windows fixes the association.

**Comment by hopewise** [comment]
As I mentioned, "I have to manually double click the swf file to start it" so, its already associated
how would I add a post command in the build dialog?

Thank you

**Comment by Meychi** [comment]
Did you open it from FD's Project Manager tree or Windows' File Explorer? Opening from FD uses FlashViewer plugin to open it, that does work.

**Comment by hopewise** [comment]
I will have to wait until I go home, and test using File Explorer,
So far, I just opened it from inside FD, will update you

On Thu, Mar 10, 2016 at 11:47 AM, Mika Palmu <notifications@github.com>
wrote:

> Did you open it from FD's Project Manager tree or Windows' File Explorer?
> Opening from FD uses FlashViewer plugin to open it, that does work.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/fdorg/flashdevelop/issues/1117#issuecomment-194759563>
> .
>



-- 
--
Kind Regards,
---------------------------------------------
Samir Sabri
Software Architect& Developer
www.dcaclab.com
Jordan-Middle East

**Comment by hopewise** [comment]
Ok, if I double click outside FD, in windows, it will open the swf file in FlashPlayer

**Comment by Meychi** [comment]
Could you share a minimal project that fails?

**Comment by hopewise** [comment]
I tried to create an empty openfl projects, and the swf files get opened,
then I noticed that I have to set the platform to lime instead of flash
player..

On Fri, Mar 11, 2016 at 5:48 PM, Mika Palmu <notifications@github.com>
wrote:

> Could you share a minimal project that fails?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/fdorg/flashdevelop/issues/1117#issuecomment-195422913>
> .
>



-- 
--
Kind Regards,
---------------------------------------------
Samir Sabri
Software Architect& Developer
www.dcaclab.com
Jordan-Middle East
