### ISSUE TITLE
"Run Project" on hxml platform shouldn't execute the hxml file

### ISSUE THREAD

**Issue by Gama11** [fdorg/flashdevelop#1124]
I have `.hxml`  files associated with FD and run it in multi-instance mode, so "Run Project" and "Test Project" create a new instance of FlashDevelop with the `.hxml` open.

**Comment by Meychi** [comment]
Could you provide a minimal demo project so i could debug this? I can't find anything from the code that jumps out.

**Comment by Meychi** [comment]
Seems that by default *.hxml files are associated with haxe.exe and then you can just double click the files to execute them with Haxe. It might be that somewhere in the toolchain the project file is runned without "haxe" in the command and as you have associated them with FD, it just opens the hxml file. In single instance mode FD should just open the file but not create a new instance.

I can't find anything that jumps out from FD, Haxe, Haxelib or Lime sources. Does it start work correctly if you reassociate *.hxml files with haxe.exe?

**Comment by Gama11** [comment]
That doesn't sound right - if .hxml was associated with haxe.exe, "Test Project" would build the hxml twice (once when building and once when running).

**Comment by SlavaRa** [comment]
not reproduced in 5.3+
