### ISSUE TITLE
Reduce installer size by removing playerglobal SWC's?

### ISSUE THREAD

**Issue by Meychi** [fdorg/flashdevelop#1130]
Currently AppMan patches installed SDK's with the latest playerglobal SWC's but FD also contains the same set of SWC's in tools/flexlibs dir. AS3Context patches the SDKs too on request the same way. Should we remove the bundled ones? The reduction would be something like 7mb.

**Comment by Meychi** [comment]
Or otherway around? Then the AppMan would download less per SDK install.

**Comment by elsassph** [comment]
Yeah maybe we should only include the latest SWC?

**Comment by Meychi** [comment]
Could we patch the SDK with latest playerglobal? So for example if you select v15, your SDK would be patched with playerglobal 20 or something. Does it complete incorrectly (like offer v20 feats) or does it affect only compiling?

**Comment by elsassph** [comment]
That's a whole topic - it would probably work, but some people complain that FD should let you only choose versions compatible with your SDK.

**Comment by Meychi** [comment]
This issue affects only manually configured SDK's, maybe we should just tell them to patch themselves with a link.

**Comment by elsassph** [comment]
Oh, like warning that the SDK is missing the SWC? That may be a good option.

Maybe we do that and include just the latest SWC; and maybe we shouldn't patch v15 for v20.

**Comment by Meychi** [comment]
Actually i think we should have these libs in FD but should remove them from HD. I will add a message for the case the libs dir is missing.

**Comment by elsassph** [comment]
Good point.

**Comment by Meychi** [comment]
I removed the playerglobal.swc's and FlexPMD from HD, its now 10mb smaller :) The SDK already says it its missing a SWC file when you are trying to compile, so i'm not adding a message for that. 

AppMan SDK's are still patched on install.
