### ISSUE TITLE
[haxedevelop] Trojan.Win32.Generic

### ISSUE THREAD

**Issue by Hersir88** [fdorg/flashdevelop#1135]
Hi, when I try to download HaxeDevelop I get this message from Kaspersky Anti-virus 6. 

Trojan.Win32.Generic for  http://haxedevelop.org/downloads/releases/HaxeDevelop-5.1.1.exe//winres.exe

**Comment by Meychi** [comment]
FlashDevelop got exactly the same detection little while back but it was marked as false detection. Please double check with some other scanner and report the detection to Kaspersky to check it.

Winres.exe is a Win32 app and contains only embedded file icons for the associated file types.

**Comment by Hersir88** [comment]
Thanks you Meychi. It happens to me only with Kaspersky Anti-virus, at home I have avasti and it doesn't detects anything.
