### ISSUE TITLE
Autocomplete popout too small on Retina / HighDPI screens

### ISSUE THREAD

**Issue by TomByrne** [fdorg/flashdevelop#1138]
![autocompleteissue](https://cloud.githubusercontent.com/assets/274228/13895887/5aec808a-edce-11e5-9e98-b1d1e23fccd0.jpg)

I'm running on Windows 10 (with screen scaling at 150%).
HaxeDevelop v5.1.1.1

**Comment by elsassph** [comment]
That may just be the regular maximum size for the list. I agree it could be wider though.
