### ISSUE TITLE
Keep selection after Find & Replace

### ISSUE THREAD

**Issue by GimmickyApps** [fdorg/flashdevelop#1139]
FD 5.1.0.3 / HD 5.1.1.1

If you want to replace multiple times on the same selected text, it's not preserved--the selection turns into a solitary cursor--so you have to keep re-selecting it.

**Comment by Meychi** [comment]
This is intended behaviour, Visual Studio does this too.

**Comment by GimmickyApps** [comment]
Really?  Then no offence, but I wouldn't like VS, either, for this.  TextPad doesn't do it this way.

Consider this: the TextPad way, if you don't need the selection, moving the arrow keys will ditch it for you anyway--so keeping the selection does not at all get in your way.  But if you do need it to do another replacement, then it's there, and you save a tedious re-select.  The VS/FD/HD way, you are not given the option, so if you don't need it, you save nothing, and if you do need it...tedium.

**Comment by Meychi** [comment]
In what use case you want to replace the same text multiple times?

**Comment by GimmickyApps** [comment]
Not the same text, different text over the same selection.

E.g. you get the logic right for x and width, then duplicate a bunch of such lines.  You then want to replace x with y and width with height.  That's two replacements (two texts!) to do over the same selection.

**Comment by Meychi** [comment]
You mean a case where you operate in a selected lines of code? The block selection is required only when you replace all, you can just replace next occurence from you current position. Or am i missing something here?

Could you create a gif showing exactly what you mean?

**Comment by GimmickyApps** [comment]
No, you understood right--for a Replace All on selected lines of code.

**Comment by Meychi** [comment]
Ah ok. Yes on replace all the selection should be restored.
