### ISSUE TITLE
Refactor and code completion doesn't work for big file 

### ISSUE THREAD

**Issue by DmitriyYukhanov** [fdorg/flashdevelop#1141]
Hey there!

Anyone willing to check out my bugreport on the forums?
http://www.flashdevelop.org/community/viewtopic.php?f=6&t=12592&p=54936#p54936

It reproduces on all FD versions since the first public 3 version and up to the current 5.1.1 version.

I can send a whole project privately to let you reproduce it on your side.

**Comment by Neverbirth** [comment]
You can send me some sample files if you want.

**Comment by DmitriyYukhanov** [comment]
Thanks for your quick reaction, @Neverbirth ! Could you please let me know how can I send them to you privately?

**Comment by Neverbirth** [comment]
Just my username at gmail.

**Comment by DmitriyYukhanov** [comment]
Thank you!
Just send you an email with all details I have.

**Comment by Neverbirth** [comment]
Got it.

**Comment by DmitriyYukhanov** [comment]
Hey, @Neverbirth !

I'm sorry for the pressure, but would you please be so kind and let me know if you were able to reproduce it or maybe you need some additional info from me?

Just trying to figure out how it goes, really show-stopping issue for my case =(

**Comment by Neverbirth** [comment]
Yes, I could identify the source of the problem.

**Comment by DmitriyYukhanov** [comment]
Awesome!
Any chance to know how much time it might take to fix it ^-^ ?

**Comment by Neverbirth** [comment]
I already fixed it at night together with issue #1125. I only have to finish writing the unit tests and make the pull request.

**Comment by DmitriyYukhanov** [comment]
Great news, thank you!
