### ISSUE TITLE
Output panel text sometimes invisible until scrolling

### ISSUE THREAD

**Issue by Gama11** [fdorg/flashdevelop#1148]
I fairly frequently have the issue that the Output panel is completely blank after a build. As soon as I start scrolling however, the output shows up.
I think this generally only happens when the panel is not active (I usually have the Results panel active in the same "container" and then switch to Output after a build). Maybe a refresh is missing when switching the active panel?

**Comment by gene-pavlovsky** [comment]
Just wanted to report this issue.
Build the project, then hover over the docked (with autohide) Output panel, it pops up, according to the vertical scrollbar there's almost two screens of content, scrolled all the way to the bottom (so nothing is showing). Scrolling up reveals the build messages, scrolling back down looks ok.

**Comment by gene-pavlovsky** [comment]
Issue is still present.
Running my app, then opening output - nothing displayed until trying to scroll with mouse wheel, then all the previously output text shows up. Using the app again (in a way which produces trace output) also displays all the contents.

**Comment by gene-pavlovsky** [comment]
Just downloaded build 5.2.1.35 to try out your fix. It still looks broken to me.
- Output panel is auto-hide (and hidden), building and running my app (AIR)
- Do something in my app that produces debug output
- Go to FD and hover mouse over `Output` to auto-show it
  + Scrollbar is at the bottom, indicating presence of content
  + But no content is visible
- Use mouse wheel over the output panel
  + Debug output appears

![20161021_165058_vplayer3 0 - flashdevelop](https://cloud.githubusercontent.com/assets/2841193/19600741/fd72be20-97ae-11e6-8e7d-9687e836aedc.png)

![20161021_165111_vplayer3 0 - flashdevelop](https://cloud.githubusercontent.com/assets/2841193/19600740/fd3c6a3c-97ae-11e6-9c45-b5f70ad1ca76.png)

**Comment by Neverbirth** [comment]
I'm sure you tried a wrong build 😜. I'll try to take a look, but I checked the same thing as you do when fixing this, except using Haxe instead of AIR.

**Comment by gene-pavlovsky** [comment]
Well it was the latest FlashDevelop-development.zip 
Numbered 5.2.1.35

**Comment by Neverbirth** [comment]
I see you are using a custom theme, what if you use one theme without custom scrollbars? do you get the same result?

**Comment by Neverbirth** [comment]
OK, found how it can still be reproduced. In the case where FD opens directly the output panel hidden and the user never gets to display it, the Output field will never get a height higher than 0, so this problem happens, although it will be right the following times.

Not really sure what may be the best solution, giving a default solution may still produce visual problems, the other option would be to get the owner dock panel and get the height it will get when showing it, but looks a bit ugly as a solution.

**Comment by gene-pavlovsky** [comment]
What happens on mouse wheel action that the output can show? And why can't the same action be applied when opening the auto-hidden Output panel?
