### ISSUE TITLE
[haxe] Fields from static imports are treated as types

### ISSUE THREAD

**Issue by Gama11** [fdorg/flashdevelop#1150]
``` haxe
import Static.test;

class Main {
    public static function main() {

    }
}
```

``` haxe
class Static {
    public static function test(s:String) {}
}
```

---

Haxe allows importing static fields of classes (see [here](http://haxe.org/manual/type-system-import.html)). FD however treats the import like any other import, namely the last segment is detected as a type and highlighted accordingly:

![](http://i.imgur.com/E99TjQe.png)

(`test` should not be highlighted)

Similar issue in completion - FD thinks `test` is a class:

![](http://i.imgur.com/RKyjFQI.png)

**Comment by SlavaRa** [comment]
Haxe, Enhancement
Work in progress

**Comment by elsassph** [comment]
Hey I thing this is a feature! it highlights the import.

**Comment by SlavaRa** [comment]
I did not understand:( What I did good or bad?

**Comment by Gama11** [comment]
@elsassph How is this a feature? In the screenshot, it claims `test` is a _class_, which doesn't make sense.
