### ISSUE TITLE
Broken auto-completion with Haxe.

### ISSUE THREAD

**Issue by melonin** [fdorg/flashdevelop#1158]
Since version 5.1.0, auto-completion for Haxe has been broken in some situations. More details at: https://groups.google.com/forum/#!topic/haxelang/43aN_aKO4CE

**FlashDevelop 5.1.0 & 5.1.1:**
- If a function type is declared (eg: Void->Void) for a function parameter, auto-completion will be broken for every function without access modifier in the same file, like [this](https://lh3.googleusercontent.com/-ZlGfAZQQaFc/VwH9pVuOtYI/AAAAAAAAACk/yOe7UrphhNU1KNY1rtb7aPJPJecl0cw5A/s1600/1.jpg). If function is declared with "private" or "public" the problem will stop.
- Sometime adding access modifier won't fix the bug and [function is colored the same as type](https://lh3.googleusercontent.com/-bvsgpX9C3Bc/VwIAP5trOZI/AAAAAAAAACs/UUDVu7loV8ImJnrc-Vl6CkqqEiUzjPJDQ/s1600/2.jpg). [This file](https://github.com/hazagames/Kala/blob/2654369109e02d6f283fcf2eb7ea7097a3b1724b/kala/components/Timer.hx) for example.

**HaxeDevelop 5.1.1:**
- Everytime I start HD, it gives me this error:

> The requested operation requires elevation
>    at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
>    at System.Diagnostics.Process.Start()
>    at HaXeContext.Context.LoadMetadata()
>    at HaXeContext.Context.SetHaxeEnvironment(String sdkPath)
>    at HaXeContext.Context.OnCompletionModeChange()
>    at HaXeContext.Context.BuildClassPath()
>    at ASCompletion.Context.ASContext.set_CurrentFile(String value)
>    at ASCompletion.Context.ASContext.SetCurrentFile(ITabbedDocument doc, Boolean shouldIgnore)
>    at ASCompletion.PluginMain.HandleEvent(Object sender, NotifyEvent e, HandlingPriority priority)

**FlashDevelop latest dev build:**
- The situation in [this screenshot](https://lh3.googleusercontent.com/-ZlGfAZQQaFc/VwH9pVuOtYI/AAAAAAAAACk/yOe7UrphhNU1KNY1rtb7aPJPJecl0cw5A/s1600/1.jpg) no longer produce the bug.
- The bug happens when a function type is being passed as the first type parameter and below the declaration, there are function with their parameter declared with a function type. [This image](https://lh3.googleusercontent.com/-WaRfe_8fPCI/VwJNygPmATI/AAAAAAAAAC8/HRJwoOCFUhwSz-FA3bNFcy8kRa67Xf7Jw/s1600/3.jpg) for example.
- In [this file](https://github.com/hazagames/Kala/blob/2654369109e02d6f283fcf2eb7ea7097a3b1724b/kala/components/Timer.hx), auto-completion for methods and local variables work but doesn't work for member variables and properties regardless of whether the functions are declared with access modifier or not.

**HaxeDevelop latest build:**
- When I open HD (without any project opened) or when I open / close a project, I get this error:

>    The requested operation requires elevation
> 
>    at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
>    at System.Diagnostics.Process.Start()
>    at HaXeContext.Context.LoadMetadata()
>    at HaXeContext.Context.SetHaxeEnvironment(String sdkPath)
>    at HaXeContext.Context.OnCompletionModeChange()
>    at HaXeContext.Context.BuildClassPath()
>    at ASCompletion.Context.ASContext.Setup(ContextSetupInfos setup)
>    at ASCompletion.Context.ASContext.SetLanguageClassPath(ContextSetupInfos setup)
>    at ASCompletion.PluginMain.HandleEvent(Object sender, NotifyEvent e, HandlingPriority priority)

In all mentioned versions of FD and HD, CompletionServer mode doesn't work in my use cases:
- With my projects using [Kha](https://github.com/KTXSoftware/Kha), this error happens as soon as FD / HD connect to the completion server:

> W:\HaxeToolkit\haxe\std/neko/_std/sys/io/File.hx:30: characters 20-51 : /"W:/Projects/Haxe/kala/build/flash/kha.swf-resources/files.json: Invalid argument
> W:/HaxeToolkit/haxe/lib/kha/git/Sources/kha/internal/AssetsBuilder.hx:46: characters 27-74 : Called from
> W:/HaxeToolkit/haxe/lib/kha/git/Sources/kha/Assets.hx:36: characters 2-7 : Called from
> Aborted

With my projects using [OpenFL](https://github.com/openfl/openfl), I get this whenever I try to build:

> The requested operation requires elevation
>    at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
>    at System.Diagnostics.Process.Start()
>    at HaXeContext.CompletionServerCompletionHandler.StartServer()
>    at HaXeContext.PluginMain.HandleEvent(Object sender, NotifyEvent e, HandlingPriority priority)
>    at PluginCore.Managers.EventManager.DispatchEvent(Object sender, NotifyEvent e)

Note that Haxe completion server works fine when I tried to use VSCode.

The bugs went away if I use FD 5.0.2.

**Comment by SlavaRa** [comment]
Not reproduced in FD 5.2.
