### ISSUE TITLE
"import de.polygonal.ds.Map;" is being auto-added to the top of my class

### ISSUE THREAD

**Issue by andytwoods** [fdorg/flashdevelop#1161]
any tips on how to prevent "import de.polygonal.ds.Map;" from being auto-added to the top of my class I am working on in FlashDevelop, when I mention 'map'?
Must say, being driven slightly mad by this!
Many thanks,
Andy.

Gama11 suggests: "I see what you mean, that's pretty annoying indeed. Top-level imports should be give a higher priority in the completion popup. Try opening an issue on the FD repo!"

PS I originally raised this issue in the haxe google group: https://groups.google.com/forum/#!topic/haxelang/rWVybiZkpP0

**Comment by Gama11** [comment]
![](http://i.imgur.com/anI6SwL.png)

Sorting of the completion list seems completely off to me here - it should be exactly reverse (closest match to least closest match).

**Comment by ianharrigan** [comment]
Something quite annoying also happens with `Void` when using the cpp target, it magically pulls in an import `cpp.Void` which invariably isnt what you actually want.

**Comment by Gama11** [comment]
Yeah, I' ve had that happen to me as well quite a few times..

**Comment by SlavaRa** [comment]
now all ok

**Comment by SlavaRa** [comment]
bump, now all ok
