### ISSUE TITLE
Missing ascsh.jar - incremental compilation doesn't work unless copied manually

### ISSUE THREAD

**Issue by gene-pavlovsky** [fdorg/flashdevelop#1167]
For some reason there is no ascsh.jar included with FlashDevelop, even though according to https://github.com/jcward/ascsh it was included in FD 4.6.1 and later.
After I downloaded `ascsh.jar` from the aforementioned github repo and put it in `FlashDevelop/Tools/flexlibs/lib/`, FD picked it up and incremental compilation started working.
Why is it not included by default?

**Comment by gene-pavlovsky** [comment]
Hmm looks like incremental compilation works even if ascsh.jar is missing from there (but it was not so in FD 5.0). I can see there is `ascsh.jar` in AIR SDK since at least 20.0. Does FD use that one automatically?

**Comment by elsassph** [comment]
Oh wow this is embarrassing it was removed (by mistake I presume) from FD since end of 2014!
Now if you have it in your SDK it's probably that an old FD has copied it in the past -.

**Comment by gene-pavlovsky** [comment]
Oops :) The one I had I've copied there manually, having downloaded it from https://github.com/jcward/ascsh
I've deleted it now and FD uses one from the recent AIR SDK (21.0) automatically (without copying). Incremental compiling works fine. I guess it's not needed anymore? Unless building some legacy project relying on some older SDK that doesn't supply ascsh.jar?

**Comment by elsassph** [comment]
Really ascsh.jar is only added by FD (or manually), and without it I don't see how incremental compilation would work - unless it was somehow built in the asc2 compiler?

**Comment by gene-pavlovsky** [comment]
All right, I see now. The `ascsh.jar` in my AIR SDK was copied there by FD. Freshly downloaded SDK from Adobe doesn't have this file. So I should keep my `FlashDevelop/Tools/flexlibs/lib/ascsh.jar`, and I hope you'll add it back there in 5.1.2 or 5.2 :)

**Comment by gene-pavlovsky** [comment]
@elsassph @Meychi FD 5.2.0 - `aschsh.jar` is still missing from `Tools\flexlibs\lib`. So with a fresh install of the most recent FD, incremental compilation with AIR SDK is not working. And probably most people don't even know about it!

**Comment by gene-pavlovsky** [comment]
Finally :) Better late than never!
Thanks

**Comment by SlavaRa** [comment]
All for you ;)
