### ISSUE TITLE
[haxe] Using -lib abe crashes FD 5.1.1.1

### ISSUE THREAD

**Issue by back2dos** [fdorg/flashdevelop#1168]
After upgrading, as soon as I add the lib through the Project menu, FD crashes while parsing. Unfortunately even adding it as an additional compiler argument (instead of a library) seems to fail.

My current workaround is to have an `extra.hxml` added as additional compiler argument and then added the lib in there. So not a total show stopper, but quite a nuisance.

**Comment by elsassph** [comment]
Where exactly do you specify the lib?

**Comment by back2dos** [comment]
It tried both `abe` in Project > Properties > Compiler Options > Libraries as well as `-lib abe` in Project > Properties > Compiler Options > Additional Compiler Options.

**Comment by elsassph** [comment]
I can't reproduce that with either HD, FD 5.1.0 or 5.2.0 dev; can you share your project file (privately)?

**Comment by SlavaRa** [comment]
Not reproduced. FD 5.3.1.28
