### ISSUE TITLE
"New Class" doesn't ensure last line end

### ISSUE THREAD

**Issue by gene-pavlovsky** [fdorg/flashdevelop#1170]
My `Class.as.fdt` and `Class.as.fdt.wizard` templates in the user dir both have a newline at the end of file. I've enabled `Ensure Last Line End` FD option.
But when I create a New class from project panel's context menu `Add > New Class`, the newly created class doesn't have a newline after the last line. Looks like the template generation trims the ending whitespace, no matter what. I want my last line end ensured! :)

**Comment by Neverbirth** [comment]
I've checked, and this setting (I didn't even know it) is designed to have an effect when saving a file already open in the editor, but not on other operations. I don't know all of the places where ensuring this setting would be required... `MainForm.FileFromTemplate` seems to be the one for this case. Maybe someone could collect all of the places needing change or come up with some common place for any similar operation.

**Comment by gene-pavlovsky** [comment]
I get your point, that's what I thought. Can't be sure if there's another point where that might be also needed, perhaps could check the source code for file saving operations?
Personally I haven't spotted other cases yet.
