### ISSUE TITLE
Replace in selection makes a mess when replacement is shorter than original text

### ISSUE THREAD

**Issue by tom-seddon** [fdorg/flashdevelop#1178]
Built from commit 71b2e6d19b56a8933a2fab35b0182683b895f15c

To reproduce:
1. Create new blank document
2. Enter the text `fred`
3. Highlight `fred`
4. Select Edit | Find And Replace
5. Set up dialog: Find what: `fred`; Replace with: `x`; Look in: `Current selection`; untick all options
6. Click `Replace All`

Expected results: the document contains `x`

Actual results: it contains something like `x\x0\x0\x0` (and Scintilla shows the `\x0` as a little `NUL` graphic)

Other notes: replacing each occurrence individually using the `Find Next` and `Replace` buttons works as expected

**Comment by jan-niestadt** [comment]
I have the same problem in HaxeDevelop (based on FlashDevelop). Also noticed that if you replace with something longer than the original, it only replaces as many characters as are in the occurrence found; after that it ignores the rest of the "replace with" string.

**Comment by SlavaRa** [comment]
Please check it in development version

**Comment by SlavaRa** [comment]
Now all ok
