### ISSUE TITLE
Haxe: Unable to recognize class defined in a swc referenced by -swf-lib

### ISSUE THREAD

**Issue by kevinresol** [fdorg/flashdevelop#118]
FD's autocomplete / refractoring tools are unable to detect classes defined in a swc which is referenced by the -swf-lib compiler flag.

For details please refer to [forum](http://www.flashdevelop.org/community/viewtopic.php?f=13&t=11497)

**Comment by SlavaRa** [comment]
Fixed in development version (for -swf-lib)

**Comment by SlavaRa** [comment]
@Meychi I think that this issue can be closed
