### ISSUE TITLE
Auto-completion for macro-built interface fails in implementing class

### ISSUE THREAD

**Issue by JoeCreates** [fdorg/flashdevelop#1182]
I have an interface for a build macro which automatically adds a field of the interface to an implementing class:

```
@:autoBuild(lycan.components.EntityBuilder.build())
interface Entity { }
```

and interfaces which extend it:

```
interface CenterPositionable extends Entity {
	public var center:CenterPositionableComponent;
    ...
}
```

and classes which implement these interfaces:

```
class Player implements CenterPositionable
```

Outside of the implementing class, auto-complete works, but inside the class it fails. E.g.

```
class Test {
	public function new() {
		new Player().ce // Autocomplete brings up "center" from the interface
	}
}

class Player implements CenterPositionable {
    public function new() {
		this.ce // "center" does not show in the list
	}
}
```
Note that I have tried this with two classes in the same file exactly as above, and auto-complete still works in the test class, but not in the player class that implements the macro-built interface.

**Comment by Gama11** [comment]
Pretty much impossible to tell what's going on here without the code to reproduce.

Generally, you're getting compiler completion?

**Comment by JoeCreates** [comment]
@Gama11 All the code required to reproduce is practically here.

Builder.hx:
```
class Builder {
	public static function build():Array<Field> {return Context.getBuildFields();}
}
```
IBuilder.hx:
```
@:autoBuild(Builder.build())
interface IBuilder { }
```
MyInterface.hx:
```
interface MyInterface extends IBuilder {
    public var completeMe:String;
}
```

MyClass.hx:
```
class Test {
    public function new() {
        new MyClass().compl // Try to get autocomplete on "completeMe" (Succeeds)
    }
}

class MyClass implements MyInterface {
    public function new() {
        this.compl // Try to get autocomplete on "completeMe" (Fails)
    }
}
```

**Comment by JoeCreates** [comment]
One sec, I'll put together a simple test case.

**Comment by JoeCreates** [comment]
It's not quite as simple as I thought. I'm going to close this until I can figure out how to reproduce consistently. I have discovered some other strange behaviour with my current test case, but not yet the original issue. :P
