### ISSUE TITLE
Results panel - don't clear on compile unless there are errors

### ISSUE THREAD

**Issue by gene-pavlovsky** [fdorg/flashdevelop#1185]
In my use case this is related to #1184 - sometimes I want to make some modifications across my code.
I use `Find and replace in files` to find all occurrences of some text, then I review them, and apply some changes to some of the results. So let's say I'm reviewing result 50 out of 100 total results. I make some code changes and build the project just to make sure my changes compile correctly. They do, I want to go continue checking my search results, but the results panel is now empty (after compile). So I have to do the search again, and scroll down the results again, until I find where I left off.
Would it be reasonable if successful compile didn't change the results panel? Or it doesn't make sense?
Alternatively, this would also work (and maybe would be a better feature, albeit more work to implement): remember the last viewed result for each F&R search (or at least for the last search), then if searching with the same search string&options again, set the results panel current item to the remembered item. So `Show next result` hotkey would take me straight to where I left off.

**Comment by wise0704** [comment]
Multiple results panel should've solved this issue.
