### ISSUE TITLE
Keep indent tabs - add indent tabs when indenting a block with empty lines

### ISSUE THREAD

**Issue by gene-pavlovsky** [fdorg/flashdevelop#1186]
I have both `Trim Trailing Whitespace` and `Keep indent tabs` options on.
Mostly it works as expected, except one condition. If I e.g. paste a block of code with 0 indent:

```
line1
// Next line is completely empty (no whitespace).

line2
```

Then select the entire block and press tab to indent it, the empty line won't get indented (I expect it should get indented as well).
If, however, code is like this (indent of 1 tab):

```
    line1
    // Next line has one tab.

    line2
```

I select the entire block and press tab, the whole block including the empty line will be indented by one more tab.

Expected results: I expect that the `keep indent tabs` options is for people who use the `trim trailing whitespace` but prefer empty lines in their code to keep proper indent tabs, so it makes sense to also add tabs to empty lines when indenting an unindented block.
Does it make sense?

**Comment by elsassph** [comment]
Keep indent rule is used when trimming spaces (on save), I'm not sure we can make it work when you press tab as it's based on Scintilla's internal logic.

**Comment by gene-pavlovsky** [comment]
Ok, I've just tested and indeed the trim/keep options have no effect on this behavior (I should have tested first). Well, then, I guess I'd better raise this question with Scintilla's devs, and report here.

**Comment by gene-pavlovsky** [comment]
[Scintilla feature request 1145](https://sourceforge.net/p/scintilla/feature-requests/1145)

**Comment by gene-pavlovsky** [comment]
Please take a look at Neil's comment here: https://sourceforge.net/p/scintilla/feature-requests/1145
And my response.
What do you think?

**Comment by elsassph** [comment]
Well that was kind of expected... Not sure what to do with that keeping indentation is kind of a really weird option in FD.

**Comment by gene-pavlovsky** [comment]
Well think about it when you have time :)

**Comment by gene-pavlovsky** [comment]
https://sourceforge.net/p/scintilla/feature-requests/1145/
Won't be implemented in Scintilla.
Do you still have any idea how this issue can be solved in FD itself?
Neil has mentioned: _While this behaviour is implemented within Scintilla, applications may override the action associated with the tab key to perform as you want._
If you don't want to modify/override the tab behavior,
Maybe when moving the cursor, it can be always positioned at the appropriate (auto-)indent level, regardless of if the line is actually empty (no leading tabs) - adding the right amount of leading tabs if the user types anything on that line?

**Comment by Neverbirth** [comment]
Yes, it's true. We could override the default behaviour of the tab key. For me this is also quite low priority, I also prefer the way it works currently. Some IDEs behave in this way, and others the way you want, so it seems to be a common topic heh.

I expect to commit a Scintilla update soon.

**Comment by gene-pavlovsky** [comment]
Would it be difficult to implement the following?

```
    _line1
    // Next line has no whitespace.

    line2
```

With `_` being the initial caret position, when moving the caret down, it should stay on the same column when it passes the empty line. This is implemented in e.g. Visual Studio.

**Comment by gene-pavlovsky** [comment]
My proposal is outlined in #1686
