### ISSUE TITLE
[haxe] Get rid of forced saving for compiler completion in 3.3+

### ISSUE THREAD

**Issue by Gama11** [fdorg/flashdevelop#1191]
A version check is going to be necessary here for backwards compatibility, but it should make for a better experience when using Haxe 3.3.0+.

See https://github.com/HaxeFoundation/haxe/pull/5120

**Comment by elsassph** [comment]
\o/

**Comment by elsassph** [comment]
We still have to save the other files but that's a huge improvement.

**Comment by SlavaRa** [comment]
Implemented #1318

**Comment by SlavaRa** [comment]
Fixed
