### ISSUE TITLE
Navigate to matching brace with F4

### ISSUE THREAD

**Issue by robinrodricks** [fdorg/flashdevelop#1197]
There should be a command to navigate to the matching curly brace ... that would be super useful for navigating to the end of a function or a long code block.

Is there a function in scintilla to find the line/char indices of the matching brace? Then we can use that data in "F4 / Navigate to Declaration" to navigate to the matching brace.

**Comment by elsassph** [comment]
`Ctrl+M` will match all braces.

**Comment by hgupta9** [comment]
Brilliant! Hidden function .. FD user for years and did not know it. Can you please merge `Ctrl+M` and `F4`?

**Comment by SlavaRa** [comment]
Why hidden?
Search > Goto Matching Brace
Tools > Keyboard chorcuts... > Searchmenu.GotoMatchingBrace
