### ISSUE TITLE
F2 as default shortcut for Refactor Rename

### ISSUE THREAD

**Issue by robinrodricks** [fdorg/flashdevelop#1198]
Refactor>Rename is a super useful command and mostly bug free. Why is F2 not the default shortcut for the command? Can it be added or is it hard since its exposed by a plugin and not part of the default command set?

**Comment by Gama11** [comment]
I'd imagine the main issue is that F2 is alredy used by "SearchMenu.NextBookmark".

**Comment by markknol** [comment]
`ctrl+shift+3`

**Comment by Gama11** [comment]
@markknol Not sure what you're trying to say?

**Comment by markknol** [comment]
Haha Sorry that was my suggestion for the keyboard shortcut :stuck_out_tongue:

**Comment by Gama11** [comment]
That seems pretty specific. Any particular reason? Is that used in other IDEs?

**Comment by markknol** [comment]
Sorry for my confusing reactions. The idea was to keep it next to the magic `ctrl+shift+1`. Most editors have their own shortcut;

visual studio uses : `CTRL+.`
eclipse uses : `ALT+SHIFT+R.`
intellij uses: `Shift+F6`
windows in general uses: `F2`

But while thinking of it, I never used the bookmark functionality so I wouldnt mind to remove that shortcut and use F2 for renaming.

**Comment by elsassph** [comment]
I'd like to use `F2` but it requires to adjust the bookmark shortcut. If something sane comes out of that we can do the shortcut change.

**Comment by wise0704** [comment]
This is what I use currently:
![image](https://cloud.githubusercontent.com/assets/13545633/16194470/b4e6ae08-372f-11e6-9d01-ab74a07a9487.png)
I think since we've added a shortcut set feature, we shouldn't be changing the defaults, but instead introduce new sets.

Meanwhile, #1245 has the VisualStudio.fda set which has the Rename set to F2 as well.
