### ISSUE TITLE
Avast! thinks CodeFormatter.dll is a virus.

### ISSUE THREAD

**Issue by mikedotalmond** [fdorg/flashdevelop#1199]
Hi,

Avast! has recently started identifying CodeFormatter.dll as a virus/suspicious file, so blocks/deletes it when starting the program. FD will complain that it can't find the file, but will still start up ok.

I've not updated FD recently, so am assuming it's likely a false positive after virus definitions were updated.

---

Windows 10 64-bit
HaxeDevelop 5.1.0.3 (master cf5bd2a504)
Avast! Free Antivirus v11.1.2253, Virus definitions: v160419-0

---

![capture](https://cloud.githubusercontent.com/assets/282299/14645875/4a0ce40a-064f-11e6-9ca6-d982e997a22e.PNG)

**Comment by elsassph** [comment]
Avast is crapware.

**Comment by mikedotalmond** [comment]
Well, quite. But what to do about it?
I've whitelisted it for now, so it's not a blocker for me. But thought you'd want to know ;)

**Comment by elsassph** [comment]
Well ok to be more constructive we need to reach our too avast to report it.

**Comment by mikedotalmond** [comment]
Yeah. I did the 'report false positive' action with a short description of the problem.. but who knows how long it may take for them to act on it.

**Comment by Meychi** [comment]
Is this fixed?

**Comment by SlavaRa** [comment]
Yep
