### ISSUE TITLE
HaxeDevelop tooltip formatting eats characters

### ISSUE THREAD

**Issue by IBwWG** [fdorg/flashdevelop#1200]
The tooltip on Haxe's Array.copy() seems off:

![haxedevelop-weird-tooltip](https://cloud.githubusercontent.com/assets/16719964/14673236/09707020-06fd-11e6-9c70-b45634e62243.png)

Whereas the actual javadoc-style comment seems to be formatted OK:

```haxe
	/**
		Returns a shallow copy of `this` Array.

		The elements are not copied and retain their identity, so
		`a[i] == a.copy()[i]` is true for any valid `i`. However,
		`a == a.copy()` is always false.
	**/
```

It looks like it's interpreting `[i]` as an italics starter.  I think it shouldn't do that within grave accents.

**Comment by Neverbirth** [comment]
Duplicate

**Comment by Neverbirth** [comment]
I have this working together with several other improvements... but there are a couple of things to improve on it, plus all of the changes are built on top on this work: https://github.com/fdorg/flashdevelop/pull/1026

**Comment by IBwWG** [comment]
Oh, sorry.  I did search...what was it under?

**Comment by IBwWG** [comment]
Ah, thanks.

**Comment by Neverbirth** [comment]
https://github.com/fdorg/flashdevelop/issues/529

**Comment by Neverbirth** [comment]
No problem at all. If you are interested to play with that build drop me a mail or something. I like to think it can encourage people to document more of their libraries public API.
