### ISSUE TITLE
Back button during F4 navigation

### ISSUE THREAD

**Issue by IBwWG** [fdorg/flashdevelop#1206]
Sometimes when investigating how a class works, I end up following a long trail by pressing F4 with the keyboard cursor on various keywords.  I've had it happen a few times, especially within a file where the scroll position has no history, when I wished that there was some way to go back to the previous position, where I was before I pressed F4.  (Between files it works a bit better, if I can remember the last file, which is usually the neighbouring tab, I just switch to it and it's in the right position.  However, if F4 history could be tracked between tabs, that would be even more useful.)

**Comment by elsassph** [comment]
Good point, we should consider remembering the scroll position as well.

**Comment by wise0704** [comment]
Remembering the scroll position isn't that necessary. Since there is Back from Declaration, that command just needs to stop positioning the cursor on the border.

**Comment by IBwWG** [comment]
Wow, how did I not see that?  And it also goes back between tabs already.  I'm not sure what you mean by position the cursor on the border, it seems to put it wherever it was.  It even seems to have magically generated history beyond when I started pressing F4.  ;)

**Comment by wise0704** [comment]
Oh okay, so scroll position is also remembered?
You can close this issue if everything is resolved :)
