### ISSUE TITLE
how get document-class in pre-build command line

### ISSUE THREAD

**Issue by matrix3d** [fdorg/flashdevelop#1211]
$(CompilerPath)/js/bin/mxmlc.bat -debug=true -external-library-path="$(CompilerPath)\js\libs\js.swc" -compiler.source-path=../src src/Main.as -define=CONFIG::as_only,false -define=CONFIG::js_only,true

how get the Main.as

**Comment by elsassph** [comment]
I'm afraid there isn't any argument for that - you should be able to extract it from the .as3proj file during prebuild phase.

**Comment by matrix3d** [comment]
maybe should add it.

the bat hard extract it from .as3proj
