### ISSUE TITLE
[haxe] function type as type parameter is missing right angle bracket

### ISSUE THREAD

**Issue by Gama11** [fdorg/flashdevelop#1218]
![](http://i.imgur.com/zWF3iuy.png)

The outline panel shows `Void-Void` instead of `Void->Void`.

**Comment by Neverbirth** [comment]
Before @elsassph says anything, this is an old bug predating any recent change heh. I'm aware of this and hopefully this week I can fix it together with the other problems recently reported.

**Comment by Gama11** [comment]
Really? Interesting I had never noticed it before now then, I guess it's pretty subtle though. :)

**Comment by Neverbirth** [comment]
Yeah, it's been there since at least 4.7.0, but I wouldn't be surprised if it's been forever.

**Comment by SlavaRa** [comment]
now all ok
