### ISSUE TITLE
code hint not work in some case

### ISSUE THREAD

**Issue by ylazy** [fdorg/flashdevelop#1223]
case 1:

var instance:Something = new Something();
instance
.property1
/\* code hint will not work after this comment */
.property2

so code hint will not work with property2 (Animate CC do work. So I think it seem like a bug)

case 2 (adding code hint support for "with" statement

with (instance)
{
// code hint will not work here
}

Please consider to fix it.

Thanks!

**Comment by elsassph** [comment]
Case 1 is an old limitation - we should try solving it but it's not trivial.
Case 2: we don't plan to support `with`.

**Comment by ylazy** [comment]
Case 3:
instance
.func('code hint will not work after ; (SemiColon)')
.hintMePlease

This work:
instance
.func('replace SemiColon to \x3B to fix it')
.gotTheHintThanks

**Comment by ylazy** [comment]
@elsassph I've found a trick to force Case 1 work: use three dot:
instance
.property1
// one line comment
/* multiline comment */
...[code hint showed up]

That mean, I can use three dot to force display the code hint, then delete 2 dot later.
So I think FD could emulate (reproduce) this behavior to fix this issue?

**Comment by ylazy** [comment]
Update:
Code hint will not work in this case:
function(param1:String = '[', param2: <= does not work

Additional, there're no code hint for built-in method like "hasOwnProperty"

Hope this will be fixed on future :)
