### ISSUE TITLE
Ability to select code comment tooltips

### ISSUE THREAD

**Issue by ylazy** [fdorg/flashdevelop#1224]
An Identifier (function/var/...) can contains comment with example or link (http, ftp) that I need to copy, but I'm not able to select it since it will disappear when I move the mouse. I know that I could press F4 to jump to the definition then copy, but if I need to copy multi lines, I have to copy unwanted asterisk and tab characters. It would be great if I can press a shortcut key to allow the tip stay visible when I move the mouse after rolling over an identifier.

Please consider to add this feature.

Thanks!

**Comment by wise0704** [comment]
???

![image](https://cloud.githubusercontent.com/assets/13545633/16176705/8498d698-3650-11e6-882e-31a58570d385.png)

**Comment by wise0704** [comment]
As a side note, I think the mouse hover tooltip should be disabled when completion list tooltip is being displayed.

**Comment by ylazy** [comment]
It really helped. Thank so much!
