### ISSUE TITLE
Horizontal Scroll Bar bug: cannot scroll to end of line

### ISSUE THREAD

**Issue by ylazy** [fdorg/flashdevelop#1235]
Please see the attached image:

![scrollbar-bug](https://cloud.githubusercontent.com/assets/6010183/15286949/e238ab16-1b89-11e6-8c44-f488c09f5769.png)

Thanks!

**Comment by elsassph** [comment]
Unfortunately this editor component has a fixed maximum width, but it can be increased in: 
`Program Settings > FlashDevelop > Editor > Scroll Areal Width`

You may want to just set line wrapping.

**Comment by ylazy** [comment]
Thanks! I changed it from 3000 to 12000 and it seems not affect to the performance.
