### ISSUE TITLE
Ability to add new Document Type

### ISSUE THREAD

**Issue by ylazy** [fdorg/flashdevelop#1236]
I can't find any guide about adding new Document Type (File > New > ...)

I placed new files (AS3 Class.fdt, AS3 Event.fdt, AS3 Static Class.fdt)
to
C:\Users\%username%\AppData\Local\FlashDevelop\Templates
then restart FD
but no luck?
If I missing somethings? Please help!

Thanks!!!

**Comment by elsassph** [comment]
- Copy `C:/Program Files/FlashDevelop/Settings/MainMenu.xml`,
- Select Tools > User Config Files... to open your user FD files,
- Paste and edit `MainMenu.xml` under `/Setting/MainMenu.xml`.

**Comment by ylazy** [comment]
Seem like a little bug here. The labels was not displayed

![label1](https://cloud.githubusercontent.com/assets/6010183/15308731/6d5818d2-1c0a-11e6-9586-fa2cb4e3854a.png)
![label2](https://cloud.githubusercontent.com/assets/6010183/15308733/72fc0c8a-1c0a-11e6-8159-e05a911c2995.png)
![mainmenu](https://cloud.githubusercontent.com/assets/6010183/15308738/7703eb86-1c0a-11e6-86dd-9ffc1e15267a.png)

Thanks!

**Comment by ylazy** [comment]
Sorry! It's my mistake. I replaced "Label.AS3ClassDocument" by "AS3 Class Document" and now it worked!

Thank so much!
