### ISSUE TITLE
adding $(className) and $(package) params

### ISSUE THREAD

**Issue by ylazy** [fdorg/flashdevelop#1237]
I need a way to add $(className) and $(package) params to my template files:

When I create a new file from template, and if the template contains $(className), FD should prompt to enter class name, so the new file will be created with all $(className) that replaced to the entered value.

Also, If my template file contains $(package) or both $(package) and $(className), FD should prompt where to save the new file, then replace $(package) and $(className) to these corresponding values.

Please consider to add support to these params.

A related question: is there a way to execute one or more macro via command prompt? If I could do it, I can execute a batch file to prompt class name, then execute the macro "NewFromTemplate" to create a new file from a modified fdt template. But even if it's possible, I still cannot handle the $(package)

Please help!

Thanks!

**Comment by markknol** [comment]
Maybe you can use `$(CurFilename)`? 

You can create custom properties with 2 money bags :moneybag::moneybag: `$$(customValue=defaultValue)`. See bottom of this page http://haxedevelop.org/arguments.html

To trigger this dialog from a macro you can use this:
```cs
string myValue = PluginBase.MainForm.ProcessArgString("$$(customValue=A,B,C)");
```

**Comment by ylazy** [comment]
Thank so much @markknol 
$(CurFilename) didn't solve the problem but custom arguments $$(className) work!.

The only issue is that I still cannot handle the $(package), but FlashDevelop will fix the package as soon as the class saved.

I readed the [help docs](http://www.flashdevelop.org/wikidocs/index.php?title=Arguments) before asking but didn't fully understand the "dynamic argument" term, until I see the illustrated image on the haxe page.

Thanks!
