### ISSUE TITLE
[Haxe] Problem with package names beginning with capital letter

### ISSUE THREAD

**Issue by thomasfkeefe** [fdorg/flashdevelop#1240]
Using HaxeDevelop 5.1.1.1 for .Net 3.5. The project is Lime based Haxe. I am attaching the
project.xml (as project.txt) file I am using. I am running on Windows 7.
[project.txt](https://github.com/fdorg/flashdevelop/files/288547/project.txt)

I used the add directory in the project window to create a directory named "Manager". Then
I refactored a class file to move it into the Manager package. Haxedevelop automatically updated
the references. However, when I try to build I get a message saying that it cannot find the type
"Manager".

Then I renamed the directory using HaxeDevelop to "manager" with reference updating. Then compilation worked as expected.

If you need more information let me know.

Tom

**Comment by elsassph** [comment]
I believe Haxe packages MUST start with a lowercase character.
