### ISSUE TITLE
appman exception

### ISSUE THREAD

**Issue by kuimoani** [fdorg/flashdevelop#1258]
Hi,
I use FD5.1.1.1 ....

when I run appman, below error is occured. what happend?

=============================================================================
System.InvalidOperationException: XML 문서(571, 65)에 오류가 있습니다. ---> System.Xml.XmlException: EntityName을 구문 분석하는 동안 오류가 발생했습니다. 줄 571, 위치 65
   위치: System.Xml.XmlTextReaderImpl.Throw(Exception e)
   위치: System.Xml.XmlTextReaderImpl.Throw(String res, String arg)
   위치: System.Xml.XmlTextReaderImpl.ParseEntityName()
   위치: System.Xml.XmlTextReaderImpl.ParseEntityReference()
   위치: System.Xml.XmlTextReaderImpl.Read()
   위치: System.Xml.XmlTextReader.Read()
   위치: System.Xml.XmlReader.ReadString()
   위치: System.Xml.XmlTextReader.ReadString()
   위치: System.Xml.XmlReader.ReadElementString()
   위치: Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderDepEntries.Read2_DepEntry(Boolean isNullable, Boolean checkType)
   위치: Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderDepEntries.Read3_Entries()
   --- 내부 예외 스택 추적의 끝 ---
   위치: System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader, String encodingStyle, XmlDeserializationEvents events)
   위치: System.Xml.Serialization.XmlSerializer.Deserialize(TextReader textReader)
   위치: AppMan.Utilities.ObjectSerializer.Deserialize(String file, Object obj, String groups)

System.NullReferenceException: 개체 참조가 개체의 인스턴스로 설정되지 않았습니다.
   위치: AppMan.MainForm.PopulateListView()

**Comment by kuimoani** [comment]
this is concerned with the below commit.

https://github.com/fdorg/flashdevelop/pull/1259

**Comment by Meychi** [comment]
The fix was merged and it should be up in few minutes when the CI build is ready. Thanks for reporting.
