### ISSUE TITLE
[haxe] Goto Declaration not compatible with "using"

### ISSUE THREAD

**Issue by Gama11** [fdorg/flashdevelop#126]
Pressing F4 while the `trim()` of the first line in `new()` is selected doesn't work. It does work just fine in the line after that. 

```haxe
package;

using StringTools;

class Test
{
	public function new() 
	{
		"Test ".trim();
        StringTools.trim("Test ");
	}
}
```

**Comment by SlavaRa** [comment]
This is works in last release

**Comment by Gama11** [comment]
Right, because of #729. :)
