### ISSUE TITLE
Contextual Generator issue with declaration detection

### ISSUE THREAD

**Issue by wise0704** [fdorg/flashdevelop#1260]
This is the method declaration:
![image](https://cloud.githubusercontent.com/assets/13545633/16221459/d37292c6-37cd-11e6-9000-6c75038175a5.png)

But somehow it thinks this is the declaration:
![image](https://cloud.githubusercontent.com/assets/13545633/16221454/cc8c3002-37cd-11e6-8cb1-ac47816d86e0.png)

And nothing works when I press Enter.

**Comment by elsassph** [comment]
This refactoring action is meant to modify the declaration based on the arguments used in a local call. Try adding an argument like `init('foo')` and execute the Change method declaration action.

**Comment by wise0704** [comment]
Then shouldn't the option be invisible when the invocation matches the declaraion?

**Comment by wise0704** [comment]
anyways, closing
