### ISSUE TITLE
"Add > New Interface" dialog title says "New class"

### ISSUE THREAD

**Issue by gene-pavlovsky** [fdorg/flashdevelop#1269]
When opening `Add > New Interface` from Project panel, the dialogs says "New AS3 class". I even thought I opened the wrong dialog, or that there's a bug. But no, actually it does create an interface, so the only problem is the dialog title (and header as well).

**Comment by SlavaRa** [comment]
@Meychi @elsassph what do you think about this?

**Comment by SlavaRa** [comment]
Now all ok

**Comment by gene-pavlovsky** [comment]
Just tried latest development build.
With a clean build (.local) it works correctly (New interface is displayed)
But with my user profile (in AppSettings) the problem still exists.
Any pointers as to which setting I should clear to fix this?
