### ISSUE TITLE
Serious file corruption issue! (FD dev build 5.2.0.68)

### ISSUE THREAD

**Issue by gene-pavlovsky** [fdorg/flashdevelop#1270]
I have a critical issue since installing the 5.2.0.68 development build yesterday.
I was just editing a class file, and all of a sudden my project stopped compiling, complaining about multiple errors in that file. All the error messages pointed to the last line of the file (beyond the final `}`). But I couldn't find any actual errors in the code, such as mismatched braces or quotes. Even when I cut out all the code in that class, leaving an empty class in a package, it still would give all those compile errors.
Strange thing is, when I opened the file in Notepad, I could see a bunch of spurious code (looking like a block of code from the same class) beyond the last `}` of the file. It doesn't show up when viewing the file in FD. But if I close and reopen file in FD I can see that code. Strangely, if I delete that crap in FD and save again, then check the saved file with a text viewer, it still has the crap in there. I had to exit FD, roll back the file to the last version, compile and then make more changes. I have no idea at all how to reliably reproduce it. Just what I was doing is adding a few more functions to the class, and using F&R dialog to rename some properties in several functions. Any idea?

Or, for example, my main class compiled fine just a moment ago. I uncommented two lines of code, saved, and hit F8. Getting an error "...\src\SandBox.as:2071: Syntax error: extra characters found after end of program."
Checking `Sandbox.as` with a text viewer and there's an extra `}` after the last line. File is open in FD and doesn't show that line, close and reopening the file makes it show up. So somehow uncommenting two lines of code and saving the file added another line with `}` at the end of the file.

**Comment by elsassph** [comment]
Noticed that too today when updating from dev. Critical issue indeed.

Thankfully the bug is only adding garbage at the end of the file so there is no data loss. It seems that when saving a file with less characters will keep the additional characters already on disk.

We're looking into that.

**Comment by gene-pavlovsky** [comment]
Was in the countryside all weekend, had to work like this. Saving file, compile error (was refactoring, file kept shrinking), open in notepad, trim the file, reload, compile.
Thanks for fixing it quickly!

**Comment by elsassph** [comment]
Haha Gene I did the same (edit in notepad to trim)...
