### ISSUE TITLE
[Haxe] Autocomplete broken for packages started from underscore

### ISSUE THREAD

**Issue by yar3333** [fdorg/flashdevelop#1273]
Autocomplete inside class from package like "_pack" say "Error: Display file was not found in class path".

Open _bad/MyBad.hx and try autocomplete.
[UnderscoreIssue.zip](https://github.com/fdorg/flashdevelop/files/335646/UnderscoreIssue.zip)

**Comment by elsassph** [comment]
I'm afraid this is a limitation of the Haxe compiler completion.
I did a quick go at VS Code with your sample and completion doesn't work at all inside MyBad.hx.

**Comment by yar3333** [comment]
Ok, Philippe, I create issue in Haxe thread.
