### ISSUE TITLE
In some case properties and function shouldn't be accessible but they are

### ISSUE THREAD

**Issue by dimmp** [fdorg/flashdevelop#1280]
Hello, 
It look like an issue :)

`class NewClass
{
	
	public static var list:Array<NewClass> = new Array<NewClass>();

	private var myPrivateVar:Float = 3;
	
	public function new() 
	{
		list[0].myPrivateFunction; 	// shouldn't be accessible
		list[0].myPrivateVar; 		// here neather
	}
	
	private function myPrivateFunction (): Void {
		
	}
	
}`

**Comment by SlavaRa** [comment]
"shouldn't be accessible"
why?

**Comment by dimmp** [comment]
because the property is private. list[0] is not necessary the same than this. no ?

**Comment by SlavaRa** [comment]
NewClass has access to their private properties and methods
for example http://try.haxe.org/#70624

**Comment by dimmp** [comment]
alright I didn't know that. I thought the access was depending of instances and not classes. Thank you

**Comment by SlavaRa** [comment]
please close this issue)
