### ISSUE TITLE
Incorrect `openfl display` command when opening a new project

### ISSUE THREAD

**Issue by jgranick** [fdorg/flashdevelop#1281]
Hello!

When opening a new project for the first time, I have the seen the following in the error log output sometimes:

```
Error: "project.xml" is an unknown target
```

I investigated, and found that FlashDevelop is calling this command:

```
openfl display project.xml -release
```

I am certain, but I think that this may be that the command runs before the target drop-down populates, sending a blank target and causing the error. Inserting a fallback target, or skipping the command, should remove the error:

```
openfl display project.xml flash -release
```

**Comment by elsassph** [comment]
Oh you may be right, just after creating a project I know the config is incorrect...
