### ISSUE TITLE
Feature: Tools > Process entire file / selection with the specified command

### ISSUE THREAD

**Issue by gene-pavlovsky** [fdorg/flashdevelop#1286]
It would be great if it was possible to pipe the current file or selected block to a specified command, and replace the file / selection with the result of that command. As a bonus, the UI for that tool should be able to manage a list of commonly used commands, assign hotkeys to them (and maybe remember last used commands).
It would allow to add some common block / file operations which FD is currently missing, e.g. make a block of text upper-case/lower-case, merge/remove blank lines, convert charset etc. - everything can be accomplished using command-line text processing tools.
Currently I have to run dd/sed/awk etc. on files manually from a shell - more cumbersome than just hitting a hotkey from FD, but most of all it doesn't allow for easy processing of a particular selected block of text.
How do you think about this idea?

**Comment by Neverbirth** [comment]
I'd say this can be done with macros, or if needed something a bit more powerful a plugin. But not integrated inside FD itself.
If you want we can discuss this over the weekend on Skype.

**Comment by gene-pavlovsky** [comment]
I'd like to help, ready to meet over the weekend (have to consult wife regarding date & time).
