### ISSUE TITLE
 Results panel: dragging scrollbar thumb issue

### ISSUE THREAD

**Issue by gene-pavlovsky** [fdorg/flashdevelop#1287]
1. Use `Find and Replace in File` to find some text (I tried two different queries, giving 10 and 170 results).
2. Drag the results panel's scrollbar's thumb. Slight movements of the mouse result in huge jerky motions, sometimes causing entire contents of the panel to disappear, sometimes scrolling the contents too far up (i.e. to a negative scroll position).

![Negative scroll position](https://i.imgur.com/0hlXjSw.png)
![Entire contents scrolled somewhere off-screen](https://i.imgur.com/hMGcdUv.png)

PS. The output panel is scrollable by thumb-dragging without issues.

**Comment by Neverbirth** [comment]
Seems to be a custom scrollbar issue.

**Comment by gene-pavlovsky** [comment]
Can't reproduce anymore
