### ISSUE TITLE
Advanced Shortcut - breaks plugin(s)

### ISSUE THREAD

**Issue by gene-pavlovsky** [fdorg/flashdevelop#1303]
Originally reported in [here](https://github.com/fdorg/flashdevelop/pull/1245#issuecomment-242407347)
On FD startup, there are around 10 identical exceptions:

```
Method not found: 'Boolean ASCompletion.Completion.ASComplete.OnShortcut(System.Windows.Forms.Keys, ScintillaNet.ScintillaControl)'.

   at PostfixCodeCompletion.PluginMain.HandleEvent(Object sender, NotifyEvent e, HandlingPriority priority)
   at PluginCore.Managers.EventManager.DispatchEvent(Object sender, NotifyEvent e)
```

This is the plugin throwing the exceptions: https://github.com/SlavaRa/fdplugin-postfix-code-completion

**Comment by Neverbirth** [comment]
I'll try to push the commit once I return to home later today if @wise0704 is not able to commit anything before.
