### ISSUE TITLE
[Haxe] Support of -D display-stdin

### ISSUE THREAD

**Issue by SlavaRa** [fdorg/flashdevelop#1311]
https://github.com/HaxeFoundation/haxe/pull/5120

**Comment by SlavaRa** [comment]
WIP

**Comment by Neverbirth** [comment]
With WIP you mean you are looking into it?

**Comment by SlavaRa** [comment]
I did support for the PostfixCodeCompletion , and now plan to make support for the editor, I'll be ready to do PR on this week

**Comment by Neverbirth** [comment]
Good one, although I have to admit I got used to the automatic saving and now I like it heh. IJ does it too for every project.

**Comment by SlavaRa** [comment]
those who use the editor via CrossOver complain that the permanent saving create problems((

**Comment by elsassph** [comment]
We really want to avoid this saving for sure. But careful keeping backwards compatibility - some people here still use Haxe 3.1.3!

**Comment by SlavaRa** [comment]
depending on the compiler will operate in different modes ))
