### ISSUE TITLE
Compiler Variables not working for SWC project.

### ISSUE THREAD

**Issue by raasumy** [fdorg/flashdevelop#1312]
I've started an SWC library project in FlashDevelop. By some unknown reason it does not recognize compiler variables and compiler constants set in apropriate menus of IDE. Even built in variables referred in as3 code are causing errors during build, like CONFIG::debug or CONFIG::release
gs.as(323): col: 12 Error: Access of undefined property release.

**Comment by wise0704** [comment]
Try the extension I made [here](http://flashdevelop.org/community/viewtopic.php?f=4&t=12458) :)
It's available via AppMan as well.

**Comment by raasumy** [comment]
Thanks, great extension. But still no luck with my project. Should it work fine with previously created projects or I must create one from scratch with extension installed?

**Comment by wise0704** [comment]
It's a compiler tool + project template, so it's meant to work with newly created projects with the provided template.

However, you can manually set up your existing project to use the compiler tool. In Project Properties window:
- Set OutputType to CustomBuild.
- Set PreBuildCommand to `"$(BaseDir)\Tools\swcbuild\swcbuild.exe" "$(ProjectPath)" "-compiler=$(CompilerPath)" "-debug=$(BuildConfig)" "-library=$(AppDir)\Library" -asdoc=true -keep-asdoc=false`.

You can see those values in the project template (`$(BaseDir)\Projects\132 ActionScript 3 - AS3 Library Project\Project.as3proj`).

**Comment by raasumy** [comment]
Thank you. Works like charm!

**Comment by wise0704** [comment]
@elsassph we could maybe remove the default swc library project template?
