### ISSUE TITLE
New setting `Max recent files` gets set to 0 by default!

### ISSUE THREAD

**Issue by gene-pavlovsky** [fdorg/flashdevelop#1313]
Apparently there is a new setting `Max recent files`, for some reason it was set to 0.
So my `File > Recent Files` menu didn't show anything, ever. Great think @Meychi told me what was the problem, hopefully there will be a sensible default value soon.

**Comment by SlavaRa** [comment]
15 by default

**Comment by gene-pavlovsky** [comment]
I don't know how, but I didn't know about this setting (didn't touch it), and when Mika told me to check it, it was 0.

**Comment by gene-pavlovsky** [comment]
Thanks!
