### ISSUE TITLE
Fails to edit project file causing `Exception has been thrown by the target of an invocation`

### ISSUE THREAD

**Issue by DleanJeans** [fdorg/flashdevelop#1317]
Here's 2 revisions of my project file: [Gist](https://gist.github.com/DleanJeans/8f3c912aeb9f36d913210f383a018de3)

Apparently, FD has failed to edit the project file. This causes the exception in the title which stops the user from building the project or opening it if not already. This part has been added to the end of the file:
```
on testMovieCommand="" />
  </options>
  <!-- Plugin storage -->
  <storage />
</project>
```
Which seems to be a part of the text above it:
```
  <options>
    <option showHiddenPaths="False" />
    <option testMovie="Custom" />
    <option testMovieCommand="" />
  </options>
  <!-- Plugin storage -->
  <storage />
</project>
```
So the result:
```
  <options>
    <option showHiddenPaths="False" />
    <option testMovie="Custom" />
    <option testMovieCommand="" />
  </options>
  <!-- Plugin storage -->
  <storage />
</project>on testMovieCommand="" />
  </options>
  <!-- Plugin storage -->
  <storage />
</project>
```

**Comment by Neverbirth** [comment]
I guess this is the same as #1330?
