### ISSUE TITLE
OpenFL code completion issue

### ISSUE THREAD

**Issue by voec** [fdorg/flashdevelop#1325]
_Using HaxeDevelop 5.1.1.1 + OpenFl 3.6.1 (+ HaxePunk 2.5.6)_

I'm having issues with the code completion tooltip when using OpenFl. Basicly if I type `myBitmapData.noise()` in HaxeDevelop I should get a small tooltip explaining what the function does. aka `Fills an image with pixels representing random noise. and then an explanation for each parameter.`

But sometimes (somehow relating to importing classes or extending my class) I only get the basic function and parameter names/types.

Here is a visual example:

![openfltooltip](https://cloud.githubusercontent.com/assets/2915643/18416577/b12da42c-7818-11e6-8644-d2cdd3d60c53.gif)

This seems to have something to do with OpenFl extern folders

For more info, I also wrote on the OpenFL forums since I thought it was an issue with OpenFL first:
http://community.openfl.org/t/code-completion-missing-function-description/8144
"player_03" describes what's actually happening quite well there from the OpenFl side.

At first I thought it had something to do with extending HaxePunk classes, but it also seems to happen when I just write garbage.

**Comment by SlavaRa** [comment]
Completion Mode: CompletionServer, Compiler

**Comment by SlavaRa** [comment]
not reproduced in the latest development-build
