### ISSUE TITLE
OCaml language support

### ISSUE THREAD

**Issue by ncannasse** [fdorg/flashdevelop#1338]
Here's a file to support syntax highlight for OCaml, which is used for haxe compiler (so suitable for HaxeDevelop), haxe compiler sources have a .hxproj ready to compile & run once you have installed OCaml.

[OCaml.txt](https://github.com/fdorg/flashdevelop/files/473532/OCaml.txt)

(should be renamed as OCaml.xml and put into the `User/<name>/AppData/Local/HaxeDevelop/Settings/Languages` directory for manual install)

**Comment by SlavaRa** [comment]
@elsassph @Meychi @Neverbirth what you think about this?

**Comment by Neverbirth** [comment]
I'm completely OK with it. I already approved for this when the issue was created. Plus I've started to learn OCaml this week, so...

**Comment by Meychi** [comment]
Im also fine with this but this needs syntax  coloring for all built in themes for complete integration.

**Comment by Neverbirth** [comment]
In progress.
