### ISSUE TITLE
Refactor-->Organize Imports Doesn't Work when Separate Packages is enabled

### ISSUE THREAD

**Issue by dkinside** [fdorg/flashdevelop#1342]
Env：
    as3 project

```
FlashDevelop 5.2.0.113 for .net 3.5
jdk-8u102-windows-i586
win10x64
```

**Comment by Neverbirth** [comment]
Could someone else confirm? When I tried it worked for me. But I didn't try too much. Maybe something related to your particular project/class?

**Comment by dkinside** [comment]
Tools-->Program Settings-->CodeRefactor-->Separate Packages
When the option is [True], "Organize Imports" result is wrong

**Comment by SlavaRa** [comment]
Not reproducible.
FD 5.3.1.28, AS3, Haxe
