### ISSUE TITLE
Show inherited items outside [inherited]

### ISSUE THREAD

**Issue by hgupta9** [fdorg/flashdevelop#136]
Usually in the FD4 debugger inherited items show inside a `[inherited]` tree item. This is very annoying and simple things like Sprites, show x/y properties inside `[inherited]`, instead of listing it side by side with other properties.

Please add the following code, and a single setting the FlashDebugger plugin (`ShowInheritedSideBySide`), which allows inherited members to be optionally displayed side by side.

**DataTreeControl.cs**

	void TreeExpanding(Object sender, TreeViewAdvEventArgs e) {
	   ....
	   if (inherited.Count > 0) {
	   
		  if (ShowInheritedSideBySide){

			 // list inherited members alongside main class members
			 foreach (DataNode item in inherited) {
				node.Nodes.Add(item);
			 }
			 
		  }else{
			 
			 ... EXISTING CODE ...
			 
			 DataNode inheritedNode = new DataNode("[inherited]");
			 
			 .....................
			 
		  }
	   }
	   ....
	}

**Comment by Meychi** [comment]
In progress for FD5, has PR.
