### ISSUE TITLE
Find All References - wrong results if function and param share same name

### ISSUE THREAD

**Issue by PierrotLL** [fdorg/flashdevelop#1370]
Hello,

It's a small bug, the "Find All References" feature makes mistakes about internal and public scopes.

Example :

```
File 1:
public function Main () : void {
    randomName(1);
}

File 2:
public function randomName (randomName:int) : void { // try Find All References on function name here
    randomName++;
}
```

Results gives the 3 occurrences of "randomName" in file 2 while they are not referring to the same object, and no allusion to the call in file 1.

**Comment by SlavaRa** [comment]
This is a very serious problem. I'm working on fixing it.
