### ISSUE TITLE
Vector.<*> incorrectly parsed

### ISSUE THREAD

**Issue by Neverbirth** [fdorg/flashdevelop#1383]
When typing `Vector.<*>` we get back a model with just `Vector.` as its type.

**Comment by Neverbirth** [comment]
For future reference: after fixing this issue remove hack introduced in https://github.com/fdorg/flashdevelop/commit/de9a4c0104646004d76419506dac03a55d453e6c.

**Comment by SlavaRa** [comment]
Will be fixed today
