### ISSUE TITLE
Error when asking for Override completion

### ISSUE THREAD

**Issue by deepnight** [fdorg/flashdevelop#1393]
If I type "override" and add a space afterward, I get an error window.
I use HaxeDevelop 5.2.0.3, and my source code is in Haxe (sorry, the error is in French). Also affects FlashDevelop 5.2.0. This error doesn't happen in any HaxeDev/FlashDev 5.1.x .

![bug](https://cloud.githubusercontent.com/assets/1671695/20069268/36469d5a-a51c-11e6-929b-c6227e8b261c.jpg)

"La référence d'objet n'est pas définie à une instance d'un objet.

   à ASCompletion.Completion.ASGenerator.HandleOverrideCompletion(ScintillaControl sci, Boolean autoHide)
   à ASCompletion.Completion.ASGenerator.HandleGeneratorCompletion(ScintillaControl Sci, Boolean autoHide, String word)
   à ASCompletion.Completion.ASComplete.OnChar(ScintillaControl Sci, Int32 Value, Boolean autoHide)"

**Comment by Neverbirth** [comment]
Does it happen in a nightly build too? Also, does this happen only on that file or everywhere you try?

**Comment by SlavaRa** [comment]
Now all ok
