### ISSUE TITLE
Autocomplete is not working with libreries added as -swf-lib-extern

### ISSUE THREAD

**Issue by dkolyesnik** [fdorg/flashdevelop#1405]
Autocomplete is not working with libraries added as -swf-lib-extern. Neither with Compiler Compiler Mode nor with CompilationServer.

**Comment by Neverbirth** [comment]
Then maybe this should be considered a Haxe problem? Although FD could also check those SWCs.

**Comment by dkolyesnik** [comment]
Compilation is working fine. 
I'm using dev build HaxeDevelop 5.2.1.39. hxml platform.

**Comment by Neverbirth** [comment]
Not talking about compilation itself, but Haxe maybe should be able to return completion information for these cases?

**Comment by SlavaRa** [comment]
compiler args with `-swf-lib-extern`:
`-main ApplicationMain  --macro "openfl._internal.utils.ExtraParams.include()" -cp "C:/HaxeToolkit/haxe/lib/openfl/4,4,1" -D openfl=4.4.1 --macro "lime.Lib.extraParams()" -cp "C:/HaxeToolkit/haxe/lib/lime/3,4,1" -D lime=3.4.1 -cp "src" -cp "c:\HaxeToolkit\haxe\lib\openfl/4,4,1/externs/core/flash" -cp "c:\HaxeToolkit\haxe\lib\openfl/4,4,1/externs/core/openfl" -cp "c:\HaxeToolkit\haxe\lib\openfl/4,4,1/externs/extras" -D tools=3.4.1 -D no-compilation  -D openfl-flash  -D web -swf-lib-extern lib/as3corelib.swc -swf-lib-extern lib/mx.swc -swf-version 11.2 -swf bin/flash/release/bin/OpenFLApp.swf -swf-header 800:480:60:000000 -cp "bin/flash/release/haxe" -D display  --display "C:\projects\OpenFLApp\src\Main.hx"@262 -D use_rtti_doc -D display-details -D display-stdin`
result: `No classes found in mx\n\u0002\n`

compiler args with `-swf-lib`:
`-main ApplicationMain  --macro "openfl._internal.utils.ExtraParams.include()" -cp "C:/HaxeToolkit/haxe/lib/openfl/4,4,1" -D openfl=4.4.1 --macro "lime.Lib.extraParams()" -cp "C:/HaxeToolkit/haxe/lib/lime/3,4,1" -D lime=3.4.1 -cp "src" -cp "c:\HaxeToolkit\haxe\lib\openfl/4,4,1/externs/core/flash" -cp "c:\HaxeToolkit\haxe\lib\openfl/4,4,1/externs/core/openfl" -cp "c:\HaxeToolkit\haxe\lib\openfl/4,4,1/externs/extras" -D tools=3.4.1 -D no-compilation  -D openfl-flash  -D web -swf-lib lib/as3corelib.swc -swf-lib lib/mx.swc -swf-version 11.2 -swf bin/flash/release/bin/OpenFLApp.swf -swf-header 800:480:60:000000 -cp "bin/flash/release/haxe" -D display  --display "C:\projects\OpenFLApp\src\Main.hx"@262 -D use_rtti_doc -D display-details -D display-stdin`
result: `"<list>\n<i n=\"accessibility\" k=\"package\"><t></t><d></d></i>\n<i n=\"containers\" k=\"package\"><t></t><d></d></i>\n<i n=\"controls\" k=\"package\"><t></t><d></d></i>\n<i n=\"core\" k=\"package\"><t></t><d></d></i>\n<i n=\"effects\" k=\"package\"><t></t><d></d></i>\n<i n=\"events\" k=\"package\"><t></t><d></d></i>\n<i n=\"messaging\" k=\"package\"><t></t><d></d></i>\n<i n=\"modules\" k=\"package\"><t></t><d></d></i>\n<i n=\"netmon\" k=\"package\"><t></t><d></d></i>\n<i n=\"printing\" k=\"package\"><t></t><d></d></i>\n<i n=\"rpc\" k=\"package\"><t></t><d></d></i>\n<i n=\"skins\" k=\"package\"><t></t><d></d></i>\n<i n=\"utils\" k=\"package\"><t></t><d></d></i>\n</list>\n"`

**Comment by dkolyesnik** [comment]
Created and issue in haxe repository
https://github.com/HaxeFoundation/haxe/issues/5841

**Comment by Neverbirth** [comment]
OK, I will leave this open for the moment. We could also parse these extern SWCs to get autocompletion information, but priority would be quite low.
