### ISSUE TITLE
Haxe develop: adobe air app fails to debug after creation

### ISSUE THREAD

**Issue by Ulfasaar** [fdorg/flashdevelop#1424]
Hi, 

I have just started with my first Haxe project, creating a mobile app using the adobe air target.

I managed to install the flex and air sdk from app man perfectly fine, however whenever I make a new project in Haxe develop and press test project (F5) it throws this error:

`invalid application descriptor: Unknown namespace: http://ns.adobe.com/air/application/18.0`

I've tried everything I could think of, I've tried changing the namespace so that it was set for swf 24 instead and various other versions, installed the air3 Haxe package, installed jre 6 and altered my path so that it points to it.

The only thing I haven't tried is installing the air and asc haxe package from appman, is that a plausible cause for it failing?

**Comment by Ulfasaar** [comment]
**Update:** 

I have tried installing the Haxe package that contains ASC and it still didn't work :(

**Comment by Neverbirth** [comment]
I don't think this is a HD issue. Sadly it's been some long time since I've last made an AIR app so I don't remember all of the related errors.  Do you have more than one AIR/Flex SDK? If so it would be possible you are using a wrong one.

**Comment by Ulfasaar** [comment]
Thanks Neverbirth, sorry for the insanely long time it took me to get back to you. I have stopped using flash now as some members of my family have macs so I don't have to use adobe air anymore.

Instead I am working hard on a IOT project and mostly using visual studio code. Thank you very much for your assistance however and I hope you have a great day :)
