### ISSUE TITLE
import.hx items are not highlighted nor shown in auto-completion

### ISSUE THREAD

**Issue by YellowAfterlife** [fdorg/flashdevelop#1426]
Static imports via `import.hx` are not highlighted the same way as static imports inside the classes are.

In addition, they are not shown in auto-completion menu, though the argument list is still displayed upon opening the bracket.
![image](https://cloud.githubusercontent.com/assets/731492/21672275/1d86740c-d32a-11e6-9047-b15c3aa1f67a.png)
Sample: https://gist.github.com/YellowAfterlife/6f3410ead21f4c015e099e6d0134d046

**Comment by asdfgl3d** [comment]
Any news about this?

**Comment by Neverbirth** [comment]
I think this would be more or less easy to support, but since my team doesn't use it I never looked into it.

**Comment by markknol** [comment]
+1

**Comment by Meychi** [comment]
@Neverbirth, @SlavaRa?

**Comment by SlavaRa** [comment]
I will be free only on weekends :(

**Comment by SlavaRa** [comment]
Haxe, enhancement
