### ISSUE TITLE
[haxe/Windows] Build/Run command not working (not sure if only openfl related or haxelib issue)

### ISSUE THREAD

**Issue by azrafe7** [fdorg/flashdevelop#1428]
Was a bit away from haxe/HaxeDevelop (a couple months at least) and couldn't build/run some of my projects through HaxeDevelop.

I'm not sure my issue is only related to openfl projects, but typically I was getting output similar to this:
![image](https://cloud.githubusercontent.com/assets/1266447/21689008/37c8663c-d36f-11e6-92ac-60fc68169ae2.png)
(where `Accesso negato` would be `Access denied`)

Couldn't find anything useful on google related to this, but luckily after soome tinkering it seemed that adding the `.exe` extension to haxelib in `Project->Properties->Build->Pre-Build Command Line` fixed it.

![image](https://cloud.githubusercontent.com/assets/1266447/21690026/d4628772-d372-11e6-90a6-08d888937b03.png)

I was really confused by the message at first, so hopefully this can help others and/or can be fixed directly in Flash/HaxeDevelop (if it's not solved already of course).

For reference: using HaxeDevelop 5.2 (from installer), haxe 3.4 rc, git openfl/lime, win7 x64.

**EDITED**

**Comment by Neverbirth** [comment]
To me this looks more like system configuration. Do you happen to have a "haxelib" file too in some of your PATH folders?

**Comment by azrafe7** [comment]
Hey @Neverbirth, investigated a bit more (although I cannot provide the exact steps to reproduce). Here's a summary:

Along with `Access denied`, after fiddling more, I was getting something ~like: `Unix_error("open_proc", 21)`.
The latter seemed to be an `Error: is directory` as reported [here](http://www-numi.fnal.gov/offline_software/srt_public_context/WebDocs/Errors/unix_system_errors.html).
Looking into my haxe folder indeed I found an `haxelib` dir (which I obviously installed at some point with `haxelib install haxelib`, but had no memory of it). Deleting that made things work again.

**Comment by Neverbirth** [comment]
Nice to know. Closing this then.
