### ISSUE TITLE
Incorrect behavior when creating class that extends base class with same name

### ISSUE THREAD

**Issue by andrew-git** [fdorg/flashdevelop#1431]
When creating new class with ClassName, that extends base class with same name ClassName, I've got
`ClassName extends ClassName`
and thus I've got inheritance loop.
What expected:
`ClassName extends base.path.ClassName`

Also such checks needed when class renames.

**Comment by andrew-git** [comment]
Any news on progress?

**Comment by andrew-git** [comment]
Looks like fix exists, any news on applying it?

**Comment by Neverbirth** [comment]
Waiting for me to check it. Sorry, everytime I want to look into it something important that takes all my time happens at work

**Comment by andrew-git** [comment]
Thanks for info! Will be waiting

**Comment by andrew-git** [comment]
Please review, when you have some time.
Thanks!

**Comment by andrew-git** [comment]
Please approve fix.
Thanks

**Comment by SlavaRa** [comment]
Fixed
