### ISSUE TITLE
Wrong generator behavior on nested Arrays

### ISSUE THREAD

**Issue by andrew-git** [fdorg/flashdevelop#1436]
If we have nested array:
`var arr:Array<Array<Int>> = [[0, 0], [0, 0]];`
`arrFunc(arr[0][0]);`
And try to generate function we got:
`function arrFunc(array:Array<Int>, int:Int)`
Expected:
`function arrFunc(int:Int) `

Same for more nested array:
`var arr2:Array<Array<Array<Int>>> = [[[0, 0], [0, 0]]];`
`arrFunc2(arr2[0][0][0]);`

`function arrFunc2(array:Array<Array<Int>>, array1:Array<Int>, int:Int)`

**Comment by SlavaRa** [comment]
WIP in https://github.com/SlavaRa/flashdevelop/tree/feature/1436

**Comment by andrew-git** [comment]
Thanks!
