### ISSUE TITLE
When In some cases generator generates code with var name from reserved words

### ISSUE THREAD

**Issue by andrew-git** [fdorg/flashdevelop#1441]
When generates code for function like
`foo({})`
You got 
`function foo(dynamic:Dynamic) {}`
Where dynamic is reserved word and that breaks code.

**Comment by SlavaRa** [comment]
I will fix this issue after #1436

**Comment by SlavaRa** [comment]
WIP

**Comment by SlavaRa** [comment]
I can make PR after merge #1476
