### ISSUE TITLE
cpp.Void prioritized over Void

### ISSUE THREAD

**Issue by Yanrishatum** [fdorg/flashdevelop#1452]
When targeting C++ target in Haxe, autocomplete prioritizing `cpp.Void` completion over `Void`, resulting in autogeneration of `cpp.Void` import, and breaking compilation as `cpp.Void` is a return type.   
Current workaround:
Write `Void` and the press escape to cancel autocomplete.

Visual representation of the problem:
https://i.imgur.com/WNgcehA.gif
![example](https://i.imgur.com/WNgcehA.gif)

**Comment by Neverbirth** [comment]
Maybe you would like to try the build for [this PR](https://github.com/fdorg/flashdevelop/pull/1346) and give your feedback to include it or further improve it:

https://ci.appveyor.com/project/FlashDevelop/flashdevelop-devel/build/5.2.1.19-hsflhfjf/artifacts

**Comment by Yanrishatum** [comment]
@Neverbirth Yes, this PR do fix that problem. I've talked with Slava about this problem last year, what actually resulted in that PR. Talked with him right now, and he said he'll fix merge conflicts soon.
![img](https://i.imgur.com/f7tyuVw.png)
