### ISSUE TITLE
Toggleable <T> on new in autocomplete

### ISSUE THREAD

**Issue by Yanrishatum** [fdorg/flashdevelop#1457]
In recent versions autocomplete started to force `<T>` parameters of classes in autocomplete of `new`. While this behaviour is correct, it isn't something that should be enforced always. It's not even necessary to create that `<T>` part on `new` as when you create typed variable compiler already knows it's `T` parameter and when you call `new` it adds that parameter automaticaly on compilation time. So, my point:
1. It creates unnecessary code.
2. It makes it more painful to change `T` parameter, as instead of just changing it in once place (variable declaration), you have to as well change it in all construction occurences.
3. Right now it impossible to turn off, which may conflict with established code-style and create unnecessary frustration to deal with.

Proposal: make it toggleable option. Adding or not adding `<T>` is mainly question of code-style, so it should be configurable.

So, examples. 
```haxe
var arr:Array<String> = new Array<String>();
var arr:Array<String> = new Array();
```
Both declarations are valid, but for first you have to edit two places to change `String` to another type (it getting worse, if it constructed on several locations, or even outside of class). In second - only one place.  
And how I currently have to deal with it:
![example](https://i.imgur.com/chKG9q9.gif)
* First line is how autocomplete always does.
* Second line is additional distraction with writing only class name, pressing escape and then continue constructor call.
* Third is most common in my case, let auocomplete add that code and delete it manually.

**Comment by Neverbirth** [comment]
I know about the short notation for generic instantiation, but has this always been a part of Haxe? I think not, but I couldn't find detailed information about it. It's also a problem that most languages with generics don't work like this, but it could be set as a language feature together with generics.

From my side this is quite subjective and not critical. The old code was completely wrong with generics and wouldn't even point to a proper type in the completion list in this case. You can also just press the down arrow when the completion list appears, that is faster than both the second and third approach.

**Comment by Yanrishatum** [comment]
I'm talking about any class with parameters. Not only `@:generic`s (autocomplete for which actually buggy right now, and Slava fixing it). As far as I remember (several years) feature with omitting class parameters with constructor was present in Haxe3.

From my side this is frustrating new "feature" that makes experience worse than it was when it didn't provided proper type :P I'm not saying it should be removed. Only option to toggle it on and off. And pressing down as distracting as pressing escape or deleting generated text.

**Comment by Neverbirth** [comment]
Well, when I talk about generics I talk in the general way including types with parameters, just like in .NET, Java, Delphi, etc.

What is wrong with `@:generic`s? Never noticed any problem with them, but I rarely needed them.

Anyway, ok, I know how it would be nicely implemented.

**Comment by Yanrishatum** [comment]
@Neverbirth 
`@:generic` autocomplete is broken this way: 
![showcase](https://i.imgur.com/T6yVJ40.png)
Autocomplete should provide completion of `structural.Pool<T>`, not `structural.Pool.Pool<T>`.

**Comment by Yanrishatum** [comment]
Bump. Because this is seriously frustrating issue. 
Add up this:
http://wb.yanrishatum.ru/i/0NC36.png
![img](http://wb.yanrishatum.ru/i/0NC36.png)
```haxe
var arr:Array<{holy:Float, crap:Array<{dat:Int, big:String}>, inlined:Bool, type:String}> = new Array<{holy:Float, crap:Array<{dat:Int, big:String}>, inlined:Bool, type:String}>();
```
Yes, this is a bad style. Yes, this example is made up. But the situation was real when I was doing a small game on game jam and loaded json config, and time was more important than good style.

**Comment by Neverbirth** [comment]
OK, if no problem arises I will do this before the end of the week.
