### ISSUE TITLE
Improve haxe errors parsing

### ISSUE THREAD

**Issue by yar3333** [fdorg/flashdevelop#1463]
Sometimes haxe output error message in several lines:
```
src/HaqComponent.hx:8: characters 7-16 : You cannot access the js package while targeting neko (for js.JQuery)
src/HaqComponentTools.hx:7: characters 7-35 :     referenced here
src/HaqTemplateManager.hx:9: characters 7-40 :     referenced here
src/Build.hx:68: characters 34-52 :     referenced here
```

FlashDevelop split this into several lines (this is not a problem) and sort them (this is not good!):
![1](https://cloud.githubusercontent.com/assets/900330/23678648/12f643ae-0396-11e7-9918-5f4fad991f53.png)

**Comment by Neverbirth** [comment]
Actually this is already planned from my side.

**Comment by Neverbirth** [comment]
In progress by a colleague.
