### ISSUE TITLE
Refactor rename class error

### ISSUE THREAD

**Issue by markknol** [fdorg/flashdevelop#1464]
Sometimes after renaming a class I get this error.  I don't notice the actual refactors/renames was failed, I just get this message.

![image](https://cloud.githubusercontent.com/assets/576184/23697879/c32f6072-03e9-11e7-8980-78d93a180f31.png)

I use a quite recent dev build (https://github.com/fdorg/flashdevelop/commit/120f067995):
![image](https://cloud.githubusercontent.com/assets/576184/23697887/c84cd508-03e9-11e7-8672-f7491365fc98.png)

**Comment by Neverbirth** [comment]
@SlavaRa ? I can confirm this error. I also got it yesterday, but didn't post because I thought that maybe it was some custom change on my side and at the moment couldn't check it.

**Comment by SlavaRa** [comment]
@Neverbirth @markknol  I'll check it out right now.

**Comment by markknol** [comment]
Great, you guys are awesome!
