### ISSUE TITLE
Cannot compile C# and C++ targets in Windows 7 x64

### ISSUE THREAD

**Issue by arietto** [fdorg/flashdevelop#1469]
I've got the following error (similar for hxcpp and hxcs) for default projects in C++/C#.
OS Windows 7 x64.

Running process: C:\Program Files (x86)\HaxeDevelop\Tools\fdbuild\fdbuild.exe "E:\temp\New Project14\New Project14.hxproj" -ipc 7de8e6ea-dcd6-4496-acea-c62337a09d79 -version "3.4.0" -compiler "C:\HaxeToolkit\haxe" -notrace -library "C:\Program Files (x86)\HaxeDevelop\Library"
Building New Project14
haxe  -cp src -cpp "E:/temp/New Project14/bin" -main Main
Unix.Unix_error(21, "open_proc", "haxelib path hxcpp")
Build halted with errors (haxe.exe).
Done(1)

hxcpp and hxcs are installed. System environment variables are set.
HAXELIB_PATH=C:\HaxeToolkit\haxe\lib
HAXEPATH=C:\HaxeToolkit\haxe
HAXE_LIBRARY=C:\HaxeToolkit\haxe\std
%HAXEPATH% is appended to PATH variable value.

Compiling simple C# project without IDE (from cmd line) is ok: 
haxe build.hxml

where
build.hxml contents:
-cs test
-main Test
-D haxe3

**Comment by SlavaRa** [comment]
What compiler do you use?

**Comment by arietto** [comment]
Haxe Compiler 3.4.0 - (C)2005-2017 Haxe Foundation

**Comment by arietto** [comment]
Any ideas? I asked about this issue in early spring, now it's summer.

**Comment by arietto** [comment]
It's autumn...

**Comment by Gama11** [comment]
Maybe related to https://github.com/HaxeFoundation/haxe/issues/6212. Have you tried the Haxe 4 preview release?

**Comment by arietto** [comment]
I have tried Haxe 4 preview release. The same error.
 >haxelib path hxcpp
C:\HaxeToolkit\haxe\lib\hxcpp/3,4,188/
-D hxcpp=3.4.188
------
I've studied haxe issue tracker. Here is the solution: set  COMSPEC variable value to cmd:
COMSPEC=%SystemRoot%\system32\cmd.exe
