### ISSUE TITLE
[haxe] structure types in function types are parsed incorrectly

### ISSUE THREAD

**Issue by Gama11** [fdorg/flashdevelop#1472]
```haxe
class C {
	function foo(a:Int->{ s: String }->Void, b:Int):Void
	var bar:Int;
}
```

`Int->?{ s: String }->Void` is valid syntax for a Haxe type.

This produces some.. funny results in the outline panel. :D

![](http://i.imgur.com/0ZUwg4d.png)

**Comment by SlavaRa** [comment]
@Gama11 Please, check it

**Comment by Gama11** [comment]
Can't reproduce it anymore.
