### ISSUE TITLE
Run the previously compiled html5 project in browser with web server without compilation

### ISSUE THREAD

**Issue by wolfhoundgelert** [fdorg/flashdevelop#1481]
On the flash-target I can once compile my project and launch the swf for debug without compilation at any time. I can't do the same on the html5-target because it doesn't start the web-server.

Moreover, in IDEA it looks like this:
![photo_2017-03-16_11-16-50](http://image.prntscr.com/image/d6fc77ad7e24418fbe87f95d36a56676.png) 

It's quite convenient!)

**Comment by Neverbirth** [comment]
You could create a macro to run the compiled HTML5 project.

But the Open in Browser option would be quite handy.

**Comment by SlavaRa** [comment]
It's a challenge for me :)

**Comment by Meychi** [comment]
We already have a macro which executes the file with its associated program, ie html with default browser, xsl with excel etc...

**Comment by Meychi** [comment]
Hmm, actually it executes the current file in editor not in project view.

**Comment by SlavaRa** [comment]
https://github.com/fdorg/flashdevelop/issues/779
