### ISSUE TITLE
FD falling down after each compile in a FLA Project

### ISSUE THREAD

**Issue by cleptoman** [fdorg/flashdevelop#1491]
i happens not in all FLA projects. i have 2 trouble projects (large projects with a lot of code.)
it was an attempts to change FLASH IDE (i try Adobe Flash CS6 and Adobe Animate CC 2017) and to change SDK - i have the same results - FD is falling
the latest version of FD installed (http://take.ms/CJ3tm)

**Comment by cleptoman** [comment]
update: FD falling down after saving FLA file

**Comment by Neverbirth** [comment]
Which error are you getting? Sadly I'm not using FLA projects anymore, but I will try soon with one.

**Comment by cleptoman** [comment]
i didn't get  any errors, just getting not response from FD in the system process list. it happens each time after saving the FLA file after compilation from FD. my FLA project is a large project with many FLA files in the project dir (if it is metter)
i using FLA projects because using specific framework CLIK for Scaleform
