### ISSUE TITLE
UI Theme do not works to the Results Panel

### ISSUE THREAD

**Issue by SlavaRa** [fdorg/flashdevelop#1492]
I think that happened after merge #1479

**Comment by Neverbirth** [comment]
Strange, it was tested with themes, but maybe some last minute oversight. It will be looked into.

**Comment by chipshort** [comment]
Okay, found the reason. In the commit, I created a new class "ResultsListView" that is inheriting from ListViewEx. However, I forgot about the reflection magic that's being done in ThemeManager, so any theme that does not enable ThemeManager.UseInheritance will not be applied to ResultsListView.
So, renaming ResultsListView to ListViewEx would solve it.
