### ISSUE TITLE
Autocompletion breaks when using multiline anonymous structures as constructor argument

### ISSUE THREAD

**Issue by sebthom** [fdorg/flashdevelop#1507]
Considering a class such as:
```haxe
class Entity {
   public var description:String;
   public function new(args: { description: String }) {
      this.description = args.description;
   }
}
```
\
When an instance of this is declared like this:
```haxe
var entity = new Entity({description:"blabla"});
```
auto completion works fine on the `entity` variable.
\
\
However when reformatting the code like this:
```haxe
var entity = new Entity({
    description:"blabla"
});
```
the auto completion dropdown list for the `entity`  variable does not show up.

In that case I would have to explicitly declare the type of the variable, e.g.
```haxe
var entity:Entity = new Entity({
     description:"blabla"
});
```
\
I am using FlashDevelop 5.2.0.3 with Haxe 3.4.2 on Windows 7 and 10.

**Comment by SlavaRa** [comment]
I can not reproduce in development version. @sebthom please check http://flashdevelop.org/downloads/builds/

**Comment by Neverbirth** [comment]
To me this seems like a possible display mode problem, as the compiler service should be giving the fields from `Entity`. Actually, I already encountered this problem several weeks ago, but it was with one Haxe 3.3 version so I didn't give it much importance...

**Comment by sebthom** [comment]
@SlavaRa can't reproduce it in the latest development version. seems to be fixed.
