### ISSUE TITLE
AIR 25 / Java issues

### ISSUE THREAD

**Issue by kevinfoley** [fdorg/flashdevelop#1542]
The latest AIR 25 SDK has some compiler issues and will only work with certain versions of Java: https://forums.adobe.com/thread/2281743

In my case I found that I had to upgrade to Java JRE 1.8.0_121 64-bit. However, when I have my system configured to use this version of Java (through JAVA_HOME and PATH), FlashDevelop does not enter debug mode properly when trying to debug an application. If I try to debug, the application launches in Flash Player, but FlashDevelop does not enter the debug view and breakpoints do not work.

I know FD has traditionally had some issues with 64-bit Java and Java 1.8. Is it possible for these issues to be resolved so that we can use AIR 25 without having to switch between Java versions for debugging and for generating APKs?

**Comment by SlavaRa** [comment]
Hi, you should use FlashDevelop64.exe instead of FlashDevelop.exe

**Comment by SlavaRa** [comment]
@kevinfoley all ok?

**Comment by kevinfoley** [comment]
@SlavaRa  I forgot there is a 64-bit executable included in the install. The release notes should be updated, they only say that 32-bit Java is required. Anyway, thanks, the 64-bit executable seems to debug properly.
