### ISSUE TITLE
`Void->Void` method generation from function argument

### ISSUE THREAD

**Issue by Yanrishatum** [fdorg/flashdevelop#1580]
Currently method generation does not work properly for `Void->Void` types when they are declared as function argument, producing `function (parameter0:Void):Void` type.
Visual representation:
![img](http://wb.yanrishatum.ru/i/g/lbCWZ.gif)
Code:
```haxe
package;

import openfl.display.Sprite;

class Main extends Sprite 
{

    public function new() 
    {
        super();
        foo(test);
    }

    private function foo(v:Void->Void) {}
}
```

**Comment by SlavaRa** [comment]
Fixed via #1572
