### ISSUE TITLE
New panels Refactor/References

### ISSUE THREAD

**Issue by andrew-git** [fdorg/flashdevelop#1596]
In latest update appears 2(maybe more) panels Refactor/References, their purpose not clearly understand - early all showed in Results panel and works ok.
In addition they don't save state where it pinned, and after restart appears in default position.
Also they don't available at View menu.

**Comment by wise0704** [comment]
Improvements for multiple results panels is already submitted at the moment, as #1578 
If you could check it out and provide feedback, that'd be nice.

**Comment by andrew-git** [comment]
Please add possibility to remember positions of new panels (after restart appears in default position)

**Comment by wise0704** [comment]
Panel layout data restoration is already implemented in the referenced PR.

If they aren't getting restored, can you confirm that positions for other panels (e.g. Output, Task List, Project) are getting restored properly?

**Comment by andrew-git** [comment]
Yes on latest (5.2.1.177) other panels restored pinned to bottom, but reference/refactor resets to popup bottom 
![screen](https://cloud.githubusercontent.com/assets/1407827/25782764/55c16108-3359-11e7-8aa2-c45ad91c3a56.png)

**Comment by wise0704** [comment]
Ah, the PR is not merged yet. I was referring to the version in #1578.
