### ISSUE TITLE
Linter panel feedback

### ISSUE THREAD

**Issue by markknol** [fdorg/flashdevelop#1601]
I have a new "linter" panel, just wanted to share my feedback:
1.  The panel should also be in the "view" top menu, to show/hide them I'm my layout when I want. Now it just appear. 
1. The unused import/variables warnings are really nice/helpful in general!
1. The unused import doesn't work when you have conditional compilation `#if macro`
1. In macro code, I get fairly random errors, I think it doesn't understand this context at all. 
1. I also have projects where variables are generated by macros, It doesn't seem to understand that. Are compiler services used for this?
1. The results are send to both output and the linter panel. Maybe the linter panel is enough?
1. The errors/warnings don't go away after I save/resolve them. While I have my setting for this turned on.
1. The errors are empty, see screenshot
![image](https://cloud.githubusercontent.com/assets/576184/25609227/9956af20-2f1e-11e7-80aa-3dd7f6dd3c4e.png)

I use dev build  https://github.com/fdorg/flashdevelop/commit/0709ecbc3816c0c5b34886a2188f25c1f08a0444

**Comment by Neverbirth** [comment]
Thanks for your feedback!

1. Yeah, this is in progress.
2. Thanks again!
3. The information is coming from the Haxe compiler service... so I'm afraid this is related to them...
4. The same as 3 I guess.
5. Same as 3 again.
6. This was done on purpose to follow the same behavior as compiler output, find references, refactor, etc, but it could be changed if more people are against it.
7. They should go away after you save, if they don't then there may be an error here.
8. @chipshort ?

**Comment by markknol** [comment]
6. In that case, it would be nice if there was an option to ignore the errors/warnings (from the settings). Now you can hide them by deselecting the icon in the panel, but it still logs to output panel.

**Comment by chipshort** [comment]
Okay, so here is what I think:
3. I could imagine this being a problem with the way we call the compiler service, since we specify the target, but I'm not completely sure.
For 8. It seems like there are more diagnostics types than I know of. At the moment, only unused variable and unused import are implemented. I recently found out there is one for cases in a switch that will never match, but there does not seem to be any documentation for any of them.
I guess, for now, I will make sure unsupported results are not shown.

**Comment by Neverbirth** [comment]
@markknol Could you try the build for PR #1627?

https://ci.appveyor.com/api/buildjobs/yf46b9shf9wipe6f/artifacts/FlashDevelop%2FInstaller%2FBinary%2FFlashDevelopPR_1627.zip

**Comment by markknol** [comment]
Yep will try tomorrow! Any specific stuff I need to look into?

**Comment by Neverbirth** [comment]
I'm curious if 8 is improved for you now.

**Comment by chipshort** [comment]
Yes, 8 and also 7 should be fixed now.

**Comment by wise0704** [comment]
@Neverbirth this can be closed now?

**Comment by Neverbirth** [comment]
I tested the PR and could also see it was reporting in a more proper way, but I prefer to keep it open until @markknol gets to reply. There is also point 6 that I don't know what others' opinion is.

**Comment by markknol** [comment]
8 It seems improved, the errors now have messages.
7. Doesn't seem to be resolved, the error stays after resolve + saving:
![linter](https://cloud.githubusercontent.com/assets/576184/26284573/fe751322-3e3e-11e7-9137-07d1aeb40fbc.gif)

**Comment by wise0704** [comment]
7 should be solved in #1631

**Comment by wise0704** [comment]
@Neverbirth 6 would require rewriting TraceManager and separating output logs and results logs.
I think that would be worth a new separate issue to be created.

**Comment by Neverbirth** [comment]
OK, I'm closing down this one, if 6 is considered really important or some other issues or suggestions are found create new tickets. Thanks everyone!

**Comment by markknol** [comment]
Thanks for all these improvements and feedback!
