### ISSUE TITLE
Error at startup in latest (5.2.1.174) version

### ISSUE THREAD

**Issue by andrew-git** [fdorg/flashdevelop#1621]
![fd](https://cloud.githubusercontent.com/assets/1407827/25781470/73d95508-3343-11e7-81d8-a783cf3ba9fb.png)

**Comment by Neverbirth** [comment]
From what I see `AddClipboardFormatListener` is Windows Vista+ only. So I guess you are still on XP, aren't you?

@wise0704

**Comment by andrew-git** [comment]
Yes

**Comment by wise0704** [comment]
Welp, I should add an OS version check on top of the Win32 check?

But seriously, why would you still use XP?

**Comment by andrew-git** [comment]
Check would be great, it's once inconsistency with XP, so better to keep support.
I have notebook with newer version and old adjusted PC, so prefer to keep as is.
