### ISSUE TITLE
airsdk compress swf not be used

### ISSUE THREAD

**Issue by matrix3d** [fdorg/flashdevelop#1625]
all fws

**Comment by Neverbirth** [comment]
Can you explain more?

**Comment by matrix3d** [comment]
adobe air sdk 25
setting optimize bytecode =true.not use.
my proj get  swf 3M size.
and i addtional compiler options -compress=true,
i get swf 1M size.

**Comment by SlavaRa** [comment]
This setting only works in release mode.

**Comment by SlavaRa** [comment]
@matrix3d This issue can be considered solved?
