### ISSUE TITLE
Support for shell syntax highlighting

### ISSUE THREAD

**Issue by sebthom** [fdorg/flashdevelop#1641]
Please add support for Shell/Bash syntax highlighting.

Should be auto enabled for *.sh and *.bash files.

Thanks!

**Comment by Neverbirth** [comment]
It would be perfectly possible to do this, if someone feels bored enough for it I would be ok, the problem would be custom theme support. I had some related discussion recently with @wise0704.

**Comment by sebthom** [comment]
I have no experience in customizing FD. Can you roughly describe the steps to add a new language?

**Comment by Neverbirth** [comment]
Oh, I'm not telling you specifically to do it. Maybe we could do some wiki article on what you ask.

**Comment by gene-pavlovsky** [comment]
Hey, that would be nice indeed. I use `Notepad2-mod` for editing my bash scripts on windows, or a not-well-known `le` editor on linux.
