### ISSUE TITLE
[AS3] Wrong function generation behavior

### ISSUE THREAD

**Issue by andrew-git** [fdorg/flashdevelop#1645]
Let's have
```
private function f1(f:Function):void{}

private function f2():void
{
	f1(f3);
}
```
when generate new function f3 we got
`private function f3():Function`
expected
`private function f3():void`

**Comment by SlavaRa** [comment]
it is for me :)

**Comment by Neverbirth** [comment]
Why `private function f3():void`? Why not `f3();*` or `f3(... args):*`. On some cases maybe we can get the exact signature, but here it's not possible.

**Comment by andrew-git** [comment]
Reasonable, but ":Function" not good anyway, If it's not void you should fix it manually, but with Function you should fix it in any case
