### ISSUE TITLE
Russian Language for FlashDevelop

### ISSUE THREAD

**Issue by ghost** [fdorg/flashdevelop#1656]
My time begining translate IDE on Russian Lang.
Here will be posted updates.

**Comment by Meychi** [comment]
@SlavaRa: could you help him if needed?

**Comment by SlavaRa** [comment]
@Meychi hi, no problem

**Comment by JuraseyGS** [comment]
@SlavaRa Я так понял, что весь текст IDE хранится в файл .resx (en_EN.resx). Есть некоторые проблемы в переводе, позже когда переведу все, добавлю сюда готовый файл.

**Comment by SlavaRa** [comment]
Да, локализации хранятся в этих файлах. Ок ждём :)
