### ISSUE TITLE
Class type detection broken

### ISSUE THREAD

**Issue by Neverbirth** [fdorg/flashdevelop#1658]
The changes to `ASComplete` in #1619 made trying to resolve class types to return std\Class.hx instead of the class itself.

So, having something like

```
function test(class:Class<Dynamic>) {}

test(SomeClass);
```

Trying to resolve `SomeClass` gives back `Class`, not `SomeClass`. As it's expected.

This is quite a problem for the main codebase of my team.

**Comment by SlavaRa** [comment]
I'm working on a fix
