### ISSUE TITLE
Auto completion for static fields/methods broken

### ISSUE THREAD

**Issue by andrew-git** [fdorg/flashdevelop#1660]
In 5.2.1.194 version of FD auto completion for static fields/methods not working.
It don't complete none of static fields/methods (Math class also).

**Comment by Neverbirth** [comment]
This sounds like it could be #1658.

**Comment by andrew-git** [comment]
Yep, I seek and see this, but was not quite sure

**Comment by Neverbirth** [comment]
Please, confirm this is fixed for you with latest development build, and close the issue if so.

**Comment by andrew-git** [comment]
Works again, thanks!
Sorry for delay
