### ISSUE TITLE
Wrong autocompletion

### ISSUE THREAD

**Issue by Neverbirth** [fdorg/flashdevelop#1664]
This bug has come to my knowledge today. Having this AS3 code (I guess Haxe is similar but didn't check):

```
package {
	public class NewClass {
		function test():void
		{
		}
		
		func
	}
}
````

Trying to autocomplete after `func` is not working nicely, after checking in depth I've seen that the changes to `ASComplete` in #1619 also broke this, and `ASComplete` is returning that the tail of the expression in that position is `{}func` instead of just `func`.

Pinging @SlavaRa in case he is not aware of this case.

**Comment by SlavaRa** [comment]
@Neverbirth I'm checking this at the moment

**Comment by SlavaRa** [comment]
@Neverbirth I found a specific place for the problem, I will fix it at night
