### ISSUE TITLE
Impossible to register to flashdevelop forum. Captcha designed by Kafkha and the Sphinx.

### ISSUE THREAD

**Issue by PippoApps** [fdorg/flashdevelop#1674]
How should this be intepreted?
"String("I'm a").toUpperCase() + "PROBOT... not." == ?:"
I tried all possible permutations, even shared it with other developers, nobody could come with a solution. What's in that forum? The codes to crack Tutankhamon treasure?

**Comment by shintiger** [comment]
Same here

**Comment by PippoApps** [comment]
It seems nobody maintains this wiki or the forum anymore...

**Comment by Meychi** [comment]
Sorry, we have very limited time so our focus has not been on the forums lately. I will check this soon.

**Comment by Meychi** [comment]
Sorry, there was a missing space in the answer, should be fixed now.

**Comment by PippoApps** [comment]
Thank you very much. Heartwarming to know FlashDevelop is still maintained. Great IDE.

**Comment by cheezboi** [comment]
Still broken

**Comment by magicmouse** [comment]
This is a really horrendous way to prevent robots. Firstly the syntax of String("I'm a").toUpperCase() + " PROBOT... not." == ?: doesn't even compile in AS3. question mark colon, what is that. I understand I'M A PROBOT... not., but why compare it with ?:, that is not a valid operator per the compiler.... i guess you don't want any community!

**Comment by ManjuladeviM** [comment]
Thank you for sharing a piece of Valuable information.
best [Google Cloud Online Certification ](url=https://www.gangboard.com/cloud-computing-training/google-cloud-training)
