### ISSUE TITLE
Find all references incorrect behaviour

### ISSUE THREAD

**Issue by andrew-git** [fdorg/flashdevelop#1675]
When searching all references for public field/method in latest version of FD also founds public references with same name from other classes.
Maybe related to https://github.com/fdorg/flashdevelop/issues/1660 / https://github.com/fdorg/flashdevelop/issues/1658

**Comment by Neverbirth** [comment]
I hope I will be able to check #1666 tomorrow, and I may look into this, as @SlavaRa seems utterly busy lately. I'm too, but I have the feeling I may be able to look into this sooner, but he can contact me at any moment in case he is available.

**Comment by andrew-git** [comment]
Thanks!

**Comment by andrew-git** [comment]
Looks like fixed with @SlavaRa latest commit https://github.com/fdorg/flashdevelop/commit/ac356244098daa43de5fff3d80182ea571925b71 Could you confirm?

**Comment by SlavaRa** [comment]
@andrew-git please check latest dev build

**Comment by andrew-git** [comment]
Looks good
