### ISSUE TITLE
Compile Errors Not Showing On Results Panel When Project Path Contains Parentheses

### ISSUE THREAD

**Issue by apptaro** [fdorg/flashdevelop#1676]
When you have a flashdevelop project somewhere like c:\projects(as3)\FDProject\
whose path contains braces, compile errors will not show on Results panel.

Ref: https://stackoverflow.com/questions/4446865/how-to-make-flashdevelop-errors-appear-in-results-panel#comment4857439_4447045

**Comment by Neverbirth** [comment]
Nice catch. I have several fixes lined-up together with some other stuff... but there is always something blocking me from committing it here. I will look into this one today.
