### ISSUE TITLE
FD sometimes crashed on startup

### ISSUE THREAD

**Issue by andrew-git** [fdorg/flashdevelop#1680]
First run fresh version 5.2.1.211
![fd-crash](https://user-images.githubusercontent.com/1407827/28475802-635dd23c-6e56-11e7-9a78-559d566444d4.png)

Update to 5.2.1.211 version
![fd-crash2](https://user-images.githubusercontent.com/1407827/28475895-be3e27b0-6e56-11e7-974f-3d414e8b5e54.png)

5.2.1.203 worked stable

**Comment by Neverbirth** [comment]
Do you have any stacktrace to share? either in the error window or in exceptions.log. Do you know commit numbers?

**Comment by andrew-git** [comment]
I'll try to make stacktrace from window, FD exception log empty. Looks like it happens between https://github.com/fdorg/flashdevelop/commit/615df487b846144cc6f64b788b7df70d7ee150d4 and https://github.com/fdorg/flashdevelop/commit/ac356244098daa43de5fff3d80182ea571925b71

**Comment by andrew-git** [comment]
Unpack and run fresh version again, now have another 2 errors and exception (but FD started)

> 23.07.2017 13:57:29
> 
> System.NullReferenceException: Object reference not set to an instance of an object.
>    at WeifenLuo.WinFormsUI.Docking.DockContent.Show()
>    at FlashDevelop.MainForm.CreateCustomDocument(Control ctrl)
> 
> 23.07.2017 13:58:06
> 
> System.NullReferenceException: Object reference not set to an instance of an object.
>    at StartPage.PluginMain.CreateStartPage()
>    at StartPage.PluginMain.ShowStartPage()
>    at StartPage.PluginMain.HandleEvent(Object sender, NotifyEvent e, HandlingPriority priority)
>    at PluginCore.Managers.EventManager.DispatchEvent(Object sender, NotifyEvent e)
![fd01](https://user-images.githubusercontent.com/1407827/28498819-980290b8-6faf-11e7-98f3-3f891f017462.png)
![fd02](https://user-images.githubusercontent.com/1407827/28498820-9b9fe09a-6faf-11e7-9125-3bedc7bc57a2.png)

**Comment by Neverbirth** [comment]
Uhm... it's strange if it indeed happened between those commits.  Previous to it d2d92590a2d5b4b59426b09cb2ac61072697c123 had some big change as it updates FD to .NET4, but the previous commit made some big problem to happen and FD was behaving incorrectly... so it's difficult to say if it's really between the commits you say.

I will try to prepare some other builds to test.

And I will see if I'm able to reproduce myself or see something else strange.

**Comment by Neverbirth** [comment]
On my side everything works correctly, but I'm not using Windows XP. As I said, I will try to make 2 builds and see what happens on your end. I also want to try out to make 2 other changes to FD that may help on this kind of case.

**Comment by andrew-git** [comment]
My fault, 5.2.1.203 refers to https://github.com/fdorg/flashdevelop/commit/19a0a479d7f303530278c9f72e3b00a2f02a791c so update FD to .NET4 could cause that

**Comment by Neverbirth** [comment]
But I guess you have latest .NET 4 installed?

**Comment by andrew-git** [comment]
Not sure about latest, but .NET 4 definitely installed

**Comment by Neverbirth** [comment]
I've uploaded a dev version targetting .NET 3.5 [here](https://www.dropbox.com/s/s83t2rrzsx3ruf8/FlashDevelop-development.zip?dl=0). If it works it's indeed the .NET 4 update, but it shouldn't cause this and we will have to track down the problem.

**Comment by andrew-git** [comment]
On start I have same error as at https://github.com/fdorg/flashdevelop/issues/1680#issuecomment-317245262 so probably it's not about .NET

**Comment by Neverbirth** [comment]
Maybe you can mail me your skype to not pollute with comments the issue. I could prepare some other versions for you.

**Comment by andrew-git** [comment]
Looks like fixed, maybe in build or maybe helps adding in config:
```
<gcServer enabled="true"/>
<gcConcurrent enabled="false"/>
```
