### ISSUE TITLE
Auto-completing function in an interface implementor adds it as `internal` instead of `public`

### ISSUE THREAD

**Issue by gene-pavlovsky** [fdorg/flashdevelop#1684]
Using the development branch, working on an AS3 project:
- Declare a function in an interface
- Create a new class that should implement this interface
- In the class, type `function ` and press Ctrl+Space, FD offers to insert the function from the interface
- Press Enter

Expected result: function added as `public`
Expected: function is added as `internal`

**Comment by Neverbirth** [comment]
I guess this comes from @SlavaRa's #1527 PR and the like.

**Comment by gene-pavlovsky** [comment]
Not sure if it's relevant, but I'm using the default setting of false for the "Generate explicit scope" ASCompletion setting.

**Comment by SlavaRa** [comment]
Hi @gene-pavlovsky, I'll check it out tonight.
