### ISSUE TITLE
Wrong indentation when adding two newlines after the beginning of a code block

### ISSUE THREAD

**Issue by gene-pavlovsky** [fdorg/flashdevelop#1685]
- Create a function or a code block, even an empty one will do e.g.
```
function test():void {
  true;
}
```
or even
```
{
}
```

- Position the cursor after the opening `{`
- Press Enter once
- Cursors moves to a new line, indenting 1 level
- Press Enter once again

Expected result: cursor moves to a new line, indent level stays the same since we're still in the same code block
Actual result: cursor moves to a new line, un-indenting 1 level

P.S. Common use case: I want to add some argument validation at the beginning of an existing function, and I want that code to be separated from the existing code by a newline for readability. I like to start by making that extra space, hence the two newlines.

**Comment by Neverbirth** [comment]
I think this one comes from some changes from @wise0704
