### ISSUE TITLE
The end?

### ISSUE THREAD

**Issue by SlavaRa** [fdorg/flashdevelop#1689]
Guys, please explain what's going on

**Comment by Neverbirth** [comment]
I'm on holidays without wifi right now. Short version on my side: waiting for @meychi's return in a few days.

**Comment by SlavaRa** [comment]
It all demotivates, I can not understand whether to do something to me or quit. All too long

**Comment by Neverbirth** [comment]
I wrote to you on slack. But yes, same here. As I said, waiting for @Meychi

**Comment by sfxworks** [comment]
Woah what do not end this project FD is awesome.

**Comment by Meychi** [comment]
Hold your horses, i will be back soon and we will start release cycle normally. I'm off from my vacation but i need to handle one work thing first and then we start to prepare for the next release.
