### ISSUE TITLE
[haxe] Outline panel: no type information through type inference

### ISSUE THREAD

**Issue by Gama11** [fdorg/flashdevelop#169]
For fields in the outline panel to be displayed with their types, you have to explicitly add the type, otherwise you'll end up with something like this:

![](http://i.imgur.com/c8UmKZn.png)

Would it be possible to use the information from the compiler completion for this?

**Comment by SlavaRa** [comment]
via https://github.com/SlavaRa/flashdevelop/commit/7cf4c028be27bc9ef9551fd959d43c82b5c9bc40
