### ISSUE TITLE
[Haxe/flash/AIR] Unable to step in the code in AIR app

### ISSUE THREAD

**Issue by delahee** [fdorg/flashdevelop#1721]
Hi

With Haxe Develop and Flash Develop ( tested both back to 5.0.1 ) , when I put breakpoint or have an error in an AIR app, I have an error :

This happens on a shallow computer out of the bow with a fresh windows 10 install:

"
Le handle Win32 passé à Icon n'est pas valide ou d'un type incorrect.

   à System.Drawing.Icon..ctor(IntPtr handle, Boolean takeOwnership)
   à System.Drawing.Icon..ctor(IntPtr handle)
   à System.Drawing.Icon.FromHandle(IntPtr handle)
   à PluginCore.Utilities.IconExtractor.GetFileIcon(String path, Boolean small, Boolean overlays)
   à PluginCore.Utilities.IconExtractor.GetFileIcon(String path, Boolean small)
   à FlashDevelop.Docking.TabbedDocument.UpdateDocumentIcon(String file)
   à FlashDevelop.Docking.TabbedDocument.DocumentControlAdded(Object sender, ControlEventArgs e)
   à System.Windows.Forms.Control.OnControlAdded(ControlEventArgs e)
   à System.Windows.Forms.Control.ControlCollection.Add(Control value)
   à System.Windows.Forms.Form.ControlCollection.Add(Control value)
   à FlashDevelop.Docking.TabbedDocument.AddEditorControls(String file, String text, Int32 codepage)
   à FlashDevelop.MainForm.CreateEditableDocument(String file, String text, Int32 codepage)
"
It doesn't happen in a regular flash execution.
I would love to have this fixed so that I can start to use that brand new baby :)

Thanks a lot!

**Comment by Neverbirth** [comment]
OS? How are you testing the new versions? is it by any chance by manually unzipping? If I'm not wrong around that version some new icons where introduced for some new features, and those icons are taken from a file located in the Settings folder. I wonder if it's related and you didn't replace the old file with the new one.

**Comment by delahee** [comment]
Windows 10
tested with new installer and old installer from 5.0.1 and unzipping and old haxdevelop, there must be something related to that...

I have an older win10 box that work like a charm...

**Comment by SlavaRa** [comment]
@delahee  the latest official release 5.2.0, please check it.
