### ISSUE TITLE
Drag & Drop not working

### ISSUE THREAD

**Issue by danilostroushko** [fdorg/flashdevelop#1742]
when i drag&drop some files (.as, .xml, etc) to the editor, it not open it, in previous builds it could be, in latest builds cursor is show "not"

**Comment by SlavaRa** [comment]
what version of the editor?

**Comment by danilostroushko** [comment]
5.3.0.66

**Comment by SlavaRa** [comment]
I can not reproduce this behavior, can you do gif?
http://www.screentogif.com/

**Comment by danilostroushko** [comment]
http://prntscr.com/h5bavk
just a drag any text file

**Comment by Neverbirth** [comment]
I cannot reproduce it either :S.
