### ISSUE TITLE
[Haxe] Switching projects throws errors in output. 

### ISSUE THREAD

**Issue by markknol** [fdorg/flashdevelop#1744]
I downloaded latest dev build, but it feels very unstable. When I open a project it says
```
Error: Display file was not found in class path

Error: Display file was not found in class path

Error: Display file was not found in class path

Error: Display file was not found in class path

Error: Display file was not found in class path
```
This is sometimes followed by a lot of
![image](https://user-images.githubusercontent.com/576184/32371359-d2425678-c090-11e7-8517-ed1e3c4bae73.png)

And I had a few crashes when saving a file.

OS: Windows 10
HaxeDevelop Version: 
![image](https://user-images.githubusercontent.com/576184/32371312-aa02f8a2-c090-11e7-8277-bfc8cdab2498.png)

If you need more info, let me know.

**Comment by SlavaRa** [comment]
@markknol what version of the compiler?

**Comment by markknol** [comment]
Doesn't seem to matter, but multiple versions:
* 4.0 preview 2
* 3.4.2

**Comment by Neverbirth** [comment]
I've seen similar errors thrown by the compiler because of macros, I wonder if it's related.

**Comment by markknol** [comment]
Yes, there are several macros involved. I now switched back to older version (https://github.com/fdorg/flashdevelop/commit/29f5e11d76) and everything works:

**Comment by Neverbirth** [comment]
Just getting those messages in the output panel doesn't mean there is actually a problem, it's just the output of the compiler itself. The difference with old FD versions is the support of the diagnostics display mode of the compiler. You can disable it in the settings, but again, these messages don't represent a real problem in the code... it's a shame to get these fake errors, I already got used to seeing them when trying to use any display mode from the compiler service...

**Comment by markknol** [comment]
This might be related to https://github.com/fdorg/flashdevelop/issues/1808, Ill close this one for now since there are no actionable points.
