### ISSUE TITLE
[HaXeContext][CodeRefactor] Refactor renaming not working for local vars

### ISSUE THREAD

**Issue by andrew-git** [fdorg/flashdevelop#1752]
With Completion Server and Enabled Compiler Services (EnableForFindAllReferences), not working renaming of local vars. 
When EnableForFindAllReferences disabled, works fine

**Comment by SlavaRa** [comment]
Haxe 3.2.1
FlashDevelop 5.3.0.68

**Comment by SlavaRa** [comment]
Bug

**Comment by SlavaRa** [comment]
Fixed in development branch.
