### ISSUE TITLE
Exception when saying yes to saving modifications when a modified file is deleted

### ISSUE THREAD

**Issue by gene-pavlovsky** [fdorg/flashdevelop#1775]
Steps to reproduce
1) Create a file in a directory, save it
2) Modify the file (don't save it)
3) In the project panel, select the file, press Delete
4) There is a dialog "File will be moved to the recycle bin. OK / Cancel"
Answer OK
5) There is a dialog "Do you want to save the current changes? Yes / No / Cancel"
Answer Yes

I think the "do you want to save the current changes" dialog shouldn't show up.
In reality the file which was supposed to be removed, is still there (with saved changes).

Related bug:
Repeat steps 1 and 2 from above, then in the Project panel try to delete the whole directory containing that file. There is a dialog "... and all its contents will be moved to the recycle bin. OK / Cancel". Answer OK. There is (again) a dialog "Do you want to save the current changes? Yes / No / Cancel". Answer Yes.
A `System.IO.DirectoryNotFoundException` exception is thrown - FD is trying to save the file to that directory which it just deleted.

**Comment by SlavaRa** [comment]
Bug

**Comment by Meychi** [comment]
I tried the first one and it deleted the file fine but asked to save the modified file and then saved a new copy. No exception here. I think its good to confirm if the changes should be saved if you accidently hit del and enter. They are next to each other in my keyboard. The second one is a bug.

@SlavaRa: Can you recreated the first?

**Comment by SlavaRa** [comment]
Yes, I came across a similar one, I'll try to figure out what's going on tonight

**Comment by gene-pavlovsky** [comment]
I think maybe in the first case a different dialog should show up, smth like. "The file has local modifications. Are you sure you want to delete it?".
I think the problem is the order of events that fire, so as a result the "do you want to save?" dialog appears after the "do you want to delete?" dialog.

Personally, if any application (or OS command) asks me a confirmation to delete something, I don't like to say "yes, yes, yes, I'm damn sure". Instead, I'd like to be presented all the info at once (e.g. I'm deleting a non-empty directory, a file inside has unsaved changes, well then tell all that in one dialog, and if I click yes, delete the whole thing without any further questions).

**Comment by gene-pavlovsky** [comment]
It looks like there were some changes regarding this issue.
Here's what's happening now in the first issue described, when I press Delete on a file in the project panel:
- A dialog pops up, titled "Confirm", message: Some elements have local modifications. Remove them anyway?
SomeFile.hx
- I answer "OK"
- Another dialog pops up, titled "Confirm", message: "SomeFile.hx" will be moved to the Recycle Bin.
- I answer "OK"
- A third (!) dialog pops up, titled "Save Changes In: SomeFile.hx", message: Do you want to save the current changes?

Personally, I think answering OK to the first dialog is enough, delete the file after that. In the most paranoid case, second dialog makes sense, after that for sure delete the file. The "Save changes" dialog shouldn't show up since the user already answered OK to the first dialog.

The second issue (with non-existing directory) is still reproducible.

There is a third issue. Sometimes, following the same steps as the first issue, a "Would you like to remove the file(s) from version control?" dialog pops up instead of the sequence of dialogs described above. Answering "OK" doesn't show any further dialogs, the file is removed.

Partially related to #1939

**Comment by SlavaRa** [comment]
```
Could not find a part of the path 'C:\projects\opensource\Haxe\NodeJSTestProject\src\final\CFoo.hx'.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy)
   at System.IO.FileStream..ctor(String path, FileMode mode)
   at PluginCore.Helpers.FileHelper.WriteFile(String file, String text, Encoding encoding, Boolean saveBOM)
   at FlashDevelop.Docking.TabbedDocument.Save(String file, String reason)
   at FlashDevelop.MainForm.Save(Object sender, EventArgs e)
```

**Comment by gene-pavlovsky** [comment]
Confirmed fixed, thanks
