### ISSUE TITLE
ADT sessions not closing and debug sessions error

### ISSUE THREAD

**Issue by Michoko92** [fdorg/flashdevelop#1778]
Hi,

I get the "Error details: net.sf.jni4net.jni.JNIException: Can't find jni4net.j-0.8.8.0.jar" error with version 5.3.0. All works fine with 5.2.0.

I tried updating from 5.2, or reinstalling 5.3 from scratch, same result.

Here is my config:
Windows 10 Pro
Intel Core i7
16 GB RAM
Java 1.8

I found a fix though: just move the "jni4net.j-0.8.8.0.jar" file that is located in the "Plugins" directory, to the root folder of your FD install dir (i.e. probably "C:\Program Files (x86)\FlashDevelop"). Strange but it works 100% for me.

**Comment by Meychi** [comment]
@Neverbirth, @SlavaRa?

**Comment by Meychi** [comment]
Do you happen to have both of these files present:
jni4net.n.w32.v20-0.8.8.0.dll
jni4net.n.w32.v40-0.8.8.0.dll

**Comment by Michoko92** [comment]
I had those 2 files when I upgraded from FD 5.2. As I suspected it may create conflicts, I uninstalled FD completely, and only installed FD 5.3. Now I only have the file named "jni4net.n.w32.v40-0.8.8.0.dll" in the Plugins dir. 
But even in that case, I need to move the "jni4net.j-0.8.8.0.jar" file one level up so FD can work properly.

**Comment by Meychi** [comment]
Ok, thanks, it needs to be in the path resolving then.

**Comment by Meychi** [comment]
@SlavaRa, @Neverbirth: Could this be due to changes to PathHelper:
https://github.com/fdorg/flashdevelop/commit/94d01d4bb66b804258fe0e10929424d073860fdd
or
https://github.com/fdorg/flashdevelop/commit/7ccc1b43f926061eb403f54c10dea09807d3f0ab

**Comment by Meychi** [comment]
More info: http://www.flashdevelop.org/community/viewtopic.php?f=13&t=13008

**Comment by Meychi** [comment]
#1787
