### ISSUE TITLE
[Haxe] References libs not found

### ISSUE THREAD

**Issue by ncannasse** [fdorg/flashdevelop#1793]
I used to be able to add -lib in "Additional Dependencies", or include other .hxml there that might have -lib as well. With latest HaxeDevelop 5.3 the libraries are only listed if they are part of the "Libraries" configuration section, which is a regression vs 5.2

**Comment by Meychi** [comment]
@SlavaRa?

**Comment by SlavaRa** [comment]
@Meychi I'll check it out throughout the day.

**Comment by SlavaRa** [comment]
@ncannasse What type of project are you using?

**Comment by ncannasse** [comment]
It's an HashLink project, but I have the same with a Haxe/JS one

**Comment by SlavaRa** [comment]
Thanks

**Comment by Meychi** [comment]
Seems it due to this PR: https://github.com/fdorg/flashdevelop/pull/1339

**Comment by Meychi** [comment]
@Neverbirth, comments?

**Comment by ncannasse** [comment]
Please note that the fix only partially close the issue : it still does not
allow to have -lib in an external hxml file referenced from the parameters
as the previous behavior did

**Comment by SlavaRa** [comment]
Please, one problem - one issue, ok?

**Comment by ncannasse** [comment]
That is the same issue, only the commit fixed it partially. Should I open
again a new one with same content ?

**Comment by SlavaRa** [comment]
I do not insist, but it's better to open a new task and describe the structure of the hxml file, ок?

**Comment by SlavaRa** [comment]
@ncannasse I think that there is some kind of nuance, because my project consists of a lot of hxml files and everything is fine

**Comment by ncannasse** [comment]
Let me try to rephrase again :

If I add `libraries.hxml` in "Advanced compiler options", HaxeDevelop will
not list the "-lib" found in this hxml as part of the "References" lists,
while it did work with HD 5.2.x

**Comment by SlavaRa** [comment]
now I understand the problem, i will fix it today

**Comment by SlavaRa** [comment]
Fix: #1827
