### ISSUE TITLE
Completion list shows up then disappears

### ISSUE THREAD

**Issue by gene-pavlovsky** [fdorg/flashdevelop#1795]
After updating FD to 5.3.0.3 (release version)

Working on a *Haxe* project:
With the new build, whenever I type something which would normally offer the completion list, e.g. `this.`, the completion list appears for a brief moment, then magically disappears. 
It happens always.
I have haxe 3.4.4.

This doesn't happen in an AS3 project.

**Comment by SlavaRa** [comment]
do you use PostfixCompletionPlugin?

**Comment by gene-pavlovsky** [comment]
Not on this PC

**Comment by SlavaRa** [comment]
Completion mode?
Can you give me sample project?

**Comment by gene-pavlovsky** [comment]
Completion mode = compiler.
I will see if I can make a minimal example.

**Comment by gene-pavlovsky** [comment]
Well unfortunately I can't reproduce it with a simple test project.
It is reproducible with the project at work, which I can't share of course. Maybe @Neverbirth should be the one to look into it since he has access to the same sources :)

**Comment by Ujimych** [comment]
In my project, it can be caught 100%.
The video can be seen.
