### ISSUE TITLE
Error after switching from an AIR AS3 project to a Haxe JS project

### ISSUE THREAD

**Issue by gene-pavlovsky** [fdorg/flashdevelop#1796]
After updating FD to 5.3.0.3 (release version)

I had an AIR AS3 project open, then I opened a recent Haxe JS project, using the Recent Projects toolbar icon.
An error dialog popped up, saying:
```
No process is associated with this object.

   at System.Diagnostics.Process.EnsureState(State state)
   at System.Diagnostics.Process.EnsureState(State state)
   at System.Diagnostics.Process.get_Id()
   at PluginCore.Utilities.ProcessRunner.KillProcess()
```

**Comment by Neverbirth** [comment]
I think this could be related to the Haxe Diagnostics support. @chipshort

**Comment by gene-pavlovsky** [comment]
I could only reproduce it once so far...

**Comment by gene-pavlovsky** [comment]
Looking at the code in `PluginCore.Utilities.ProcessRunner`, I see an unsafe usage of `Process.Id` (which was the cause of the exception). The docs on this property mention: "The process Id is not valid if the associated process is not running. Therefore, you should ensure that the process is running before attempting to retrieve the Id property. Until the process terminates, the process identifier uniquely identifies the process throughout the system."
The code in `ProcessRunner` only checks if process is not null, but doesn't check if it has exited. It also doesn't check if the process has ever been started (it's possible that the process property had already been assigned to, but then the thread was interrupted before starting it).

**Comment by SlavaRa** [comment]
I can't reproduce it

**Comment by gene-pavlovsky** [comment]
I think it's a very transient problem probably related to linters, like @Neverbirth said.
And probably adding some safety to the `Process.Id` usage I've mentioned above (as recommended by .NET docs) wouldn't hurt.
