### ISSUE TITLE
Intellisense listing keeping disappearing after 1 sec

### ISSUE THREAD

**Issue by zacdevon** [fdorg/flashdevelop#1805]
I've installed the latest FD 5.3 and am using Haxe. I just created a new project and whenever I start typing any code, the Intellisense listing shows and disappears within a second, even before I have a chance to choose any item from the list. Is this a known issue?

Even the Intellisense documentation tips hide after a second...

**Comment by zacdevon** [comment]
See this GIF here: 

![GIF](http://g.recordit.co/14JRwxwBkN.gif)

**Comment by SlavaRa** [comment]
#1795

**Comment by zacdevon** [comment]
I am providing my FD and project for you to reproduce this...

Project:
[Openbook.zip](https://github.com/fdorg/flashdevelop/files/1503941/Openbook.zip)

FD:
https://we.tl/cle2bqJaVb

**Comment by SlavaRa** [comment]
Thanks

**Comment by Neverbirth** [comment]
Got a repro of this and I'm looking into it. It's interesting... either this bug has been here forever but before was not possible to trigger, or it's new, I will investigate more and try to fix it today.

**Comment by Neverbirth** [comment]
So it's kind of new bug, but by looking at the logic it was going to happen sooner or later I would say... looking at what is the best way to solve.

**Comment by Neverbirth** [comment]
I will work on a fix later today unless I got other problems.

**Comment by zacdevon** [comment]
Thank you. It's a show stopper so waiting for a fix. FD is cool otherwise :)

**Comment by Neverbirth** [comment]
Pushed a fix, although the original problematic logic is still there, hopefully can be removed for FD 6.

**Comment by zacdevon** [comment]
Wow, thanks. What was the original problematic logic?
