### ISSUE TITLE
Comments for extension methods are not showing [haxe]

### ISSUE THREAD

**Issue by zacdevon** [fdorg/flashdevelop#1806]
I've installed the latest FD 5.3 and am using Haxe. I just created a new project and created some static extension methods. 

```haxe
/**
	 * Checks if the array contains the given value.
	 * 
	 * @param array			The input array. Can be null.
	 * @param searchTerm	What to find within the input array
	 * @param startAt		Which index to start searching at?
	 * 
	 * @author Zac Devon
	 */
	static public function contains<T>(array:Array<T>, searchTerm:T, startAt:Int = 0):Bool {
		if (array == null){
			return false;
		}
		return array.indexOf(searchTerm, startAt) > -1;
	}
```

But when I try to use it like `myArray.contains()` the intellisense tip comes up without any comments. I think this is a missing feature.

![image](https://user-images.githubusercontent.com/33624470/33239103-492829ce-d2c1-11e7-9981-0e5446167694.png)

When I use it normally like `Arrays.contains`, the tip shows up fine.

![image](https://user-images.githubusercontent.com/33624470/33239099-3d8dcf60-d2c1-11e7-858e-54ec4f17199f.png)

**Comment by SlavaRa** [comment]
I'll check it tomorrow

**Comment by Neverbirth** [comment]
If I'm not wrong extension methods information comes from the compiler service, maybe it's not providing the description in this case? of course it could be that we miss displaying it too.

**Comment by zacdevon** [comment]
Excellent. Thank you for this quick fix. Awaiting the next build eagerly.

**Comment by Neverbirth** [comment]
You can download development builds here:

http://flashdevelop.org/downloads/builds/
