### ISSUE TITLE
Some .NET problems probably

### ISSUE THREAD

**Issue by NicholasHasAwoken** [fdorg/flashdevelop#1807]
Whenever I start FlashDevelop, I get next exception:

> System.NullReferenceException: Ссылка на объект не указывает на экземпляр объекта.
>    в System.String.Concat(Object arg0, Object arg1, Object arg2)
>    в FileExplorer.PluginUI.UpdateUI(String path, DirectoryInfo directory, FileSystemInfo[] infos)
>    в FileExplorer.PluginUI.<>c__DisplayClass40_0.<PopulateFileView>b__2()
>    в System.Windows.Forms.Control.InvokeMarshaledCallbackDo(ThreadMethodEntry tme)
>    в System.Windows.Forms.Control.InvokeMarshaledCallbackHelper(Object obj)
>    в System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
>    в System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
>    в System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
>    в System.Windows.Forms.Control.InvokeMarshaledCallback(ThreadMethodEntry tme)
>    в System.Windows.Forms.Control.InvokeMarshaledCallbacks()

**Comment by NicholasHasAwoken** [comment]
I tried deleting both FileExplorer and Data folders separately. It didn't work. 

It's happening since fresh install. I hadn't such problems in past while using FlashDevelop.
When I found out that there is no Linux version for FlashDevelop , I switched back. 
Then I had to install all those .NET frameworks and Java, could forget something on the way.

**Comment by Neverbirth** [comment]
I don't think this is some missing component installation, or it would somehow show in another way. I could make a build with extra log if you are ok with that.

**Comment by NicholasHasAwoken** [comment]
Sometimes, I get another exception:

> System.AccessViolationException: Попытка чтения или записи в защищенную память. Это часто свидетельствует о том, что другая память повреждена.
>    в System.String.wstrcpy(Char* dmem, Char* smem, Int32 charCount)
>    в System.String.FillStringChecked(String dest, Int32 destPos, String src)
>    в System.String.Concat(String str0, String str1)
>    в FileExplorer.PluginUI.UpdateUI(String path, DirectoryInfo directory, FileSystemInfo[] infos)
>    в FileExplorer.PluginUI.<>c__DisplayClass40_0.<PopulateFileView>b__2()
>    в System.Windows.Forms.Control.InvokeMarshaledCallbackDo(ThreadMethodEntry tme)
>    в System.Windows.Forms.Control.InvokeMarshaledCallbackHelper(Object obj)
>    в System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
>    в System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
>    в System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
>    в System.Windows.Forms.Control.InvokeMarshaledCallback(ThreadMethodEntry tme)
>    в System.Windows.Forms.Control.InvokeMarshaledCallbacks()

**Comment by Meychi** [comment]
http://www.flashdevelop.org/community/viewtopic.php?f=6&t=13014&p=55728#p55728

**Comment by Meychi** [comment]
The forum poster said that the crash happened on x64 not on x86, could anything be on that side?

**Comment by Neverbirth** [comment]
Back in the day when I fixed that one I tried searching for possible similar problems, but couldn't find anything, of course everything is possible.

Maybe we should provide also the pdbs for the builds as an option so people can use them for reporting errors... with them when getting stack traces we would get more information like the exact line where the error happened.

**Comment by NicholasHasAwoken** [comment]
Well. I have Win 7 64 bit.

It was interesting fact, that someone had problem exactly same as mine. So I tried installing FD 5.2.
And it worked! I don't get those exceptions for some time yet!

**Comment by NicholasHasAwoken** [comment]
I tried 5.3.1.2 recently. I don't get such type of exception anymore.
