### ISSUE TITLE
[Haxe] Refactor - Organize Imports incorrect behavior

### ISSUE THREAD

**Issue by andrew-git** [fdorg/flashdevelop#1809]
In latest FD verison (5.3.1.20), Refactor - Organize Imports action removes all imports (in Haxe, as3 work ok)

**Comment by Neverbirth** [comment]
I guess it comes from #1776?

**Comment by andrew-git** [comment]
Probably yes, missed that issue

**Comment by gene-pavlovsky** [comment]
I see that the fix for #1776 has been merged, however I can reproduce the issue with the latest development build.
Sample class:
```haxe
package;

import haxe.Timer;
import tink.CoreApi.Future;

class Test {
	public function new() {}

	public function getBalance():Future<Float>
	{
		return Future.async(function (cb) {
			Timer.delay(function () cb(Math.PI), 100);
		});
	}
}
```

Organize imports removes both imports.

**Comment by markknol** [comment]
I experience this too

**Comment by Neverbirth** [comment]
Gene misunderstood me, I meant that I think that PR broke this (I could be wrong of course). Hopefully @SlavaRa will have time to look into this soon?

**Comment by SlavaRa** [comment]
I will check during the day

**Comment by SlavaRa** [comment]
I was able to reproduce, I will fix it during the day, sorry

**Comment by andrew-git** [comment]
Thanks. Fix works

**Comment by markknol** [comment]
Awesome, thanks for fast fix!

**Comment by SlavaRa** [comment]
@Mark, thanks for @Neverbith
