### ISSUE TITLE
Haxe completion breaks after a regex

### ISSUE THREAD

**Issue by gene-pavlovsky** [fdorg/flashdevelop#1814]
Valid Haxe code:

```haxe
package;

class Test {
	public function new() {}

	function parseClassBody(text:String):String {
		var rx = ~/\bclass\b[^{]*{\s*\n/;
		return rx.match(text) ? ~/\s*}\s*$/.replace(rx.matchedRight(), '\n') : 'Error\n';
	}
}
```

Place the caret after the end of the function, and type `fu`.
Expected to see `function`, instead the completion list has `Float` etc.
The culprit that confuses the completion is the `}` in the second regexp (`~/\s*}\s*$/`). Looks like it is treated as `}` closing the function block.
Tried Compiler and FlashDevelop completion modes, same result.

**Comment by Neverbirth** [comment]
What if you try the previous stable FD build? I have the feeling it may come from the changes that also created issue https://github.com/fdorg/flashdevelop/issues/1664 or other similar changes, but who knows.

**Comment by SlavaRa** [comment]
Bug, I will fix it tomorrow

**Comment by SlavaRa** [comment]
please mark as bug

**Comment by gene-pavlovsky** [comment]
Seems to be fixed by the PR
