### ISSUE TITLE
Contextual import generation doesn't work in Haxe enums

### ISSUE THREAD

**Issue by gene-pavlovsky** [fdorg/flashdevelop#1833]
Create a new enum file, give one of the constructors an argument of a type which should be imported.
Press `Ctrl+Shift+1` with the cursor on the argument type.
Result: No contextual code generation available.
Expected: Auto-import the type.

```haxe
package;

enum TimerSignal {
  Fire(timer:Timer); // try to import Timer
}
```

**Comment by SlavaRa** [comment]
Bug

**Comment by SlavaRa** [comment]
I could fix it today, but at the moment there are too many open PRs from me

**Comment by gene-pavlovsky** [comment]
Nice use of blackmail to motivate people to do CR :)

**Comment by SlavaRa** [comment]
yes

**Comment by SlavaRa** [comment]
@gene-pavlovsky fixed, but I'm sure that the fix will not soon fall into the editor

**Comment by gene-pavlovsky** [comment]
We will see :) Hope dies last
