### ISSUE TITLE
Haxe 4.0 support

### ISSUE THREAD

**Issue by ncannasse** [fdorg/flashdevelop#1861]
In Haxe 4.0+ , columns are 1 based instead of 0 based (before the first char of a line was 0, now it's 1), and positions in the file are utf8-based instead of binary-based (before "é" was counting as 2 chars, it's one now).

This lead to problems with error reporting not being correctly done in HaxeDevelop, including completion if there are utf8 chars in the file. Could you detect if Haxe is 4.0+ and change the behavior accordingly ?

**Comment by SlavaRa** [comment]
WIP

**Comment by SlavaRa** [comment]
I was faced with the fact that the antivirus does not allow me to install haxe-4.0.0preview2, but with 3.4.4 no problem.
As soon as I can install haxe4 and check the functionality, I will make a pull request.

**Comment by SlavaRa** [comment]
@ncannasse hi, how can i test it?

**Comment by ncannasse** [comment]
Any Haxe error using 4.0-RC3 will display wrongly only HaxeDevelop.
And if you have a string containing "é" before that it will produce another issue.
Disable your A/V to install Haxe, it's safe.

**Comment by SlavaRa** [comment]
> Disable your A/V to install Haxe, it's safe.

ok :)
