### ISSUE TITLE
[Haxe] Autocomplete: Class-level autocomplete when writing default values in `new`

### ISSUE THREAD

**Issue by Yanrishatum** [fdorg/flashdevelop#1887]
Issue: When writing default values in constructor autocomplete provides completion for class-level instead of function-level.  
For clarity:  
![what I'm talking about](https://i.imgur.com/c68mcPR.gif)
Reproduction: Add a value to constructor and start writing default value for it.  
Version: FD#825cdded68  
Present since: So long, I can't remember already.  

Reproduction project: https://drive.google.com/open?id=1OflVsWGLp2XH7kpO56astTVI-GcZd8zn (is openfl project, but can be reproduced even with hxml project)

**Comment by SlavaRa** [comment]
@Yanrishatum Thanks
