### ISSUE TITLE
[Bug][Haxe][ASFileParser] Wrong parse of class with single-line functions

### ISSUE THREAD

**Issue by SlavaRa** [fdorg/flashdevelop#1907]
```haxe
package;
class Main {
	public function extractLocalVariable() var a = 1;
}
```
Members - 2
- extractLocalVariable : Function
- a : Variable
  
![2018-01-05_7-53-55](https://user-images.githubusercontent.com/1700940/34596034-9b8b41ba-f1ed-11e7-9d9c-8fadc7dbec31.png)

**Comment by gene-pavlovsky** [comment]
Perhaps it's time to split Haxe parser from AS parser. Haxe will make more and more changes in the future, while AS can be considered frozen. Can't see any point to keep them together, further Haxe-related development may cause regressions for AS, while they don't bring any benefits to AS.
