### ISSUE TITLE
[haxe] Completion not usable...

### ISSUE THREAD

**Issue by delahee** [fdorg/flashdevelop#192]
Hi !

This is a bit obscure here but when we try to use completion (CTRL-SPACE) with motion-twin/h3d, we have errors :

Haxelib not found
Error: Could not process argument haxelib
Class name must start with uppercase character

This sometime work though...is there anyway we can get it back ? 
Can you instruct us how to help you fix this ? 

Thanks !

**Comment by NemoStein** [comment]
I think we have a king of regression here: https://github.com/HaxeFoundation/haxe/issues/1932#issuecomment-189713925
