### ISSUE TITLE
[AS3] Code completion broken for Vectors on 5.3.1 

### ISSUE THREAD

**Issue by neuronix** [fdorg/flashdevelop#1947]
Code completion detects type correctly but fails to properly create the import of the sub class and complete the line of code with `Vector.<T>`.

1. `var myvector:Vector.< MyType > = new Vec`...
2. drop down shows `new Vector.<my.package.MyType>`
3. Press ENTER or Click on drop down suggestion
4. Code completion imports: `import Vector;`
5. Code completion stays on:  `var myvector:Vector.<MyType> = new Vector`

Expected result: `import my.package.MyType;` and `var myvector:Vector.<MyType> = new Vector.<MyType>;`

**Comment by SlavaRa** [comment]
I will check it today

**Comment by SlavaRa** [comment]
`var myvector:Vector.` - really?

**Comment by neuronix** [comment]
Sorry Github markdown was hiding the type for some reason. I added spaces around the type : Vector.< T > for it to show up.

**Comment by SlavaRa** [comment]
You can use ` for escaping your code
