### ISSUE TITLE
MXML creation

### ISSUE THREAD

**Issue by SandersAlex** [fdorg/flashdevelop#1948]
When creating "mxml", you can not specify a parent class, the "Application" type is immediately suggested. If I create a "Skin", then I need "HostComponent", this functionality is in the FB.

При создании "mxml" нельзя указать родительский класс, сразу предлагается тип "Application". Если я создаю "Шкурку", то мне нужен "HostComponent", данный функционал есть в ФБ (Rus)

**Comment by Neverbirth** [comment]
I'm surprised people are still using MXML heh. I did back in the day a lot of MXML improvements for my current company but most of these changes were never merged back into the official branch... maybe I could look into this, but I don't know if it's worth it actually :S.

Both this and #1949 were done.
