### ISSUE TITLE
MXML import outside <fx:Script><![CDATA[ ... ]]></fx:Script>

### ISSUE THREAD

**Issue by SandersAlex** [fdorg/flashdevelop#1949]
When importing a class for a variable, "import" throws to the xml zone, sample:

```mxml
<s:DataGroup >
   ...
</s:DataGroup>
import mx.collections.IList;

<fx:Script>
<![CDATA[
var a:IList;
]]>
</fx:Script>
```

**Comment by Neverbirth** [comment]
I'm surprised people are still using MXML heh. I did back in the day a lot of MXML improvements for my current company but most of these changes were never merged back into the official branch... maybe I could look into this, but I don't know if it's worth it actually :S.

Both this and #1948 were done.

**Comment by SandersAlex** [comment]
I need this decision

**Comment by Neverbirth** [comment]
The fix for this I think is easy to port back, I will look into it.
