### ISSUE TITLE
MXML Automatic completion & substitution of properties

### ISSUE THREAD

**Issue by SandersAlex** [fdorg/flashdevelop#1951]
1. When creating an "mxml" element and populating its properties, you must additionally click on "=" to display the property and fill it, if necessary.

As would be desirable: if the property is present in the element, then:
1.1. You start typing - "vi", the tooltip "visible" is displayed;
1.2. Press "enter" and immediately fill this property with its possible values, if necessary and do not press "=".

2. When displaying possible values for a property, you need to cycle through the "up" button to go to the last item in the list of suggested values. Similarly, for the button "down", when we are on the last element of the list of suggested values, immediately go to the first value in the list.

**Comment by Neverbirth** [comment]
I also did this back in the day. Second case is completely unrelated, and I think there is already a setting for this? Wrap completion list or something like that maybe?

**Comment by SlavaRa** [comment]
Tools -> Program Settings -> FlashDevelop -> Controls -> Wrap List
