### ISSUE TITLE
Autoimport importing private type on completion in it's body

### ISSUE THREAD

**Issue by Yanrishatum** [fdorg/flashdevelop#1969]
Autoimport currently automatically imports private type if it's name was autocompleted inside private said private type.

<details><summary>Example code</summary><p>

```haxe
package com;

class SomeClass
{

  public function new() 
  {
    
  }
  
}

private class SomeOtherClass // <- is private, no imports allowed.
{
  public function new(tail:SomeOtherClass) // <- when autocompleting private class name, import will be inserted.
  {
    
  }
}
```

</p></details>

Showcasing issue:
![img](https://i.imgur.com/V5NC6NM.gif)

**Comment by SlavaRa** [comment]
I will check this today

**Comment by SlavaRa** [comment]
I will fix it tonight
