### ISSUE TITLE
Haxe - Reference updates according to Haxelib tag

### ISSUE THREAD

**Issue by ericguo** [fdorg/flashdevelop#197]
I can see the References of project update according to haxelib tags in Project.xml usually like <haxelib name="gamecenter" />
However it doesn't work when I adds some conditional tag like <haxelib name="gamecenter" if="ios" />

**Comment by elsassph** [comment]
Libraries not matching the selected target in the main toolbar are omitted, this is the expected behaviour.
You can manually type 'ios' as target even if it's not in the default list.
