### ISSUE TITLE
haxe libs install prompt, also ask for -net-lib attribute

### ISSUE THREAD

**Issue by sebpatu** [fdorg/flashdevelop#1981]
Hi,
 the new feature that can detect missing haxe libraries and propose to install them for the user is good.
but it also detect potential ibraries with -net-lib attribute
it should detect the haxe compiler attribute more precisely.
Thanks

**Comment by SlavaRa** [comment]
Thanks, I will check it tonight

**Comment by sebpatu** [comment]
thanks :)
