### ISSUE TITLE
import Vector;

### ISSUE THREAD

**Issue by matrix3d** [fdorg/flashdevelop#1998]
the fd auto add import Vector; code
input new Vector.<String>;
and can not add new Vector.<String>();

**Comment by SlavaRa** [comment]
![newvector](https://user-images.githubusercontent.com/1700940/35902053-d2b6b2fc-0bea-11e8-96c1-21dd18267547.gif)
FD 5.3.1.122

**Comment by matrix3d** [comment]
![bug2](https://user-images.githubusercontent.com/4150631/35903666-264816d8-0c1b-11e8-950d-4d260f5de67e.gif)

**Comment by matrix3d** [comment]
5.3.1.2  master#be0b331f18

**Comment by SlavaRa** [comment]
Thanks

**Comment by SlavaRa** [comment]
#1947

**Comment by SlavaRa** [comment]
Will be fixed tomorrow:)
