### ISSUE TITLE
FlashDevelop can't find Vector class

### ISSUE THREAD

**Issue by NicholasHasAwoken** [fdorg/flashdevelop#2002]
Autocompletion doesn't see Vector class. I'm afraid I will not be able to compile code.

Also, Vector is not highlighted, just like any unknown or unreachable definition.

**Comment by SlavaRa** [comment]
as3|haxe|php|js?

**Comment by NicholasHasAwoken** [comment]
As3

**Comment by SlavaRa** [comment]
fd version?

**Comment by NicholasHasAwoken** [comment]
5.3.1.2

**Comment by SlavaRa** [comment]
![2002_as3_vector](https://user-images.githubusercontent.com/1700940/36024905-4843ccf4-0da2-11e8-8e60-77cf558eb42d.gif)

**Comment by NicholasHasAwoken** [comment]
What should I do if some reason, I don't have such class? http://prntscr.com/icc5z7
