### ISSUE TITLE
F4 opens file from the wrong folder

### ISSUE THREAD

**Issue by gene-pavlovsky** [fdorg/flashdevelop#2014]
I was working on project A, which has library L in it's .haxelib dir.
While doing so, I've opened `ISomeInterface` (coming from library L).
I then closed all files, and opened library L's project (in a completely separate dir).
I opened a class which `implements ISomeInterface`, pressed F4 on that interface, and instead of opening it's source in the current project's dir, FD opened the one in the previous project's .haxelib dir. By contrast, opening this interface via the "Open Resource" (Ctrl+R) dialog, the correct file from the current project is opened.

**Comment by SlavaRa** [comment]
WIP

**Comment by SlavaRa** [comment]
@gene-pavlovsky please try development-build from https://ci.appveyor.com/project/FlashDevelop/flashdevelop-devel/build/5.3.3.13-lynciepp/artifacts

**Comment by gene-pavlovsky** [comment]
Doesn't fix this bug

**Comment by SlavaRa** [comment]
Ok, thanks

**Comment by gene-pavlovsky** [comment]
Works correctly with the latest dev build

**Comment by gene-pavlovsky** [comment]
Thanks!
