### ISSUE TITLE
 Full code hint is not available Is there a solution?

### ISSUE THREAD

**Issue by bihan81** [fdorg/flashdevelop#2042]
![code_hint](https://user-images.githubusercontent.com/13758235/36530159-ae190ef8-17fd-11e8-95a3-91cc98f9f57f.png)  
[ 5.3.3 ]

![code_hint_5_2](https://user-images.githubusercontent.com/13758235/36531642-ef4afdb0-1801-11e8-9606-95da029a78e0.png)
[ 5.2 ]

TweenMax, one of the commonly used twin classes.
I could see the full code before (perhaps version 5.2), but now I can see it (5.3.3) 
This is not all I get. Did anything change?
Maybe I was not good at English so I could not understand the release notes.

Does the extension class do not appear to have any parent function hints, have any of the settings been added?

**Comment by SlavaRa** [comment]
Thanks for the report. I will check it tonight.

**Comment by SlavaRa** [comment]
AS3 or Haxe?
Can you try build from http://flashdevelop.org/downloads/builds/
Can you give me simple project on which I can reproduce the error?

**Comment by bihan81** [comment]
I was forgetting about this problem. >,<
The same problem did not occur when we received the new version.

Thank you
