### ISSUE TITLE
Basic support for AIR 29 and FP 29

### ISSUE THREAD

**Issue by SlavaRa** [fdorg/flashdevelop#2045]
https://labs.adobe.com/technologies/flashruntimes/air/

**Comment by Xgamefactory** [comment]
and where is the support ? some notes maybe would be helpful

**Comment by kevinfoley** [comment]
@SlavaRa  AIR 29 does not show up in the "install software" AppMan. When can we expect to see AIR 29?

**Comment by SlavaRa** [comment]
https://github.com/fdorg/flashdevelop/pull/2116
