### ISSUE TITLE
Ctrl + Click goto Declaration is not working on Windows 10

### ISSUE THREAD

**Issue by dkolyesnik** [fdorg/flashdevelop#2049]
F4 and Right Click -> Goto Declaration is working.
There is no highlighting or cursor change when I press Ctrl and hover mouse over method or type

HD 5.3.x, I had this issue with all last versions that I was using including 5.3.3.1.
Didn't pay attention to this until I saw this feature working on my laptop (windows 8.1).

**Comment by elsassph** [comment]
AFAIK Ctrl+Click navigation was provided by a plugin. It isn't a default feature.

**Comment by SlavaRa** [comment]
@dkolyesnik https://github.com/SlavaRa/fdplugin-quicknavigate
