### ISSUE TITLE
is the *.as,but get hx

### ISSUE THREAD

**Issue by matrix3d** [fdorg/flashdevelop#2056]
![default](https://user-images.githubusercontent.com/4150631/36766611-93e12cb4-1c71-11e8-83d4-67b19fee2fb0.gif)

**Comment by SlavaRa** [comment]
Is it Haxe project?

**Comment by matrix3d** [comment]
it is as3 project

**Comment by matrix3d** [comment]
![3](https://user-images.githubusercontent.com/4150631/36773636-8a9a82c6-1c95-11e8-85e5-c28439377e1b.gif)
and this [model]code ,not the true code.

the left is the source of swc.

**Comment by matrix3d** [comment]
@SlavaRa it is get the as.but not the same code of my swc.

my swc the same package name of adobe

**Comment by SlavaRa** [comment]
Do you have some code in the files whose names and packages are the same as the names and package from the swc library?

**Comment by matrix3d** [comment]
I wrote some as the same package name provided by Adobe. Then the generated SWF into the box directory. Then through the FD view, I found it is not as written, but use Adobe as the code. However, this error will not cause any impact.
The most important is that F4 error, this error is difficult to use.

**Comment by SlavaRa** [comment]
@matrix3d Please try latest development build from http://flashdevelop.org/downloads/builds/

**Comment by matrix3d** [comment]
@SlavaRa the same
