### ISSUE TITLE
Can't install the plugins ! from the latest build 

### ISSUE THREAD

**Issue by Gamezpedia** [fdorg/flashdevelop#2066]
Hi, i just build a new machine for development and did install everything fresh , and it goes smoothly till this problem - i can't install plugins it just throws me this error so i guess may be there is something wrong with the URL.

it's same with the Themes & Haxe Neko compiler links too.

![image](https://user-images.githubusercontent.com/1169093/36906556-a17f1f68-1e4f-11e8-9274-4ae478c7872f.png)

thanks

**Update** 

so i ended up copying the dll's from the old installation folders.

**Comment by HerrBvomSee** [comment]
On my side it's the same problem. Tried to install HaxeDevelop on two clean machines with the same result that I can not install any tool/plugin from this dialog. 
Also I do not have an preinstalled versions so I can not copy any old dlls to this installation.

**Comment by Neverbirth** [comment]
It seems related to this: https://githubengineering.com/crypto-removal-notice/

**Comment by blipvert** [comment]
Is there any workaround for this?  Even a way to change the failing URL to a local path would be fine.

**Comment by SlavaRa** [comment]
via #2715
