### ISSUE TITLE
[AS3] latest dev build injects package name instead of just classname

### ISSUE THREAD

**Issue by neuronix** [fdorg/flashdevelop#2082]
Had to update to dev build to fix F4 bug, but now run into this one:

1. Type "MyCla...", select suggested "my.package.MyClass"
2.  my.package.MyClass is injected instead of MyClass

Thanks

**Comment by neuronix** [comment]
Hey @SlavaRa have you found a fix for this yet? It's quite annoying :(

**Comment by SlavaRa** [comment]
@neuronix I'll fix it at this week.

**Comment by SlavaRa** [comment]
@neuronix please try build from https://github.com/fdorg/flashdevelop/pull/2109

**Comment by neuronix** [comment]
Hi @SlavaRa now the autocomplate injects "globalclassifier.Boolean" instead of true/false...

**Comment by SlavaRa** [comment]
Wow, I'll fix it today

**Comment by PierrotLL** [comment]
The package name injection bug reappeared in 5.3.3.41
