### ISSUE TITLE
Disabling unused import warnings

### ISSUE THREAD

**Issue by djaonourside** [fdorg/flashdevelop#2084]
Is it possible to turn off unused import warnings? They are rather annoying in haxe-react projects with jsx-function when component class imports are marked as unused.

**Comment by Neverbirth** [comment]
Tools -> Program Settings -> HaxeContext -> Enabled Compiler Services. Disable the Diagnostics support.

Alternatively you can also disable linting in the LintingHelper section.

**Comment by djaonourside** [comment]
@Neverbirth 
Thank you for your help)
