### ISSUE TITLE
[Bug] [AS3] Goto declaration doesn't work on "new MyClass()" (v5.3.3)

### ISSUE THREAD

**Issue by PierrotLL** [fdorg/flashdevelop#2099]
Hi,
Since v5.3.3, feature "Goto declaration" doesn't work on class name preceded by keyword "new" and followed by "()".
It brings to the declaration of the class i'm currently in.

Flashdevelop 5.3.3.1, Windows 10, .NET 4.0

**Comment by SlavaRa** [comment]
@PierrotLL Please try latest development build from http://flashdevelop.org/downloads/builds/

**Comment by PierrotLL** [comment]
Thanks, it works :)
