### ISSUE TITLE
Add support for lix/haxeshim

### ISSUE THREAD

**Issue by gene-pavlovsky** [fdorg/flashdevelop#2103]
1. FD relies on parsing the Haxe SDK `CHANGES.txt` file to determine the SDK version. This breaks when trying to add `haxeshim` as the Haxe SDK.
Proposed changes: When adding an SDK:
- run `haxe --run show-version` (haxeshim feature) to check for haxeshim
- if failed, run `haxe -version` (haxe feature) to get the version
- if failed, try to get the version from `CHANGES.txt`
Another option - check if project has a `.haxerc` file to detect haxeshim

2. FD relies on `haxelib` to get the standard library path and to resolve other libraries. This breaks if the project uses `haxeshim`/`lix` for haxe version management and library management, respectively.
Proposed changes:
- if the selected SDK is actually `haxeshim`, use features provided by it to resolve libraries
- otherwise, use `haxelib`

**Comment by markknol** [comment]
Just sharing my setup here. I have lix installed locally in the project, maybe it helps getting it work.

I use this as "prebuild command-line":
```
$(ProjectDir)\node_modules\.bin\haxe.cmd --run resolve-args build-$(BuildConfig).hxml > haxedevelop.hxml
$(ProjectDir)\node_modules\.bin\haxe.cmd $(OutputFile)
```
> Note that `build-$(BuildConfig).hxml` is a personal thing. It could be any hxml you want to build.

I use haxedevelop.hxml as hxml config:
![image](https://user-images.githubusercontent.com/576184/38629003-1bc2a3bc-3db3-11e8-87f1-3f1f7b8b4cbf.png)

This all works nicely, but I only need to configure the SDK.

I tried this, but this doesn't work:  
![image](https://user-images.githubusercontent.com/576184/38629070-4e4fc3b4-3db3-11e8-8870-b7fc4d1b230e.png)

To support lix  it would be nice if this could be supported (or we should know what path to enter here)

**Comment by gene-pavlovsky** [comment]
@markknol I would appreciate if you can test the PR (with haxeshim/lix project as well as a regular project).
I tested with a sample Haxe-JS project.
- Add an SDK pointing to your `%APPDATA/npm`, where haxeshim's `haxe.exe` resides.
- Add your library names to libraries list in the project properties (e.g. `tink_core`, etc.)
Nothing else should be necessary.

**Comment by markknol** [comment]
That assumes lix/haxeshim is installed globally? Is it also possible with local installed versions?

How can I test this version? Is there a binary available or something?

**Comment by gene-pavlovsky** [comment]
I tested with a global installation, but you can try to add a locally installed SDK (FlashDevelop properties, HaxeContext, Installed SDKs) and see if it works. In theory it might :)

Here's a direct link to the build: https://ci.appveyor.com/api/buildjobs/9urt84p92t91a0yh/artifacts/FlashDevelop%2FInstaller%2FBinary%2FFlashDevelopPR_2112.zip

Tip: you can find a build for any open Pull Request:
- Open the PR link, e.g. in this case it's https://github.com/fdorg/flashdevelop/pull/2112
- Scroll down to "All checks have passed", and click "Show all checks" on the right, you will see AppVeyor build, click "Details"
- On the right side, click "ARTIFACTS", there will be a link to a Zip you can download and test

**Comment by gene-pavlovsky** [comment]
@back2dos maybe you can also take a look together with @Neverbirth to check what is wrong, which features are missing etc?

**Comment by back2dos** [comment]
So, it works for globally installed lix! :) 

But: 
- the version detection logic derails somewhat if you have the latest haxe (probably because `haxe -version` yields `4.0.0 (git build development @ 3018ab109)` which is what `haxe --run resolve-args` prints). 
- if I try to use `node_modules\.bin` I get "this project doesn't have a proper SDK defined". That one contains only a `haxe.cmd`, although I could dump an exe there on windows if it helps?

**Comment by gene-pavlovsky** [comment]
@back2dos 
https://ci.appveyor.com/api/buildjobs/66cb8x8qxhvun2hv/artifacts/FlashDevelop%2FInstaller%2FBinary%2FFlashDevelopPR_2112.zip
The two issues you reported should be resolved now. Please try it :)

**Comment by back2dos** [comment]
Ok, seems to work fine.
