### ISSUE TITLE
Debugger startup error.

### ISSUE THREAD

**Issue by Hakunametata** [fdorg/flashdevelop#2104]
Error details: net.sf.jni4net.jni.JNIException: Can't load java class for flash.tools.debugger.concrete.DValue_ from classLoader sun.misc.Launcher$AppClassLoader@addbf1 ---> java.lang.LinkageError: flash/tools/debugger/concrete/DValue_ : Unsupported major.minor version 51.0
   在 net.sf.jni4net.jni.JNIEnv.ExceptionTest()
   在 net.sf.jni4net.jni.JNIEnv.CallObjectMethodPtr(IJvmProxy obj, MethodId methodIdNative, Value[] args)
   在 java.lang.ClassLoader.loadClass(String par0)
   在 net.sf.jni4net.utils.Registry.LoadClass(String name, ClassLoader classLoader, JNIEnv env)
   --- 内部异常堆栈跟踪的结尾 ---
   在 net.sf.jni4net.utils.Registry.LoadClass(String name, ClassLoader classLoader, JNIEnv env)
   在 net.sf.jni4net.utils.Registry.RegisterClass(RegistryRecord record, ClassLoader classLoader, JNIEnv env)
   在 net.sf.jni4net.utils.Registry.BindJvm(RegistryRecord record, ClassLoader classLoader, JNIEnv env)
   在 net.sf.jni4net.utils.Registry.BindJvm(RegistryRecord record, JNIEnv env)
   在 net.sf.jni4net.utils.Registry.RegisterType(Type type, Boolean bindJVM, JNIEnv env)
   在 net.sf.jni4net.utils.Registry.RegisterAssembly(Assembly assembly, Boolean bindJVM)
   在 net.sf.jni4net.Bridge.RegisterAssembly(Assembly assembly)
   在 FlashDebugger.DebuggerManager.Start(Boolean alwaysStart)

Initialize info：
mxmlc -load-config+=obj\EnhanceViewConfig.xml -debug=true -incremental=true -swf-version=36 -o obj\EnhanceView636588906522579437
Starting java as: C:\Program Files (x86)\Java\jre1.6.0_04\bin\java -Xmx800m -Dsun.io.useCanonCaches=false -Duser.language=en -Duser.region=US -Djava.util.Arrays.useLegacyMergeSort=true -Dapplication.home="D:\work\flexairsdk\4.6.0+28.0.0" -jar "D:\work\flexairsdk\4.6.0+28.0.0\lib\fcsh.jar"
INITIALIZING: Adobe Flex Compiler SHell (fcsh)
Starting new compile.
Loading configuration file D:\work\flexairsdk\4.6.0+28.0.0\frameworks\flex-config.xml
Loading configuration file D:\work\AS3WorkSpace\EnhanceView-master\obj\EnhanceViewConfig.xml
obj\EnhanceView636588906522579437 (877 bytes)
(fcsh)Build succeeded

JRE：1.6.0 X86
FD：5.3.1.101 development

**Comment by Hakunametata** [comment]
I debug success in FD 5.1.1

**Comment by SlavaRa** [comment]
Please try latest build from http://flashdevelop.org/downloads/builds/
