### ISSUE TITLE
[Bug] [AS3] Help tooltip shows wrong parameters when using keyword "as"

### ISSUE THREAD

**Issue by PierrotLL** [fdorg/flashdevelop#2108]
![fd](https://user-images.githubusercontent.com/16303333/38723746-5a90904a-3f02-11e8-8229-1e8bf05d74bc.png)
As you can see, the help tooltip shows the Rectangle constructor parameters when I expected parameters of the "contains" method.

FlashDevelop 5.3.3.37

**Comment by SlavaRa** [comment]
WIP, I'll fix it weekend(I should write tests).
