### ISSUE TITLE
Support markdown syntax highlighting

### ISSUE THREAD

**Issue by sebthom** [fdorg/flashdevelop#2111]
Please add support for markdown syntax highlighting.

Should be auto enabled for *.md and *.markdown files.

**Comment by elsassph** [comment]
I had attempted a MD syntax a long time ago - it wasn't amazing and language syntax file format may have changed subtly but someone could try to bring it back:
https://github.com/fdorg/flashdevelop/blob/feature/markdown/FlashDevelop/Bin/Debug/Settings/Languages/Markdown.xml

You can drop this file in your user application files under `Settings/Languages`.

**Comment by sebthom** [comment]
@elsassph Unfortunately I only get "Lexer 'markdown' (0) unknown" when trying to open a MD file after installing the xml config.

**Comment by elsassph** [comment]
Hmmm unfortunately there are also changes to cherry pick at the C# level to expose this lexer (built in Scintilla) :(
