### ISSUE TITLE
[AS3] [Bug] Autocomplete auto-replace "true" (or "false") by "Boolean"

### ISSUE THREAD

**Issue by PierrotLL** [fdorg/flashdevelop#2113]
![bool](https://user-images.githubusercontent.com/16303333/38935014-8401cd44-431d-11e8-8bef-317764b783ac.gif)
Dev build 5.3.3.40

**Comment by SlavaRa** [comment]
fixed in http://flashdevelop.org/downloads/builds/

**Comment by PierrotLL** [comment]
Thanks, fixed in 5.3.3.41
