### ISSUE TITLE
FD 3.x.x install requirement missing (win10)

### ISSUE THREAD

**Issue by tadeubas** [fdorg/flashdevelop#2121]
I've installed Win10 right now on a blank drive and tried to install FlashDevelop 5.3.3 release. The blog post don't say it needs Microsoft .NET 3.5 but it does.

The only way I could install FD was enabling this first option .NET 3.5:

![net3_5 2](https://user-images.githubusercontent.com/5518496/39843109-ecd25520-53bf-11e8-9315-04d3200120fd.PNG)

The forum release post don't say this - http://www.flashdevelop.org/community/viewtopic.php?f=11&t=13028&sid=9909aed4cfd56336516a3966483458dd

**Comment by Neverbirth** [comment]
Is it the same also with a dev build? http://flashdevelop.org/downloads/builds/

**Comment by tadeubas** [comment]
This?
```
FlashDevelop-development.exe | 25.59MB | 19 hours  old
```

**Comment by Neverbirth** [comment]
Yes, you can use the zipped one too.

**Comment by tadeubas** [comment]
On a brand new and updated Win10 Pro OS:
```
FlashDevelop-development.exe | 25.59MB | 3 days old
OR
FlashDevelop-5.3.3.exe
```
I've installed without any problems. But the issue is when I open FD, It says: **Initializing FD**, and then **Windows ask for .NET Lib 3.5** (with 2.0 and 3.0).

When I cancel the Windows pop-up, I see FD home screen, but **AppMan did not show up**. When I try to open it, Windows ask again about .NET libs.

So it is **not related to FD, but to AppMan**. But if AppMan is a tool that comes with FD, the forum release post should point to that .NET 3.5 pre-requisite, right?

![appman](https://user-images.githubusercontent.com/5518496/39969911-61c997fc-56b9-11e8-8e9a-eda80993fb36.PNG)

**Comment by Neverbirth** [comment]
You are fully right, I guess it's an oversight nobody ever realized before, I will update shortly.

**Comment by Neverbirth** [comment]
I pushed yesterday an updated AppMan, and also some other stuff. It's possible some external tools require .NET 3.5, but they are out of our control. Feel free to report any other missing thing you may find.

Thanks again for the report.

**Comment by tadeubas** [comment]
Thank you for the quick response and suggestions!

Closing the issue.
