### ISSUE TITLE
the fcsh can not be work

### ISSUE THREAD

**Issue by matrix3d** [fdorg/flashdevelop#2128]
the fcsh can not be work

**Comment by SlavaRa** [comment]
What do you mean?

**Comment by matrix3d** [comment]
The second compilation of a large project is too slow. The second compilation of flashbuilder is very fast. Looks like a lack of caching system

**Comment by SlavaRa** [comment]
What compiler do you use(in FB, in FD)?

**Comment by matrix3d** [comment]
airsdk30

**Comment by SlavaRa** [comment]
#1167
https://github.com/exaphaser/EHaxeStudio/commit/bde0328b4236a22fabac83abe45da0c113750391

**Comment by matrix3d** [comment]
also bug
