### ISSUE TITLE
Should the dialogs be editable in the Visual Studio designer?

### ISSUE THREAD

**Issue by tom-seddon** [fdorg/flashdevelop#2164]
With FlashDevelop.sln open in VS2017, when I try to open ShortcutDialog.cs in the form designer I get an error pointing at `ScaleHelper.GetScale`, apparently becuase `PluginBase.MainForm` is null when in the designer.

Other dialogs are also affected (I didn't do an exhaustive check).

Is this supposed to work? Or are the dialogs just known not to be compatible with the designer?

Thanks,

--Tom

**Comment by elsassph** [comment]
Unfortunately, the way high dpi was implemented isnt compatible with visual mode.

**Comment by tom-seddon** [comment]
OK, no problem - just checking that there isn't something wrong with my setup.

Thanks,

--Tom
