### ISSUE TITLE
Multiple Haxe processes

### ISSUE THREAD

**Issue by markknol** [fdorg/flashdevelop#2173]
In development build (1ddbef48c55c0eed20a14b51ae3de577ea059ee6) I see multiple Haxe processes starting. 
![image](https://user-images.githubusercontent.com/576184/42111995-a15a180e-7be6-11e8-8b78-0e8939d4c9a3.png)

* when haxedevelop starts, a process is started.
* when requesting completion, a new process is started.
* when switching haxe sdk, a new process is started.
* when requesting completion again, a new process is started.

I just had ~10 Haxe processes running

Using this build 1ddbef48c55c0eed20a14b51ae3de577ea059ee6

**Comment by SlavaRa** [comment]
Completion Mode: Compiler

**Comment by SlavaRa** [comment]
WIP

**Comment by markknol** [comment]
Yes this seems resolved now! 👍
