### ISSUE TITLE
Popup completion list replaced with different popup completion list

### ISSUE THREAD

**Issue by tom-seddon** [fdorg/flashdevelop#2177]
SOmetimes when pressing Ctrl+Space, I get one type of completion list that's quickly replaced by a different one with different contents.

What appears first:

![image](https://user-images.githubusercontent.com/1269020/42271457-46bb90b0-7f7b-11e8-8e96-faa170668b11.png)

What it's replaced with, usually exactly when I press a key to select an item:

![image](https://user-images.githubusercontent.com/1269020/42271464-4c587006-7f7b-11e8-9741-a32e41362722.png)

What's the difference between these two types of popup? Can I switch one of them off?

Thanks,

--Tom

**Comment by SlavaRa** [comment]
- FD completion
- Compiler completion

I know how to improve it, I'll do it in the near future.
