### ISSUE TITLE
Multiple Neko processes

### ISSUE THREAD

**Issue by chosencharacters** [fdorg/flashdevelop#2179]
Hey,
When compiling Flash, FD always opens up two neko processes that don't close afterwards. This does not happen with just `lime test flash` normally. These neko processes don't replace eachother, so if you compile 3 times you'll have 6 neko processes.

**Comment by SlavaRa** [comment]
@chosencharacters What version of the editor do you use?

**Comment by chosencharacters** [comment]
@SlavaRa 5.3.3.1, just updated actually, problem still persists

**Comment by SlavaRa** [comment]
Can you try the latest development build?
http://flashdevelop.org/downloads/builds/

**Comment by chosencharacters** [comment]
Just updated, tried compiling again, issue still persists :\

Did you do anything new with optimization within the last few versions btw?
Just got a big speed increase in compile time.

**Comment by SlavaRa** [comment]
> Just updated, tried compiling again, issue still persists :\

Thanks. I'll try to deal with this problem in the near future.

> Did you do anything new with optimization within the last few versions btw?

There are a lot of improvements in this version :)

**Comment by SlavaRa** [comment]
@chosencharacters I was able to repeat this from the command don't use FD.
But I'll try to find a solution to this problem.

**Comment by SlavaRa** [comment]
#1777
