### ISSUE TITLE
Crash without errors, “No localized string found: Info.HaXeRunning”

### ISSUE THREAD

**Issue by HelmiBastami** [fdorg/flashdevelop#2188]
I've been trying to use HaxeDevelop on a new (Windows 10) computer, and it works fine until I get any sort of error while the export is running. Instead of showing the error info, the export just crashes and it says:

`No localized string found: Info.HaXeRunning`

I have no idea what that means, and my Google searches have revealed no clues, and no one else with this problem.

I've already tried:
> Reinstalling HaxeDevelop
> Installing each of the older builds
> Installing the various "nightly builds"
> Installing to a different folder
> Installing FlashDevelop
> Deleting the HaxeDevelop AppData folder
> Disabling windows defender

No difference. Note that the weird "no localized string" output only appears in the 64 bit version; otherwise it only says "Done(1)" when it crashes. Also when HaxeDevelop starts, it outputs:

```
No localized string found: Info.MTASCRunning
No localized string found: Info.MTASCDone
No localized string found: Info.MxmlcRunning
No localized string found: Info.MxmlcDone
No localized string found: Info.HaXeRunning
No localized string found: Info.HaXeDone
No localized string found: Info.PHPRunning
No localized string found: Info.PHPDone
Error: Display file was not found in class path

Error: Display file was not found in class path
```

I'm kind of out of options at this point. Any tips?

**Comment by Meychi** [comment]
This a problem where the 64bit binary for some reason can't access the resources in the plugin core dll. We need to investigate why this happens. Is it a path/process issue or a access right issue?

**Comment by HelmiBastami** [comment]
Thanks for the reply. I thought that HaxeDevelop.exe was the 32 bit version and HaxeDevelop64.exe was the 64 bit version, but both versions just crash the export instead of showing errors.

> Is it a path/process issue or a access right issue?

Is this something I can answer? I've enabled full access under security for PluginCore.dll, but no difference.

**Comment by Meychi** [comment]
Correct, ok thanks. We need to investigate this. The question was for us devs :)

**Comment by SlavaRa** [comment]
I'll check.
