### ISSUE TITLE
[haxe] Contextual code generation for getters/setters

### ISSUE THREAD

**Issue by Tiago-Ling** [fdorg/flashdevelop#221]
Using the contextual code generation hotkey (Ctrl+Shift+1) to create getter and setter for a variable generates this:

``` haxe
function get_test():Int 
{
    return test;
}

function set_test(value:Int):Int 
{
    return test = value;
}

private var test(get, set):Int;
```

Which causes these errors when compiling:

"This field cannot be accessed because it is not a real variable
Add @:isVar here to enable it"

Wouldn't the correct generation be like this:

``` haxe
function get_test():Int 
{
    return test;
}

function set_test(value:Int):Int 
{
    return test = value;
}

private var test(get_test, set_test):Int;
```

**Comment by SlavaRa** [comment]
I think that this issue is no longer relevant

**Comment by SlavaRa** [comment]
@Tiago-Ling, you have found a solution to your issue?

**Comment by Tiago-Ling** [comment]
Still happening here, using FlashDevelop version 5.1.1.1 and Haxe 3.2.0

If you create a variable like this:
```haxe
var foo:String;
```
And then use the contextual generation to create the getter / setter the same error from before will happen. To solve this the contextual generation could either:

- Add the `private var _foo:String` or
- Add the `@:isVar` macro over the variable.

Other issue related to this one is if you create the variable with an underline prefix. Then FlashDevelop will not generate the getter / setter with the underline and another error will happen:
```haxe
//Prefix
var _foo:String;

//After Ctrl + Shift + 1 and selecting create getter and setter

//Should be "get__foo()"
function get_foo():String 
{
	return _foo;
}

//Should be "set__foo(value:String)"
function set_foo(value:String):String 
{
	return _foo = value;
}
```

This will generate another error since the compiler won't recognize the functions:
```
src/Main.hx:12: characters 1-27 : Method set__foo required by property _foo is missing
src/Main.hx:12: characters 1-27 : Method get__foo required by property _foo is missing
```

**Comment by SlavaRa** [comment]
I will be fix it today.
