### ISSUE TITLE
[Haxe][CodeComplete] Support for `Type.new`

### ISSUE THREAD

**Issue by SlavaRa** [fdorg/flashdevelop#2217]
- [x] completion for `Type.ne|` -> `Type.new`
- [x] tooltip for `Type.ne|w`
- [x] Goto declaration for `Type.ne|w` 
- [ ] Assignment to variable for `Type.new|` -> `var type:Void->Void = Type.new`

**Comment by gene-pavlovsky** [comment]
Is `Void->Void` just for example, right?

**Comment by SlavaRa** [comment]
```haxe
class Foo {
    public function new() {}
}
```
`$type(Foo.new)` => `Void->Foo`

**Comment by gene-pavlovsky** [comment]
Right. And if the constructor has params, it would be something else. I wonder if it would be tricky to figure out all the types.
As with the other issue, I hope there's an option to specify whether or not you want the explicit type for the var.

**Comment by SlavaRa** [comment]
I think it's necessary to add this setting to `Tools -> Settings -> HaxeContext -> Code Generator`
