### ISSUE TITLE
Maintain indentation when pasting in code

### ISSUE THREAD

**Issue by smks** [fdorg/flashdevelop#224]
Hello,

It would be great if FlashDevelop could keep alignment of formatting when you paste a block of code. Problem is when you paste lets say 4 lines the top line will be in the correct position. But the following lines are an indentation back. It is such a small issue but would be great if it didn't do this:

![image](https://cloud.githubusercontent.com/assets/4087157/2938397/92ddb982-d908-11e3-8063-57056e484f59.png)

**Comment by Meychi** [comment]
Edit -> Smart Paste (Ctrl+Alt+V)
