### ISSUE TITLE
Autocompletion when iterating XML in haxe

### ISSUE THREAD

**Issue by NicoM1** [fdorg/flashdevelop#228]
for some reason, I have a lot of trouble getting auto-completion to show up when running the following code:  
    var Root:Xml = Xml.parse(xml);
    Root = Root.firstChild;

```
for (entity in Root.elementsNamed("entity"))
{
    //entity. <--- no auto complete
}
```

Do you have any idea why this is? maybe I'm doing this in an ugly way without knowing it?
Thanks,
Nico

**Comment by SlavaRa** [comment]
This issue is still relevant?

**Comment by SlavaRa** [comment]
Fixed in latest development build.
