### ISSUE TITLE
[UI][Project tree] renaming folder's name to it previous name calls a bug

### ISSUE THREAD

**Issue by DarthVan** [fdorg/flashdevelop#2318]
Hi! I tryed to rename one folder in the project rtee by click it name twise, and after writing some chars i wanted to cancel to make new name, so i wrote it name before renaming :)

FD askd me, want i to update a references, i picked 'yes' and got a bug:
https://www.dropbox.com/s/bfxx7lzsyir1sut/%D0%A1%D0%BA%D1%80%D0%B8%D0%BD%D1%88%D0%BE%D1%82%202018-08-06%2011.14.00.png?dl=0

FD 5.3.4.162

**Comment by SlavaRa** [comment]
![bug](https://user-images.githubusercontent.com/1700940/44160250-82998980-a0c2-11e8-849f-e8ef90d74d69.gif)
