### ISSUE TITLE
Haxe project reader failing to read sub-hxml file

### ISSUE THREAD

**Issue by gene-pavlovsky** [fdorg/flashdevelop#2322]
This recently merged [PR](https://github.com/fdorg/flashdevelop/pull/2052) broke reading sub-hxml files for Haxe projects (in some cases).

In our project, platform is set to `hxml` and the configuration file is `build/haxe/build-desktop-dev.hxml`.
This file includes `build/haxe/build-desktop.hxml` which in turns includes `build/haxe/build.hxml`.
The last file includes all of the `-lib` directives for the project, etc.

Due to some of the changes from the PR mentioned above, the `HaxeProject::ParseHxmlEntries` doesn't work correctly. I checked in the debugger, and when this function gets the path to the last hxml file, somehow the path ends up being `build/haxe/build/haxe/build.hxml` (it should be `build/haxe/build.hxml`), so the file is considered as not existing.

Something is going wrong with all the GetAbsolutePath/GetFullPath etc.

**Bonus points**: currently if the hxml file doesn't exist, it is just skipped, it would be helpful to at least log a warning to the Output panel (or maybe even an error dialog?)

**Comment by SlavaRa** [comment]
![2018-08-18_18-49-37](https://user-images.githubusercontent.com/1700940/44300941-ac97b980-a317-11e8-8232-4173e9b10523.png)

**Comment by gene-pavlovsky** [comment]
In my case the hxml files are in build/haxe/ subdirectory. I took that is
important to reproduce

**Comment by gene-pavlovsky** [comment]
@SlavaRa can you please look into this? If this is not fixed I vote for reverting the commit(s) that broke it recently, I think it's either PR #2052 or PR #1827 .

Project build file is set to `build/haxe/build-desktop-dev.hxml`.

Project directory structure:
`build/haxe/build-desktop-dev.hxml`:
```
./build/haxe/build-desktop.hxml
...
```

`build/haxe/build-desktop.hxml`:
```
./build/haxe/build.hxml
...
```

`build/haxe/build.hxml`:
```
-lib hexdsl
-lib hexcore
-lib hexannotation
-lib hexinject
-lib hexunit
-lib hexcommand
...
```

Here's what's happening when HaxeProject.parseHxmlEntries gets called:
- It's called with the lines from the project hxml file (`build/haxe/build-desktop-dev.hxml`)
  lines: [
    "./build/haxe/build-desktop.hxml",
    ...
  ]
- First line is taken, the code reaches this condition on line 463: `else if (!trimmedLine.StartsWith("#") && trimmedLine.EndsWith(".hxml", StringComparison.OrdinalIgnoreCase))`, which evaluates to true
- These variables are set
		subhxml	"C:\\project\\armageddon-client\\build\\haxe\\build-desktop.hxml"	string
		subhxmlDir	"C:\\project\\armageddon-client\\build\\haxe"	string
- The code then proceeds with the inner `foreach (var it in File.ReadAllLines(subhxml))` loop
- The first line read is "./build/haxe/build-desktop.hxml"
- The code reaches this condition on line 491: `else if (subline.EndsWith(".hxml", StringComparison.OrdinalIgnoreCase) && !Path.IsPathRooted(subline))`, which evalutes to true
- Here the problem happens
Current state of variables:
		subhxmlDir	"C:\\project\\armageddon-client\\build\\haxe"	string
		subline	"./build/haxe/build.hxml"	string
Code on line 493 is executed: `subline = GetRelativePath(CleanPath(Path.GetFullPath(Path.Combine(subhxmlDir, subline)), cwd));`
After that, we have:
		subline	"build\\haxe\\build\\haxe\\build.hxml"	string
I don't understand the point of line 493. It seems to be following some misguided idea.
`Path.Combine(subhxmlDir, subline)` returns "C:\\project\\armageddon-client\\build\\haxe\\./build/haxe/build.hxml" which is not the correct path.
When running `haxe build/haxe/build-desktop-dev.hxml` (from the project root, obviously, not from `build/haxe` directory), the build runs correctly. Which means that when haxe sees a sub-hxml files with a relative paths, it calculates the absolute path based on the current working directory (project root), not the path of the current hxml file (`subhxmlDir` in the FD code). So I don't understand why here is `Path.Combine(subhxmlDir, subline)`.

**Comment by gene-pavlovsky** [comment]
P.S. I originally suspected the problem came from #2052.
This is not actually the case, the bug appeared due to #1827.
Reverting the following commit fixes the problem for me:
https://github.com/fdorg/flashdevelop/commit/f8fb91b6836437ebba2c1857021ac16dd469a185

**Comment by SlavaRa** [comment]
Thanks, The problem will be fixed tonight. I'm sorry

**Comment by gene-pavlovsky** [comment]
No problem, these things happen.
Thank you for quick response :)
