### ISSUE TITLE
FD 5.3.3.1 crashes when trying to save a new .as file

### ISSUE THREAD

**Issue by NicholasHasAwoken** [fdorg/flashdevelop#2327]
Имя события проблемы:	APPCRASH
  Имя приложения:	FlashDevelop.exe
  Версия приложения:	5.0.0.0
  Отметка времени приложения:	5a8bfa14
  Имя модуля с ошибкой:	clr.dll
  Версия модуля с ошибкой:	4.7.2558.0
  Отметка времени модуля с ошибкой:	59d413ce
  Код исключения:	c0000005
  Смещение исключения:	00137d0e
  Версия ОС:	6.1.7601.2.1.0.256.1
  Код языка:	1049
  Дополнительные сведения 1:	6c49
  Дополнительные сведения 2:	6c498705d48f9eb4ad83b5391d3d314f
  Дополнительные сведения 3:	feb6
  Дополнительные сведения 4:	feb6f5bd5086b91a63878ac7754bdc81

**Comment by SlavaRa** [comment]
do you speak russian?

**Comment by NicholasHasAwoken** [comment]
Конечно.

**Comment by SlavaRa** [comment]
Тогда мне нужно больше деталей, о том как этот crash происходит

**Comment by NicholasHasAwoken** [comment]
Иногда мне нужен новый класс в уже существующем проекте и тогда я выбираю File -> New -> AS3 Document, который генерируется по шаблону и получает название Untitled3.as.
Я меняю название класса в самом файла, нажимаю Ctrl+S; FD предлагает поменять имя файла, я выбираю то, которое соответствует новому классу. Что происходит далее — в основном зависит от того, сколько времени FD уже работает.

Если я его только открыл — скорее всего сохранит без вылетов. В остальных случаях может аварийно закрыться без сохранения файла вовсе, а иногда успеть сохранить, но все закладки слетают(то есть, возвращаются/остаются лишь те, что были на момент последнего успешного закрытия).

**Comment by SlavaRa** [comment]
какая точная версия редактора? `Help -> About FlashDevelop...`

**Comment by NicholasHasAwoken** [comment]
5.3.3.1

**Comment by SlavaRa** [comment]
Предлагаю взять версию отсюда http://flashdevelop.org/downloads/builds/ это девелопмен билд, который сейчас готовится к релизу. Я уверен, что на нем проблемы прекратятся, но было бы не плохо, если бы вы скачали его, поставили и поработали какое-то время, в случае если падений не будет, прошу написать сюда и закрыть issue, если падения продолжатся, то я подумаю как мы сможем залогировать и решить это дело :)

**Comment by NicholasHasAwoken** [comment]
Установщик это — FlashDevelop-development.exe ?

**Comment by SlavaRa** [comment]
да, это он

**Comment by NicholasHasAwoken** [comment]
До создания новых файлов ещё не дошло, но пока я делал дела, внезапно, без какой-либо причины случилось следующее:

```
startIndex не может быть больше, чем длина строки.
Имя параметра: startIndex

   в System.String.Substring(Int32 startIndex, Int32 length)
   в AS3Context.Completion.CodeComplete.EvalExpression(String expression, ASExpr context, FileModel inFile, ClassModel inClass, Boolean complete, Boolean asFunction, Boolean filterVisibility)
   в ASCompletion.Completion.ASComplete.EvalExpression(String expression, ASExpr context, FileModel inFile, ClassModel inClass, Boolean complete, Boolean asFunction, Boolean filterVisibility)
   в AS3Context.Completion.CodeComplete.EvalExpression(String expression, ASExpr context, FileModel inFile, ClassModel inClass, Boolean complete, Boolean asFunction, Boolean filterVisibility)
   в ASCompletion.Completion.ASComplete.GetExpressionType(ScintillaControl sci, Int32 position, Boolean filterVisibility, Boolean ignoreWhiteSpace)
   в ASCompletion.PluginMain.OnMouseHover(ScintillaControl sci, Int32 position)
   в PluginCore.Controls.UITools.MouseHoverHandler.Invoke(ScintillaControl sender, Int32 position)
   в PluginCore.Controls.UITools.HandleDwellStart(ScintillaControl sci, Int32 position, Int32 x, Int32 y)
```

**Comment by SlavaRa** [comment]
Можете попробовать определить на каком именно файле/коде это валится?

**Comment by NicholasHasAwoken** [comment]
Это произошло в файле Config.as. Это пока ещё необработанный код Си, скопированный из оригинального файла как есть с минимальными изменениями.

[Архив ZIP - WinRAR.zip](https://github.com/fdorg/flashdevelop/files/2278214/ZIP.-.WinRAR.zip)

**Comment by SlavaRa** [comment]
Спасибо, после работы займусь

**Comment by NicholasHasAwoken** [comment]
Сегодня ошибка повторилась, снова когда я пытался создать новый файл. 
Почти в точь-точь такая же, как в ОП, но 5 строк немного другие:

>   Отметка времени приложения:	5b6c5055
>   Дополнительные сведения 1:	2401
>   Дополнительные сведения 2:	24015db34f25c07415660e1d6f286898
>   Дополнительные сведения 3:	b5f0
>   Дополнительные сведения 4:	b5f06ec92fdb1a00728e179e74b7a58d

**Comment by SlavaRa** [comment]
будем смотреть, но вот что это за лог, который в последнем сообщении - я не понимаю, что это за набор данных и что я с ним могу сделать :(

**Comment by SlavaRa** [comment]
Если бы вы скинули полный стек, файл Exception.log (Tools -> User Config File...) или могли снять видео как это происходит, я бы смог вам помочь, пока я вижу, что падение происходит при наведение курсора на что-то...

**Comment by NicholasHasAwoken** [comment]
Этот последний лог — тоже самое, что и в самом первом сообщении, только я выбрал лишь те строки, которые отличаются хоть чем-то. Это краш при сохранении некоторых файлов, который не оставляет сам по себе никаких сообщений в этих логах. Там только одно, которое относится к другому исключению, которое у меня случилось в этом билде всего один раз(которое и происходит при наведении на что-то).

Возвращаясь к исходной проблеме, то она не такая серьёзная, но может надоедать, если часто что-то сохранять. Оно происходит ведь только при сохранении каких-нибудь новых файлов, а если нужно сохранить какие-то изменения в существующем, вылета не произойдёт. Я просто сохраняю пустой файл, если вылетит — пробую снова, а если нет, то можно уже и заполнять его понемногу.

**Comment by SlavaRa** [comment]
```Этот последний лог — тоже самое, что и в самом первом сообщении```.
Никогда так не делайте, пожалуйста, есть проблема - надо скидывать всю информацию, чтобы не заставлять гадать, на тему того что происходит.

UPD
Если бы я увидел Exceptions.log и понял по числам, что например я уже исправил ошибку связанную с наведением - я бы, скажем, не потратил 2-ое суток, на то, чтобы придумать ситуацию, когда код может упасть, это так к слову.

**Comment by NicholasHasAwoken** [comment]
[Exceptions.log](https://github.com/fdorg/flashdevelop/files/2290946/Exceptions.log)

**Comment by SlavaRa** [comment]
Спасибо :)

**Comment by NicholasHasAwoken** [comment]
Я записал краш на видео в формате .flv, только совершил ошибку, захватил окно FD, вместо экрана, поэтому там не видно как открываются окна, предлагающие сохранить файл, то как я меняю ему название, и не захватился сам лог с ошибкой, к сожалению. А потом чёрный экран, потому что окно закрылось.

[2018-08-17 19-09-58.zip](https://github.com/fdorg/flashdevelop/files/2297987/2018-08-17.19-09-58.zip)

**Comment by SlavaRa** [comment]
Спасибо, постараюсь сегодня вернуться к вашей проблеме

**Comment by NicholasHasAwoken** [comment]
Записал новое видео, в этот раз с захватом экрана. 
[2018-08-19 10-44-09.zip](https://github.com/fdorg/flashdevelop/files/2300153/2018-08-19.10-44-09.zip)

**Comment by SlavaRa** [comment]
@NicholasHasAwoken привет, можешь проверить на последнем билде http://flashdevelop.org/downloads/builds/ ?

**Comment by NicholasHasAwoken** [comment]
Проверил на последнем FlashDevelop-development.exe. 
Обрушение всё ещё может произойти при сохранении файла.
