### ISSUE TITLE
[Haxe][CodeRefactor] Renaming Main.hx from ProjectTree panel calls a bug

### ISSUE THREAD

**Issue by DarthVan** [fdorg/flashdevelop#2348]
Hi! Here a way to reproduce:
![main_rename_bug](https://user-images.githubusercontent.com/5062893/44415406-0814b200-a579-11e8-8371-e6eed7ad39e9.gif)

ty!

Ps: renaming via hotkey works fine. 
FD 5.3.4.172

**Comment by SlavaRa** [comment]
Thanks

**Comment by DarthVan** [comment]
Ty! it works in 5.3.4.176
