### ISSUE TITLE
Haxe auto-formatter logic

### ISSUE THREAD

**Issue by tom-seddon** [fdorg/flashdevelop#2404]
I've got disable completion on demand disabled, i.e., completion on demand is enabled. I think this means FlashDevelop only displays a code completion popup by request, when I press Ctrl+Space, and never automatically while I'm typing. But this option means FlashDevelop doesn't reformat my code when I press `;`.

This looks like it's due to this code here, maybe: https://github.com/fdorg/flashdevelop/blob/41581cca368b133ad40610f0e21062e38011e183/External/Plugins/HaXeContext/Completion/CodeComplete.cs#L18

Called from here when you press a key: https://github.com/fdorg/flashdevelop/blob/41581cca368b133ad40610f0e21062e38011e183/External/Plugins/ASCompletion/Completion/ASComplete.cs#L68

Should these two options not be separate? I never want FlashDevelop to badger me with popups when typing, because they steal keypresses, but I always want it to reformat my code, because it can do that without messing about with the focus.

Thanks,

--Tom

**Comment by SlavaRa** [comment]
I can fix it tomorrow ;)
