### ISSUE TITLE
Haxe completion mode showing errors when set to compiler

### ISSUE THREAD

**Issue by TomFors** [fdorg/flashdevelop#2422]
When running FlashDevelop 5.3.3.1 and using a Haxe C++ project our team is seeing red errors while using the IDE, especially when the go to declaration feature is used. Here is an example:

../FilePath/UDPConnection.hx:18: characters 25-37 : Type not found : UDPClientPtr

This file is importing that file using the following code:
```
#if cpp
import UDPClient;
#end
```

After doing some more investigation this error occurs when Tools>Program Settings>HaxeContent>Completion Mode is set to Compiler. When Tools>Program Settings>HaxeContent>Completion Mode is set to FlashDevelop this error does not occur. When looking at how FlashDevelop is calling Haxe there is no -cpp parameter while calling for completion, unlike compilation. I believe this is causing Haxe to not know we are using cpp to compile and is causing the red warnings we're seeing.

Here is the command line FlashDevelop is using:
"C:\HaxePath\haxe.exe" -lib platform -D devonly -main Game --display "C:\Path\GameFile.hx"@21650@position -D use_rtti_doc -D display-details

Adding -cpp "C:\OutputPath" to the above command allows it to return successfully.

**Comment by SlavaRa** [comment]
Please try development build from https://flashdevelop.org/downloads/builds/
