### ISSUE TITLE
"Install software" is missing AIR 30 and 31

### ISSUE THREAD

**Issue by kevinfoley** [fdorg/flashdevelop#2463]
Even with the latest development build, the "Install software" AppMan only shows AIR 29.

**Comment by SlavaRa** [comment]
I'm sorry, but I can't update `http://www.flashdevelop.org/appman.xml`, you can change your `/EditorFolder/Tools/appman/Config.xml` (use `https://github.com/fdorg/flashdevelop/blob/development/appman.xml`).
I think that `http://www.flashdevelop.org/appman.xml` will be updated after release.

**Comment by markknol** [comment]
If updating this file is a problem, we can host it on HaxeDevelop.org (?)
The site is automatically deployed when you commit it in its repository.

**Comment by SlavaRa** [comment]
via
https://github.com/fdorg/flashdevelop/commit/3d376ee2ebcb5bc05c2a4428ac97ed9082a7603b
https://github.com/fdorg/flashdevelop/commit/741e814dc00157ca5dba17be838985e4b4e97f91
