### ISSUE TITLE
Set As Default Style button is not clear enough

### ISSUE THREAD

**Issue by elsassph** [fdorg/flashdevelop#252]
Having a little, somewhat hidden, icon to apply a font/size to all the syntaxes is bad usability and I always spend too much time hovering all the buttons to find the right one - and thankfully I know the feature is there but it's really not discoverable enough.

**Comment by Meychi** [comment]
This button is somewhat hidden as the user could use it incorrecly making a style that doesn't have font defined a default style and fallback to system default (it doesn't break or anything). Also currently we have dynamic preferred font list and leaving fonts and default style as they are is desired. It's there if you need it and know what you are doing. Also I tried to change its position and looks but could not find a proper layout that i was ok with. :)
