### ISSUE TITLE
Configuring AppMan's Install path

### ISSUE THREAD

**Issue by elsassph** [fdorg/flashdevelop#253]
How can we do that?

**Comment by Meychi** [comment]
There are some issues to manage this properly with user priviledges but for admins:
 
FD5 now has a dynamic config file "Config.xml" next to appman binary. Make a copy of it and name it "Config.local.xml". By customizing this file you can modify the apps path and FD will not overwrite this copy of the file when updating FD. This change affects all users on the same computer.

**Comment by elsassph** [comment]
I hope you note that on the wiki somewhere ;)

**Comment by Tudumanu** [comment]
I managed this installing FD4 on a custom folder (G:\FlashDevelop) and created a .local file on it. So appman uses G:\FlashDevelop\Apps

**Comment by LeightonFerris** [comment]
This doesn't seem to work anymore. Is there a new method?
