### ISSUE TITLE
[Haxe] completion not working until saved

### ISSUE THREAD

**Issue by yurike** [fdorg/flashdevelop#2561]
For some variables (probably with inferred type) completion is not working until you manually save the file.
It is working for release version (5.3.3.1) but fails for dev versions for both FD and HD (tested on HD 5.3.4.281 and a bit older FD 5.3.4.269). Completion mode: compiler
Haxe 3.4.7

Example project: 
[completion_test.zip](https://github.com/fdorg/flashdevelop/files/2610381/completion_test.zip)
Screen with the way it should work (and working in release version) without saving:
![image](https://user-images.githubusercontent.com/2974254/48939179-52f0ed80-ef0b-11e8-8034-4746d6693ff4.png)

**Comment by rottor** [comment]
Probably it is related to #2436 - full completion list is opening only after saving. Example:
![completionctrls](https://user-images.githubusercontent.com/379026/49342591-6e2bcd80-f66e-11e8-9b5d-36d03176b840.gif)
Hope it helps.
