### ISSUE TITLE
Performance Project Tree

### ISSUE THREAD

**Issue by markknol** [fdorg/flashdevelop#2562]
I notice for a while now that the project tree sometimes is quite slow. See it takes here ~3 seconds to expand the folder (which contains 72 files)
![haxedevelop-project-tree](https://user-images.githubusercontent.com/576184/48939483-aae02200-ef14-11e8-9c2b-a489c73ed41a.gif)

I have SSD and don't notice this behavior in other applications.

Is there a way to somehow speed this up a bit?

**Comment by SlavaRa** [comment]
@markknol hi, can you test build from https://ci.appveyor.com/project/FlashDevelop/flashdevelop-devel/builds/20607947/artifacts ?

**Comment by markknol** [comment]
That is way faster! Ship it! 

Thank you so much.

**Comment by markknol** [comment]
![haxedevelop-project-tree2](https://user-images.githubusercontent.com/576184/49143602-aee8b700-f2fb-11e8-9aea-007a3ce3f1cf.gif)
