### ISSUE TITLE
[Haxe] HaxeDevelop Crashes on Startup

### ISSUE THREAD

**Issue by Doppp** [fdorg/flashdevelop#2565]
I'm using HaxeDevelop Development Build 5.3.4.283. This crash happens more often than not i.e. I have to keep starting up HaxeDevelop until it stops crashing on that rare occasion to be able to get work done. The IDE doesn't crash upon reinstalling/fresh install. Might be related to #1979.

Currently using Haxe 4.0.0-preview 5.

See the attached gif for the crash. No logs or crash messages so far.

![crash](https://user-images.githubusercontent.com/627410/48998857-c73bc300-f18f-11e8-88e5-89a13187bbe0.gif)

**Comment by SlavaRa** [comment]
@Doppp Can you try the latest development build?
http://flashdevelop.org/downloads/builds/

**Comment by Doppp** [comment]
@SlavaRa HaxeDevelop Development Build 5.3.4.339?

**Comment by SlavaRa** [comment]
5.3.4.384 at the moment
(http://flashdevelop.org/downloads/builds/HaxeDevelop-development.txt)

**Comment by Doppp** [comment]
Sorry, my mistake. I downloaded FlashDevelop. So far HaxeDevelop 5.3.4.384 works well. Any idea what was the issue?
