### ISSUE TITLE
Autoselect class in completion matches wrong class

### ISSUE THREAD

**Issue by elsassph** [fdorg/flashdevelop#258]
import flash.display.Sprite;
    var foo:Sprite;
    foo = new <starling.display.Sprite is selected>

http://www.flashdevelop.org/community/viewtopic.php?f=6&t=11769

**Comment by SlavaRa** [comment]
i checked in last release, aill works ok, may be should close this issue?

**Comment by SlavaRa** [comment]
@elsassph ?
