### ISSUE TITLE
[Haxe][CodeComplete] Wrong tooltip

### ISSUE THREAD

**Issue by SlavaRa** [fdorg/flashdevelop#2600]
```haxe
package;
import js.html.VideoElement;
class VideoElementLoader extends Loader<VideoElement> {
    override function load() {
        content.onerror$(EntryPoint)
    }
}

class Loader<T> {
    public var content(default, null):Null<T>;
}
```

**Comment by gene-pavlovsky** [comment]
Just reproduced it. I was browsing a Facebook page (a picture, specifically) in Google Chrome, then I clicked the address bar (the URL got auto-selected) and pressed Ctrl-C, FD threw that exception. Allowing it to continue, I went back to Chrome and did Ctrl-C again, FD threw the exception again. I then went to Chrome, clicked the address bar once again, pressed Ctrl-A to reselect the URL, and did Ctrl-C again (in theory, copying the same url). This time FD didn't throw an exception.
I could reproduce by repeating the steps above.
