### ISSUE TITLE
[5.3.4.318] Exception in Goto Declaration when function name selected with opening brackets

### ISSUE THREAD

**Issue by andrew-git** [fdorg/flashdevelop#2627]
When select function name with open bracket and try to Goto Declaration you got exception:

> System.NullReferenceException: Object reference not set to an instance of an object.
> in HaXeContext.Completion.CodeComplete.LocateMember(ScintillaControl sci, Int32 line, String keyword, String name)
> in ASCompletion.Completion.ASComplete.LocateMember(String keyword, String name, Int32 line)
> in HaXeContext.Context.HandlePositionResult(HaxeComplete hc, HaxePositionResult result, HaxeCompleteStatus status)
> in HaXeContext.Context.OnPositionResult(HaxeComplete hc, HaxePositionResult result, HaxeCompleteStatus status)
> in HaXeContext.HaxeComplete.Notify[T](HaxeCompleteResultHandler`1 callback, T result)
> in HaXeContext.HaxeComplete.<>c__DisplayClass23_0`1.b__0()
> in System.Windows.Forms.Control.InvokeMarshaledCallbackDo(ThreadMethodEntry tme)
> in System.Windows.Forms.Control.InvokeMarshaledCallbackHelper(Object obj)
> in System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
> in System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
> in System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
> in System.Windows.Forms.Control.InvokeMarshaledCallback(ThreadMethodEntry tme)
> in System.Windows.Forms.Control.InvokeMarshaledCallbacks()

[FlashBugs.zip](https://github.com/fdorg/flashdevelop/files/2790716/FlashBugs.zip)
```haxe
SimpleClass
test( // into super
```

**Comment by SlavaRa** [comment]
What's version of editor do you use?
Can you provide me code for reproduce?
