### ISSUE TITLE
Haxe argument completion not shown for `using`

### ISSUE THREAD

**Issue by YellowAfterlife** [fdorg/flashdevelop#2636]
With a method native to class:
![image](https://user-images.githubusercontent.com/731492/51693011-c21bb880-2006-11e9-809f-e33e4a3c2561.png)
With `using`:
![image](https://user-images.githubusercontent.com/731492/51693149-0e66f880-2007-11e9-9f9b-870c7e503b9a.png)
```haxe
using StringTools;
class Test {
	static function main() {
		var s:String = "hi!";
		// type "s.replace(" here
	}
}
```
5.3.4.319

**Comment by SlavaRa** [comment]
#1900
