### ISSUE TITLE
Haxe syntax problem in functions within blocks

### ISSUE THREAD

**Issue by ciscoheat** [fdorg/flashdevelop#264]
Opening the issue from http://www.flashdevelop.org/community/viewtopic.php?f=6&t=11513 here, as suggested by Philippe. There is some confusion with code completion when using special code constructs like functions within blocks. Here's how to reproduce:
1. Install haxedci from command line: `haxelib install haxedci`
2. Clone this repository: `https://github.com/ciscoheat/haxedci-example`
3. Open the project and and a context class, for example `dci.examples.moneytransfer.contexts.MoneyTransfer`
4. Add code to the function `transfer` or some other function.

Especially in the beginning of functions in such a block, the tab indentation won't work.

More details can be found in the thread. Thanks!

**Comment by SlavaRa** [comment]
```haxe
class Main {
	static function main() {
		{
			fun| // | <-- cursor
		}
	}
}
```

**Comment by SlavaRa** [comment]
Fixed in latest development build.
