### ISSUE TITLE
[CodeComplete] argument completion popup doesn't close on opening a string

### ISSUE THREAD

**Issue by YellowAfterlife** [fdorg/flashdevelop#2640]
5.3.4.324
![gif2](https://user-images.githubusercontent.com/731492/51760309-d62cec00-20d2-11e9-9af7-32c04052dc41.gif)
Sample:
```haxe
class Test {
	static function main() {
		trace
	}
}
```
inputs: `("(`

**Comment by SlavaRa** [comment]
I'm sorry :(
