### ISSUE TITLE
Autocomplete uses fully qualified class names for Vector types

### ISSUE THREAD

**Issue by kevinfoley** [fdorg/flashdevelop#2702]
Autocomplete always inserts fully qualified class names for `Vector` types, even if the type is imported. For example,
```actionscript3
    var data:Vector.<MovieClip> = new Vector.<flash.display.MovieClip>();
```
To reproduce: 
1. Start a new class file
2. `import flash.display.MovieClip`
3. In a function, type `var data:Vector.<MovieClip> = new` After you type "new", press space, and the autocomplete list appears.
4. Press Enter to confirm the default selection.

**Comment by SlavaRa** [comment]
via #3017
