### ISSUE TITLE
Trace overflow message

### ISSUE THREAD

**Issue by markknol** [fdorg/flashdevelop#2723]
I overwritten my HaxeDevelop installation with latest development build, now got this warning:

```
HaxeDevelop: Trace overflow, you can configure "Max Trace Lines" in: Tools >> Program Settings >> FlashDevelop >> Features
```

I think it _Max Trace Line_ should have a default value (?)

**Comment by SlavaRa** [comment]
I'm sorry, it's bug, I can fix it today.

**Comment by markknol** [comment]
Thanks!
