### ISSUE TITLE
FlashDevelop: Trace overflow - default config value

### ISSUE THREAD

**Issue by gene-pavlovsky** [fdorg/flashdevelop#2727]
After I got the version with the feature added in #1247, I stopped seeing any trace - because the Max Trace Lines configuration setting was 0. I changed it to 1000 and I started getting traces again.
P.S. The description of the config value is not very clear to me - what does it mean "max number of lines that can be output at a time"? What is "one time"? One "write" from the running program? One run of a program?

**Comment by markknol** [comment]
Duplicate of https://github.com/fdorg/flashdevelop/issues/2723
