### ISSUE TITLE
Every time on debugging the Threads panel comes back and gets the focus.

### ISSUE THREAD

**Issue by techkey** [fdorg/flashdevelop#273]
To me personal it would make more sense to give the output panel the focus on debugging.

The IDE doesn't remember the layouts, is there something wrong with my install or is there a setting that I overlooked?

I'm using `FlashDevelop 4.6.2.5 for .NET 2.0 (master#f290597ff8)` on `Windows 7 Enterprise SP1 x86`. As far as I remember earlier versions also didn't remember the layouts. 

Any info on this will be greatly appreciated.

Thank you, Cornelis.

**Comment by Meychi** [comment]
Fixed for FD5.
