### ISSUE TITLE
Cut Indent guides (reopen)

### ISSUE THREAD

**Issue by deepnight** [fdorg/flashdevelop#275]
Empty lines cut the indent guides:
https://dl.dropboxusercontent.com/u/4952054/flashDev/indentGuidesBug.png

The original issue is here (https://github.com/fdorg/flashdevelop/issues/154). It was fixed once, but the bug occurred again shortly after.

**Comment by Meychi** [comment]
This is a setting you can change: Indent Guide Type. Defaults to old behaviour.
