### ISSUE TITLE
Latest nightly doesn't read inherited property types correctly

### ISSUE THREAD

**Issue by kevinfoley** [fdorg/flashdevelop#2765]
Using 5.3.4.386 (d69e630365):

![FlashDevelop bug](https://user-images.githubusercontent.com/7231744/57343417-2b2bc580-70f8-11e9-925b-369f5509709d.png)

**Comment by kevinfoley** [comment]
Related to #2701

**Comment by SlavaRa** [comment]
Can you provide me the full code(I don't know what `bounds` is)?

**Comment by kevinfoley** [comment]
Bounds is a standard property of Starling DisplayObjects. But you should be able to reproduce this with pretty much any property. See #2701 also

**Comment by SlavaRa** [comment]
I think you should remove `Tools -> User Config Files...`\Data\ASCompletion\FileCache

**Comment by SlavaRa** [comment]
@kevinfoley Any news?

**Comment by kevinfoley** [comment]
@SlavaRa  I think that fixed it.

**Comment by kevinfoley** [comment]
@SlavaRa I think that fixed it.

**Comment by kevinfoley** [comment]
Never mind; the issue still occurs. It doesn't always occur immediately after launching FD, but will start happening after a few minutes of use.

**Comment by kevinfoley** [comment]
@SlavaRa In case you missed my last message, the issue isn't fixed.
