### ISSUE TITLE
AIR 32 Support?

### ISSUE THREAD

**Issue by ghost** [fdorg/flashdevelop#2785]
Hello!

Is Adobe AIR 32 supported? I'm currently using Flex SDK 4.6 and extracted the AIR SDK v32 in there and set it as my SDK in FD, but I can only use AIR 28.

**Comment by SlavaRa** [comment]
What version of the editor are you using?

**Comment by ghost** [comment]
I'm using 5.3.3.1

**Comment by SlavaRa** [comment]
Try using the development version from http://flashdevelop.org/downloads/builds/

**Comment by ghost** [comment]
Oh I didn't know that there's a development version. Thank you!
