### ISSUE TITLE
[Haxe][InferVariableType] Crash when typing '-' instead of '='

### ISSUE THREAD

**Issue by Klug76** [fdorg/flashdevelop#2788]
Screenshot:
![fd_crash_tween](https://user-images.githubusercontent.com/1420061/58960178-af38a200-87b7-11e9-92d4-01298cc889eb.PNG)

Project to reproduce:
[fd_crash_tween.zip](https://github.com/fdorg/flashdevelop/files/3257383/fd_crash_tween.zip)

**Comment by SlavaRa** [comment]
`var a - (this.x = 0)`
