### ISSUE TITLE
[HAXE] Code generation: generate a class from an interface

### ISSUE THREAD

**Issue by disean** [fdorg/flashdevelop#2793]
NewInterface.hx:
```Haxe
package src.test;
interface NewInterface 
{
    private var _field:Bool;
}
```
Add > New Class...
![class](https://user-images.githubusercontent.com/37072976/59564934-9e691580-906e-11e9-875d-cd43e967e464.png)

NewClass.hx:
```Haxe
package src.test;
class NewClass implements NewInterface
{
    public function new()
    {
    }
    /* INTERFACE src.test.NewInterface */
    public var _field:Bool;
}
```

Issue - wrong access modifier:  `public var _field:Bool` instead `private var _field:Bool`.

**Comment by SlavaRa** [comment]
The interface cannot provide private properties and methods.

**Comment by disean** [comment]
I'm sorry, this is my fault.
