### ISSUE TITLE
Import generation fails in specific project

### ISSUE THREAD

**Issue by YellowAfterlife** [fdorg/flashdevelop#2835]
FD version: 5.3.4.430
Haxe version: 4, RC3

1. Checkout https://github.com/GameMakerDiscord/GMEdit/commit/df1a3aa1ae8b9df205ff40c18a39ae014309fc03 (JS target, no dependencies)
2. Open src/parsers/GmlLinter.hx
3. Uncomment line 12
4. Start typing ":EditC" on line 12 and press Enter to insert `editors.EditCode`
5. Note that `EditCode` is inserted but no import is created for it.
This seems to be a strangely widespread problem in this specific project and I cannot seem to replicate it in an empty one.

**Comment by SlavaRa** [comment]
@YellowAfterlife can you try the latest dev build?

**Comment by YellowAfterlife** [comment]
Seems to work as intended, cheers!
