### ISSUE TITLE
Electric Power is off and I got a blank file!

### ISSUE THREAD

**Issue by hoangdung-qbt** [fdorg/flashdevelop#2854]
Hi! While working with Haxe Develop and Flash Develop, the electric power was suddenly off and I got many blank files with no code lines showed when it was on. It happened to me last week twice at the company and at home. Luckily, the pre-version of all my files are still stored on my company server and my Dropbox.
Yo can test it by opening any AS file or HX file then turn off your computer without closing Haxe Develop or Flash Develop.
*Devices: Windows 10 64-bit*
Please fix. Thanks!

**Comment by SlavaRa** [comment]
For such situations, the files for recovery are saved in the folder \FlashDevelop\Bin\Debug\Settings\Recovery\
