### ISSUE TITLE
as3 inline debug line error

### ISSUE THREAD

**Issue by matrix3d** [fdorg/flashdevelop#2882]

**Comment by SlavaRa** [comment]
?

**Comment by matrix3d** [comment]
As3 project, compile online with inline parameter. When debugging, the line number of debug is incorrect, resulting in incorrect breakpoint.

**Comment by SlavaRa** [comment]
for debug mode, you must disable `Inline` flag
![image](https://user-images.githubusercontent.com/1700940/92896490-15818b00-f425-11ea-9e47-52fab7c7a308.png)
I can force the editor to do this
