### ISSUE TITLE
Error after installing JDK

### ISSUE THREAD

**Issue by hoangdung-qbt** [fdorg/flashdevelop#2903]
Hi after installing JDK 1.8 for Android build, I had this issue. It might cause glitches when typing code.

> Error: Could not process argument Files\Java\jdk1.8.0_231
> Package name must start with a lowercase letter
> Error: Could not process argument Files\Java\jdk1.8.0_231
> Package name must start with a lowercase letter

How to fix it? Thanks!

**Comment by SlavaRa** [comment]
Hi @cat7gods. until I can understand what is happening. Could you tell in more detail what you are doing?

**Comment by hoangdung-qbt** [comment]
Hi! Steps to reproduce
1. Install HD nightly build
2. I'm using OpenFL and I have to install JDK for gradle build.
3. Re-open HD and there is no code completion especially when you type something like this.
Actuate.timer(0.5).onComplete();
Press Ctrl +Space Bar, no code hints showed and I have this error.
Thanks!

**Comment by SlavaRa** [comment]
HD version - ?
Haxe version - ?
openfl(others libraries) version - ?
openfl target - ?

**Comment by hoangdung-qbt** [comment]
- I have Haxe 4.0.1 installed on my machine.
- I just downloaded and updated on all newest versions of Haxe Develop Nightly Build and OpenFL.

**Comment by SlavaRa** [comment]
Please
HD -> Help -> About ...  (I must know for sure :))
cmd|shell|etc -> haxelib list
openfl build target - ?

**Comment by hoangdung-qbt** [comment]
1. haxe libraries

> actuate: [1.8.9]
> box2d: [1.2.3]
> hxcpp: [4.0.64]
> layout: [1.2.1]
> lime-samples: [7.0.0]
> lime: [7.6.3]
> openfl-samples: [8.7.0]
> openfl: [8.9.5]
> starling: [2.5.1]

2. Haxe Develop 5.3.4.460 for .Net 4.0 (development #285d828d28)

3. OpenFL Build target: HTML5 + Android

4. Path to JDK 1.8 (64-bit): C:\Program Files\Java\jdk1.8.0_231

I'm using Windows 10 64bit.

**Comment by SlavaRa** [comment]
HD x64 ?

**Comment by hoangdung-qbt** [comment]
No, x86. I open HD by using shortcut at the desktop screen.
Hd -- help-- about--x86 win32 app.
I guessed HD does not recognize the JAVA path. I will try to uninstall JRE 1.8 and post the result here.

**Comment by SlavaRa** [comment]
Can you try x64 version? `HaxeDevelopDirectory/HaxeDevelop64.exe`

**Comment by hoangdung-qbt** [comment]
I will try as soon as as possible.

**Comment by hoangdung-qbt** [comment]
1. Try HaxeDevelop64.exe: failed
2. Uninstall JDK 18. download and install only JRE 1.8: failed.
Haxe Develop always remember the old Java Path: **C:\Program Files\Java\jdk1.8.0_223.**
3. Delete all setting files in folder:  

> C:\Users\Name\AppData\Local\HaxeDevelop : **failed**

Are there any remaining locations on C: Drive or registry keys that Haxe Develop creates the config files and values?
_

> Nightly Build #285d828d28

_

**Comment by SlavaRa** [comment]
Did you change the settings? (Tools -> Properties -> FlashDebugger -> Java Home Directory)
If not, then the editor uses the system path. (JAVA_HOME) Jdk is needed only for debugging flash applications.
But openfl has its own settings! (UserDirectory/.lime/config.xml)

**Comment by hoangdung-qbt** [comment]
Hi i did a test with as3 code, it worked well. I guess this error causes by new version of haxe(4.0.2) and Haxe Develop(and flash develop).

**Comment by hoangdung-qbt** [comment]
Fixed with nightly build 5.3.4.494 (64 bit) #2942 fd14759736
