### ISSUE TITLE
Disable scaling based on DPI

### ISSUE THREAD

**Issue by hgupta9** [fdorg/flashdevelop#291]
Can you add a project settings option to disable DPI scaling? All of the icons have gone very huge on one of my PCs.

**Comment by Meychi** [comment]
FD is now fully DPI aware, you can disable DPI scaling from app compability options.

**Comment by hgupta9** [comment]
Where is the DPI scaling option?

**Comment by Meychi** [comment]
Right click FlashDevelop.exe > Properties > Compability > Disable display scaling on high DPI settings.
