### ISSUE TITLE
FD crash in for loop when write code

### ISSUE THREAD

**Issue by shaman4dd** [fdorg/flashdevelop#2963]
![photo_2020-01-17_20-48-49](https://user-images.githubusercontent.com/53446113/72634685-17657e00-396c-11ea-9584-e63c73bfc82a.jpg)
If click mouse in place (which arrow points) and try to press some key to continue to write a code -  FD will crash.

**Comment by SlavaRa** [comment]
how I like to retype your code from the image ...
