### ISSUE TITLE
[Bug] F4 does not navigate to function definition

### ISSUE THREAD

**Issue by neuronix** [fdorg/flashdevelop#2981]
Latest development build. Instead of navigating to function definition, F4 takes you to the first parameter's definition.

Input

```
import mypackage.MyFunctionClass;
import mypackage.ParamType;

myFun[cursor here, press F4]ction(myParam);
```

Expected result:

```
public class MyFunctionClass {

  function myFunction(myParam ParamType) : void { ... }

}

```
Actual result:

```
public class ParamType {

  public ParamType() {
  ...
  }

}
```

**Comment by SlavaRa** [comment]
Which version are you using?
Flash\AS3?

**Comment by neuronix** [comment]
Hi Slavara, version is latest development build (#cc409b4192) and yes, Flash/AS3.

**Comment by SlavaRa** [comment]
thx

**Comment by SlavaRa** [comment]
Hi, can you give me provide real code?

**Comment by neuronix** [comment]
Hi @SlavaRa, it's pretty random so it's hard to make a use case. Here is a video of the bug in action. F4 on the function name, sends me to the String.as definition file instead of the appropriate class & method.

![ezgif com-optimize](https://user-images.githubusercontent.com/219800/78673153-0597d500-78e2-11ea-886e-92f80344b9f5.gif)

**Comment by matrix3d** [comment]
I have used flashdevelop for many years since development, and I always think that fd is easier to use than bulky flashbuilder. But the recent versions are really disappointing.
1: f4 often fails
2: Set the document class will cause the ide stuck
3: Find references will be ide stuck
4: The stability of this version is really much worse than the old version

**Comment by neuronix** [comment]
@matrix3d same here. I'm still hanging on to some old half bugged build that's less bugged than the last release but I think we will move to VScode + the AS3MXML plugin which looks promising and actively developed.

The FD team is focused on Haxe development, all the bugs are related to refactoring for better Haxe support and the AS3 support is now just a lucky side-effect. It's the way OSS goes, the people putting their time into the project naturally work on what is important for them, but it is frustrating.

**Comment by matrix3d** [comment]
![fdbug1](https://user-images.githubusercontent.com/4150631/82398757-28430f00-9a86-11ea-84e9-d37b026e98fa.gif)

**Comment by matrix3d** [comment]
I don't really like vscode because there is no toolbar and no visual configuration. I admire the idea framework most and support many languages, but each language does a good job.

**Comment by matrix3d** [comment]
![fdbug2](https://user-images.githubusercontent.com/4150631/82400431-def4be80-9a89-11ea-9f0c-41c249d1b721.gif)
everyday

**Comment by matrix3d** [comment]
![fdbug4](https://user-images.githubusercontent.com/4150631/82409377-2d14bc80-9aa0-11ea-9b12-6dc1587fffd6.gif)
agine

**Comment by matrix3d** [comment]
![fdbug5](https://user-images.githubusercontent.com/4150631/82409747-effcfa00-9aa0-11ea-9ac3-95adc55abdc9.gif)

**Comment by matrix3d** [comment]
Errors occur many times a day. The name of this project is flashdevelop, not haxedevelop. Even if haxelang is supported, it will not make flash development so bad.

**Comment by matrix3d** [comment]
![fdbug6](https://user-images.githubusercontent.com/4150631/82521739-fac79580-9b59-11ea-9887-4b509bc66e51.gif)

**Comment by SlavaRa** [comment]
ok i will check tomorrow

**Comment by matrix3d** [comment]
![fdbug7](https://user-images.githubusercontent.com/4150631/83474916-c213ae80-a4bf-11ea-8b74-949671347f72.gif)
