### ISSUE TITLE
Bug with exe64 only

### ISSUE THREAD

**Issue by Alama32** [fdorg/flashdevelop#2984]
version 5.3.4.513
![exe64](https://user-images.githubusercontent.com/1370864/76390091-0a15b000-636d-11ea-8c2a-9c2ee4d37dbc.jpg)

**Comment by B-Interactive** [comment]
Looks to be the same issue as https://github.com/fdorg/flashdevelop/issues/2973

**Comment by SlavaRa** [comment]
will be fixed today, im sorry ;)
