### ISSUE TITLE
Select the tree item when switch to a file tab

### ISSUE THREAD

**Issue by hgupta9** [fdorg/flashdevelop#299]
Often you open 20 tabs, in the process having navigated to some other part of the folder structure in the Project Manager tree. When you switch to a tab, you cannot easily open the nearby files. You have to search for the file again in the tree, and then search for the nearby files, to open them.

It would be nice to auto-select the tree item, whenever you switch a tab. So it keeps the text editor & the project manager tree in "sync". Obviously if the file is not found in the tree (external file or non-src file), nothing is selected.

**Comment by Meychi** [comment]
Done.
