### ISSUE TITLE
[5.3.*] AppMan: Item list could not be downloaded

### ISSUE THREAD

**Issue by mbndr** [fdorg/flashdevelop#3023]
I'm using HaxeDevelop but I guess this goes to the same place.

I tried to install something through AppMan. But if I open it, it just says it could not download the item list.

![grafik](https://user-images.githubusercontent.com/7734369/78677319-e4d27e00-78e7-11ea-8184-b53a1b00e52f.png)

I'm using HaxeDevelop 5.3.3.1

**Comment by Shadowblitz16** [comment]
I also get this and installing .net framework 3.5 doesn't work at all
the installer just closes

EDIT: can't seem to check for updates either.

**Comment by Shadowblitz16** [comment]
can we get a reply on this?
or at least a way to fix it in the meantime?

I'm not going to use visual studio code and this is keeping me from learning the haxe language

**Comment by ugotopia123** [comment]
The only thing I've found is this xml file that AppMan is supposed to pull from: https://www.flashdevelop.org/appman.xml

Put that in your browser and you'll have to manually go to the links of the things you need.
[This forum post](https://www.flashdevelop.org/community/viewtopic.php?f=6&t=13156&p=55990#p55990) says you can simply put the xml data into the \<Config\> section of the AppMan config file but I tried that with no luck so I downloaded everything manually.

**Comment by Shadowblitz16** [comment]
where is this AppMan config located on windows?

**Comment by Shadowblitz16** [comment]
so they don't care to fix this?

**Comment by ugotopia123** [comment]
The admin that posts the release versions on the forums hasn't made a post since 2018 but the repository seems to still get updates so I'm not sure

**Comment by thomrnowtea** [comment]
Found a way to fix it!
You need to download the appman.xml manually and paste it wherever you want. In my case, the appman folder.
Then, right-click pressing SHIFT > Copy As Path
After that, you need to edit the Config.xml file, and replace the url https://www.flashdevelop.org/appman.xml from config and paste your file path without quotation marks. And save it.

![image](https://user-images.githubusercontent.com/60904612/87983480-d2530d80-caae-11ea-8ca7-6f892a971044.png)

Finally, the AppMan should be working.

**Comment by SlavaRa** [comment]
Please use development build from https://flashdevelop.org/downloads/builds/

**Comment by ugotopia123** [comment]
Holy crap you're a lifesaver. I haven't updated my FlashDevelop version in a long time and the development build fixed so many problems I had with the old version!

**Comment by hlizard** [comment]
raw.githubusercontent.com It's not usually unavailable in China, so please change to auto try https://www.flashdevelop.org/appman.xml  when https://raw.githubusercontent.com/fdorg/flashdevelop/development/appman.xml is unavailable.

**Comment by SlavaRa** [comment]
hm... ok
