### ISSUE TITLE
How to get started... trying to debug and it gives me message "Application not fond"

### ISSUE THREAD

**Issue by magicmouse** [fdorg/flashdevelop#3029]
First run, trying to comple the Hello world, that has some trace statements in it. 
Can't seem to get the PROJECT / DEBUG command to work. It says haxe -debug...., build succeeded, Done(0), then says "Application not found".

Will be glad to pay for some help.

**Comment by SlavaRa** [comment]
What type of project?
FD version? (Help -> About...)
Haxe version?
