### ISSUE TITLE
Cannot update

### ISSUE THREAD

**Issue by VanBandama** [fdorg/flashdevelop#3037]
![Bez tytułu](https://user-images.githubusercontent.com/22223143/87961361-dfbfc600-cab5-11ea-96ba-3e7dbb1b27c9.png)
Tried to reinstall it. I got HD 5.3.3.1 . PS also Appman shows nothing.

**Comment by SlavaRa** [comment]
@VanBandama, What did you expect to see?

**Comment by SlavaRa** [comment]
Please use development build from https://flashdevelop.org/downloads/builds/
