### ISSUE TITLE
[Haxe][CodeComplete][InferVarType] Hard crash upon opening a specific file

### ISSUE THREAD

**Issue by YellowAfterlife** [fdorg/flashdevelop#3075]
Version: 5.3.4.570

1. Download the [sample project](https://github.com/fdorg/flashdevelop/files/5360361/sprite_add_gif.zip)
2. Open it in FD/HD
3. Open Gif.hx

If that doesn't crash, install dependencies
```
haxelib install format
haxelib git sfhx https://github.com/YellowAfterlife/sfhx
haxelib git sfgml https://github.com/YellowAfterlife/sfgml
```

**Comment by SlavaRa** [comment]
i'll check it tomorrow

**Comment by SlavaRa** [comment]
it's for me:
addBuffer { LineFrom : 101, LineTo : 157 }, error line: 132
