### ISSUE TITLE
[Haxe][OpenFL] Inheritance loop warning in OpenFL project

### ISSUE THREAD

**Issue by andrew-git** [fdorg/flashdevelop#3079]
FD 5.3.4.570, Completion Server, OpenFL project (OpenFL 8.9.0 / Lime 7.3.0)
When start to type 
`var p = new [space]`
I got warning: "Inheritance loop detected between openfl.display.IGraphicsStroke and openfl.display.IGraphicsStroke."

**Comment by SlavaRa** [comment]
Cannot be reproduced for latest development
