### ISSUE TITLE
[Haxe] crash after completion canceled

### ISSUE THREAD

**Issue by Klug76** [fdorg/flashdevelop#3080]
![fd_crash_after_completion_canceled](https://user-images.githubusercontent.com/1420061/96773356-73769a80-13f5-11eb-82bd-16270aa1a239.gif)
[fd_crash_after_completion_canceled_stack.txt](https://github.com/fdorg/flashdevelop/files/5418329/fd_crash_after_completion_canceled_stack.txt)
Haxe: 4.1.4
FD:  https://github.com/fdorg/flashdevelop/commit/31cda34fea58181edc4e0e3e2831c4428f85a30b
Sample project: 
[fd_crash_test.zip](https://github.com/fdorg/flashdevelop/files/5418336/fd_crash_test.zip)
The crash reproduces stably, every time I type '=' in line ``var picarr[i] = pic;``.

**Comment by SlavaRa** [comment]
will be fixed on sunday
