### ISSUE TITLE
Issue after installing (attempted to read or write protected memory)

### ISSUE THREAD

**Issue by markknol** [fdorg/flashdevelop#3081]
A colleague wanted to install latest haxedevelop (development build from https://github.com/fdorg/flashdevelop/commit/31cda34fea58181edc4e0e3e2831c4428f85a30b) 

She gets:   
![image](https://user-images.githubusercontent.com/576184/96988335-7cb25500-1524-11eb-9432-7fcaa0c15bba.png)

I actually tried same but have no issues, any idea?

**Comment by markknol** [comment]
Actually she gets multiple errors in a row 

![image](https://user-images.githubusercontent.com/576184/96990235-209d0000-1527-11eb-90be-bce738304031.png)
![image](https://user-images.githubusercontent.com/576184/96990279-2eeb1c00-1527-11eb-9fd3-6ea247634af7.png)
![image](https://user-images.githubusercontent.com/576184/96990289-34486680-1527-11eb-97b4-f1463302f0a0.png)
![image](https://user-images.githubusercontent.com/576184/96990333-42968280-1527-11eb-9fdb-e70f36bccfd5.png)
![image](https://user-images.githubusercontent.com/576184/96990401-5b9f3380-1527-11eb-9702-6022b5d90b84.png)
![image](https://user-images.githubusercontent.com/576184/96990540-88534b00-1527-11eb-9f27-be8694447950.png)
![image](https://user-images.githubusercontent.com/576184/96990699-b9cc1680-1527-11eb-9860-f45cbb85912b.png)

**Comment by SlavaRa** [comment]
x64?

**Comment by SlavaRa** [comment]
Duplicate #3036
