### ISSUE TITLE
HaxeDevelop no longer working after windows update

### ISSUE THREAD

**Issue by ianharrigan** [fdorg/flashdevelop#3089]
Hi There - ive been using a HaxeDevelop nightly for ages (most recently yesterday), this morning I updated my windows machine and after HD no longer opens at all, ive tried reinstalling and nothing. Same issues, things along these lines (which are found in various other issues on this repo):

![image](https://user-images.githubusercontent.com/3024242/98786698-bdeca500-23fe-11eb-96fe-90f7257c78e8.png)

Ive also tried rebuilding FD from source and seemed to build fine, the x86 version didnt open due to trying to access protected memory, fine. The x64 seemed to run fine (i didnt thoroughly test it) - however, was after haxe develop rather than flash develop - so i guess my question is in multiple parts:

1) any idea what the original issue is, and if there will be a fix for it
2) how can i build haxe develop from source, in the same method you do to produce the nightlies - i just copied over the files from "Distros" to overwrite the relevant files in the relevant root dirs, which im sure isnt the right method
3) is there a way to help you move forward on this, or help with FD/HD in general :)

Cheers,
Ian

**Comment by SlavaRa** [comment]
Hi, in progress

**Comment by SlavaRa** [comment]
Windows?
.net 4.8 update?

**Comment by ianharrigan** [comment]
Yup, windows... not sure what the update was to be honest... but installed .net 4.8 again anyway just in case the update borked it, didnt seem to make a difference

**Comment by SlavaRa** [comment]
windows version? (LTSC, 10, ....)
windows -> settings -> updates -> update log
![image](https://user-images.githubusercontent.com/1700940/98793401-eb464c80-2418-11eb-93a9-12ef76cf3cbe.png)
I need to know which update was the last

**Comment by markknol** [comment]
Same.
This is second time I got this issue, with last windows update this happened too.
Last time, after a few restarts/reinstalls and at certain magical moment it started to work again. 
![image](https://user-images.githubusercontent.com/576184/98793866-bd590c00-2408-11eb-8607-a4ae597ab56b.png)

**Comment by ianharrigan** [comment]
![image](https://user-images.githubusercontent.com/3024242/98793958-d497f980-2408-11eb-93eb-debcdd41da7c.png)
Windows 10, yeah, ignore the fact my system is in spanish... i use a spanish keyboard ;)

**Comment by SlavaRa** [comment]
thx, I have an idea
> i use a spanish keyboard ;)

no problem ;)

**Comment by ianharrigan** [comment]
![image](https://user-images.githubusercontent.com/3024242/98794201-0e690000-2409-11eb-9d44-3c0dbac638de.png)


ive also just realised there is a cumulative update also - going to install that, maybe it'll fix it, but id want to install it anyway, so will see

**Comment by markknol** [comment]
Not sure if this helps but this is the error I get a lot of times when starting HaxeDevelop
```
Object reference not set to an instance of an object.

   at System.Windows.Forms.Form.CreateControlsInstance()
   at FlashDevelop.Docking.TabbedDocument.AddEditorControls(String file, String text, Int32 codepage)
   at FlashDevelop.Docking.TabbedDocument.AddEditorControls(String file, String text, Int32 codepage)
   at FlashDevelop.MainForm.CreateEditableDocument(String file, String text, Int32 codepage)
```
or
```
Attempted to read or write protected memory. This is often an indication that other memory is corrupt.

   at System.Windows.Forms.Form.CreateControlsInstance()
   at FlashDevelop.Docking.TabbedDocument.AddEditorControls(String file, String text, Int32 codepage)
   at FlashDevelop.Docking.TabbedDocument.AddEditorControls(String file, String text, Int32 codepage)
   at FlashDevelop.MainForm.CreateEditableDocument(String file, String text, Int32 codepage)
```

**Comment by SlavaRa** [comment]
the problem is in accessing Scintilla(to dll). I know a specific place in the code, but so far I can't figure out how to solve the problem once, almost every windows update breaks everything (((

**Comment by ianharrigan** [comment]
Where to the scintilla bindings for .net come from? Is it an issue in that project? Also, i managed to build (i think at least) Flash Develop from source with no issues, at least it started up, didnt open an editor to check scintilla though - not sure if that helps ny but _does_ indicate things "can" be fine... (i had to use the x64 .exe though)

**Comment by ianharrigan** [comment]
All look to be fine... could it just be that the nightlies also need an x64 version? 

![image](https://user-images.githubusercontent.com/3024242/98800007-209a6c80-2410-11eb-87a6-184b96e695e4.png)

**Comment by markknol** [comment]
For some magical reason it just started to work for me, ✨ I did nothing special except from coding in VSCode the whole day. Maybe it's jealous and does some psychological tricks on us to see if we really love it enough once in a while..?

**Comment by ianharrigan** [comment]
hahaha... what the hell?!?!? Same here!

**Comment by ianharrigan** [comment]
@SlavaRa - can you also post x64 nightlies when you do post nightlies? Might be the issue (cant be sure though)

**Comment by SlavaRa** [comment]
duplicate #3081 #3036

**Comment by hachigoro** [comment]
As expected, the latest Windows Update fixed this issue. Let's hope this does not become a pattern of windows updates breaking and fixing FD every other month.

**Comment by SlavaRa** [comment]
I am working to prevent this from happening again, I found the reason, but the task turned out to be very difficult.

**Comment by markknol** [comment]
Hey SlavaRa, Happy new year! 

Microsoft blessed us with another new windows update 🤦‍♀️, so I got new errors on startup .. I hope they will leave automatically as they always seem to do, but here you go
![image](https://user-images.githubusercontent.com/576184/104892496-8bb57180-5972-11eb-9032-88ea0aeb0e5d.png)

**Comment by ianharrigan** [comment]
... weirdly i havent gotten this one (yet)... and am up-to-date... *shrug*

**Comment by SlavaRa** [comment]
Agrh....

**Comment by markknol** [comment]
It does work after few hours of wait + restarting few times.. So odd.

**Comment by hlizard** [comment]
> 
> 
> It does work after few hours of wait + restarting few times.. So odd.

yes, me too

**Comment by ianharrigan** [comment]
OK, well, another windows update another issue of HD not working... wont even open this time... Ive uninstalled and reinstalled and nothing. I did noticed the development build from here: https://flashdevelop.org/downloads/builds/ is a month old... is there a more up to date version to try?

Cheers,
Ian

EDIT: actually, nevermind, my shortcut was pointing to the 32bit build... the 64 bit build seems fine... phew :)

**Comment by hlizard** [comment]
another windows update KB4601554 also bring "MDI container forms must be top-level." error. Just uninstall it.

**Comment by hlizard** [comment]
and KB5003173

**Comment by hypersurge** [comment]
and KB5013624

For reference on how to hide unwanted updates:
https://www.repairwin.com/prevent-a-specific-windows-update-or-driver-from-installing-in-windows-10/

**Comment by haxecoder** [comment]
SlavaRa doesnt have access to github rn. The problem can be solved within a month.

**Comment by hypersurge** [comment]
and KB5013887

For reference on how to hide unwanted updates:
https://www.repairwin.com/prevent-a-specific-windows-update-or-driver-from-installing-in-windows-10/

**Comment by hypersurge** [comment]
and KB5015730
(these are usually labelled as "Cumulative Update [Preview] for .NET Framework 3.5 and 4.8 for Windows 10")

**Comment by andrew-git** [comment]
[(Re)Building FD manually](https://github.com/fdorg/flashdevelop#building) resolved issue for me.
