### ISSUE TITLE
Add classpath directory in OpenFL project

### ISSUE THREAD

**Issue by kreator83** [fdorg/flashdevelop#309]
Flashdevelop version: 4.6.2.5
Haxe: 3.1.3
OpenFL: 2.0.1

1) create openfl project
2) add src path in "project -> properties -> classpath"
3) press ok
4) the classpath appeared in project references (on the right)
5) open "project -> properties -> classpath". 
6) added classpath disappeared.
7) try to compile: the compiler doesnt see imports from that path
8) restart flash develop: the path disappears from references

classpath was added manually in application.xml as source path

**Comment by Meychi** [comment]
In FD5.
