### ISSUE TITLE
HXML MultiTarget project improvement

### ISSUE THREAD

**Issue by Klug76** [fdorg/flashdevelop#3132]
It would be nice to split ``js`` target in a ``HXML MultiTarget``-project, so that ``js`` is launched in the browser from some ``index.html``, and ``nodejs`` is like ``js`` now: ``node $(ProjectID).js``.
The ``Projects/395 Haxe - HXML Project/hxml/nodejs.hxml.template`` file could be like this:
```
hxml/common.hxml
-lib hxnodejs
-js bin/js/$(ProjectID).js
```
Also, may be it is time to remove the deprecated as3 target from the list of default targets (in ``/Settings/Platforms/Haxe/multitarget.xml``) because as3 target not supported in haxe 4.1+ anymore.

**Comment by Klug76** [comment]
Perhaps it is better to keep this type of project as it is, but make a new type of project with a list of targets, which is formed from a hxml-file (for each ``--next`` entry), with different runners. But it is not yet clear how to organize runners for targets.

**Comment by SlavaRa** [comment]
via #3138
