### ISSUE TITLE
My classes folder inside References folder becomes impossible to expand 

### ISSUE THREAD

**Issue by joseroux** [fdorg/flashdevelop#314]
I have this bug for some time: after awhile, 1 or 2 times a day, my "AS3 Classes" folder inside the References virtual folder becomes un-expandable!
I never collapse it, somehow it collapse at some point and the + disappears...
Restarting FD resolve the problem.
![image](https://cloud.githubusercontent.com/assets/5633182/4133892/a28d98a0-3364-11e4-9b0f-b1fadec08e7e.png)

Windows 7 64bit ENG
NET Version: 2.0.50727.5420

**Comment by joseroux** [comment]
hummm, sorry to say this still happen to me regularly, and a simple refresh doesn't do; I have to restart...

**Comment by Meychi** [comment]
Could you test a standalone version of FD5 dev build?

**Comment by joseroux** [comment]
OK, will try. I think a week will be enough to see if the problem is still
around (I use FD almost every day ;)

2015-03-21 19:10 GMT-04:00 Mika Palmu <notifications@github.com>:

**Comment by joseroux** [comment]
Hi, just want to let you know the last *development* build files are
broken: "...damaged or download incomplete...: both exe and zip are not
opening. The master version is fine.

2015-03-21 19:15 GMT-04:00 José Roux <joserouxx@gmail.com>:

**Comment by joseroux** [comment]
Two months and no more problem: seem fixed with FD5.

**Comment by Meychi** [comment]
Thank you for letting us know.
