### ISSUE TITLE
2 suggestions (UI)

### ISSUE THREAD

**Issue by deepnight** [fdorg/flashdevelop#32]
Hi! 

Here are 2 suggestions for the FD interface:

1- Color code preview : https://dl.dropboxusercontent.com/u/4952054/flashDev/colorPreview.png
The principle is simple (in theory): display a small preview near any detected color code in source code (like 0xRRGGBB, or #RRGGBB)

2- an alternative to the region system which is not really ergonomic:
https://dl.dropboxusercontent.com/u/4952054/flashDev/outlinePanel.png
The system detects specific comment patterns in the code and shows them as separator in the Outline panel.

Thanks!

Note: these are suggestions I initially posted in the Cactus IDE comments.

**Comment by SlavaRa** [comment]
Now you can install this plugin from AppMan.
I think this issue completed
