### ISSUE TITLE
Bug: an extra space is inserted after the return statement if the function returns void

### ISSUE THREAD

**Issue by Klug76** [fdorg/flashdevelop#3228]
Bug: an extra space is inserted after the return statement **inserted by code completion** if the function explicitly returns void:
```
function foo(): Void
{
  return ;
}
```
Expected result:
```
function foo(): Void
{
  return;
}
```
FD version: https://github.com/fdorg/flashdevelop/commit/c4264e9f73

**Comment by SlavaRa** [comment]
duplicate #3229
