### ISSUE TITLE
Enhacement: option "add necessary space after code completion"

### ISSUE THREAD

**Issue by Klug76** [fdorg/flashdevelop#3229]
Since some commit about a month ago, FD started inserting a necessary space after the code completion. For beginners, this is good. But people like me who are reflexively adding a space want to turn this behavior off.
Old behavior:
![fd_old_return_behavior](https://user-images.githubusercontent.com/1420061/104441668-6b219c00-55ad-11eb-9591-b5ca122f4a08.gif)
New behavior:
![fd_new_return_behavior](https://user-images.githubusercontent.com/1420061/104441251-ddde4780-55ac-11eb-8b6d-9cdd90641e75.gif)

**Comment by SlavaRa** [comment]
Regression #3127
