### ISSUE TITLE
"MDI container forms must be top-level." error occurs on startup

### ISSUE THREAD

**Issue by hlizard** [fdorg/flashdevelop#3230]
HaxeDevelop-development.exe (1 week old)
![image](https://user-images.githubusercontent.com/6994037/105122726-b558cf00-5b11-11eb-8845-fbe44c9244de.png)

**Comment by SlavaRa** [comment]
duplicate https://github.com/fdorg/flashdevelop/issues/3089

**Comment by hlizard** [comment]
another windows update KB4601554 also bring "MDI container forms must be top-level." error. Just uninstall it.

**Comment by hlizard** [comment]
and KB5003173
