### ISSUE TITLE
Trouble downloading releases

### ISSUE THREAD

**Issue by PStibbons13** [fdorg/flashdevelop#3249]
When I try to look at the forum post for any of the releases on this page https://www.flashdevelop.org/community/viewforum.php?f=11 I am getting a series of php errors at the top of the page and there is no link to download that version.

**Comment by SlavaRa** [comment]
I`ll fix it at night

**Comment by SlavaRa** [comment]
please use development build from https://flashdevelop.org/downloads/builds/
