### ISSUE TITLE
haxedevelop doesn't show bookmark panel under view menu

### ISSUE THREAD

**Issue by f-rank** [fdorg/flashdevelop#3257]
Got nightly donwloads from https://flashdevelop.org/downloads/builds/
Strange that I can't see the bookmark panel option in the view menu, the keys to set, navigate and delete bookmarks are still there.
Maybe there's a way to bring it back, or is this the new way and it won't return ?
Got version 5.3.4.676, thought it would have it back, but not there either.

**Comment by SlavaRa** [comment]
i'll check today
