### ISSUE TITLE
[haxe] Unspecified type + metadata leads to MemberModels with invalid types

### ISSUE THREAD

**Issue by Gama11** [fdorg/flashdevelop#372]
With the following, `ASContext.Context.CurrentMember` is not null, which it should be. Additionally, the type of the member is `"allow"`. Seems like the logic that parses variables, looking for colons, might be a bit too aggressive.

`|` is the caret position.

``` haxe
class Main 
{
    var test = 1;

    @:allow(haxe.ds.ArraySort|)
    static function main() 
    {

    }
}
```

This breaks my fix for metadata paths (#336) and who knows what else.

**Comment by Gama11** [comment]
This only seems fixed in cases where there already exists a closing paren while typing the module path (which is unlikely to be the case unless you have "Add closing braces" activated). I can reproduce the bug from #204 otherwise.

**Comment by Neverbirth** [comment]
That's a wrong syntax case, but I agree the method shouldn't use the meta as information of the member.

**Comment by Neverbirth** [comment]
Could you give more details? I cannot reproduce it currently :/.

**Comment by Gama11** [comment]
Are you using the example code from the original issue? There has to be a member var using type inference before.

```haxe
var test = 1;

@:allow(
static function main() 
{

}
```

**Comment by Neverbirth** [comment]
I see, you must have the whole code as you typed it. Even if you have:

```haxe
var test = 1;

@:allow(
static function main() 
```

It works fine
