### ISSUE TITLE
[haxe] Parsing problems with nested function types

### ISSUE THREAD

**Issue by Gama11** [fdorg/flashdevelop#379]
FD doesn't like types like this one much:

```haxe
var f:(Void->Void)->Void;
```

The resulting `MemberModel` has the type `Void->Void -> Void`. Because of that, it's also displayed incorrectly in the outline panel and in completion.

**Comment by Neverbirth** [comment]
I'd say this can be closed now.

**Comment by Gama11** [comment]
You're right, that case seems to work now, but if type parameters are involved it breaks:

![](http://i.imgur.com/zGjXH5e.png)

**Comment by Gama11** [comment]
Haven't managed to construct an example where it fails anymore with the improvements.. (so far ;))
