### ISSUE TITLE
copy path to clipboard

### ISSUE THREAD

**Issue by markknol** [fdorg/flashdevelop#386]
I would love to see a _'copy path to clipboard'_ function on files/folders in the project manager.

On the tabs menu above the editor. It would be handy to have both _'copy filepath to clipboard'_ and _'copy directory to clipboard'_, where the directory copies the directory of the file. 

I now use this in my _tabmenu.xml_, but that opens/closes an annoying prompt window.
```
<separator />
<button label="Copy path to clipboard" click="RunProcess" tag="cmd;/c echo $(CurFilename)|clip" image="278" />
<button label="Copy directory to clipboard" click="RunProcess" tag="cmd;/c echo $(CurDir)|clip" image="278" />
```
This would be a simple time saver.

**Comment by Meychi** [comment]
The context menu is already crowded. :) This can be done a plugin or script.

**Comment by markknol** [comment]
I still open a new explorer window about 15 times a day to get a folder path copied to the clipboard..

**Comment by Meychi** [comment]
To not leave FD and see the path, you can Ctrl+RightClick the dir and select properties. :)
