### ISSUE TITLE
Some packages being shortened

### ISSUE THREAD

**Issue by ncannasse** [fdorg/flashdevelop#429]
[Haxe] I have a class called `hxd.Math`. I have imports generation disable, but everytime I write `hxd.Math` it will remove the hxd package and simply write `Math` which is pretty annoying :)

**Comment by SlavaRa** [comment]
> I have imports generation disable
For HaxeContext Plugin?

I checked the latest release and was unable to repeat the mistake

**Comment by SlavaRa** [comment]
all ok in FD 5.3.1.28
