### ISSUE TITLE
Haxe multi-targets

### ISSUE THREAD

**Issue by ncannasse** [fdorg/flashdevelop#455]
Haxe allows several compilations to be performed in a single command by using `--next`

For instance the following HXML builds 3 different targets:

```
-swf out.swf
-main Main
-lib mylib

--next
-js out.js
-main Main
-lib mylib
-D fdLaunch=index.html

--next
-cpp bin
-main Main
-lib mylib
```

FlashDevelop could split the different compilations ocurring between `--next`, analyse the target which is compiled, and propose it as part of a drop down menu similar to NME target one.

In the previous HXML that would be:

```
All (default, current behavior)
Flash
JavaScript
C++
```

In case the same target is used in several parts of the compilation, we could add the output file to differentiate between them (eg `C++ (bin)`)

When testing the project, if the target is set to `All` then we can use `Test Project` as we do already.

However if we have a target selected or if our Test Project is set to OpenDocument with documentName="", we can use the following behavior:
- if we have `-D fdLaunch=<file>` we can use that as OpenDocument
- if not, we use default behavior on a per-target basis:
- on Flash, play the output SWF with Flash Player
- on C++, run the `<output-dir>\<main-class>[-debug].exe`
- on other targets print an error saying missing `-D fdLaunch=<document>`

**Comment by SlavaRa** [comment]
via #2663
