### ISSUE TITLE
Refactor->Rename fails when renaming function parameters in some cases

### ISSUE THREAD

**Issue by Gama11** [fdorg/flashdevelop#467]
Renaming a parameter to have the same name as another variable currently available in the context can break the code.

Example:

``` haxe
class Test
{
    var v:Int; 

    public function new(w:Int)
    {
        v = w;
    }
}
```

Renaming `w` to `v` leads to:

``` haxe
class Test
{
    var v:Int; 

    public function new(v:Int)
    {
        v = v;
    }
}
```

However, it should be `this.v = v;`

Similarly, if `v` is a `static var`, it should turn into `Test.v = v;`.

**Comment by SlavaRa** [comment]
Fixed
