### ISSUE TITLE
Remember "Code files only" checkbox in the "Open Resource" window

### ISSUE THREAD

**Issue by burakkurkcu** [fdorg/flashdevelop#483]
Selection of "Code files only" checkbox in the "Open Resource" window is remembered just for current session. It would be nice not to set it again for every session.

![codefilesonly](https://cloud.githubusercontent.com/assets/5931039/4801092/0353379c-5e2d-11e4-8e24-069efd111172.png)

**Comment by Meychi** [comment]
Atm all dialogs are session managed as this works best with our multi instance mode wich is poor managing settings with multiple instances. If we find a proper solution to this issue, all dialogs will be changed to fully managed. We have centralized functionality already available for easy change.
