### ISSUE TITLE
Typing } in a string eats a tab

### ISSUE THREAD

**Issue by Gama11** [fdorg/flashdevelop#489]
Seems to happen in 4.6.4 as well, so it's not a recent regression (if it is one).

![](http://i.imgur.com/oOxxSUD.gif)

**Comment by andrew-git** [comment]
Seems like "{" or "}" processed not like String
```
	function test(data:String)
	{
		if (data == "{")
		{
			
		}
	}
```
For above example if press Enter on line before "if" you'll got

```
	function test(data:String)
	{
		
		if (data == "{")
		{
	}
			
		}
	}
```
