### ISSUE TITLE
Refactor rename class explores too many files

### ISSUE THREAD

**Issue by elsassph** [fdorg/flashdevelop#501]
When renaming a class in a path inside the project folder, the refactoring tool should not look for references outside.

Generally for refactoring, Haxe SDK classpath should be ignored.

**Comment by Neverbirth** [comment]
Maybe this one shouldn't be closed. The commit fixed the issue for AS projects, but not for Haxe, because those have the SDK classpaths included in the Project classpaths... I realized it after pushing the changes.

**Comment by Meychi** [comment]
Ah, true.

**Comment by Meychi** [comment]
CodeRefactor now ignores files from the SDKs. Issue is still present with local dev haxelibs.
