### ISSUE TITLE
Implement trace colors in output panel for Haxe projects

### ISSUE THREAD

**Issue by Tiago-Ling** [fdorg/flashdevelop#530]
A simple yet nice and useful feature in As3 projects is being able to use different colors for tracing in the output console:

```as3
trace("0:Test"); //Gray
trace("1:Test"); //Black
trace("2:Test"); //Yellow
trace("3:Test"); //Red
trace("4:Test"); //Fuchsia
```
It would be nice to also have this in Haxe projects :)

**Comment by markknol** [comment]
In the meanwhile you can use haxe magic to solve this:
```
package;
/**
 * @author Mark Knol
 */
class FDTrace
{

	inline public static function nativeTrace(a:Dynamic)
	{
		#if flash
			untyped __global__["trace"](a);
		#else
			trace(a);
		#end
	}
	
	inline public static function log1(a:Dynamic) nativeTrace('1: $a');
	inline public static function log2(a:Dynamic) nativeTrace('2: $a');
	inline public static function log3(a:Dynamic) nativeTrace('3: $a');
	inline public static function log4(a:Dynamic) nativeTrace('4: $a');
}
```

**Comment by madrazo** [comment]
Hi, this feature would be cool. 
This works great for flash, but not for Windows target (native c++).
I have tried using untyped __trace and Sys.println with no use.
Would be a way to do it by send a tag like in html text? 
Cheers

**Comment by elsassph** [comment]
It sounds like we should look into parsing a few ANSI escape sequences:
http://ascii-table.com/ansi-escape-sequences.php

BTW it doesn't in standard Window cmd but replacements like ConEmu (cmder
for a nice skin) or console2 will process them.

On Thu, Feb 5, 2015 at 3:55 PM, Carlos Madrazo <notifications@github.com>
wrote:

> Hi, this feature would be cool.
> This works great for flash, but not for Windows target (native c++).
> I have tried using untyped __trace and Sys.println with no use.
> Would be a way to do it by send a tag like in html text?
> Cheers
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/fdorg/flashdevelop/issues/530#issuecomment-73069858>.
>



-- 
Philippe

**Comment by madrazo** [comment]
Hi. I have sent a pull request in Haxe's Git to fix "trace" for Flash traget to take into account the starting decimals and show the colors. https://github.com/HaxeFoundation/haxe/pull/3840

**Comment by elsassph** [comment]
I don't think Haxe has anything to do with that.

**Comment by madrazo** [comment]
Sorry, It is just a "hack" to make it work with the current FD color scheme, but parsing the ESC sequences sounds like a definitive solution for all targets. Also @grapefrukt 's sounds like what it have in mind since only colors for 5 log levels is enough I think.

**Comment by Meychi** [comment]
FD5 now has customizable coloring markers.
