### ISSUE TITLE
a bug of autocomplete

### ISSUE THREAD

**Issue by matrix3d** [fdorg/flashdevelop#565]
![fdbug](https://cloud.githubusercontent.com/assets/4150631/5751930/c4aa3f32-9ca6-11e4-8764-8a0e76633288.png)

**Comment by matrix3d** [comment]
can not autocomplete the test function

**Comment by markknol** [comment]
Maybe you should use `public var a:Function` instead of `Object`.

**Comment by matrix3d** [comment]
a not a function;
i want code  a =test();

**Comment by Neverbirth** [comment]
Would that even be valid code? at least not on many languages, and for good reasons.
