### ISSUE TITLE
Where is FlashConnect.flush()?

### ISSUE THREAD

**Issue by wvxvw** [fdorg/flashdevelop#575]
Hi,
I've tried to compile the AS3 code related to profiler, which relies on FlashConnect. I didn't find AS3 sources for FlashConnect, only Haxe and AS2. I've tried to build a SWC from Haxe sources and then link the AS3 code against it, but then I discovered that `FlashConnect.flush()` doesn't exist.

I'm not sure what the problem is, but I'd guess that the AS3 version is simply missing from the repository?

**Comment by Meychi** [comment]
All FlashConnect version sources: https://github.com/fdorg/flashdevelop/tree/development/FlashDevelop/Bin/Debug/Library

**Comment by wvxvw** [comment]
@Meychi I'm sorry to insist, but it's not there. Please see: https://github.com/fdorg/flashdevelop/search?utf8=%E2%9C%93&q=FlashConnect It only finds the Haxe and AS2 code.

**Comment by Meychi** [comment]
https://github.com/fdorg/flashdevelop/blob/development/FlashDevelop/Bin/Debug/Library/AS3/classes/org/flashdevelop/utils/FlashConnect.as?

**Comment by wvxvw** [comment]
Ugh... I have no idea why the search didn't find it before :/ Thanks Mika!
