### ISSUE TITLE
Double file reloading dialogs

### ISSUE THREAD

**Issue by Simn** [fdorg/flashdevelop#579]
1. I have a 450kb log.txt open in FlashDevelop.
2. In a command prompt I run something like `haxe build.hxml > log.txt`.
3. I wait for the command to finish without doing anything.
4. Focusing back FD is waiting for me with the "A file has been modified externally" dialog. I click Yes.

So far so good, but then a few seconds later the dialog appears _again_. It doesn't seem to matter how long I wait before clicking Yes on the first one. I would understand this behavior if the file was still being modified, but it's long done by the time I confirm the first dialog.

FD 4.7.1.1.

**Comment by Meychi** [comment]
Fixed.
