### ISSUE TITLE
Haxe - Suggestion - Enum autocomplete and templating with all possible values.

### ISSUE THREAD

**Issue by sebpatu** [fdorg/flashdevelop#589]
Hi,
It would be very usefull to be able to leverage the Enum mechanism of haxe in flahdevelop by being able to pre fill a switch Template with ALL values of an Enum as cases, and also give autocomplete tooltip info with all the possible values.
Thanks

**Comment by SlavaRa** [comment]
via #2466 #2507 #2508

**Comment by sebpatu** [comment]
hi your updates of switch autocomplete are great, but it is not exactly what was suggested.
i meant to pre fill all cases one under the other for the switch.
from 
switch(varName) {}
to
switch(varName) {
 case VAL1:
case VAL2:
case VAL3:
}
in one keyboard typing.

if there are a lot of them, you dont want to put them one at one by hand even with autocomplete. 
thanks

**Comment by SlavaRa** [comment]
You can try `var$(EntryPoint)Name` where $(EntryPoint) is cursor, press `shift+ctrl+1` or `Refactor -> Code Generator` then select and execute `Generate swith` ;)

@sebpatu if this case does not suit you, you need to describe how the editor should work in a separate issue.
