### ISSUE TITLE
Suggestion - Target Build history - default list at startup

### ISSUE THREAD

**Issue by sebpatu** [fdorg/flashdevelop#590]
Hi,
Please add a setting in .settings file or somewhere else to fill a default list of values at startup of flashdevelop to Target build history, instead of always using only the last selected item.

Because its quite annoying to have to set them each time.
And this middle solution is more easy to add, than always saving all items and adding an editor to delete items afterwards.

Thanks

**Comment by BenLeffler** [comment]
This would be a nice feature, actually. I'd find it quite handy.
