### ISSUE TITLE
Cant type character @ with french azerty keyboard

### ISSUE THREAD

**Issue by sebpatu** [fdorg/flashdevelop#591]
Hi,
I can't type the character @ in flashdevelop code editor.
But it works fine anywhere else.
It never worked with any other previous and current version i used.

I have Windows 7 with azerty keyboard. 
its french configuration
Flashdevelop is installed as English language.

Thanks

**Comment by elsassph** [comment]
Strange, I have used FD with French keyboards forever.
Do you have any keyboard-related application running on your computer?

**Comment by sebpatu** [comment]
Strange indeed, because i have nothing specific installed.
To answer your question, i use Notepad ++ with no issue for this character. In fact i never noticed such issue with any other software.

**Comment by sebpatu** [comment]
Thing is that its the only character i can't use.
Any other character works fine in the editor of flashdevelop, so its not a keyboard config issue.
What could be specific to this character in code?

**Comment by elsassph** [comment]
Does it happen with an old version of FD (like 4.0 - you can install standalone to not break your setup)?

**Comment by sebpatu** [comment]
Nop :) 4.0.0 RC1 is working fine, no issue with the character.
found a possible reason?

**Comment by elsassph** [comment]
That's just a wild guess - we need to figure at what release we introduced a breaking change...

**Comment by sebpatu** [comment]
ok after a lot of installations, i finally found out that it came from a plugin:
http://www.flashdevelop.org/community/viewtopic.php?f=4&t=10103
