### ISSUE TITLE
Autocomplete and organize imports not working with custom namespaces in AS3

### ISSUE THREAD

**Issue by choephix** [fdorg/flashdevelop#592]
I've recently started defining and using some namespaces in my AS3 project to better control the visibility of my methods, but the IDE seems a bit surprised at my decision :smiley:
Autocomplete does not find methods and variables my class should see (the app builds without errors) and if I use "organize imports" (which I do as often as "ctrl+s", it's a beautiful feature! :stuck_out_tongue_winking_eye:) it deletes the imports of my namespaces as well.

Is this a known bug, or should I not use my own namespaces any way (few people seem to do, which makes me wonder if there's a reason beyond the IDE)

**Comment by gene-pavlovsky** [comment]
I noticed the same problem. Particularly, if I have
```
package com.something {
	import com.something.smth_internal;
	
	use namespace smth_internal;
```
And I use ``reorganize imports``, the import line gets deleted.

**Comment by gene-pavlovsky** [comment]
Hey,, cool job :)
