### ISSUE TITLE
Fold incorrect in Javascript

### ISSUE THREAD

**Issue by WORMSS** [fdorg/flashdevelop#593]
FD: 4.7.1, Windows 8.1 64bit

````javascript
var config = {
	'prop1': {
		"stuff1": "stuff1",
		//{ }
		"stuff2": "stuff2",
		//{ }
		"stuff3": "stuff3",
	}
	'prop2': {
		"stuff4": "stuff4",
		//{ }
		"stuff5": "stuff5",
		//{ }
		"stuff6": "stuff6",
	}
}
````

If you try and fold at **'prop1'** then it folds everything.
I have worked it out to be the **//{}** (as demonstrated by my cut down file).

Matching Bracket works correctly by highlighting the correct **{** and **}**, but if you were to paste this into FD, you will see it adds a [-] next to the comments and incorrectly folders **'prop2'** into **'prop1'**

- Colin.

PS, just found out by accident, if you change **//{** into **// {** (note the space) then it folds correctly.

**Comment by WORMSS** [comment]
PS, just found out by accident, if you change **//{** into **// {** (note the space) then it folds correctly.

**Comment by Meychi** [comment]
//{ is a special folding marker in Scintilla and with this complex object and folding marker setup it gets confused. This is an issue with the Scintilla component, new sci versions should fix this.
