### ISSUE TITLE
DebugMenu.Continue keyboard shortcut is missing 

### ISSUE THREAD

**Issue by 62316e** [fdorg/flashdevelop#595]
In AS3 i've used to press F5 to continue.
In have it just runs new build process.

The problem is that i cant find "DebugMenu.Continue" shortcut in keyboard preferences.

AS3:
F5 works as Continue

Haxe:
Starts new build process

Both languages shall work as expected - run new build process.

Please add "DebugMenu.Continue" shortcut.

**Comment by elsassph** [comment]
The shortcut is called `DebugMenu.Start`
