### ISSUE TITLE
<T> autocompletetion unexpected behavior

### ISSUE THREAD

**Issue by 62316e** [fdorg/flashdevelop#596]
How to reproduce:
1. Type "var a:Array<Int> = new .." in haxe or "Vector<T>" in AS3
2. Press [SPACE][ENTER]
3. Auto Completetion Window appears which shows random items not related to left-side type.

Expected results:
AutoCompletetion shall auto type "new Array<Int>(); or Vector<Int>

**Comment by SlavaRa** [comment]
Now all ok
