### ISSUE TITLE
Tasks panel update

### ISSUE THREAD

**Issue by markknol** [fdorg/flashdevelop#597]
It would be nice when you start flashdevelop or open/switch a project, it will refresh the tasks panel. It would be nicer if it keeps up-to-date, now I manually have to refresh.

**Comment by Meychi** [comment]
There is a setting to make it update automatically, it's on manual by default. Atm it updates only the opened files or when user hits refresh.

**Comment by markknol** [comment]
Ah, is that the "complete" mode setting?
May I ask why it isn't enabled by default?

**Comment by Meychi** [comment]
Sorry, i forgot to respond. The setting is not enabled by default as it constantly monitors the files and cause file reads even if you don't use it at all. This might cause issues to some for example when working under virtualization or with a slow HDD.

**Comment by markknol** [comment]
Thanks! :smile:
