### ISSUE TITLE
Haxe Java / C# Project

### ISSUE THREAD

**Issue by markknol** [fdorg/flashdevelop#598]
1. Would it be possible to add a Haxe Java and C# project template? 
2. I created a new haxe project, selected java as target.Now a bizar thing happens. I used `java -jar bin/Main.jar` as _run custom command_. That doesn't work (cannot find file). When I put it in post-build, I get the same error. When I start a cmd from Flashdevelop I get this same error. BUT when i open a cmd from windows (outside Flashdevelop) I can perfectly run `java -jar bin/Main.jar`.  How is that possible? I cannot run java from flashdevelop?

**Comment by Meychi** [comment]
1. I think we could do that for FD5, would you like to contribute them?
2. Syntax for run custom command is: app;args so i think you should put that as: java;-jar bin/Main.jar. Its using FD internal functionality, therefore the format but we could check if we could support both formats.

**Comment by markknol** [comment]
1. Yes, maybe
2. For me it looks like somehow it does not see what java is when I attempt to run it, no matter the syntax.

**Comment by Meychi** [comment]
Could you share the project so i could check it?

**Comment by elsassph** [comment]
The path to java.exe must be absolute. Maybe we can add an argument to use FD's resolved path to Java.exe.

**Comment by waneck** [comment]
I've seen this problem as well. It seems that flashdevelop doesn't use the whole system `PATH` somehow.

**Comment by elsassph** [comment]
That's because we don't use "shell execution" but run a specific executable to create the process. There are technical reasons for that.

One possibility would be to reproduce what the shell does in terms of resolving the absolute executable path from the PATH. That may even be quite a nice improvement to our RunProcess command and it would simplify quite a few things.

**Comment by mikicho** [comment]
I shared 2 templates for Haxe C#(Exe and Dll) in FD forum.
http://www.flashdevelop.org/community/viewtopic.php?f=20&t=12187
Hope that will help you.

**Comment by markknol** [comment]
We have it now, ill close it.
