### ISSUE TITLE
Add "Escape String" command to scintilla

### ISSUE THREAD

**Issue by hgupta9** [fdorg/flashdevelop#601]
How often have you manually escaped a string? (ie. changed the "\" to "\\" so it compiles OK?). I am requesting a command, to be added to the scintilla context menu, for "Escape String".

Here is the code to perform the actual escaping, can this please be added as a command into FD4?

	// List of escape sequences
	private static string[] CS_EscapeSequences = new string[] { "\aa", "\bb", "\ff", "\nn", "\rr", "\tt", "\vv", "\"\"", "\\\\", "??", "\00" };

	private static char[] CS_EscapeTable;

	private static bool EscapeCSInited = false;

	
	/// <summary>
	/// Convert the string to the escaped string literal
	/// </summary>
	public static string EscapeString(this string str) {

		if (EscapeCSInited == false) {
			EscapeCSInited = true;
			CS_EscapeTable = new char[256];
			foreach (string escape in CS_EscapeSequences) {
				CS_EscapeTable[escape[0]] = escape[1];
			}
		}

		if (str == null) return "null";

		StringBuilder sb = new StringBuilder(str.Length + 2);

		for (int rp = 0; rp < str.Length; rp++) {
			char c = str[rp];

			// if it is an escape char
			if (c <= 255 && CS_EscapeTable[c] != '\0') {

				// ASCII escaped character
				sb.Append('\\').Append(CS_EscapeTable[c]);

			} else {

				// ASCII printable character
				sb.Append(c);

			}
		}

		return sb.ToString();
	}

**Comment by elsassph** [comment]
Use a C# macro!
http://www.flashdevelop.org/community/viewtopic.php?f=20&t=5846&p=53209#p53209

**Comment by hgupta9** [comment]
Thanks for the macro tutorial. I'll use that, but I still think it will be useful for everyone. Consider adding it into the main codebase.

**Comment by elsassph** [comment]
Reopening for @Meychi consideration.

**Comment by hgupta9** [comment]
Thank you!!

**Comment by Meychi** [comment]
Macro is easily shareable and i think this is not so common task.
