### ISSUE TITLE
Haxe call argument completion blocks spacebar

### ISSUE THREAD

**Issue by Simn** [fdorg/flashdevelop#604]
This is a bit wonky to reproduce and usually happens to me in larger files. Right now I'm working on this line with the cursor being at the end:

```
return untyped (o : IHxObject).__hx_getField(field,
```

The problem is that upon pressing spacebar, FD's console tells me "Error: Display file was not found in class path" but doesn't actually advance the cursor.

**Comment by elsassph** [comment]
Maybe something related to this new-ish casting syntax (`o : IHxObject`)...
With this exact line of code I get a Haxe compiler completion error, which should certainly not happen at all here.

**Comment by elsassph** [comment]
Ah no actually the compiler is invoked to get the parameters of the `__hx_getField` function. Also the cursor advances for me.

**Comment by Simn** [comment]
Yeah I can't figure out the exact circumstances for this to happen.Sometimes it works, sometimes it doesn't. I'll try to find a file where it can be reliably reproduced.

**Comment by Simn** [comment]
This file should do: https://gist.github.com/Simn/d7e836971513bcaec201

Drop it to someplace that is not in the class path of your current project, then move the cursor to the end of line 33 and press spacebar.

**Comment by elsassph** [comment]
Doesn't happen for me with latest haxe nightly and java target. I had to replace `IHxObject` with some existing class however.

**Comment by Simn** [comment]
I experimented with the settings, try setting "Strip Trailing Spaces" to True.

**Comment by elsassph** [comment]
Oh that would be it! FD has to save the file to provide haxe completion - and that's going to be tricky to work around as we're doing a "save all" blindly. Th

**Comment by Simn** [comment]
But why does it only fail if the Haxe completion fails?

**Comment by elsassph** [comment]
That may be because this result is cached. If the compiler was successfully called `(` it won't be called again after `,` if you write everything in one go.

**Comment by Simn** [comment]
But it also works if I restart FD and get completion after the comma.

```
class Main {
	static function main() {
		call("foo",
	}

	static function call(s:String, s2:String) { }
}
```

If I open that file, place the cursor after the comma and press space everything works just fine. If I remove the `call` function and do the same the space is eaten.

**Comment by elsassph** [comment]
In that case FD doesn't even call Haxe completion because it can resolve the function with enough certainty - so saving the file doesn't happen.

**Comment by Simn** [comment]
Come to think of it, why does completion trigger at all upon pressing spacebar? It should be sufficient to run it on `(` and `,` which covers all argument cases.

**Comment by elsassph** [comment]
That's because FD shows the call tip if you press space after a coma in a function call: that's a "smart trigger". But if the function wasn't resolved previously, FD will need to resolve it.

**Comment by SlavaRa** [comment]
Actually?
