### ISSUE TITLE
Auto Complete for custom events with event metadata

### ISSUE THREAD

**Issue by merrazquin** [fdorg/flashdevelop#606]
**Issue:**
Instead of listing a custom event, auto complete offers up the string value of the event's constant.

**Steps to replicate: **
1. Create a custom class that dispatches a custom event
2. Add the correct event metadata for the custom events to the custom class
3. Build a SWC including the custom class/event including ASDocs
4. Add the SWC to a project's library
5. Attempt to list the custom events via auto complete on addEventListener

**Custom Event:**
```actionscript
public static const POLLER_UPDATED:String = "pollerUpdated";
public static const POLLER_ERROR:String = "pollerError";
```
**Event metadata:**
```actionscript
/**
 * mm.utils.load.PollerEvent.POLLER_UPDATED
 * @eventType mm.utils.load.PollerEvent
 */
[Event(name = "pollerUpdated", type = "mm.utils.load.PollerEvent")]
/**
 * mm.utils.load.PollerEvent.POLLER_ERROR
 * @eventType mm.utils.load.PollerEvent
 */
[Event(name="pollerError", type="mm.utils.load.PollerEvent")]
```
**Auto complete:**
![Auto complete](http://i.gyazo.com/dc59adfba58bb1060f8c4cf362e3d3bb.png)

Github doesn't support attaching SWCs, so here's a link to the sample SWC on google drive: https://drive.google.com/file/d/0B-E-NS9ouP-ANExTd0dleHJ1QkU/view?usp=sharing (need to click the download button because Google Drive recognizes the file as an archive).

**Comment by elsassph** [comment]
I found the reason: that's complicated :)

The comment before the metadata isn't used in fact, the important information is the `POLLER_ERROR` const's value. The bug is that the value isn't extracted from the doc unless it has a doc comment.

The solution for now is to comment your consts:

    /** Poller error event */
    public static const POLLER_ERROR:String = "pollerError";

**Comment by merrazquin** [comment]
The work around of commenting the consts worked perfectly. Thank you for you fast response!
