### ISSUE TITLE
Add snippets for "for" loops

### ISSUE THREAD

**Issue by hgupta9** [fdorg/flashdevelop#612]
Can you add these named snippets for `for` loops? I've created versions for A-Z and forward and reverse loops.

Say you need to loop through an array of points, you can type `forp` to give this:

    for (var p:int = 0, pl:int = ?.length; p < pl; p++) {
    }

These have been optimized for speed, notice how we cache the length into `pl`, this is faster in AS3 than accessing length each time.

There are also versions for looping through an array backwards.

https://app.box.com/s/9th0asbh7kk19v7xusyxlihha7moj39q

**Comment by elsassph** [comment]
Use the  snippet editor to create new snippets.

**Comment by hgupta9** [comment]
Of course. Thats how I created these. I'm asking that you add into the repo for other FD5 users, since these are very useful snippets and saves a lot of time. Consider adding into the repo.

**Comment by elsassph** [comment]
You should share that in the forum, we prefer not adding snippets.
