### ISSUE TITLE
Add snippets for common var and property types

### ISSUE THREAD

**Issue by hgupta9** [fdorg/flashdevelop#613]
I've created useful snippets for `var` and properties (getter/setter). Say you need to add an integer property, just type `prop_int` to give this:

	public function get ():int {
	}
	public function set (value:int):void {
	}

Similarly, `var_int` is useful for local vars, and gives this:

	var :int = 0;

https://app.box.com/s/9dk6cjle3nglfl7iu8bag8tsw17hjoee

**Comment by hgupta9** [comment]
Consider adding into the repo for other FD5 users, since these are very useful snippets and saves a lot of time. I am already using them.

**Comment by elsassph** [comment]
Thanks but no. People who like snippets just create theirs.
