### ISSUE TITLE
java8 flashdevelop and jpexs

### ISSUE THREAD

**Issue by matrix3d** [fdorg/flashdevelop#620]
the jpexs is a flash tool need java8.
and Registry key 'Software\JavaSoft\Java Runtime Environment\CurrentVersion'
has value '1.8', but '1.6' is required.
Error: could not find java.dll
Error: could not find Java SE Runtime Environment.

**Comment by Neverbirth** [comment]
I've seen some people run into this error because they didn't have the JAVA_HOME environment variable correctly set.
