### ISSUE TITLE
FlashViewer -> External player path

### ISSUE THREAD

**Issue by ryzed** [fdorg/flashdevelop#621]
After updating to new build value resets to default (empty string).

**Comment by Meychi** [comment]
FlashDevelop will reset the path if the previous exe can not be found. Is it still present? Also it might be that when FlashDevelop restarts again it redetects the exe again.

**Comment by ryzed** [comment]
Yes, exe still present.
No, it clears after reinstalling.

Checked now:
1. Set path.
2. Reinstall (just run setup (4.7.2 release) over existing installation).
3. Checked path - it empty.
4. Restarted FlashDevelop.
5. Check path - still empty.

**Comment by Meychi** [comment]
Where do you have the exe? Is it downloaded with appman or manually?

**Comment by ryzed** [comment]
Downloaded from site: http://www.flashdevelop.org/community/viewtopic.php?f=11&t=12165
Direct link - http://www.flashdevelop.org/downloads/releases/FlashDevelop-4.7.2.exe

**Comment by Meychi** [comment]
No, i meant the FP exe? Where do you have it located?

**Comment by ryzed** [comment]
![image](https://cloud.githubusercontent.com/assets/1711255/6664777/1a4724d6-cbec-11e4-9a8a-a8bd3bdf7e3c.png)
Downloaded from adobe site (https://www.adobe.com/support/flashplayer/downloads.html)
I have some versions of players (16, 17) for testing.

**Comment by Meychi** [comment]
Ah, FlashDevelop tries to be smart and redetect the path from appman directories. You need to set the Disable Auto-Configure = true to keep the path and stop FlashDevelop from redetecting.

**Comment by Meychi** [comment]
I will improve it so that if the path is valid and no other FP is found, it keeps the path intact.
