### ISSUE TITLE
Trim trailing spaces

### ISSUE THREAD

**Issue by deepnight** [fdorg/flashdevelop#623]
This option doesn't work anymore in FD5 : 
Settings > CodeFormatter -> Trim Trailing Whitespace (TRUE)

**Comment by Meychi** [comment]
How it doesn't work? I set it to true and ran the Code Formatter and it did remove added spaces and tabs from end of comment and code lines.

**Comment by deepnight** [comment]
Hi,

There used to be an option that allowed Trimming Spaces upon saving, and I thought it was this one.
The real option is actually name "strip trailing spaces" in Settings > FlashDev (which is a bit confusing as it does the same thing).

Not exactly an issue, except the option name itself :)

**Comment by Meychi** [comment]
There few other settings overlapping there but i think its good to have separate settings for code formatter. Like if you need to temporarily format code differently from your own code.

**Comment by Gama11** [comment]
The issue isn't so much having two different settings for this, but that their names / descriptions are so similar that it's unclear what the difference is.

**Comment by Meychi** [comment]
Very true, renamed FD setting to match CodeFormatter setting which is better.
