### ISSUE TITLE
FProt Antivirus

### ISSUE THREAD

**Issue by deepnight** [fdorg/flashdevelop#624]
In FD5, the file "fdbuild.exe" is now detected as a potential virus by F-Prot Antivirus.

**Comment by Neverbirth** [comment]
What I do in these situations is write to the antivirus people, they should have a false reports contact address.

Being a .NET application, it can be decompiled easily and should closely match the source in the repository.

I compiled the current FDBuild, and I seriously doubt it has any malicious code in it.

**Comment by Meychi** [comment]
I rebuilt the binary, please check if the new build (5.0.0.10+) still flags as virus.

**Comment by deepnight** [comment]
Thanks, I will check it tonight.

**Comment by Meychi** [comment]
I checked with http://virusscan.jotti.org/en with all their scanners and only CYREN and F-PROT (same corp) gave positive for adware. Sent them a report of incorrect detection with a link to source code. Not much what we can do more here.

**Comment by Meychi** [comment]
Got a response from them that it was an invalid detection and should be ok now.
