### ISSUE TITLE
can not see break point

### ISSUE THREAD

**Issue by matrix3d** [fdorg/flashdevelop#626]
![dd225607-0a3c-42c1-95d1-dc8d4270c7da](https://cloud.githubusercontent.com/assets/4150631/6704229/d3123e16-cd80-11e4-8339-c699bf573791.png)

**Comment by Meychi** [comment]
What are you DPI settings and what font size do you use?

**Comment by matrix3d** [comment]
set font size 22

**Comment by Meychi** [comment]
Did this work correctly in FD4?

**Comment by Meychi** [comment]
No it did not. These areas are scaled based on your DPI settings in FD5. I need to check if i can somehow scale this also with font size.
