### ISSUE TITLE
Automatically Remember syntax coloring association

### ISSUE THREAD

**Issue by delahee** [fdorg/flashdevelop#627]
For example, my .hxt files are actually regular xml. I think any user would benefit that when they switch one .xml alike file, all other files from the same extensions gets colored the same way.

This way when i switche my .hxt  to xml syntax coloring once, it gets retained for all my .hxt.

This would change my experience forever :)

**Comment by Gama11** [comment]
Perhaps a second drop-down with "Open all with current extension as..."  like in Sublime Text would make sense here:

![](http://i.imgur.com/eqFk4QS.png)

Otherwise, you wouldn't have the option to only temporarily change syntax coloring (if I understood your suggestion correctly).

**Comment by delahee** [comment]
the suggestion was simpler, when we change the syntax on a given *.truc file a popup ask us if we want all *.truc files colored the same way. 

You suggestion could to too as well to meet the same goal.

**Comment by Meychi** [comment]
I think a dialog would be good and then add it to the syntax config file, tagging for future.

**Comment by Gama11** [comment]
Implemented in #636. :)

**Comment by delahee** [comment]
Cool :)
