### ISSUE TITLE
GOTO (CTRL+G) caret positionning

### ISSUE THREAD

**Issue by delahee** [fdorg/flashdevelop#628]
when taping CTRL+G ( which i do often), i would like the caret to be placed automagically at the first non space, non tab caracter rather than at being of line,

This would save me (and hardcore debuggers that use CTRL+G a lot )  a large number of stroke each day.
Thanks.

**Comment by Gama11** [comment]
Makes sense, Visual Studio does it that way.

**Comment by Neverbirth** [comment]
Just a comment about the large number of strokes, you can press Ctrl+Right.

**Comment by delahee** [comment]
@Neverbirth cool !

**Comment by Meychi** [comment]
Do you mean goto dialog should do that or gotoline in Scintilla editor should do that?

**Comment by delahee** [comment]
@meychi, I am scintilla editor agnostic...so I let you handle the way to go :)
