### ISSUE TITLE
syntax coloring HTML

### ISSUE THREAD

**Issue by delahee** [fdorg/flashdevelop#629]
Should also color inline css blocks..
```
<style>
.sheet{
	width: 300vpxi;
	height: 360vpxi;
	background-color:transparent;
	border:2px solid gray;
	padding:5vpxi;
	layout:vertical;
}
</style>
```
should have css coloring inside the style tags,

thanks !

**Comment by Gama11** [comment]
I don't think Scintilla's HTML lexer supports this. There's been [an open issue](http://sourceforge.net/p/scintilla/bugs/341/) about it since 2005.

**Comment by Neverbirth** [comment]
This could be more or less solved by FD, like with MXML, in that if you are inside the style block the syntax is changed. But this would require a new dedicated plugin (or at least some code) to HTML.

BTW, just wanted to say that the default CSS syntax coloring is as ugly as a sin heh.

**Comment by Meychi** [comment]
I don't see us implementing this but i hope this will eventually come from Scintilla.
