### ISSUE TITLE
[haxe][openfl] Changing project Pre-Build step

### ISSUE THREAD

**Issue by void616** [fdorg/flashdevelop#633]
Pre-Build field content could not be changed. It's returns to default value
"$(CompilerPath)/haxelib" run lime build "$(OutputFile)" $(TargetBuild) -$(BuildConfig) -Dfdb

![123123](https://cloud.githubusercontent.com/assets/10888589/6786167/9ab0b916-d19b-11e4-9a69-93946b0a79b7.png)

**Comment by elsassph** [comment]
That's by design now - the build command for 3rd party build tools is now injected as the build action. It currently isn't possible to add your own command.
We can probably fix it by not overwriting the command if the required command is present...

**Comment by void616** [comment]
It would be a very handy feature. Thanks

**Comment by elsassph** [comment]
Another possibility may be to reserve the post-build step.

**Comment by void616** [comment]
In my case I really need to preprocess resources (for various platforms) before the build started.

**Comment by itzikiap** [comment]
It makes no sense if the build command is hard coded in the "pre build" section. 
Maybe there should be another field for "build" between the pre and post build...

**Comment by elsassph** [comment]
Solved in latest dev build: pre-build command is set only if the command is empty.
