### ISSUE TITLE
Option to show static function icons in pink

### ISSUE THREAD

**Issue by hgupta9** [fdorg/flashdevelop#652]
This is regarding the intellisense listing.
Icon for static function is too similar to static vars. Its very confusing.
As you can see here:

![fd func icon](https://cloud.githubusercontent.com/assets/6797866/6992882/1e2ea746-daff-11e4-8ee1-55c6a229fd2b.png)

Provide an option in fd5 to show static functions in pink (like it was before).

**Comment by Meychi** [comment]
Pink is now only for instance methods. These two icons are similar in colour on purpose. The icons themselves are different.

**Comment by hgupta9** [comment]
I need an option for this!!! Why do you just close an issue when its so simple to add an option for it???

**Comment by Meychi** [comment]
To your question why:

1. We can not satisfy all request from all users.
2. You request a setting for incorrect behaviour.
3. The setting needs to be added to 4 files, including public PluginCore API
4. The setting needs to be localized and maintained in multiple languages.

If you really want to change this, source code is open and C# scripts are available.

**Comment by Gama11** [comment]
I can distuingish the colors of the static var icon and the static function icon pretty easily, but I guess colorblind people might have issues with it?

**Comment by Meychi** [comment]
If you are thinking of red, shouldn't pink have the same issue? Again its still against the functionality to have it as pink.

**Comment by hgupta9** [comment]
Yes at least red would be similar to pink, that would be great compared to yellow.

When I'm looking at my code I don't really care if its static or dynamic, all I need to check is if its a var (getter/setter) or a function (I can call it).

My brain works like that. If I confuse vars with functions, then I don't know if I should set it or call it.

**Comment by Meychi** [comment]
Even if the colors might be near for you the icons are different. They are to opposing directions and methods with speed lines.

Could this be due to high screen brightness or color calibration as i can see them way better than on your images? I'm running on 100% text scaling with DimGray theme.

![screen](https://cloud.githubusercontent.com/assets/2213937/7077673/78b9a768-df1b-11e4-92d3-1b4479c52a16.png)

**Comment by elsassph** [comment]
I agree that static vars and functions should have a more distinct different color, but we want to differentiate static and instance members.

**Comment by Meychi** [comment]
I'm ok with that, should we try to push the orange to pop out more or totally different color? Red might be too close to pink imho.

**Comment by hgupta9** [comment]
Keep static vars yellow is fine, but static funcs should be red or pink.
Visual Studio has NO differentiation between static and instance members, in intellisense menus.

Visual Studio 2010:
![vs2010_intellisense_a](https://cloud.githubusercontent.com/assets/6797866/7083356/58da5b14-df7e-11e4-99ce-a0ceec337453.png)
![vs2010_intellisense_b](https://cloud.githubusercontent.com/assets/6797866/7083357/5aef5e54-df7e-11e4-961b-44d88b982d24.png)

Visual Studio 2012:
![vs2012_intellisense](https://cloud.githubusercontent.com/assets/6797866/7083355/55606ece-df7e-11e4-878e-cbb28c002c99.png)

**Comment by Meychi** [comment]
Static variable icons now have more contrast to separate better from the yellow.

**Comment by hgupta9** [comment]
Why cant you just keep it like Visual Studio? Pink and Blue .. its so easy and clean.
Anyways attach a screenshot at least.

**Comment by elsassph** [comment]
We actually like to have different colors :) Maybe we could make it possible to hack them... If they were added to the icons map you could change the images.
