### ISSUE TITLE
Breakpoints can lead to path too long exception

### ISSUE THREAD

**Issue by larsiusprime** [fdorg/flashdevelop#655]
As mentioned here:
http://www.flashdevelop.org/community/viewtopic.php?f=6&t=12191

Recently I started up FlashDevelop and got this bug:

```
The specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, and the directory name must be less than 248 characters.

   at System.IO.Path.SafeSetStackPointerValue(Char* buffer, Int32 index, Char value)
   at System.IO.Path.NormalizePathFast(String path, Boolean fullCheck)
   at System.IO.Path.NormalizePath(String path, Boolean fullCheck)
   at System.IO.Path.GetFullPathInternal(String path)
   at System.IO.Path.GetFullPath(String path)
   at ProjectManager.Projects.ProjectPaths.GetAbsolutePath(String baseDirectory, String path)
   at ProjectManager.Projects.Project.GetAbsolutePath(String path)
   at FlashDebugger.BreakPointManager.Load()
   at FlashDebugger.PluginMain.HandleEvent(Object sender, NotifyEvent e, HandlingPriority prority)
   at PluginCore.Managers.EventManager.DispatchEvent(Object sender, NotifyEvent e)
```

Which was weird because it used to be fine; I hadn't just installed a new version or done anything weird. At first I though my project might have recently added really long, deeply nested folders or something, so I even ran Path Length Checker to be sure. I was well within the safe margins for everything.

But I knew the bug was caused by a file path somewhere being too long or else malformed. 

Looking through the stack I noticed it was the breakpoint manager. So I dug up the location of the breakpoints data in the settings, which turned out to be:

```
C:\Users\YOUR_USER_NAME\AppData\Local\FlashDevelop\Data\FlashDebugger\Breakpoints\
```

And deleted all the xml files. Now when I start up FlashDevelop it works perfectly!

I wish I would have saved some of those xml files, but even so I can almost certainly guess the issue is that I put breakpoints in some weird obscure places that ultimately generated fully resolved file paths that were too long for FD to handle.

**Comment by Meychi** [comment]
Do you still happen to have the breakpoint files? It would help us to fix the issue if we could see the bad path.

**Comment by larsiusprime** [comment]
I really wish I did, unfortunately I deleted them from the recycle bin before I created this bug report, and immediately regretted it. I might be able to regenerate the scenario, and if so I will post the files.

**Comment by elsassph** [comment]
My guess is that we somehow end up with a path with a lot of `/../` in it, and when it is recomposed with the project directory to rebuild an absolute path it then gives a path over 260 chars and that causes an exception.

**Comment by gamicklisafisher** [comment]
For deletion or handling of long name i check that "Long Path Tool" software should be try, many articles refer this for such solutions.
