### ISSUE TITLE
[haxe] Consider adding "from" and "to" to keyword or word3 group

### ISSUE THREAD

**Issue by YellowAfterlife** [fdorg/flashdevelop#661]
These can be used in definitions of [abstract types](http://haxe.org/manual/types-abstract-implicit-casts.html), most commonly like so:
```haxe
abstract AbstractName(BaseType) from BaseType to BaseType {
    // ...
}
```

**Comment by Gama11** [comment]
Probably not gonna happen, the Scintilla Lexer's keywords aren't contextual, and you wouldn't want these highlighted elsewhere in your code (similar to get / set / never in property declarations).

**Comment by Meychi** [comment]
I agree with @Gama11, would be great to have a dedicated lexer for Haxe in Scintilla.
