### ISSUE TITLE
Catch Leave Event

### ISSUE THREAD

**Issue by mikicho** [fdorg/flashdevelop#665]
Hi,
I'm working on http://www.flashdevelop.org/community/viewtopic.php?f=4&t=12200 this plugin and I want that UI will change when the plugin get and lose focus so I trying to catch a "Leave" Event with(this line place in PluginMain.cs):
this.pluginPanel.Leave += new EventHandler(pluginUI.PluginUI_Leave);
But this event dispatch only when I click on other plugin of FD (output panel, file explorer, bookmarks etc..) and not if the focus back to scintila(the code editor).
I know it's possible because the title color change to blue when the panel's plugin got focus and back to gray when focus lost.
How I can listen to "lost focus" Event?
Thanks a lot!
Miki
p.s: I try also: this.pluginPanel.LostFocus+= new EventHandler(pluginUI.PluginUI_Leave);

**Comment by Meychi** [comment]
We are doing some custom focusing and Scintilla is a Win32 control which might affect things but you can use DockPanel events for this:

```csharp
PluginBase.MainForm.DockPanel.ActiveContentChanged += DockPanel_ActiveContentChanged;`

void DockPanel_ActiveContentChanged(object sender, EventArgs e)
{
    if (PluginBase.MainForm.DockPanel.ActiveContent == this.pluginPanel) TraceManager.Add("Enter");
    else TraceManager.Add("Leave");
}
```
