### ISSUE TITLE
Autocomplete bug

### ISSUE THREAD

**Issue by nomikovsupe** [fdorg/flashdevelop#666]
FD version 4.7.2.8

Sometimes autocomplete don't show variables and methods of ancestors.

For example
```
    Car extends EventDispatcher
    Mercedes extends Car
```

then
```
    var m:Mercedes = new Mercedes();
    m.
```
Autocomplete show only properties of Mercedes.

If press F4 on Mercedes, then press F4 on Car, then press F4 on EventDispatcher, then autocomplete start working.

Maybe bug emerge if there are overrided methods in Mercedes.

**Comment by elsassph** [comment]
There are occasional bugs with the classes cache. FD5 will solve that with a new caching engine.

To fix that go Tools > User Application Files... then delete files under Data/ASCompletion/FileCache

**Comment by nomikovsupe** [comment]
ok, thanks for your reply
