### ISSUE TITLE
fd5 {} not auto tab

### ISSUE THREAD

**Issue by matrix3d** [fdorg/flashdevelop#669]
(){
a
}

error
function a():void{
b
}

()
{
       a
}
but this good.

the fd4 is good.but fd5 has the bug.

**Comment by Meychi** [comment]
Sorry, your descriptions are pretty to hard to understand, could you maybe create simple gifs to show the correct behaviour and the bug?

**Comment by matrix3d** [comment]
![rtx](https://cloud.githubusercontent.com/assets/4150631/7175599/142534d8-e449-11e4-9544-3dcb4ac34833.png)

sorry ,i do not speak english.it is the image can use?

**Comment by matrix3d** [comment]
in the image.the end line of "a".
not have the tab

**Comment by matrix3d** [comment]
? not body find this bug?

**Comment by elsassph** [comment]
Doesn't happen to me with FD5 dev.

**Comment by matrix3d** [comment]
@elsassph 
![test](https://cloud.githubusercontent.com/assets/4150631/7804576/85d89abc-0397-11e5-9252-35b0838d2da5.gif)

it is a gif ,pls try.i have bad english.

**Comment by matrix3d** [comment]
just test the gif
