### ISSUE TITLE
Porting FlashDevelop to Linux and MacOS X?

### ISSUE THREAD

**Issue by tesfabpel** [fdorg/flashdevelop#677]
I've tried compiling the FlashDevelop 4.7.2 and it worked (after renaming Strings.resX to Strings.resx in PluginCore/DockPanelSuite/Strings.resx, and by deleting the .rev extension in FlashDevelop/Properties/AssemblyInfo.cs.rev)...

Sadly it did not run since it uses some native methods in the class WeifenLuo.WinFormsUI.Docking.NativeMethods.

Please consider porting FlashDevelop to Linux and MacOS X, if there is enough interest in this...
Thanks! :)

Build successful
![screen](https://cloud.githubusercontent.com/assets/1371976/7339278/a1122432-ec69-11e4-8a06-f318e71e5f77.png)

**Comment by Neverbirth** [comment]
The Dock Panel Suite is the least of the problems, in fact you can get it running on Mono without much problem. The actual headache is getting Scintilla to work.

**Comment by Neverbirth** [comment]
Also, forgot to say. You can get FD working on Linux/Mac using CrossOver: https://www.youtube.com/watch?v=lZOfBnmetVs

Compatibility for it is improving constantly.

**Comment by RUSshy** [comment]
Wine is not solution when a project is still maintained, better to put effort on porting instead of trying to use hack
Just my opinion
