### ISSUE TITLE
ASCompletion explicit scope - broken

### ISSUE THREAD

**Issue by gene-pavlovsky** [fdorg/flashdevelop#678]
ASCompletion: Generate explicit scope is set to True.
Using "Promote to class member" on button, result is:
button = new Button();
instead of this.button

Using "Generate Event handler" code generator, result is
      private function onAddedToStage(e:Event):void {
         removeEventListener(Event.ADDED_TO_STAGE, onAddedToStage);
Expected this.removeEventListener(Event.ADDED_TO_STAGE, onAddedToStage);

http://www.flashdevelop.org/community/viewtopic.php?f=6&t=12180

**Comment by SlavaRa** [comment]
WIP https://github.com/SlavaRa/flashdevelop/tree/feature/678
