### ISSUE TITLE
[loom] FlashDevelop often locks the "Feathers.loomlib" file

### ISSUE THREAD

**Issue by SmilyOrg** [fdorg/flashdevelop#684]
This is not a major issue, but it's somewhat annoying while actively working on the SDK. When deploying a new version, the dev sdk directory gets deleted / overwritten and that gets blocked (the deployment fails at the end) by FD locking the above file for seemingly the entire session. Closing FD, deploying the SDK and reopening fixes it.

It's not a huge deal, so I can try looking at it later on when I have the time, but any immediate ideas would be welcome. I'm on 4.7.1.1, but I think this issue has existed for a while. Not sure if there was any additional work in FD5 (I haven't tested it yet), but I thought it would be nice to document this behavior at least.

**Comment by elsassph** [comment]
The issue is that FD is monitoring the .loomlib files.
I could disable the watcher, in which case you would have to restart FD to reload these libs - is that better?

**Comment by SmilyOrg** [comment]
That might be better, but even better might be if there was a way to monitor loomlib files and still allow for them to be deleted and recreated. I don't know how easily achievable that is though.
