### ISSUE TITLE
Feature request: Close others in "group"

### ISSUE THREAD

**Issue by Simn** [fdorg/flashdevelop#687]
Not sure what exactly to call it, but I'm talking about this situation:

![fd_close_others_in_split](https://cloud.githubusercontent.com/assets/634365/7675496/60fe5bc8-fd39-11e4-9bda-cdeaed97d75a.png)

Could we have an additional option to only close tabs in the current split?

**Comment by Gama11** [comment]
Maybe "close others" / "close all" should only apply to the current split in the first place? That's how it works in Ecilpse, seems more intuitive to me.
