### ISSUE TITLE
[Haxe] Error: No completion point was found

### ISSUE THREAD

**Issue by daisuda** [fdorg/flashdevelop#689]
I reproduce it in my project. I hope someone can fix it.

First install edge:
haxelib install edge
Then past it into a new class
```
package;

import edge.ISystem;

class TestSystem implements ISystem
{
	public function new() 
	{
		
	}
	
	public function update():Void
	{
		this.| // Error: No completion point was found
	}
	
}
```
( Make soure haxe compile it )

And I try to narrow down the problem, maybe around in edge's source code:
`f.expr = macro $b{exprs};`
https://github.com/fponticelli/edge/blob/master/src/edge/core/macro/BuildSystem.hx#L94

**Comment by MSGhero** [comment]
This happens all the time. Every time you add `(default, null)` or `cast(a, b)`, haxe says that and FD displays it.

**Comment by elsassph** [comment]
I can reproduce the error but there isn't anything particular in the completion call so you should report that to @fponticelli maybe

**Comment by fponticelli** [comment]
Not sure what can I do on my side, suggestions?

**Comment by elsassph** [comment]
@fponticelli does completion work for you in another editor?
