### ISSUE TITLE
 Top level Class autocompletion stopped working

### ISSUE THREAD

**Issue by jean-benoit** [fdorg/flashdevelop#692]
.NET version = v4.0.30319
OS = Win7 Pro SP1

Autocompletion stopped working for top level classes at version 4.6.0. 
( ok versions tested : 4.3.0, 4.4.0, 4.5.0, 4.5.1, 4.5.2, not ok versions tested 4.6.0, 4.7.2, 5)
I compiled a little example :
[download](http://test.eventattitude.com/djib/flashdev/example.zip)

Classes:
Main.as = Document Class
topLevel.as = Top level Class returning a MyCustomClass object
MyCustomClass.as = custom dummy class

Main.as :

    package  
    {    
    	import flash.display.MovieClip;
    	public class Main extends MovieClip 
    	{
    		public function Main() 
    		{
    			topLevel.helloWorld();					// no autocompletion
    			MyCustomClass(topLevel).helloWorld();	// autocompletion
    			// Both works & outputs "hello world"
    		}
    	}
    }

MyCustomClass.as :

    package 
    {
    	public class MyCustomClass 
    	{
    		public function MyCustomClass() 
    		{
    			
    		}
    	
    	    public function helloWorld():void
    	    {
    	    	trace('hello world');
    	    }
        }
    }

topLevel.as :

    package 
    {
    	public function get topLevel():MyCustomClass
    	{
    		return new MyCustomClass();
    	}
    }

If i type "topLevel." i have no autocompleteion,
![screenshot 1](http://test.eventattitude.com/djib/flashdev/sc1.jpg)

if i type "MyCustomClass(topLevel)." i have autocompletion.
![screenshot 2](http://test.eventattitude.com/djib/flashdev/sc2.jpg)

**Comment by elsassph** [comment]
Should be fixed, please test the next dev build.

**Comment by jean-benoit** [comment]
It is fixed. Thanks a lot :)
