### ISSUE TITLE
 Please support Apache Flex - FlexJS

### ISSUE THREAD

**Issue by bigosmallm** [fdorg/flashdevelop#70]
Now that FlexJS is approaching a "near-alpha" state and the technologies it would be great to have support for this new promising technology in Flash Develop. It would bring faster technology development and adoption and fresh air to the myriad of javascript frameworks and technologies that doesn't rely in a robust technology based on a OOP language (AS3) + declarative language (MXML), a compiler, and so on...

Some requirements are shared here that would make the basic set of tools to make an initial and basic roundtrip that allows a developer to create a project, compile it with a FlexJS sdk, and get the output to show in a browser. As well basic language intellisense based on Flex/AS3 already in Flash Develop functionality:

Support add a FlexJS SDK to make it available to the IDE
Support to create a FlexJS boilerplate project.
Some things should be shared with actual Flex plugin (AS3, MXML development), but maybe some revisión should be done to allow new namespaces in FlexJS, and other things that could be tied in actual implementation
Run FlexJS: Support new target to build different outputs: SWF, JS (HTML), JS(HTML5), JS (JQuery)...

There is a master ticket created at Apache Flex's bug tracker here: https://issues.apache.org/jira/browse/FLEX-33937
More detailed info about FlexJS is available here: https://cwiki.apache.org/confluence/display/FLEX/FlexJS

We now have a nightly build of FlexJS that creates the source and binary kits in various formats.

They are available here: https://builds.apache.org/job/flex-asjs/lastSuccessfulBuild/artifact/out/

The ApacheFlexJS.tar.gz and ApacheFlexJS.zip files should contain what you are looking for in terms of a drop in deployment.

**Comment by matrix3d** [comment]
![flexjs](https://cloud.githubusercontent.com/assets/4150631/10839821/230a5586-7f13-11e5-8ec4-bf81315ec3ff.gif)

i have make flexjs work on fd

**Comment by aharui** [comment]
That’s great news.

-Alex

**Comment by matrix3d** [comment]
the bat command line ,
`set FLEX_HOME=d:/sdk/flexjs
set main=Main
start %FLEX_HOME%/js/bin/mxmlc -external-library-path="%FLEX_HOME%\js\libs\js.swc" -compiler.source-path=../src src/%main%.as -remove-circulars -define=CONFIG::as_only,false -define=CONFIG::js_only,true
pause`

**Comment by bigosmallm** [comment]
No longer relevant.
