### ISSUE TITLE
No hint on new Vector<T>

### ISSUE THREAD

**Issue by konsnos** [fdorg/flashdevelop#71]
When I declare a Vector variable and trying to initate it, the hint when I type new directs me to adobe.utils.CustomActions, when it should hint to Vector.

Similar forum post here: http://www.flashdevelop.org/community/viewtopic.php?f=6&t=11386

OS: Win7 x64
FD: 4.5.2.5
Project: AS3 Project

**Comment by wise0704** [comment]
This issue is still present. Not only for `Vector`, but also for other native classes such as `Object`, `String`, `Array`, etc.
