### ISSUE TITLE
Appman: "restart FD" prompt

### ISSUE THREAD

**Issue by Gama11** [fdorg/flashdevelop#712]
It might not be obvious to some users that a plugin is not available right away after installing it / that FD has to be restarted. Typically, there's a prompt that informs the user about this and offers to restart right away.

**Comment by Gama11** [comment]
@Meychi That icon is barely noticable - I only saw it because I was actively looking for it.

Also, how can that icon be visible while `File->Restart` is disabled?

**Comment by Meychi** [comment]
I just put something there, i'm trying to find a better one. The icon can be visible but restart action should be disabled for multi instance mode as restart doesn't work with instances properly.

**Comment by Meychi** [comment]
Improvements done in 30e951c4b3260bc07d30321a8768d3f3d4ebe06e
