### ISSUE TITLE
Custom UI Scheme: the color of command trace() in the Output Panel

### ISSUE THREAD

**Issue by neirogames** [fdorg/flashdevelop#714]
I created custom UI Scheme for FlashDevelop.
How can I change the color of command trace() in the Output Panel?
(The dark UI Scheme background is very good for the eyes)

-Philippe
>>It isn't possible yet but I think Mika's working on it. Please create a github issue to track it.

Forum topic: www.flashdevelop.org/community/viewtopic.php?f=9&t=12226

Thanks!

Screenshot:
![trace](https://cloud.githubusercontent.com/assets/8101101/7833143/07e04dd4-0497-11e5-9994-3390adae2311.jpg)

**Comment by Meychi** [comment]
In FD5, we follow the foreground color of the control, others are static for now, might be improved later.

**Comment by neirogames** [comment]
Thank you for Dark Theme in FD 5 - it's great!
However, can not change color of command trace() in the Output Panel.
Write about it and other users:
http://www.flashdevelop.org/community/viewtopic.php?f=5&t=10098

Please fix it.

Thanks.

**Comment by gene-pavlovsky** [comment]
What is the control name, RichEdit? I would also like to be able to customize the trace colors. Current colors don't work well with my solarized dark theme, either.

**Comment by Meychi** [comment]
Done, in 5.1 new theme settings.

**Comment by neirogames** [comment]
Meychi 
 >>Done, in 5.1 new theme settings.

1. Install Flash Develop 5.0.2
2. Install theme github/flashdevelop/External/Themes/SyntaxThemes/ThyleusTheme - FD UI THEME (5.1+)
3. Change (for example): 
#OutputPanel.InfoColor=#ffffff
#OutputPanel.DebugColor=#000000
#OutputPanel.WarningColor=#ffa500
#OutputPanel.ErrorColor=#ffffff
#OutputPanel.FatalColor=#ff00ff
#OutputPanel.ProcessStartColor=#ff0000
#OutputPanel.ProcessEndColor=ff0000
#OutputPanel.HighlightColor=#ff0000
4. Restart Flash Develop 
5. The panel output - not change (text color)?

What should I do to make the changes take effect?

**Comment by Meychi** [comment]
The settings take effect when you use 5.1 development version. 5.1 is not released yet.
