### ISSUE TITLE
Project Manager: track active document is missing shortcut tooltip

### ISSUE THREAD

**Issue by Gama11** [fdorg/flashdevelop#719]
[The button has a Shift + Alt + L shortcut](https://github.com/fdorg/flashdevelop/blob/baa91f27483faddeb4bb725402ee8b9bdac622ac/External/Plugins/ProjectManager/Controls/TreeBar.cs#L53), but is missing the tooltip description:

![](http://i.imgur.com/bR8XKX9.png)

The problem here is that the `ShortcutHelper` API assumes that "primary" shortcut items are `ToolStripMenuItem` instances and buttons like this one can only be "secondary" shortcut items. In this case though, it'd need to be both.

**Comment by Meychi** [comment]
You can have both :)

**Comment by Gama11** [comment]
Hm, really? I remember I was looking into this a while ago and had some issues with it. Maybe I did something stupid.

**Comment by Meychi** [comment]
Its also used in FDMenus.cs in PM.
