### ISSUE TITLE
Reconsider the "find and replace in files" default shortcut

### ISSUE THREAD

**Issue by Gama11** [fdorg/flashdevelop#726]
There seems to be somewhat of a convention for `Ctrl+Shift+F` across most IDEs / editors. This works in:

- IntelliJ IDEA
- Visual Studio
- Sublime Text
- Notepad++
- SciTE
- Keil μVision

The only ones I have installed where this shortcut doesn't work are Eclipse and FD.

Of course shortcuts are configurable, but at the same time sticking to conventions makes life a lot easier for users. Also, the shortcut makes more sense semantically (Ctrl+F being a search in the current file, Ctrl+Shift+F across all project files).

**Comment by Meychi** [comment]
I'm ok with this, @elsassph?

**Comment by elsassph** [comment]
Yeah I don't mind. It always annoys me to have to look for Find in Files in the menus in ST or IntelliJ when I help a coworker...
What do you do about the current binding of Ctrl+Shift+F? Folding I guess it's not very useful anyway.

**Comment by Gama11** [comment]
Either remove it, or just swap the shortcuts? Both options might confuse users that are used to the shortcuts.

**Comment by elsassph** [comment]
Swapping would be a bad idea :D

**Comment by Meychi** [comment]
Hmm... more i think of this i think we should keep the default and not confuse existing users.

As said, its customizable but i think we should offer sets of shortcuts similar fashion to UI themes. We should produce at minimal two sets: default and VS. Target would be 5.1.

How does this sound?

**Comment by Gama11** [comment]
I like the idea of shortcut sets that try to be similar to other IDEs - just not in this particular case. I as I said in my original post, this seems like a widely accepted standard (6/8 IDEs / editors support it!).

And I bet a lot of exisiting users are *already* confused because FD isn't the only IDE they use.

**Comment by Meychi** [comment]
Ok, instead of swapping shortcuts, my suggestion is to set ctrl+shift+o to toggle fold and ctrl+shift+f to Find in Files? Ok?

**Comment by Meychi** [comment]
So that mainly keyboad users have a shortcut :)

**Comment by Gama11** [comment]
Just opened a pull, I'll add the Ctrl+Shift+O.

You should open a separate issue about shortcut sets.
