### ISSUE TITLE
server bug

### ISSUE THREAD

**Issue by matrix3d** [fdorg/flashdevelop#733]
i make 2 fd project,a typescript,and a createjs.
i run ts is the typescript.html.
and i run createjs proj,also the ts project.
i must clear the chrome history?

**Comment by Meychi** [comment]
What version of FD? How do you run the project? Using Webserver Test Movie option?

**Comment by matrix3d** [comment]
version 92beb1f3eb

i run the project use f5. the option just the same new typescript project.

and the ts project ,i change the  the main.ts,it is work.but i change the project,it can not work.

and i use http://xxxxxxx/index.html?v=1.
add a diff verion "v=1".it is work.

**Comment by elsassph** [comment]
The webserver has a fixed IP so the first server started wins. FD will keep the server running until you close the project.

**Comment by matrix3d** [comment]
can not use ,i have restart my os.

i think it is a browse Cache iussee
