### ISSUE TITLE
Project Manager: node background colors aren't reset on theme switch

### ISSUE THREAD

**Issue by Gama11** [fdorg/flashdevelop#738]
- Switch from Default to Thyleus:

![](http://i.imgur.com/JwZ214T.png)

- Switching back:

![](http://i.imgur.com/lhxv8fJ.png)

The background colors from the old theme stick around. They reset after selecting and deselecting each node.

**Comment by Meychi** [comment]
Try manually refreshing the tree. There are few other cases where the colors or settings are not appied correctly and may require restarting. I'll try to improve this later on.

**Comment by Gama11** [comment]
With the "Refresh" button? Doesn't do anything. Selecting and deselecting all nodes is relatively quick with Ctrl+Shift+Click though.

**Comment by Meychi** [comment]
Ah, the refresh helped on some other occasion it seems.
