### ISSUE TITLE
Simple quick find

### ISSUE THREAD

**Issue by deepnight** [fdorg/flashdevelop#749]
When hitting the Quick Find Next (F3) shortcut while the Quick Find panel was hidden, it used to perform a simple quick find directly based on the currently selected text.

Now, F3 only repeats the last Quick Find and doesn't use the selected text anymore.

**Comment by Gama11** [comment]
What version was that, 4.7.2?

**Comment by deepnight** [comment]
Nope, 5.0.0.2

**Comment by Gama11** [comment]
I meant the version where it was still working. :) Sorry, should've made that clearer.

**Comment by Meychi** [comment]
What text you are looking for? We did some adjustments here so i am looking in detail what did it affect.

**Comment by deepnight** [comment]
I used a 5.0.0 dev build version (not sure which version it was, updated about 4 weeks ago).

The previous behavior that doesn't work anymore :
 * select something in an open document
 * hit F3 to perform a simple quick find: it should select the next occurrence of the selected text
 * hitting F3 again cycles though all occurrences.
 * if you select something else and hit F3 again, it used to initiate a new quick find with this newly selected text. Now it only continues to cycle through all occurrence of the previous quick find operation, ignoring the newest selection.

**Comment by Meychi** [comment]
Works here fine with a word. How long text? A word or part of a word? Have you adjusted any find related setting from main settings?

**Comment by deepnight** [comment]
This is quite strange. The bug did occur til yesterday, and this morning, the F3 shortcut now works like it used to... I'm lost o_o
The problem did occur after I updated my 5.0.x dev build to the latest 5.0.0.2 public release. Probably solved after a reboot... Odd.
