### ISSUE TITLE
[Haxe] include .code in single char String completion

### ISSUE THREAD

**Issue by Gama11** [fdorg/flashdevelop#750]
This feature not really documented (https://github.com/HaxeFoundation/HaxeManual/issues/161) and also missing from compiler completion: https://github.com/HaxeFoundation/haxe/issues/4270. FD's internal completion engine should have a special case for this ideally.

**Comment by elsassph** [comment]
No it should be in std String definition.

**Comment by Gama11** [comment]
How would that work? It's a special property that's only available for single character strings.

**Comment by elsassph** [comment]
Ah, well that sound ok to still have that in the definition but the compiler would make sure you're calling it in the right case.... Or Haxe compiler completion should provide it.

I don't really want to hardcode that in FD.

**Comment by Simn** [comment]
I think we can hack this into completion the same way we hack this into typing itself. I'll take care of that, feel free to close here.

**Comment by Gama11** [comment]
In my opinion it would be nice if FD's internal completion also had a hack for this - of course not from a code-perspective, but from a usability perspective. Compiler completion doesn't always work.

**Comment by elsassph** [comment]
I agree it may be nice, but it's not a good approach..

**Comment by SlavaRa** [comment]
Can be fd macro is the best solution?
