### ISSUE TITLE
[haxe] FlashDevelop inserts a space after a `with` word

### ISSUE THREAD

**Issue by YellowAfterlife** [fdorg/flashdevelop#759]
As you may know, `with` is not a keyword in Haxe.
FlashDevelop seems to threat it as if it is though, inserting a space after it on multiple occasions. For example,

``` haxe
var with:String
```

becomes

``` haxe
var with :String;
```

upon inserting a semicolon.

Is no big deal, but probably shouldn't be doing that.

**Comment by Gama11** [comment]
This can be configured in ASCompletion -> Always Add Space After. Somewhat tricky to deal with that, you'd have to make that setting language-specific somehow...

Maybe HaxeDevelop could have different default settings, in this case "with" wouldn't be included.

**Comment by SlavaRa** [comment]
@YellowAfterlife This issue is relevant?
