### ISSUE TITLE
[Haxe] Calltip completion breaks if previous argument uses array comprehension

### ISSUE THREAD

**Issue by Gama11** [fdorg/flashdevelop#764]
``` haxe
class Main {
    static function main() {
        test([for (i in 0...10) i]
    }

    static function test(a:Array<Int>, b:Int) {

    }
}
```

Expected behavior: the calltip completion pops up after typing the comma like here:

![](http://i.imgur.com/fIywg7W.png)

Actual: nothing happens.

**Comment by Neverbirth** [comment]
Does it happen with older FD versions? I'm curious as I made some changes to that part recently, but I'd swear I didn't touch anything that could make this case to work before and not now.

**Comment by Gama11** [comment]
No idea, I have only tested this with the latest version so far.

**Comment by SlavaRa** [comment]
Bug
