### ISSUE TITLE
parser as3 error

### ISSUE THREAD

**Issue by matrix3d** [fdorg/flashdevelop#771]
![default](https://cloud.githubusercontent.com/assets/4150631/8223140/f2c120ce-15a6-11e5-8cda-21eb96455e32.gif)

<pre>package 
{
    import flash.display.Sprite;
    /**
     * ...
     * @author lizhi
     */
    public class Test extends Sprite
    {
        
        public function Test() 
        {
            var a:A = new A;
            a.test(new Vector.<int>);
            a.
        }
        
    }

}

class A {
    public function test(v:Vector.<int>):void {
            
    }
}</pre>

**Comment by Neverbirth** [comment]
Surely the same bug https://github.com/fdorg/flashdevelop/issues/617

**Comment by SlavaRa** [comment]
Now all ok
