### ISSUE TITLE
Class wizard base class and imported types

### ISSUE THREAD

**Issue by Gama11** [fdorg/flashdevelop#775]
Modules that are imported in the current file are displayed twice in the "open type" dialog of the class wizard, once without their full dot path and once with it.

![](http://i.imgur.com/dQRm6PD.png)

Choosing the one without the dot path leads to the file being generated incorrectly.

Incorrect:

```haxe
package;

/**
 * ...
 * @author ...
 */
class Player extends FlxSprite
{

	public function new() 
	{
		
	}
	
}
```

Correct:

```haxe
package;

import flixel.FlxSprite;
import flixel.system.FlxAssets.FlxGraphicAsset;

/**
 * ...
 * @author ...
 */
class Player extends FlxSprite
{

	public function new(?X:Float=0, ?Y:Float=0, ?SimpleGraphic:FlxGraphicAsset) 
	{
		super(?X, ?Y, ?SimpleGraphic);
		
	}
	
}
```

**Comment by Gama11** [comment]
The same applies to interfaces.

**Comment by Neverbirth** [comment]
Yes, IIRC this is because of the GetExternalVisibleElements (or something like that) call before showing the dialog.
