### ISSUE TITLE
Override default browser

### ISSUE THREAD

**Issue by JeriXNet** [fdorg/flashdevelop#779]
It would be helpful if there is option to override default browser when testing settings defined like that:

```
<option testMovie="Webserver" />
<option testMovieCommand="html5/index.html" />
```

I mean my default browser if Firefox and I love it, but for haxe debugging Chrome is better for now and it's annoying to switch between them all the time :(
Discussed [here](http://www.flashdevelop.org/community/viewtopic.php?f=5&t=12283)
Thanks.

**Comment by SlavaRa** [comment]
via #1481
