### ISSUE TITLE
[haxe] add `using` next `import` declaration generation

### ISSUE THREAD

**Issue by markknol** [fdorg/flashdevelop#790]
To allow haxe developers work more easier with static extensions.

At the moment I import the class I need, then scroll up, then rename `import` to `using`. It would be neat to have it in the options list. Ctrl+Shift+1 ftw!

**Comment by Gama11** [comment]
What options list?

**Comment by markknol** [comment]
To the autocomplete option list.

![image](https://cloud.githubusercontent.com/assets/576184/8478745/98f87a00-20d3-11e5-84d8-334978040bc5.png)

**Comment by Gama11** [comment]
With Ctrl+Shift+1, modules are imported automatically without any options list popping up... or am I missing something?

**Comment by markknol** [comment]
Yes but I think to implement this idea you do need a option list.

So this would be the flow:
```
Math<CTRL-SHIFT-1>
```
this list appears
```
Import Math
Using Math
```
* When I choose `Import Math` it adds an import-statement
* When I choose `Using Math`  it adds an using-statement, the class will be available as static extension.

**Comment by Gama11** [comment]
Yeah, that wasn't really clear from your original suggestion. It sounded like "just add that to the options list", when there really isn't any options list right now.

This makes RALP4B

**Comment by markknol** [comment]
RALP4B?

**Comment by elsassph** [comment]
We don't want every Ctrl+Shift+1 to import to be a list unless there's an ambiguity. I believe it's fairly rare to add a using statement in practice.

But it would be nice to have some quick way to add a using type - open to other suggestions.

**Comment by markknol** [comment]
I'm using these using-statement quite often tbh, it's really nice. For example to work with [bitsets](https://github.com/aduros/flambe/blob/master/src/flambe/util/BitSets.hx). Also, I have quite some utility classes that are written for it.

As alternative, create auto-imports without and add one option with the using-statement when "Ctrl+Shift+1"ing on a type?

**Comment by markknol** [comment]
I don't see this happening anymore, ill close it.

**Comment by elsassph** [comment]
I still think it is a reasonable request but we didn't agree on a way to approach it.
Maybe we could "promote" an import to "using" using Ctrl+Shift+1?

**Comment by markknol** [comment]
You mean like a toggle? I think (not sure) you _could_ use `using` and `import` at the same time.

**Comment by Gama11** [comment]
If FD properly understood `using`, it could suggest them in completion and add them automatically when selecting (Visual Studio does this for static extension methods in C#).

**Comment by elsassph** [comment]
No I meant maybe if you Ctrl+Shift+1 on an imported type it could propose to promote it to 'using'.

Suggesting static extensions automatically might be a costly operation using FD code model because I think absolutely any static method could be used.

**Comment by Gama11** [comment]
Right, I guess it works well in C# since you have to be explicit about it there (adding the `this` keyword to the parameter)...
