### ISSUE TITLE
Cancel button for moving classes

### ISSUE THREAD

**Issue by markknol** [fdorg/flashdevelop#791]
Sometimes when I'm in a hurry I move classes into other folders at the projects tree view accidentally. It happens because I use a wacom pen maybe.

![image](https://cloud.githubusercontent.com/assets/576184/8518546/66558296-23cb-11e5-8161-b4347ef8557d.png)

It would be nice to have a _cancel button_ that does not move the file at all.

**Comment by SlavaRa** [comment]
Yes, i think that good idea, i can made this today

**Comment by SlavaRa** [comment]
Done, PR in lunch.

**Comment by markknol** [comment]
Very nice!! Thanks
