### ISSUE TITLE
Build-in browser

### ISSUE THREAD

**Issue by markknol** [fdorg/flashdevelop#794]
What browser is build-in FlashDevelop?

When I open the startpage and click on github icon it says im using a very old internet explorer version.
![image](https://cloud.githubusercontent.com/assets/576184/8558438/7ff48654-2504-11e5-9873-d8c089987bf8.png)

 Also the language reference are opened in this browser and don't look that good.

![image](https://cloud.githubusercontent.com/assets/576184/8558427/73efd354-2504-11e5-964a-ea28faa51c5b.png)

Can it be updated or use the windows default browser or something?

**Comment by elsassph** [comment]
We need  to set a registry value during setup to use the latest version of IE - cf. http://dennymichael.net/2015/06/22/web-browser-control-specifying-the-ie-version/

**Comment by elsassph** [comment]
Note: as noted at the end of the article, it seems to work with the value `0` instead of one value setting a specific browser version and I'm seeing IE11. That's future proof.

**Comment by markknol** [comment]
Ah nice found! looking forward to have this in. It would improve the looks (and maybe speed) of the docs. :+1:

**Comment by elsassph** [comment]
You can do this registry change yourself right now. It will just be nice to have that in the setup.

**Comment by markknol** [comment]
Sorry for the bump, It would be really nice to have this in the setup, since the Haxe documentation doesn't look good atm. I ask this especially for HaxeDevelop.

**Comment by markknol** [comment]
Awesome! :+1:
