### ISSUE TITLE
Method auto-completion can pick up "nearby" type-looking data if no type is specified.

### ISSUE THREAD

**Issue by YellowAfterlife** [fdorg/flashdevelop#798]
Say, if you have
```haxe
@:publicFields class Main {
	function new() {
		
	}
	function test() {
		trace("Main->test");
	}
}
@:publicFields class Some extends Main {
	|
}
```
and then in place of "|" type "override t" and pick "test" from the auto-completion, you suddenly get
```haxe
	override function test():publicFields {
		return super.test();
	}
```
(supposedly because `:publicFields` is the nearest structure that looks like a type)
which is not a desired result.

**Comment by Gama11** [comment]
Duplicate of #372 I think.

**Comment by elsassph** [comment]
Yeah, time to parse those metas...

**Comment by SlavaRa** [comment]
@Meychi @elsassph @Neverbirth please add a duplicate label
