### ISSUE TITLE
Missing icon sizes in AIR properties editor

### ISSUE THREAD

**Issue by kevinfoley** [fdorg/flashdevelop#804]
The icon sizes in the AIR Application Properties window are outdated and missing some modern icon sizes. Some of the iOS sizes that are missing:

64 x 64
87 x 87
180 x 180 (required for iPhone 6 Plus)
320 x 320

See https://developer.apple.com/library/ios/documentation/UserExperience/Conceptual/MobileHIG/IconMatrix.html

**Comment by Meychi** [comment]
Fixed in f7faaadfd68982aecad1f99194f0a93493e6d19d
