### ISSUE TITLE
@inheritDoc tag doesn't work with code completion

### ISSUE THREAD

**Issue by kevinfoley** [fdorg/flashdevelop#805]
FlashDevelop does not properly support the ASDoc "@inheritDoc" tag in the code completion window.

**Steps to reproduce:**
- Create a new interface with a function that has an ASDoc comment
- Create a class that implements the interface
- Use the @inheritDoc tag in the ASDoc comment above the function in the class file
- Start typing a call to the function in the class file, such that the code completion window appears

**Expected behavior**: The code completion window shows the ASDoc comment inherited from the interface

**Actual behavior**: The code completion window does not show the comment

```
public interface IExample {
    /**
     *  This is an example ASDoc comment
     */
    function exampleFunction();
}

public class Example implements IExample {
    /**
     * @inheritDoc
     */
    public function exampleFunction() {
    }
}
```

**Comment by SlavaRa** [comment]
Fixed in development branch.
