### ISSUE TITLE
Expressions in Watch Panel disappear after stopping debugging

### ISSUE THREAD

**Issue by dleanjeans** [fdorg/flashdevelop#806]
It's really annoying when you add a lot of expressions into the Watch Panel and they disappear after stopping debugging. If I recall correctly, Visual Studio keeps them after that.

**Comment by ortizgames** [comment]
I second this; this feature would be really useful for the heavy development I've been doing lately.

**Comment by Neverbirth** [comment]
I´ll look into this today.

**Comment by Neverbirth** [comment]
Just FYI, this was done yesterday, but before committing I want to also persist the expressions between application sessions like in other IDEs.

**Comment by ortizgames** [comment]
Neverbirth, you are awesome! :)

Andres Ortiz
Game Designer & Programmer
http://www.ortizgames.com

**Comment by Neverbirth** [comment]
In case you are not aware, this was merged yesterday, so you can download a development build for the feature.

**Comment by ortizgames** [comment]
Neverbirth,




I had been watching your pull request, but I hadn't checked in a couple of days - thank you!! I'll be back at my desk on Sunday and trying this out immediately.



—
Andres

**Comment by ortizgames** [comment]
Watch entries persist and it's a miracle!! :)

Issue is finally resolved; thank you, Neverbirth! The day when this hits the release channel can't come soon enough!



—
Andres
