### ISSUE TITLE
False Haxe auto-generated code with question mark

### ISSUE THREAD

**Issue by dleanjeanz** [fdorg/flashdevelop#807]
When create new class file: Add > New Class... and select base class, FlashDevelop generates this:

	public function new(?X:Float=0, ?Y:Float=0, ?Width:Int, ?Height:Int) 
	{
		super(?X, ?Y, ?Width, ?Height);
	}

It should be like this:

	public function new(?X:Float=0, ?Y:Float=0, ?Width:Int, ?Height:Int) 
	{
		super(X, Y, Width, Height); // no question mark !!!
	}

**Comment by SlavaRa** [comment]
Duplicated #801?

**Comment by elsassph** [comment]
Yes this is a duplicate. And it's fixed on Github.
