### ISSUE TITLE
Cmd key bindings on Mac OS over CrossOver

### ISSUE THREAD

**Issue by zaynyatyi** [fdorg/flashdevelop#808]
Hi,
Most of keys in FD are bound to Ctrl, but system action on mac bound to Cmd key (such as App switching, etc). When i'm using Cmd key in FD it switches to top FD menu (File, Edit, etc.) and turning on Block selection.
Is it possible to bind FD hotkeys on Mac from Ctrl to Cmd key?

**Comment by elsassph** [comment]
You'll have to look into CrossOver/VirtualBox/Parallels options for custom key binding.

**Comment by zaynyatyi** [comment]
As i read in CrossOver setting Cmd key is always works as Alt for win apps

**Comment by elsassph** [comment]
Then you can go in Tools > Shortcuts and reassign everything...
