### ISSUE TITLE
Function autogeneration without file save.

### ISSUE THREAD

**Issue by nomikovsupe** [fdorg/flashdevelop#809]
Project -> New Project -> AS3 Project

Open Main.as.
Mouse click in the end of "// entry point" line.
Press Enter.
Type "blabla();"
Try to "Generate private function" via Ctrl+Shift+1

Result (look at brackets):

```
private function init(e:Event = null):void 
{
    removeEventListener(Event.ADDED_TO_STAGE, init);
    // entry point
    blabla();


private function blabla():void 
{

}}
```

But if you save file before generation, then bug don't emerge.

**Comment by SlavaRa** [comment]
I checked the release of 5.1.1 - the error is not repeated.
@nomikovsupe please close the issue if it is not relevant at the moment.
Thanks.

**Comment by SlavaRa** [comment]
Now all ok
