### ISSUE TITLE
Completion doesn't support multiple interfaces

### ISSUE THREAD

**Issue by kevinfoley** [fdorg/flashdevelop#811]
In AS3, a class can implement multiple interfaces, for example:

```
public class ChildClass extends ParentClass implements ICustomInterface1, ICustomInterface2 {
```

FlashDevelop completion stops working after the comma after the first interface. In the above example, no completion will be provided while typing ICustomInterface2. This issue exists in FlashDevelop 5.0.1 and earlier.

**Comment by elsassph** [comment]
Yes this is a known limitation.
