### ISSUE TITLE
Editor window has vertical scroll bar for no reason

### ISSUE THREAD

**Issue by nomikovsupe** [fdorg/flashdevelop#814]
Editor window has vertical scroll bar for no reason

4.7.2 don't have the problem
5.0.0 have the problem
5.0.1 have the problem

I have made clean install after removing FlashDevelop with its settings.

Project->New Project->AS3 Project

![scrollbug](https://cloud.githubusercontent.com/assets/10908676/9025979/68373ec8-3925-11e5-8f71-f8979ea2cc2e.png)

**Comment by Meychi** [comment]
This is a default behaviour of our editor component due to performace reasons, see: http://www.scintilla.org/ScintillaDoc.html#SCI_SETSCROLLWIDTH

**Comment by nomikovsupe** [comment]
This issue about vertical, not horizontal scrollbar. Please reopen.

**Comment by Meychi** [comment]
Ah true but this is also a new feature, overscroll.

**Comment by elsassph** [comment]
I didn't find an option for the overscroll in the program settings BTW.
