### ISSUE TITLE
Haxe: Hide code inside #if (target/flag) blocks based on the selected target/flag

### ISSUE THREAD

**Issue by sruloart** [fdorg/flashdevelop#816]
Have an option to hide the code you don't want to see based on the flags you've set (maybe as an available dropdown). This can really improve readability with cross-targets' code.  

You already have a "hiding" mechanism in the target-based-completion (e.g. if you choose `flash` from the targets' dropdown, expressions in `#if !flash` blocks would not be seen in the completion). So, it would be helpful to have something similar for the actual code as well (like, if you set your target to `flash` all the !flash blocks close).

**Comment by Gama11** [comment]
Not sure hiding the blocks is a great idea, I'd prefer if they were greyed out (see #83).

FD doesn't have a hiding mechanism, Haxe compiler completion is responsible for that. FD's internal completion engine ignores `#if` blocks entirely. You can observe this by setting the `Completion Mode` in `HaxeContext` to `FlashDevelop`:

![](http://i.imgur.com/hCTT0DU.png)
(with the target dropdown set to neko)

**Comment by sruloart** [comment]
Hmm, so not so doable. I was thinking mainly just having an option for collapsing specific #if blocks, but if FD can't handle them at all...

**Comment by elsassph** [comment]
This isn't really doable in a robust way.
