### ISSUE TITLE
[suggestion] autocompletion list, "up"-key wrap 

### ISSUE THREAD

**Issue by markknol** [fdorg/flashdevelop#821]
It would be nice if you press the arrow "up" key when you are on top of the list, it would select to one at the bottom of the list. Now it just stops.

![image](https://cloud.githubusercontent.com/assets/576184/9274169/814ccbcc-4293-11e5-893c-417e1b3d1081.png)

**Comment by Gama11** [comment]
Tools -> Program Settings... -> FlashDevelop -> set "Wrap List" to "True"

**Comment by markknol** [comment]
Ah super awesome (again)!

You should enable it by default :smile:

**Comment by Gama11** [comment]
I find wrapping pretty annoying personally, so I'm glad it's not the default. ;)
