### ISSUE TITLE
Duplicate plugin adds extra characters

### ISSUE THREAD

**Issue by markknol** [fdorg/flashdevelop#822]
I really like the duplicate plugin. But I have for a while now that when I duplicate something, I get an extra character. It occurs with all functions  (duplicate switch, direct switch, duplicate increase)

![duplicate-issue](https://cloud.githubusercontent.com/assets/576184/9300734/7a8b244a-44c9-11e5-905c-3c2d4548b4e4.gif)

Is there anything I can do to avoid this?

I a dev-build with the Haxe platform (development#https://github.com/fdorg/flashdevelop/commit/b909af4267) but it already happened on FD4.

**Comment by Gama11** [comment]
What's the "duplicate plugin"? There's Ctrl+D / Edit -> Duplicate Selection, but I wouldn't really consider that a plugin. And I can't reproduce this issue with that.

**Comment by markknol** [comment]
It's this plugin: https://github.com/fdorg/flashdevelop/tree/development/External/3rdParty/Duplicate

**Comment by itzikiap** [comment]
Hi.
You are refering to this third party plugin:
http://www.flashdevelop.org/community/viewtopic.php?f=4&t=2993

Never did any problems for me (I also really like it.)

**Comment by markknol** [comment]
I figured out it has something to do with the input language keyboard setting. When I choose "English - United States International" it gives the extra character, with "English - US" it does work (no extra character). It's not a keyboard I prefer (because quotes work different), but in case anyone finds the same issue, this is part of the problem.
