### ISSUE TITLE
Windows 10 Compiler Options Not editable

### ISSUE THREAD

**Issue by smks** [fdorg/flashdevelop#826]
I want to add some extra compiler options but this is not possible at present.

![image](https://cloud.githubusercontent.com/assets/4087157/9491804/b3cab2b2-4be9-11e5-9e7e-92750e345e06.png)

**Comment by Gama11** [comment]
That has nothing to do with windows 10 and is intentional - these are read-only.

What project type do you have? OpenFL?

**Comment by smks** [comment]
Yes OpenFL with HaxeFlixel. I specify compiler arguments in project.xml?

**Comment by Gama11** [comment]
Correct. What compiler argument specifically?

**Comment by smks** [comment]
http://www.openfl.org/documentation/command-line-tools/project-files/xml-format/

I can see now this xml file belongs to OpenFL. Will specify <haxedef> as an argument to the build. Sorry to waste your time.

**Comment by Gama11** [comment]
No worries, glad to be able to clear things up.
