### ISSUE TITLE
ImageManager.ImageSet - filter is applied more than once

### ISSUE THREAD

**Issue by gene-pavlovsky** [fdorg/flashdevelop#828]
When using a theme with ImageManager.ImageSet setting different from default, something causes the filter to get applied more than once, making the images more and more dark (or bright).
This might have something to do (or not) with project panel getting updated with source control status.

Here's my theme with the Default image set selected. There are no problems here.
![img1](http://i.imgur.com/ZgMKxjc.png)
Next step - modify the theme to use the Darker image set. Restart FlashDevelop, take a screenshot.
![img2](http://i.imgur.com/mHmmlRA.png)
A couple seconds later, the source control status has been updated. The images have become even darker.
![img3](http://i.imgur.com/UWaLOzm.png)
Just wandering around the project for a bit. The images have become almost black.
![img4](http://i.imgur.com/DPKgz3d.png)

FD 5.0.1 
.NET CLR 2.0.50727

http://www.flashdevelop.org/community/viewtopic.php?f=6&t=12383

**Comment by gene-pavlovsky** [comment]
Is there a way to download a nightly build to test?

**Comment by Meychi** [comment]
Here: http://www.flashdevelop.org/community/viewtopic.php?f=9&t=3529

**Comment by gene-pavlovsky** [comment]
Thanks, already found it. Looks like it's fixed indeed. Thanks!
