### ISSUE TITLE
Some themes features not activated until FD restart 

### ISSUE THREAD

**Issue by gene-pavlovsky** [fdorg/flashdevelop#832]
I'm using a dark theme in the evening and a light theme in the daytime, so I switch themes couple times a day.
I've noticed some settings don't get applied until FD is restarted.

What I've noticed so far:

    DockPanelControl.BorderColor
    VS2005DockPaneStrip.ImageColor - refreshed by using document tabs list button then selecting another tab
    ImageManager.ImageSet
    ProjectTreeView.*Library*Color - refreshed by adding/removing some library in the project panel

Additionally, when switching between themes with a different VS2005AutoHideStrip.TabStyle setting, the auto hide items width doesn't get updated and becomes incorrect.

Some more settings I've noticed but forgotten.

Are there plans to fix those, or basically I should restart FD between theme changes?

**Comment by gene-pavlovsky** [comment]
Upon reloading a theme the colors highlighting an SWC added to library are replaced with default text color used for normal text in the project panel (until FD is restarted or a project is reloaded).

**Comment by wise0704** [comment]
The core problem is addressed and fixed in #981. However there are still some images not being adjusted. PR is still being worked on atm however.
