### ISSUE TITLE
Quick-find and outline panel search box text color gets reset to black

### ISSUE THREAD

**Issue by gene-pavlovsky** [fdorg/flashdevelop#833]
I'm working on a new dark theme. I've found out that the outline panel (and quick-find panel) text box text color is controlled by ToolStripTextBoxControl.ForeColor setting. My theme is dark, so I set it to a light color. Problem is, the text color gets reset to black after closing the search.
For example, load the default theme, open the outline panel, type something in the search box.
Load VsDark theme, open the outline panel - the same text you typed is still there, in the (almost) white color.
Press the "X" button to the right of the search box, and type something new in the search box - the text will be black!

Something similar goes on in the tree of the outline panel itself.
Just load the VsDark theme.
Open some AS3 class.
Open the outline panel and click on several items in the tree, one by one.
Some of the items become black after selecting a next item.

FD 5.0.1 
.NET CLR 2.0.50727

**Comment by gene-pavlovsky** [comment]
![image](http://i.imgur.com/z7B8BaD.png)
Theme has:
```
ToolStripTextBoxControl.BorderColor=0x657b83
```
Sometimes (I think when the theme is freshly applied) the text is correct color, but quickly the setting is lost.

**Comment by gene-pavlovsky** [comment]
This is still the case with the latest dev build.
It was working ok, at some point I noticed text is black:
![quick-find-1](http://i.imgur.com/MFmBWmb.png)

Reloaded the same theme:
![quick-find-2](http://i.imgur.com/45LVArX.png)

**Comment by Meychi** [comment]
Could you share your UI theme so i could debug with it?

**Comment by gene-pavlovsky** [comment]
I don't have this issue anymore. Apparently fixed. Will report if notice again.
