### ISSUE TITLE
It's possible to scroll a file down too far down

### ISSUE THREAD

**Issue by gene-pavlovsky** [fdorg/flashdevelop#835]
A file can be scrolled down until it's last line is the only line visible on the screen (as first line), with empty space (and no line numbers either) covering the rest of the screen.
I think at the bottom-most scroll position the last line of the file should be at the bottom of the screen, not at the top.

![image1](http://i.imgur.com/OVB0wLS.png)

![image2](http://i.imgur.com/eICyvwN.png)

FD 5.0.1 
.NET CLR 2.0.50727

http://www.flashdevelop.org/community/viewtopic.php?f=6&t=12362

**Comment by Meychi** [comment]
This is a new feature, overscroll. Visual Studio does this to so does many other IDEs. We could maybe add an option to use the old behaviour, need to think if thats necessary.

**Comment by gene-pavlovsky** [comment]
Oh. This feels very unnatural and unpleasant to me. I think all the editors and IDEs I've used before don't have this "feature", what's the usefulness of this?
I really wish there was an option to turn it off! Maybe we can make a poll and find out how many users like/hate/don't care about it.
Personally, I hate it so far. Unless somebody enlightens me on what I'm missing here.

**Comment by elsassph** [comment]
I like it but it has to be an option, Mika.

**Comment by gene-pavlovsky** [comment]
Philippe, can you tell me what do you like about it? I'm really curious.

**Comment by elsassph** [comment]
When I write code at the end of a file I don't like typing at the bottom of
the screen - often when that happens I add a bunch of dummy new lines. Not
sure why, I just don't feel comfortable.

**Comment by gene-pavlovsky** [comment]
Ah, I can imagine feeling like this, might depend on size and position of your screen as well as personal preference. If I read a book using a computer screen, I do prefer to use the continuous mode and scroll often, so that I'm reading around the top or middle of the screen. But for some reason when programming I don't feel like that. I'm sure there are many people like you and like me as well.

**Comment by gene-pavlovsky** [comment]
This issue still exists. Could anybody please add the option to disable overscroll?

**Comment by gene-pavlovsky** [comment]
Guys, please add `enable/disable overscroll` option
