### ISSUE TITLE
Theme: Style all the scrollbars according to current theme scrollbar settings

### ISSUE THREAD

**Issue by gene-pavlovsky** [fdorg/flashdevelop#842]
The theme engine allows to change the style of the editor scrollbars, but those styles don't apply to Output panel or debugger panels scrollbars.
It's not that big deal, but if it's not too hard, would be nice for that scrollbar to look same as editor scrollbar (default scrollbars are quite hard on the eyes when using a dark theme).

**Comment by Meychi** [comment]
Tricky but on our todo list.

**Comment by gene-pavlovsky** [comment]
It's not that big deal but would be nice to have it eventually (for dark themes)

**Comment by wise0704** [comment]
@Neverbirth  HYPEEEEE

**Comment by Meychi** [comment]
Done for 5.2

**Comment by gene-pavlovsky** [comment]
Great, looks super sweet now!
