### ISSUE TITLE
Theme: Improve debugger theme-ability

### ISSUE THREAD

**Issue by gene-pavlovsky** [fdorg/flashdevelop#843]
Right now the debugger is really hard to use when using a dark theme like VsDark. We need to have some new settings to setup reasonable colors for the debugger:
![Image1](http://i.imgur.com/REi7Pb8.png) ![Image2](http://i.imgur.com/DlAYded.png)

Everything is supposed to be dark or not too bright in these themes.

**Comment by Meychi** [comment]
On our todo list.

**Comment by gene-pavlovsky** [comment]
That's great! Looking forward to improving my Solarized light and dark themes.

**Comment by gene-pavlovsky** [comment]
One more thing to be able to customize: the "Enabled" column's background in the Breakpoints panel right now it's light blue).

**Comment by gene-pavlovsky** [comment]
So breakpoints panel colors are customizable as DataGridView.
Locals and Watch use DataTreeControl, but for some reason theme settings for DataTreeControl doesn't seem to apply (well at least the text is black not matter what).

**Comment by gene-pavlovsky** [comment]
At the moment it looks like locals and watch panel data tree uses DataTreeControl.ForeColor for text color, but TreeViewAdv.BackColor for background color. Maybe pick one of them to use for both settings (DataTreeControl?) for consistency.

**Comment by gene-pavlovsky** [comment]
I'd like to know what new settings are there. What is the commit ID?
