### ISSUE TITLE
Theme: Add extra settings to theme engine

### ISSUE THREAD

**Issue by gene-pavlovsky** [fdorg/flashdevelop#844]
Working on a dark theme, keep encountering cases where a default color can't look good on a dark background. Some new settings should be added to the theme engine.

Completion tool-tip - the current param has a black background (not pretty), the text "Press F1 to toggle details" is black (almost unreadable) - should be customizable
![Image1](http://i.imgur.com/A11awl4.png)

Hover on a property tool-tip - the class name is black (almost unreadable)
![Image2](http://i.imgur.com/BpGCt1C.png)

Quick-find bar - when text is not found, the background color only works well with bright text, I'd like a darker text and a darker background - background (or text/background if not found) should be customizable
![Image3](http://i.imgur.com/NLLd995.png)

Highlight matching words (selected word) background - color seems to be derived from some syntax highlighting color (selection?), but it's too dim, I need to make it more noticeable - should be customizable.
![Image4](http://i.imgur.com/qZRMUCR.png)

Quick-find highlight all highlight background - color seems to be derived from some syntax highlighting color (word?), it looks fine, but I would like it customizable as well.
![Image5](http://i.imgur.com/HRkDGzc.png)

**Comment by Meychi** [comment]
Theming improvement are coming in next major release. Noted.

**Comment by gene-pavlovsky** [comment]
That's great! Looking forward to improving my Solarized light and dark themes.

**Comment by Meychi** [comment]
These and some more and now in dev.

**Comment by gene-pavlovsky** [comment]
Mika, this is wonderful! I've updated my theme and usability improved noticeably (especially the Output panel: trace messages are now readable).
There are some questions still  :)
1) Global.Highlight - used as text color for current item in Results or Outline panel, but as background color for matching items when doing a search in the Outline panel - is that by design?
2) OutputPanel.WarningColor - only colors the "Warning:" line, but the following lines (source code and detailed description of the warning) are colored using ``OutputPanel.ErrorColor``. Errors are colored in that color, both "Error:" line and the following lines. Is that intended?
3) OutputPanel.FatalColor - example how to get something ``fatal`` to test? I've grepped the FD source code and haven't found it adding any ``fatal`` entries.
4) CompletionList.SelectedBackColor - not implemented yet? Besides in the themes, it's not used in FD source code.
5) MethodCallTip.SelectedBack - doesn't work for me, background is still black, and some html tags...
![call-tip-selected-back](http://i.imgur.com/a4RrqrB.png)
Sometimes the html tags show like this, sometimes not. When I set 0xff000 as the color, the tag said "Red:OVERLAY" but still no coloring.

**Comment by gene-pavlovsky** [comment]
A couple restarts and theme reloads later, method call tip back is showing in a different color - not black, and not the one set in my theme:
``MethodCallTip.SelectedBack=0x268bd2``
But the highlight is some dark bluish color?
![call-tip-selected-back](http://i.imgur.com/lO9FwXE.png)
