### ISSUE TITLE
Haxe completion error

### ISSUE THREAD

**Issue by kevinresol** [fdorg/flashdevelop#851]
```
--macro:1: character 0 : Could not parse `snow.system.module.Module.set(\"Audio\",\"snow.core.web.audio.Audio\")`
--macro:1: character 0 : Invalid character '\'
```

Was using Luxe and got this error during completion. Probably related to https://github.com/fdorg/flashdevelop/commit/a739113e801536528515abdd395c4183715f84b9

ref: https://github.com/underscorediscovery/snow/blob/master/framework.flow#L185

**Comment by elsassph** [comment]
Hmm, how is configured your project? Is it FD flow integration  or something manual?

**Comment by kevinresol** [comment]
using this template https://github.com/Chman/Snowkit-FD

**Comment by kevinresol** [comment]
it is strange though: if I clone the repo and build it, it works. but it fails if I download the build from build server, both at c9e1bcc

**Comment by kevinresol** [comment]
This error still exist at latest build 6e32087b2d91
Are there anything I can do to provide more info?

**Comment by kevinresol** [comment]
OK, i double checked, building FD from source does not solve the problem. What solve the problem is not to use completion server
