### ISSUE TITLE
Menu bar keyborad navigation bug

### ISSUE THREAD

**Issue by M-Azuma** [fdorg/flashdevelop#857]
In FlashDevelop 5.0.1, <kbd>←</kbd>/<kbd>→</kbd> on menu bar item navigate to opposite direction.
1. Press <kbd>Alt</kbd> to focus on the menu bar.
2. Press <kbd>↓</kbd> to open menu items.
3. Keep menu items open and press <kbd>←</kbd>/<kbd>→</kbd> to navigate.

**Comment by elsassph** [comment]
That is really funny :)
