### ISSUE TITLE
Code snippet editor doesn't recognize Unix line ending.

### ISSUE THREAD

**Issue by S-Aoi** [fdorg/flashdevelop#858]
Code snippet displays Unix line ending snippets in one line. The default code snippets in FlashDevelop 5.0.1 are Unix line ending. I convert the snippets to Windows line ending and I can see multiple lines in snippet editor.

**Comment by matrix3d** [comment]
截个图

**Comment by S-Aoi** [comment]
![problem](https://cloud.githubusercontent.com/assets/3676278/9806807/5f438bca-587c-11e5-9908-ab554a67801b.png)
