### ISSUE TITLE
edit *.html always make fd die

### ISSUE THREAD

**Issue by matrix3d** [fdorg/flashdevelop#869]

**Comment by Gama11** [comment]
Could you be a bit more specific? "Die" means crash I guess? Is there an error message? What FD version?

**Comment by matrix3d** [comment]
no error message,just die long long time,30ms,and not die.
i use the last version fd,not dev version.
the index.html of the bin folder.change some work,save,die

**Comment by SlavaRa** [comment]
@matrix3d Is this reproduced in the latest release(or the latest development version)?
