### ISSUE TITLE
Source control bug with referenced projects in FD 5

### ISSUE THREAD

**Issue by neuronix** [fdorg/flashdevelop#874]
Herewith a picture. Referenced projects are all grey whereas they are updated and all the content is green.

The other grey folders are ignored so they shouldn't have a grey spot either.
![untitled-1](https://cloud.githubusercontent.com/assets/219800/9958862/558409f6-5e0e-11e5-9d53-33ba22a2cd3a.jpg)

Edit: refreshing or restarting the program doesn't help

**Comment by neuronix** [comment]
The "Source control" entry in the context menu is also disappearing very often, refresh not solving meaning having to restart FD :(

**Comment by SlavaRa** [comment]
Now all ok
