### ISSUE TITLE
chinese char show bug

### ISSUE THREAD

**Issue by matrix3d** [fdorg/flashdevelop#875]
![fdbug](https://cloud.githubusercontent.com/assets/4150631/9986109/ad8c523a-606a-11e5-8060-06cbb33ed269.gif)

the 1.txt,just new with ms notepad,input some char,norm.and save,open with fd,have this bug.and some other editor,not have the bug,nodepad++,etc

**Comment by elsassph** [comment]
Can you compare with SciTE? This is the reference integration of Scintilla editor.

**Comment by matrix3d** [comment]
the scite can not open chinese file.but the notepad++ also a scite base editor.

but can edit the sciteuser.properties file.

code.page=936
output.code.page=936

make the scite support chinese file good.

**Comment by Meychi** [comment]
Is this in 8bit encoding? Does UTF-8 work correctly in Chinese?

**Comment by matrix3d** [comment]
utf-8 work good.it is 8bit.

**Comment by Meychi** [comment]
8bit is tricky. FD defaults to your system ANSI encoding if it doesn't detect any UTF sequences. Could you please share the files? If i try to copy from here they are in UTF-8 encoding.

**Comment by matrix3d** [comment]
http://pan.baidu.com/s/1bnpx9AR

**Comment by Meychi** [comment]
What is your system locale? Run systeminfo in command prompt:

http://www.microsoft.com/resources/documentation/windows/xp/all/proddocs/en-us/systeminfo.mspx?mfr=true

**Comment by matrix3d** [comment]
<pre>C:\Users\222222>systeminfo

主机名:           DESKTOP-EU26KPM
OS 名称:          Microsoft Windows 10 专业版
OS 版本:          10.0.10240 暂缺 Build 10240
OS 制造商:        Microsoft Corporation
OS 配置:          独立工作站
OS 构件类型:      Multiprocessor Free
注册的所有人:     1111
注册的组织:
产品 ID:          00330-80000-00000-AA326
初始安装日期:     2015/9/27, 17:18:51
系统启动时间:     2015/10/1, 11:47:13
系统制造商:       To Be Filled By O.E.M.
系统型号:         To Be Filled By O.E.M.
系统类型:         X86-based PC
处理器:           安装了 1 个处理器。
                  [01]: x64 Family 18 Model 1 Stepping 0 AuthenticAMD ~800 Mhz
BIOS 版本:        American Megatrends Inc. P1.10, 2011/10/14
Windows 目录:     C:\WINDOWS
系统目录:         C:\WINDOWS\system32
启动设备:         \Device\HarddiskVolume1
系统区域设置:     zh-cn;中文(中国)
输入法区域设置:   zh-cn;中文(中国)
时区:             (UTC+08:00)北京，重庆，香港特别行政区，乌鲁木齐
物理内存总量:     1,772 MB
可用的物理内存:   974 MB
虚拟内存: 最大值: 2,958 MB
虚拟内存: 可用:   1,555 MB
虚拟内存: 使用中: 1,403 MB
页面文件位置:     C:\pagefile.sys
域:               WORKGROUP
登录服务器:       \\DESKTOP-EU26KPM
修补程序:         安装了 8 个修补程序。
                  [01]: KB3074678
                  [02]: KB3074686
                  [03]: KB3081440
                  [04]: KB3081449
                  [05]: KB3081452
                  [06]: KB3081455
                  [07]: KB3087040
                  [08]: KB3095020
网卡:             安装了 1 个 NIC。
                  [01]: Realtek PCIe GBE Family Controller
                      连接名:      以太网
                      启用 DHCP:   是
                      DHCP 服务器: 192.168.1.1
                      IP 地址
                        [01]: 192.168.1.103
                        [02]: fe80::61f4:b413:bb15:7f5f
Hyper-V 要求:     虚拟机监视器模式扩展: 是
                  固件中已启用虚拟化: 是
                  二级地址转换: 是
                  数据执行保护可用: 是</pre>

**Comment by Meychi** [comment]
https://github.com/fdorg/flashdevelop/pull/899

**Comment by matrix3d** [comment]
but this but not fixed in 5.0.22
