### ISSUE TITLE
[haxe] Option to have 'private' in generators

### ISSUE THREAD

**Issue by markknol** [fdorg/flashdevelop#879]
I'm not sure if I miss something in the settings, but we try to change our code convention by adding "private" on all private fields and functions. Mostly for readability and have it more consistent across other code languages we use. 

Now when pressing _the magic ctrl-shift-1_ it just generates `var myField` or `function myFunction()`, we like to choose to have it generated like `private var myField` or `private function myFunction()`.

Can there be an option to have "private" be part of the generation? Of course this also should happen on overrides and statics etc.

**Comment by Meychi** [comment]
I would also like to have this setting. @elsassph?

**Comment by markknol** [comment]
Shameless bump, can this setting be added?

**Comment by markknol** [comment]
I think this can be fixed here: 
https://github.com/fdorg/flashdevelop/blob/development/External/Plugins/ASCompletion/Completion/TemplateUtils.cs#L57-L58

**Comment by markknol** [comment]
Sorry I bump this again, but for me it would be a productivity boost if this feature was added. 

![Please?](https://media.tenor.co/images/330ec052802f60f51ac5deaaa7ef4876/raw)

**Comment by SlavaRa** [comment]
I do PR with fix in this week

**Comment by elsassph** [comment]
I hope we can get rid of the `private` we get when generating a static function VS non static ;)
