### ISSUE TITLE
ASCompletion: access modifiers before static, but after override (like flex sdk)

### ISSUE THREAD

**Issue by gene-pavlovsky** [fdorg/flashdevelop#885]
ASCompletion already has a useful option ``start declaration with access modifiers``. There should also be an option to control where the ``override`` keyword goes.
Basically I think there should be a new option to replace the ``start declaration with access modifiers``.
My proposal is a multi-value option (dropdown) with different combinations of access-modifiers, override and static.
Personally I need it because I want to start declaration with override, then access modifiers, then static.
This is the same style as used in Flex SDK, and it makes sense to me.
```
override public function x():void { ... }
public static function s():void { ... }
override public static function s():void { ... }
```

**Comment by wise0704** [comment]
The PR allows you to choose from 11 options hehe

**Comment by SlavaRa** [comment]
```override public static function s():void { ... }``` it is invalid code.

**Comment by wise0704** [comment]
Having all 3 types of modifiers may be invalid in AS3 and probably some other languages, but still, the idea is to be able to have `override` before access, and `static` after access. They don't all need to be in the same line.
Having both `override public function s():void {...}` and `public static function s():void {...}` is impossible with the current dev version.

**Comment by SlavaRa** [comment]
you forget about the "final"

**Comment by SlavaRa** [comment]
I think that your decision should be replaced by a string pattern, 
no drop-down list

**Comment by wise0704** [comment]
I thought of those, and decided that `static`, `final`, `inline`, `virtual` or anything else should categorise as "others".
So if you want final to come between override and access, for example, `StartWithOverride_EndWithAccess` is the one.

String pattern is the first solution I thought of. However, currently there is no settings editor in FD (I think) that allows entering of only keywords (like, only allows entering/drag-dropping `override`, `access`, `static`, `final`, etc.).

**Comment by SlavaRa** [comment]
Now "start declaration with access modifiers" performs the claimed behavior.
@gene-pavlovsky described the task for the invalid code, so if you decide it, I think in vain.
If you want to improve the setting for the user, I think we must look in the direction of the IDEA/R# because there is implemented user-friendly.
Compare for yourself with IDEA: ![](http://service.crazypanda.ru/v/clip2net/I/N/5IohnyShCs.png)

ps
I do not mean that you did something bad, I want to say that if you improve the user settings, it is necessary to do so to make it convenient than it is now, the setting must be simple and unambiguous

**Comment by gene-pavlovsky** [comment]
Pardon me for mentioning invalid code `override public static function s():void { ... }`, it was not intended as an example of a real code that should compile, just demonstrating the order of keywords, of course override and static can't be both present at the same time.

**Comment by gene-pavlovsky** [comment]
Of course what @SlavaRa proposes would be more user-friendly, but wouldn't that require major upgrades to FD's settings dialog?
At the moment I would be satisfied with the solution offered by @wise0704 - it's better than the current state of affairs.

**Comment by Neverbirth** [comment]
When the user wants to modify the setting a customized dialog could be open, no need to make upgrades to the FD settings dialog itself, it could come handy for some plugins tho, mainly CodeFormatter, although a similar thing could be done.

**Comment by wise0704** [comment]
A customized dialog was what I meant heh. My bad wording.
I am working on the new dialog already.

**Comment by gene-pavlovsky** [comment]
@wise0704 Did you ever have a chance to finish your new dialog?

**Comment by wise0704** [comment]
The PR is finished, and I think it just need some time for review.
