### ISSUE TITLE
Viewing a model of an interface inside SWC doesn't work

### ISSUE THREAD

**Issue by gene-pavlovsky** [fdorg/flashdevelop#886]
When I press F4 on a built-in interface, e.g. ``flash.utils.IExternalizable``, it opens a ``[model] IExternalizable.as`` tab, containing (as expected):
```actionscript
// C:\Users\root\AppData\Local\FlashDevelop\Apps\ascsdk\18.0.0\frameworks\libs\air\airglobal.swc\flash\utils\IExternalizable
...
public interface IExternalizable
...
```

I'm working with Feathers (feathersui.com), when I press F4 on ``feathers.core.IFeathersControl``, it opens a ``[model] IFeathersControl``, but instead of an interface, it shows a class, with a strange ``extends *`` all methods as protected:
```actionscript
// C:\project\apps\FXCalc\lib\feathers.swc\feathers\core\IFeathersControl
...
public class IFeathersControl extends * implements IValidating
{
	protected function get clipRect () : Rectangle;
...
```

In the feathers source code IFeathersControl is an interface (that doesn't extend anything).
Either feathers SWC is compiled in some strange way, or FD for some reasons fails to extract the interface's model from the SWC correctly.

**Comment by gene-pavlovsky** [comment]
Also, due to this, FD doesn't offer code completion for the interface in question.

**Comment by gene-pavlovsky** [comment]
The SWC to test can be found here:
https://github.com/BowlerHatLLC/feathers/releases/download/v2.2.0/feathers-ui-2.2.0.zip
According to Josh, author of Feathers, it's compiled with AIR SDK 18.0.0 with no special tricks.

Side question: if I have a class feathers.controls.Button both inside an SWC and in my source path, the compiler picks the file in the source path (overriding the class in the SWC). That is useful, since I can use a complete SWC, but when I want to debug something related to a particular class that SWC provides, I can put just that one class in my source path and add debugging code there, avoiding to use the whole library as source or recompiling the SWC. However if there was a way to point FD to a source path, but give that source path lower priority than SWC, then the source files in there could be used for code completion, pressing F4 on a class/property/method would open the actual source files, not just an extracted model - but on compile only the classes from SWC would be used.

**Comment by Neverbirth** [comment]
Try the latest development build. It should be fixed.

**Comment by gene-pavlovsky** [comment]
Yep, it is working now. What was the cause of the bug?
