### ISSUE TITLE
Find and Replace - make dialog resizable

### ISSUE THREAD

**Issue by gene-pavlovsky** [fdorg/flashdevelop#887]
The ``Find and Replace in files`` dialog is resizable (and remembers it's size even across restarts - great! I like to make it bigger than default.
It would be great if the ``Find and Replace`` dialog would also have the same features. Sometimes it's way too small, especially when using RegExps.

**Comment by Meychi** [comment]
Done.

**Comment by gene-pavlovsky** [comment]
Hey Mika, nice work! It's great :)
