### ISSUE TITLE
FlashDevelop crash on debugging Haxe Flash

### ISSUE THREAD

**Issue by DleanJeans** [fdorg/flashdevelop#889]
FlashDevelop was working fine. Then one day, it started to crash everytime I debug Haxe Flash. Building/Compiling is fine. I've also tried to reinstall FD but it won't work.

**Comment by Gama11** [comment]
Is it a hard crash (any error messages)?

**Comment by dleanjeanz** [comment]
No, not at all. FD closes immediately right after starting debugging, Flash Player isn't opened. I did 'lime setup android' and about an hour later it started to crash. I used to setup Android before and it didn't caused FD to crash.

**Comment by dleanjeanz** [comment]
Installing android tools through `lime setup android` could be the problem. I deleted everything and installed them again. At first, debugging worked just fine. After `lime setup android` and a restart, FlashDevelop crashed again. I used to setup android tools before and it didn't cause FD to crash. Weird... Anyway to fix this?
