### ISSUE TITLE
ASCompletion: Generate Protected Declarations if class is not final

### ISSUE THREAD

**Issue by gene-pavlovsky** [fdorg/flashdevelop#890]
Many classes I write can in theory be extendable later, so I like to set the "Generate Protected Declarations" setting to true.
However, many other classes, mostly app-specific UI classes that are not planned to be reusable, I'd like the code generator to generate private declarations instead. 
I think the behavior that would make sense is: Event if "Generate Protected Declarations" is true, if class is declared as final, generate private declarations. Alternatively, some comment "metadata" could be added to class declaration, similar to the way FD allows to type var tokenArray:Array/*Token*/; and have completion treat it as array of Token objects. Could be something like "public class ClassName/*private*/" and "public class ClassName/*protected*/" to tell the generator to respectively generate private and protected declarations. But I like the "final class" => private declarations idea more.
If not everybody would want such a feature, "Generate Protected Declarations" could be changed to "Generate Declaration with Access Modifier" with options of Private / Protected / Auto.

**Comment by wise0704** [comment]
I think having a `protected` member in a sealed class doesn't really make sense either.
