### ISSUE TITLE
Find and Replace dialogs - keyboard shortcuts should focus dialogs if already open

### ISSUE THREAD

**Issue by gene-pavlovsky** [fdorg/flashdevelop#896]
If a Find and Replace dialog is already open, then lose focus (e.g. I click the source code editor), then using Ctrl+Shift-F or Ctrl+H keyboard shortcuts should bring the already open F&R dialog back into focus. Same as it works with quick-find and Ctrl+F.

**Comment by Neverbirth** [comment]
Please, test latest development build to confirm this is fixed.

**Comment by gene-pavlovsky** [comment]
It works now. However (might be unrelated), my keyboard shortcut Ctrl-I for "F&R in files" stopped working for some reason (nothing happens).

**Comment by Neverbirth** [comment]
That shortcut was changed to Ctrl+Shift+F some time ago because it's the default one for most, if not all, other mainstream editors out there. Maybe you were using an older version, your settings were reset, or you tried running in local settings mode.

I'd say you can close this one now.

**Comment by gene-pavlovsky** [comment]
When I first noticed that the shortcut has changed a while ago, I went to Tools > Keyboard Shortcuts and changed SearchMenu.FindAndReplaceInFiles to Ctrl+I. It used to work (Ctrl+Shift+F also worked). But now whatever I change that shortcut to, only Ctrl+Shift+F is working. If this is not related at all to the work you've done on this issue, I can close this one and open a new one.

**Comment by gene-pavlovsky** [comment]
![ctrl_i](https://cloud.githubusercontent.com/assets/2841193/11608493/bd50d164-9b9d-11e5-9a01-44e21b97ad5f.png)

**Comment by gene-pavlovsky** [comment]
As a matter of fact, none of my custom keyboard shortcuts are working in the latest dev build.

**Comment by Neverbirth** [comment]
That's unfortunate, but completely unrelated to this, probably caused by this PR:

https://github.com/fdorg/flashdevelop/pull/974

There is already another PR pending that I think fixes the problem.

**Comment by gene-pavlovsky** [comment]
All right thanks a lot for fixing this issue!
