### ISSUE TITLE
Find and Replace dialogs - add keyboard shortcuts to focus "Find what" or "Replace with"

### ISSUE THREAD

**Issue by gene-pavlovsky** [fdorg/flashdevelop#897]
Many times I'm searching for something using Find and Replace, and have to change the "match case" or "use regular expressions" settings. When I do, the focus goes to these checkboxes, and it's hard to get back to the "find what" and "replace with" text fields using keyboard. It would be good if there were shortcuts to focus those fields (similar, for example, how in any web browser there's a shortcut to focus the address bar).

**Comment by Meychi** [comment]
Control+F now focuses Find what on both dialogs.

**Comment by gene-pavlovsky** [comment]
Great, it works. Would it be too much to ask if Control+R would go to Replace ?

**Comment by gene-pavlovsky** [comment]
And also I wonder, how are users gonna learn/guess about this feature? I know only because I read this issue :)
