### ISSUE TITLE
Duplicate file (by copy&paste in same directory) - default name

### ISSUE THREAD

**Issue by gene-pavlovsky** [fdorg/flashdevelop#903]
When copying a file then pasting in the same directory, the `Duplicate file` dialog offers to name the duplicated file "Copy of XXX" by default. But anybody ever agrees to create a file with a name like this? Personally I copy&paste a file in the same directory because I want to make a class that will be similar to an existing class, and will quite likely have a similar name. For example, if I have a MathExpressionNumberToken class, I would copy&paste the file in the same dir and name the new class MathExpressionIdentifierToken. So I think by default the dialog should offer "XXX", making it easy to change the name appropriately without having to remove "Copy of " every time. Or have it as an option?

**Comment by Gama11** [comment]
I agree, the "Copy of" being there doesn't really help. Not sure what you mean by "XXX" though.

Maye the default "new name" should just be the same as the original file name, with "Ok" being disabled out as long as the name is the same.

Another potential issue is that the file ending isn't included in the textfield (i.e. can't be changed).

**Comment by gene-pavlovsky** [comment]
By XXX I meant whatever the original name of the file was!
And your suggestion for default and disabling the Ok button is spot on, just what I was thinking.
I was also thinking about the file ending, it makes some sense since if you're copy&pasting an .as file the copy will also be an .as file in 99% of cases. But there are cases where you might want to specify an extension, for example if you're not using a source control system and you want to make a quick back-up of a file before changing something for testing. How the dialog should treat that is a question.
E.g. you have a ``Console.as``, copy&paste offers ``Copy of Console``, typing ``Copy of Console.bak`` results in a ``Copy of BenchmarkConsole.bak.as`` being created, rather than the desired ``Copy of Console.as.bak``.
I see 3 acceptable solutions at the moment
1) Function should offer a full name from the beginning, with filename without the extension selected by default (since in most use cases the extension will not be changed).
2) Function works same as it does now, but if the user enters ".ext", the original extension is replaced with the specified ext. E.g. copy&paste ``Console.as`` offers ``Console``, user has to type ``Console.as.bak`` to paste as ``Console.as.bak``.
3) Function works same as it does now, but if the user enters ".ext", the specified ext is appended to the original extension (so user type ``Console.bak`` creates ``Console.as.bak``). I think this is the most confusing option.

**Comment by gene-pavlovsky** [comment]
It's somewhat same topic, so I will say another thing. The current behavior of this dialog and renaming using F2 in the project panel are different and this is confusion and common source of user error for me. I.e. if I'm used to being able to just write down the class name in the copy&paste duplicate dialog, with the original extension being appended automatically (e.g. .as copied is .as pasted), then I'm automatically expecting similar "smartness" when renaming a class file in the project panel with F2. So I have a ``Console.as``, I press F2 and file name gets selected. I changed it ``BenchmarkConsole``, omitting .as, and then instead of guessing that I actually wanted to rename to ``BenchmarkConsole.as``, FD asks me to confirm changing extension since the file might become unusable.
I think FD should have same or similar behavior in both copy&paste duplication and F2 renaming cases, so there's no confusion.
