### ISSUE TITLE
Clear find results highlight by searching for an empty value

### ISSUE THREAD

**Issue by gene-pavlovsky** [fdorg/flashdevelop#904]
I like the feature of highlighting search results (F&R in files, quick find), but it's not easy to clear that highlight. To do that, I have to search for some dummy string which I know wouldn't be found. That string ends up in the find what history, which I don't want.
I think it would make sense if open F&R in files or quick-find again, clear the search box, then press enter (basically search for an empty string), the highlight should be cleared.

**Comment by Meychi** [comment]
In QuickFind, just uncheck highlight all and in F&R in files, Results panel adds the highlights. Just clear results.

**Comment by gene-pavlovsky** [comment]
I'd prefer to leave "highlight all" on as I use it often.
Results panel - is there any way to quickly clear results with the keyboard? I haven't found a shortcut for this.
