### ISSUE TITLE
Switching Layouts without Documents Open

### ISSUE THREAD

**Issue by wise0704** [fdorg/flashdevelop#912]
When FlashDevelop is trying to switch between layouts without any documents open (e.g. only StartPage is open), it crashes with the following error message and StartPage is no longer openable until FlashDevelop is restarted. 

>
    Index was outside the bounds of the array.
>
        at PluginCore.Managers.DocumentManager.ActivateDocument(Int32 index)
        at FlashDevelop.Managers.SessionManager.RestoreSession(String file, Session session)

**Comment by Meychi** [comment]
I tried this and i could not repro with latest dev version. Its seems FD is trying to restore invalid session. Can you repro this reliably?

**Comment by wise0704** [comment]
This is the content of the default layout file, in case there is something missing or extra invalid here.
The problems still occurs with version 5.0.2, and I'm not quite sure what other information I should provide as the error message is all I get. It seems like the error occurs when `PluginBase.MainForm.Documents[0].Activate()` is called inside `DocumentManager.ActivateDocument()`, and the Documents array has no elements in it.
>
    <?xml version="1.0" encoding="utf-16"?>
    
    
    <DockPanel FormatVersion="1.0" DockLeftPortion="0.25" DockRightPortion="0.25" DockTopPortion="0.25" DockBottomPortion="0.25" ActiveDocumentPane="14" ActivePane="14">
      <Contents Count="18">
        <Content ID="0" PersistString="ccf2c534-db6b-4c58-b90e-cd0b837e61c4" AutoHidePortion="0.25" IsHidden="True" IsFloat="True" />
        <Content ID="1" PersistString="078c7c1a-c667-4f54-9e47-d45c0e835c4e" AutoHidePortion="0.25" IsHidden="False" IsFloat="False" />
        <Content ID="2" PersistString="078c7c1a-c667-4f54-9e47-d45c0e835c4f" AutoHidePortion="0.25" IsHidden="True" IsFloat="True" />
        <Content ID="3" PersistString="9b79609e-2b05-4e88-9430-21713aafc827" AutoHidePortion="0.25" IsHidden="False" IsFloat="False" />
        <Content ID="4" PersistString="f534a520-bcc7-4fe4-a4b9-6931948b2686" AutoHidePortion="0.25" IsHidden="False" IsFloat="False" />
        <Content ID="5" PersistString="f9d8faf1-31f7-45ca-9c14-2cad27d7a19e" AutoHidePortion="0.25" IsHidden="True" IsFloat="False" />
        <Content ID="6" PersistString="49eb0b7e-f601-4860-a190-ae48e122a661" AutoHidePortion="0.25" IsHidden="True" IsFloat="False" />
        <Content ID="7" PersistString="c4a0c90a-236c-4a41-8ece-85486a23960f" AutoHidePortion="0.25" IsHidden="True" IsFloat="False" />
        <Content ID="8" PersistString="6ee0f809-a3f7-4365-96c7-3bdf89f3aaa4" AutoHidePortion="0.25" IsHidden="True" IsFloat="False" />
        <Content ID="9" PersistString="7ce31ab1-5a40-42d5-ad32-5df567707afc" AutoHidePortion="0.25" IsHidden="True" IsFloat="False" />
        <Content ID="10" PersistString="f95e799b-424b-4eee-80ef-8cd071ec16c8" AutoHidePortion="0.25" IsHidden="True" IsFloat="False" />
        <Content ID="11" PersistString="2cf76544-5736-11dc-8314-0800200c9a66" AutoHidePortion="0.25" IsHidden="False" IsFloat="False" />
        <Content ID="12" PersistString="3450fd43-3112-4b3f-a02a-e6bdbadcb971" AutoHidePortion="0.25" IsHidden="False" IsFloat="False" />
        <Content ID="13" PersistString="54749f71-694b-47e0-9b05-e9417f39f20d" AutoHidePortion="0.25" IsHidden="False" IsFloat="False" />
        <Content ID="14" PersistString="30018864-fadd-1122-b2a5-779832cbbf23" AutoHidePortion="0.25" IsHidden="False" IsFloat="False" />
        <Content ID="15" PersistString="24df7cd8-e5f0-4171-86eb-7b2a577703ba" AutoHidePortion="0.25" IsHidden="False" IsFloat="False" />
        <Content ID="16" PersistString="40feac2b-a68a-498e-ad78-52a8268efa45" AutoHidePortion="0.25" IsHidden="False" IsFloat="False" />
        <Content ID="17" PersistString="FlashDevelop.Docking.TabbedDocument" AutoHidePortion="0.25" IsHidden="False" IsFloat="False" />
      </Contents>
      <Panes Count="15">
        <Pane ID="0" DockState="DockRight" ActiveContent="1">
          <Contents Count="6">
            <Content ID="0" RefID="0" />
            <Content ID="1" RefID="1" />
            <Content ID="2" RefID="2" />
            <Content ID="3" RefID="3" />
            <Content ID="4" RefID="4" />
            <Content ID="5" RefID="14" />
          </Contents>
        </Pane>
        <Pane ID="1" DockState="Float" ActiveContent="-1">
          <Contents Count="1">
            <Content ID="0" RefID="0" />
          </Contents>
        </Pane>
        <Pane ID="2" DockState="Float" ActiveContent="-1">
          <Contents Count="1">
            <Content ID="0" RefID="2" />
          </Contents>
        </Pane>
        <Pane ID="3" DockState="DockLeft" ActiveContent="-1">
          <Contents Count="1">
            <Content ID="0" RefID="5" />
          </Contents>
        </Pane>
        <Pane ID="4" DockState="DockLeft" ActiveContent="-1">
          <Contents Count="1">
            <Content ID="0" RefID="6" />
          </Contents>
        </Pane>
        <Pane ID="5" DockState="DockLeft" ActiveContent="-1">
          <Contents Count="1">
            <Content ID="0" RefID="7" />
          </Contents>
        </Pane>
        <Pane ID="6" DockState="DockLeft" ActiveContent="-1">
          <Contents Count="1">
            <Content ID="0" RefID="8" />
          </Contents>
        </Pane>
        <Pane ID="7" DockState="DockLeft" ActiveContent="-1">
          <Contents Count="1">
            <Content ID="0" RefID="9" />
          </Contents>
        </Pane>
        <Pane ID="8" DockState="DockLeft" ActiveContent="-1">
          <Contents Count="1">
            <Content ID="0" RefID="10" />
          </Contents>
        </Pane>
        <Pane ID="9" DockState="DockBottomAutoHide" ActiveContent="11">
          <Contents Count="1">
            <Content ID="0" RefID="11" />
          </Contents>
        </Pane>
        <Pane ID="10" DockState="DockBottomAutoHide" ActiveContent="12">
          <Contents Count="1">
            <Content ID="0" RefID="12" />
          </Contents>
        </Pane>
        <Pane ID="11" DockState="DockBottom" ActiveContent="13">
          <Contents Count="1">
            <Content ID="0" RefID="13" />
          </Contents>
        </Pane>
        <Pane ID="12" DockState="DockBottomAutoHide" ActiveContent="15">
          <Contents Count="1">
            <Content ID="0" RefID="15" />
          </Contents>
        </Pane>
        <Pane ID="13" DockState="DockBottomAutoHide" ActiveContent="16">
          <Contents Count="1">
            <Content ID="0" RefID="16" />
          </Contents>
        </Pane>
        <Pane ID="14" DockState="Document" ActiveContent="17">
          <Contents Count="1">
            <Content ID="0" RefID="17" />
          </Contents>
        </Pane>
      </Panes>
      <DockWindows>
        <DockWindow ID="0" DockState="Document" ZOrderIndex="1">
          <NestedPanes Count="1">
            <Pane ID="0" RefID="14" PrevPane="-1" Alignment="Right" Proportion="0.5" />
          </NestedPanes>
        </DockWindow>
        <DockWindow ID="1" DockState="DockLeft" ZOrderIndex="3">
          <NestedPanes Count="6">
            <Pane ID="0" RefID="3" PrevPane="-1" Alignment="Bottom" Proportion="0.5" />
            <Pane ID="1" RefID="4" PrevPane="3" Alignment="Bottom" Proportion="0.5" />
            <Pane ID="2" RefID="5" PrevPane="4" Alignment="Bottom" Proportion="0.5" />
            <Pane ID="3" RefID="6" PrevPane="5" Alignment="Bottom" Proportion="0.5" />
            <Pane ID="4" RefID="7" PrevPane="6" Alignment="Bottom" Proportion="0.5" />
            <Pane ID="5" RefID="8" PrevPane="7" Alignment="Bottom" Proportion="0.5" />
          </NestedPanes>
        </DockWindow>
        <DockWindow ID="2" DockState="DockRight" ZOrderIndex="4">
          <NestedPanes Count="1">
            <Pane ID="0" RefID="0" PrevPane="-1" Alignment="Bottom" Proportion="0.5" />
          </NestedPanes>
        </DockWindow>
        <DockWindow ID="3" DockState="DockTop" ZOrderIndex="5">
          <NestedPanes Count="0" />
        </DockWindow>
        <DockWindow ID="4" DockState="DockBottom" ZOrderIndex="6">
          <NestedPanes Count="5">
            <Pane ID="0" RefID="9" PrevPane="-1" Alignment="Right" Proportion="0.5" />
            <Pane ID="1" RefID="10" PrevPane="9" Alignment="Right" Proportion="0.5" />
            <Pane ID="2" RefID="11" PrevPane="10" Alignment="Right" Proportion="0.5" />
            <Pane ID="3" RefID="12" PrevPane="11" Alignment="Right" Proportion="0.5" />
            <Pane ID="4" RefID="13" PrevPane="12" Alignment="Right" Proportion="0.5" />
          </NestedPanes>
        </DockWindow>
      </DockWindows>
      <FloatWindows Count="2">
        <FloatWindow ID="0" Bounds="0, 0, 600, 400" ZOrderIndex="0">
          <NestedPanes Count="1">
            <Pane ID="0" RefID="1" PrevPane="-1" Alignment="Right" Proportion="0.5" />
          </NestedPanes>
        </FloatWindow>
        <FloatWindow ID="1" Bounds="0, 0, 600, 400" ZOrderIndex="1">
          <NestedPanes Count="1">
            <Pane ID="0" RefID="2" PrevPane="-1" Alignment="Right" Proportion="0.5" />
          </NestedPanes>
        </FloatWindow>
      </FloatWindows>
    </DockPanel>

**Comment by Meychi** [comment]
I added a check that makes sure docs are available. Could you try the dev build?

**Comment by wise0704** [comment]
Now the error dialogue doesn't show up, but everything else is still the same... I can't open StartPage afterwards. I think what happens is that when switching layouts with only StartPage open, FlashDevelop closes StartPage, but somehow still thinks that it is open - therefore after switching layouts, clicking on View > StartPage doesn't open it.

**Comment by Meychi** [comment]
Have you customized any StartPage plugin settings, do you have third party plugins installed and what are your system details?

**Comment by wise0704** [comment]
I only have NavigationBar installed as a third party plugin. 
![StartPage settings](https://cloud.githubusercontent.com/assets/13545633/10778095/16bc6f68-7d87-11e5-877c-930c95c82762.PNG)
![capture 2](https://cloud.githubusercontent.com/assets/13545633/10778213/8109dbac-7d88-11e5-905e-064736d25403.PNG)
