### ISSUE TITLE
Quick find bar - sometimes clearing the text box doesn't clear the error background

### ISSUE THREAD

**Issue by gene-pavlovsky** [fdorg/flashdevelop#918]
Type something in the quick find bar, which doesn't match anything. The background of the text box changes to QuickFind.ErrorBack color. Clear the search query using Backspace, if after removing some characters some matches are found, the error background changes back to normal. But if even the first character of the search query doesn't match anything, the error background stays even when the search box is now empty. Same happens when clearing it using Ctrl-A then Delete, error background and "no matches found" stays. I think if the quick find box normally updates live while typing, it should also clear while deleting. So with an empty search box, the quick find bar shouldn't show "no matches found" and error background

**Comment by Meychi** [comment]
Should be fixed now.

**Comment by gene-pavlovsky** [comment]
I don't see it fixed, trying with the last dev build. And noticed an extra bug (I believe I've seen same or similar in the output panel when using the "clear results" button).
1) Open a new blank document
2) Write "message"
3) Ctrl-F, type "zzz", nothing found, observe "ErrorBack" background color
4) Use backspace to clear "zzz", still have error bg.
5) Type "ssa" - get matching "ssa" selected in the editor. Type "z" after "ssa" (result is "ssaz"), error bg appears. use Ctrl-A to select the whole search text, then Del or Backspace to clear the search box. Error bg still there.
6) Type "ss" - get matching "ss" selected in the editor. Press backspace once, editor shows "s" selected. Press backspace another time, nothing in search box now, but editor still shows that "s" selected (and "Showing results 1 of 2." in the quick find box status).

**Comment by gene-pavlovsky** [comment]
Ok with the latest dev build most of the problems are gone, only one remains, I'll post as separate issue then.
