### ISSUE TITLE
Highlight matching words and quickfind's highlight all overlap

### ISSUE THREAD

**Issue by gene-pavlovsky** [fdorg/flashdevelop#920]
If quick find's highlight all checkbox is enabled, when using "find next", the next match gets selected and of course highlighted (matching words highlight). The two highlights overlap (mix their colors). Is that the intended behavior?
![highlight-overlap](http://i.imgur.com/aPcOYWX.png)
Search text was "timeSlice", the first timeSlice is the current search result (got there by F3), asyncTimeSlice has TimeSlice highlighted (green) only by quick-find, since it's not a whole-word match for timeSlice, then the third timeSlice is highlighted (green-blue) by both quick-find and highlight matching words. I could see some use for this behavior in this example - namely you can distinguish between whole-word matches and non-whole-word matches by color, but frankly I'm not sure how useful is this. 
Otherwise, the results of this behavior is, if both ``highlight-back`` and ``highlightword-back`` are set (to different colors), then during searching, ``highlight-back`` will be muddled with ``highlightword-back``, and only seen purely if the cursor (caret) is moved away from the matching word. Personally, I think if some text is already highlighted by quick-find, same text shouldn't be highlighted again by highlight matching words.

**Comment by Meychi** [comment]
This is intended behaviour so that you can see both highlights but some colors don't work with this all that well. For example blue and red mix nicely giving you a nice new color :)

**Comment by gene-pavlovsky** [comment]
Ok no worries, thanks
