### ISSUE TITLE
Dock panels on the right missing a bottom horizontal line (?)

### ISSUE THREAD

**Issue by gene-pavlovsky** [fdorg/flashdevelop#921]
![project-pane](http://i.imgur.com/GdcA2fG.png)
The panels docked on the right side has borders on three sides but on the bottom there's no border / horizontal line. Other panels (e.g. Threads debug panel) have a border on all sides.

**Comment by Meychi** [comment]
Does this happen when you hover autohidden panel or always?

**Comment by gene-pavlovsky** [comment]
Only on hovering an autohidden panel. If I pin even a single panel (so no tab bar on the bottom), there's a border all around.

**Comment by gene-pavlovsky** [comment]
Only on hovering an autohidden panel. If I pin even a single panel (so no tab bar on the bottom), there's a border all around.

**Comment by Meychi** [comment]
Should be fixed now.

**Comment by gene-pavlovsky** [comment]
I'm still seeing this problem on the latest dev build

**Comment by gene-pavlovsky** [comment]
![project-no-bottom-border](https://cloud.githubusercontent.com/assets/2841193/10676041/a87eafc8-792d-11e5-8ec4-d7f7138a3829.png)
