### ISSUE TITLE
Theme: add setting for current block highlight guide color

### ISSUE THREAD

**Issue by gene-pavlovsky** [fdorg/flashdevelop#922]
It would be nice to have a setting for the current block highlight guide color. Right now it uses the matching bracket fore color. I like my brackets red and noticeable, but I'd prefer the highlight guide not stand out that much, so a separate color would be nice...
![highlight-guide](http://i.imgur.com/08rF51t.png)

**Comment by Meychi** [comment]
This is not customizable in Scintilla: http://www.scintilla.org/ScintillaDoc.html#SCI_SETHIGHLIGHTGUIDE

**Comment by gene-pavlovsky** [comment]
All right, then.
