### ISSUE TITLE
Theme: Flash Log Viewer: use text colors from Output panel

### ISSUE THREAD

**Issue by gene-pavlovsky** [fdorg/flashdevelop#925]
Output panel's new theme-customizable colors are great, but Flash Log Viewer still showing results in black. I think it should use same color as the Output panel does for Debug (trace) lines.

**Comment by gene-pavlovsky** [comment]
Actually I just found out for some reason the first line of text in Flash Log Viewer get colored black, the following lines get colored with whatever color comes from the theme (RichTextBox?)
![flash-log-viewer](http://i.imgur.com/koc6EyL.png)

**Comment by gene-pavlovsky** [comment]
Log display was empty, then I clicked "Start tracking" (when my app already finished), new entries appeared, first one in black, the rest in the correct color.

**Comment by Meychi** [comment]
Implemented and should be fixed now.

**Comment by gene-pavlovsky** [comment]
Works for me now. By the way, I've taken a look at  the warning and error regexps in the settings, on what conditions the flash player actually outputs a warning or error message like this in the log?
If an exception happens, the Output panel highlights the exception line in Red, but flash log viewer's doesn't (the regexp with "Error #" in it doesn't match), e.g.
``An exception has occurred:
  ArgumentError: Incorrect argument``

**Comment by Meychi** [comment]
Great. The regexes are customizable but will update the default regex.

**Comment by gene-pavlovsky** [comment]
Found the customizable settings. Thanks.
