### ISSUE TITLE
Project panel: Track active document not always tracking

### ISSUE THREAD

**Issue by gene-pavlovsky** [fdorg/flashdevelop#928]
I have ``Track Active Document`` enabled in the project panel, it updates when switching tabs, opening a new tab using Ctrl+R shortcut, opening one of project's file with a file manager (e.g. Explorer).
However, when I first start (or restart) FD, it restores the last session including the tab I was on, but on the project panel everything is collapsed and the root node is selected. Have to ctrl-tab to another tab then back to get my current tab's document tracked. Similar (more common) scenario is switching between projects, both of which reference some common code. E.g. I have a class library I'm developing together with a main project, and a simple sandbox project where I just test various things from that class library. So sandbox project includes the source path from the class library. I'm working with the sandbox project, modifying some class in the class library, then after some sandbox testing I want to switch to the main project and test the new feature in there. After I switch, the project tree collapsed and the active doc is not tracked. Switching back to the sandbox project, still it's all collapsed.
I think when a project is opened, FD should check if the active document is a part of, or referenced by that project, if so, navigate to that document's node in the project tree.

**Comment by Neverbirth** [comment]
Please, test latest development to confirm this is fixed.

**Comment by gene-pavlovsky** [comment]
Works beautifully! Thanks a lot!
