### ISSUE TITLE
Insert > Timestamp format

### ISSUE THREAD

**Issue by gene-pavlovsky** [fdorg/flashdevelop#929]
Would be nice if the timestamp format was customizable. Right now I'm getting:
"2015-10-19 3:15 PM"
While my system is supposed to be set up for 24-hour clock. And I'd like the time padded with zeros. Can a date format setting be added?

**Comment by wise0704** [comment]
You know that you can modify the file `$(BaseDir)\Settings\MainMenu.xml`?
Look for `Label.Insert` -> `Label.Timestamp` and you can modify `tag="g"`.

**Comment by gene-pavlovsky** [comment]
As a user, even though I'm a linux sys admin and used to editing arcane config files, I don't prefer doing that for a desktop application such as FD. I'd love every setting to be available in the nice GUI settings dialog, rather than having to edit xml files. I think for that menu item to be useful, the format definitely should be customizable, since different countries use different formats for dates and times.
Having said that, what're the available codes in the timestamp tag? I'd like to have "yyyy-MM-dd HH:mm" as a result.

**Comment by wise0704** [comment]
The tag is directly passed to `DateTime.ToString()` as the `string` type format argument.
Have a look at those links:
https://msdn.microsoft.com/en-us/library/zdtaw1bw(v=vs.110).aspx
https://msdn.microsoft.com/en-us/library/az4se3k1(v=vs.110).aspx
https://msdn.microsoft.com/en-us/library/8kb3ddd4(v=vs.110).aspx

The PR I made makes `Insert Timestamp` prompt for the format string if the `tag` in the file is empty. So if it does get accepted, you could have the tag set to empty if you want to insert different time format every time you use it.

**Comment by gene-pavlovsky** [comment]
What do you know, `yyyy-MM-dd HH:mm` works as is, neat! I don't think it would be convenient to choose different time format on every use... And what if a user routinely uses more than one format? In that case, a persistent history combo box or a customizable list might be convenient. I don't know though, how many ppl use that feature at all, maybe it's not worth putting more effort there.

Since I didn't know about MainMenu.xml way of customizing the tag, personally I've found another solution some time ago - using AutoHotkey's hotstrings. Here's an excerpt from my AutoHotkey.ahk
```autohotkey
SendDate(Format) {
	FormatTime, CurrentDate,, %Format%
	SendInput %CurrentDate%
}

:*:ds#::
	SendDate("yyyyMMdd")
	return
:*:dd#::
	SendDate("yyyy-MM-dd")
	return
:*:tt#::
	SendDate("HH:mm")
	return
:*:dt#::
	SendDate("yyyy-MM-dd HH:mm")
	return
```

Typing ds, dd, tt, dt followed by # inserts the date/time in 4 different formats, works in any application.

**Comment by wise0704** [comment]
Hmmm... instead of implementing a "history" system to this,
how about having first a set of predefined list of formats, and also that you can add more to it?
So that if the `tag` is empty, it brings up the dialog to add/remove time formats and also choose a format from.

**Comment by gene-pavlovsky** [comment]
Yeah, that makes sense. If you want to invest your time into this.
Appreciate your work!

**Comment by gene-pavlovsky** [comment]
I'm still using the AutoHotKey hotstrings (see comment above) to insert timestamps, so don't care about this anymore
