### ISSUE TITLE
Bookmarks panel improvements

### ISSUE THREAD

**Issue by gene-pavlovsky** [fdorg/flashdevelop#931]
Would be nice to have a "clear (all) bookmarks" button in the Bookmarks panel.
The search box should use ToolStripTextBoxControl.ForeColor theme color, at the moment it uses some other setting.

**Comment by Meychi** [comment]
It uses ToolStripComboBoxControl.ForeColor. :)

**Comment by gene-pavlovsky** [comment]
I see, Flash Log Viewer's similar-looking combo box uses ToolStripTextBoxControl.ForeColor, that's why I assumed it.

**Comment by gene-pavlovsky** [comment]
I see, Flash Log Viewer's similar-looking combo box uses ToolStripTextBoxControl.ForeColor, that's why I assumed it. Since it's a combo box too, perhaps you should change it to use  ToolStripComboBoxControl.ForeColor as well

**Comment by Meychi** [comment]
ToolStripComboBoxControl.ForeColor is now used
