### ISSUE TITLE
Exception after restart when closed FD during debugging

### ISSUE THREAD

**Issue by gene-pavlovsky** [fdorg/flashdevelop#933]
I opened a small project, set a breakpoint, then ran it in debug mode. Debugger started, then execution stopped at the breakpoint. At that moment, I quit FlashDevelop. Upon starting FD again, I got an exception ``System.ComponentModel.Win32Exception: Error creating window handle.``. I clicked continue and FD kept running. The debugger panels were open. Exiting FD and restarting and same exception. To get rid of it, I had to run the project in debug mode again, then close it, debugger panels auto-closed and after that restarting FD didn't make an exception.
Looks like something's fishy is going on if FD is quit during a debugger session?

**Comment by gene-pavlovsky** [comment]
Exception details here:
http://pastebin.com/Q7DG6rfg

**Comment by Meychi** [comment]
Weird. This should be catched now.

**Comment by gene-pavlovsky** [comment]
No more exceptions, but the debugger panels are still shown on start. I think if `Disable panel show` setting is `false` (default), they should be hidden on start-up if they're open?
