### ISSUE TITLE
Debugger shows 1D Vector as 2D Vector

### ISSUE THREAD

**Issue by hgupta9** [fdorg/flashdevelop#943]
The debugger value tree shows a simple `Vector.<Object>` as a `Vector.<Vector.<Object>`, yes, with the closing `>` missing. Here is a screenshot:

![fd5_vector_bug](https://cloud.githubusercontent.com/assets/6797866/10710966/7dbc8dec-7a8a-11e5-846e-48ae9fd72208.png)

I may be responsible for this behavior since I updated the debugger rendering recently. I just don't have time right now to fix it, but if no one does soon, I will. I think the code responsible for this is [ValueNode.cs#L65][1] and/or.[ValueNode.cs#L42][2].
  [1]:https://github.com/fdorg/flashdevelop/blob/development/External/Plugins/FlashDebugger/Controls/DataTree/ValueNode.cs#L65 
[2]:https://github.com/fdorg/flashdevelop/blob/development/External/Plugins/FlashDebugger/Controls/DataTree/ValueNode.cs#L42

**Comment by Neverbirth** [comment]
The fix for this was merged in the official branch yesterday.

**Comment by hgupta9** [comment]
Thank you! That's cool.
