### ISSUE TITLE
Formatter bug in if else brackets

### ISSUE THREAD

**Issue by 22Round** [fdorg/flashdevelop#951]
I have noticed following bug in if .. else conditional statement
after first bracket is pointer and press enter formatter creates close bracket

this case works

``` ActionScript
if(key1 && kay2 == value2 || boo3 || boo4){
  trace(key1)
}
```

this does't

``` ActionScript
if(key1 && kay2 == value2 || 
   boo3 || 
   boo4){
   trace(key1)
}
```

see gif anim.
![ezgif-3712572377](https://cloud.githubusercontent.com/assets/5682469/11060994/34350f42-87bd-11e5-8129-0f55c5b20b12.gif)

**Comment by Meychi** [comment]
@elsass: Seem this is in ASCompletion formatter.

**Comment by elsassph** [comment]
Yes the detection of matching closing brace could be improved - it doesn't get far enough to understand that it's an `if` statement.

**Comment by Neverbirth** [comment]
Seems to not be reproducible anymore.
