### ISSUE TITLE
[Haxe] Editor auto-indents the lines after variables starting with "class"\"enum"

### ISSUE THREAD

**Issue by YellowAfterlife** [fdorg/flashdevelop#960]
Say, you have
```haxe
class Some {
	public var classList:Array<Dynamic> = [];
	|
}
```
upon writing `public ` on the next line, the editor will indent it to level 2. Changing "classList" to "clasList" or any other name (not starting with the keyword) will have it work as usual.
The same happens if a variable name starts with "enum".
Minor stuff.

**Comment by elsassph** [comment]
Should be fixed now in dev builds.
