### ISSUE TITLE
Theme: A non-configurable gray border

### ISSUE THREAD

**Issue by YellowAfterlife** [fdorg/flashdevelop#962]
There's this gray (105, 105, 105) border:
![png2](https://cloud.githubusercontent.com/assets/731492/11459542/de26028a-96e1-11e5-80fe-853b4471843f.png)
If you have a single "tab set" open, it appears between the tab set and the right-side dock. If you have multiple "tab sets" open, it'll appear between them - that said, there's always only a single border of this kind visible in the IDE.
None of the existing themes seem to change it's color so I'm assuming that it is not an intended effect.

**Comment by Meychi** [comment]
It now follows DockWindow.BorderColor.
