### ISSUE TITLE
Startpage cannot be overriden in user config files

### ISSUE THREAD

**Issue by markknol** [fdorg/flashdevelop#983]
This is very specific, but to test a new startpage (for the custom distribution) I'd like to be able to override it in the user config files, since editing in the programfiles does not work very nice.

**Comment by Neverbirth** [comment]
If this is a custom distribution, why don't you distribute it with the custom start page as well? Just asking, maybe I'm missing something else.

**Comment by markknol** [comment]
Ok I'm not clear, sorry :smile:  This is the case:
- I don't have a custom distribution, I'm just messing with the current FlashDevelop version. 
- I don't want to build FD from source, but just test a possible new startpage inside FlashDevelop.
- To change the startpage, you need to do alter the files in `C:\Program Files (x86)\FlashDevelop\StartPage`
- I'd like to copy paste that folder to the userconfig files, so I can mess easier with it.

**Comment by Neverbirth** [comment]
You can use FD wherever you want, no need to modify the installed version in Program Files, just unzip it in any folder. If you have the .local file in the root folder it will use settings, snippets, etc from that same folder, if not it will use the files from the user AppData/Local folder.

**Comment by Meychi** [comment]
Exactly. Download the Zip version of FD and use that standalone version to work with the Startpage.

**Comment by markknol** [comment]
Good idea, thanks!
